### ISSUE TITLE
🐞 Windmille not building

### ISSUE THREAD

**Issue by omri81** [sequentech/meta#1005]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

Not building

### Expected Behavior

Should build

### Steps To Reproduce

-

### Environment

- **OS**: Mac OS X Ventura
- **Web browser**: Google Chrome 112.0.5615.137 (Official Build) (arm64)
- **Sequent Platform Version**: 10.0.0

### Tasks

```[tasklist]
# Tasks
- [ X] Issue has been triaged
- [ X] Successful replication of the defect
- [ ] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] PR 1
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```
