### ISSUE TITLE
✨ new ballot verifier: support first gen ballots

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#102]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

new-ballot-verifier: we should support the first gen auditable ballots.

### Tasks

```[tasklist]
# Tasks
- [x] Replace current interfaces with interfaces for the first gen auditable ballots.
- [x] Make it compile.
- [x] Make tests work again.
- [x] Make UI (new-ballot-verifier) work with the updated interfaces.
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/sequent-core/pull/16
- [ ] https://github.com/sequentech/new-ballot-verifier/pull/33
```
