### ISSUE TITLE
✨ Enable contests and elections ordering

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#1023]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Enable contests ordering

### Tasks

# Screenshots
# Video

https://github.com/sequentech/meta/assets/171477957/13f360c8-3c07-421e-8108-fd30b2ae93cc

<empty>

```[tasklist]
# Tasks
- [x] Create Contest and Elections presntation sorting
- [x] Enable contest sorting on admin portal
- [x] Enable elctions sorting on admin portal
- [x] Setup shared logic for applying contest sorting across admin-portal, voting-portal
- [x] Write the sorting function in Rust - WASM
- [x] Create ui-core to be in charge of all shared functionallity - types and wasm in all ui projects
- [x] Remove functionality and logic from ui-essentials
- [x] Update README + Update Docker Files for build
- [x] Remove Option from rust structs and modify frontend to adapt
- [ ] Implement sorting logic inside tally sheets and tally results
- [ ] Implement sorting logic in ballot verifier
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/477
```
