### ISSUE TITLE
✨ Add a Presentation Blank Vote policy option in the contest

### ISSUE THREAD

**Issue by lnabergoi** [sequentech/meta#1026]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

The admin portal will need to have the option to configure the Blank vote policy in the back office, allowing the Admin to choose if they want a warning or not in the voting portal.

### Possible Implementation

The policy options should be:
- Allowed
- Show Message
- Show Message and Modal
- Not allowed*

In this case, `Not allowed` means Show Message, Modal and do not allow to continue to the next screen if there's a Blank vote.

The configuration should appear at the contest level in the Admin Portal. Please group all contest level policies inside the Contest > Data > Ballot Design, adding a `Policies` sub-section inside there. 

### Tasks

# Screenshots
**Show modal and allow next option:**

https://github.com/user-attachments/assets/3e5c1dd5-09d4-44e4-ab44-d14d6377d5f1

**Show modal and warnings in voting portal depending on configuration:**

https://github.com/user-attachments/assets/a764f30c-a298-4f45-85bb-54e69b779f1f

<img width="1042" alt="Screenshot 2024-07-22 at 14 26 40" src="https://github.com/user-attachments/assets/c85eee02-8e46-4855-89bc-fe8712ba5855">

```[tasklist]
# Tasks
- [x] Add the contest to the election config presentation section [rust, backend]
- [x] Voting-portal
- [x] Add the option to the contest ballot style [rust, backend]
- [x] Admin-portal: implement the option in ballot design
- [x] adding a Policies sub-section
- [x] Admin portal & Server - change options to Allowed, Show Modal and allow, Not allowed
- [x] Voting-Portal: Add warning and error while configuring the ballot
- [ ] Add unit tests for `errors.implicit.blankVote`  
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/576
```
