### ISSUE TITLE
✨ Add Blank vote explicit option

### ISSUE THREAD

**Issue by lnabergoi** [sequentech/meta#1027]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Add an option to create explicit blank votes in the system in the same way that is now managed for invalid/null votes

### Tasks

# Screenshots

Admin portal:

![Image](https://github.com/sequentech/meta/assets/3913223/1257d128-fe05-4def-a7bc-064bd2696999)

Voting portal - selection screen.

![Image](https://github.com/sequentech/meta/assets/3913223/9b490c6c-07f2-49d2-bb2c-f92801bbd22a)

Voting portal - review screen.

![Image](https://github.com/sequentech/meta/assets/3913223/ffdc44d2-865e-45bf-9449-24ee321f8ebf)

Admin portal - Dashboard - Login url (see bottom):

![Image](https://github.com/sequentech/meta/assets/3913223/04930828-0b38-4dde-83ad-120f4c20702b)

<empty>

```[tasklist]
# Tasks
- [x] Enable configuring a candidate as an explicit blank vote from the `admin-portal`.
- [x] Show explicit blank vote in the `voting-portal`.
- [x] Create sequent-core function that generates the voting portal login url.
- [x] Use sequent-core function in the `admin-portal` to show the voting portal login url.
- [ ] Modify deployments to include new env/config var `VOTING_PORTAL_URL` in the admin-portal deployment.
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/546
- [ ] https://github.com/sequentech/gitops/pull/493
- [ ] https://github.com/sequentech/gitops/pull/494
```
