### ISSUE TITLE
✨ Deploy the 2nd gen system for CICCP

### ISSUE THREAD

**Issue by lnabergoi** [sequentech/meta#1029]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Deploy the last release of the 2nd gen system in AWS in **EUROPE**

USE the following URL:  `colegiocaminos.sequent.vote`

Ensure SMS and email features are working

### Tasks

# Screenshots

<empty>

```[tasklist]
# Tasks
- [x] Deploy the environment
- [x] Check Admin Portal Login
- [x] Check Emails
- [x] Check SMS
- [ ] Trustee ceremony
- [ ] Tally
```

```[tasklist]
# Main PRs
- [X] https://github.com/sequentech/gitops/pull/352
- [X] https://github.com/sequentech/infrastructure/pull/46
- [X] https://github.com/sequentech/backend-services/pull/486
```

**Comment by edulix** [comment]
I've checked and admin portal login was not working to me because the admin-portal realm didn't have disabled the ISS query param. I've fixed that. Please fix the SMS messaging and do a whole electoral process including a tally.

**Comment by angelAtSequent** [comment]
Im not sure how to test the remaining two points :(
