### ISSUE TITLE
✨ Edit voting portal texts for each Election Event

### ISSUE THREAD

**Issue by lnabergoi** [sequentech/meta#1030]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

As an Admin User
I want to be able to edit all the text in the voting portal, including 'error/warning' messages, button labels, and information text...

### Possible Implementation

Do be discussed

### Tasks

# Screenshots

# Video

https://github.com/sequentech/meta/assets/171477957/09566098-8adb-451d-9fb2-a3b41e2dd916

https://github.com/sequentech/meta/assets/171477957/a1e54e36-2b61-4e99-879c-bc1890435c21

<empty>

```[tasklist]
# Tasks
- [x] Add a tab with a table of keys and values for customizing texts for any language in the voting portal. should be part of the election event or election presentation, and should be part of the ballot style.
- [x] Make sure Voting portal overwrites defaults based on prentation ballot style translations
- [x] Ensure edited texts are imported and exported with the election events
- [x] Update "Texts" to "Localization"
- [x] Place select languages and Add button on same row
- [x] Change Select Languages input to show full language text - en to english
- [x] Make value input in Admin-portal - Support multi line
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/537
```
