### ISSUE TITLE
✨ Rename 2nd-gen repos

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1038]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

`backend-services`  -> `step`
`infrastructure` -> `beyond`

### Tasks

```[tasklist]
# Tasks
- [x] Rename repositories
- [x] Update any reference in code to old repos
- [x] Update any documentation reference to old repos
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/meta/pull/1094
- [ ] https://github.com/sequentech/gitops/pull/367
- [ ] https://github.com/sequentech/infrastructure/pull/47
- [ ] https://github.com/sequentech/backend-services/pull/490
- [ ] https://github.com/sequentech/cd/pull/13
```

**Comment by angelAtSequent** [comment]
I don't have permissions to rename repositories :(

**Comment by angelAtSequent** [comment]
https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository

**Comment by angelAtSequent** [comment]
@edulix renamed these two repositories

**Comment by edulix** [comment]
For reference:
- @Findeton found out trustees didn't work after the renaming in the codespaces (see https://github.com/sequentech/meta/issues/1096)
- @angelAtSequent please review documentation in gitops repo (`docs/` folder) referring to "infrastructure" repo or `backend-services` repo, and update.

**Comment by angelAtSequent** [comment]
> For reference:
> 
>     * [@Findeton](https://github.com/Findeton) found out trustees didn't work after the renaming in the codespaces (see [🐞 trustees don't work after repo name change #1096](https://github.com/sequentech/meta/issues/1096))
> 
>     * [@angelAtSequent](https://github.com/angelAtSequent) please review documentation in gitops repo (`docs/` folder) referring to "infrastructure" repo or `backend-services` repo, and update.

I've opened a few PRs changing all the references I found to backend-services and infrastructure.
The fix @Findeton addressed was already identified in my PRs.

Anyway, give it a look to the PRs, then merge whenever you consider :)
