### ISSUE TITLE
✨ Under Vote notification

### ISSUE THREAD

**Issue by OmerN-Moveo** [sequentech/meta#1044]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Add toggle to contest edit on Admin Portal to determine whether to show under vote notifications.
Update DB to include this field.
Implement notification in Voting Portal

### Tasks

# Screenshots

![Image](https://github.com/sequentech/meta/assets/171477957/33e1007c-bb9e-43d5-9d4d-4393b9d5903c)

<empty>

```[tasklist]
# Tasks
- [x] Adding the inavlid_alerts vec! to the contest struct
- [x] Add sequent-core wasm validation for undervote
- [x] Create unit test for undervote and overvote cases
- [x] Add undervote message in translation files
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/482
- [ ] https://github.com/sequentech/backend-services/pull/484
```

**Comment by Findeton** [comment]
Hi @OmerN-Moveo   I'm adding the comment here because we need to merge this first PR (please continue in another PR with the exact same branch name):

* We prefer not to use booleans, and use other structures instead (for example enums), as they are more easily extensible.
* Now that we have multiple deployments, we need to take backward-compatibility and graceful degradation seriously. Basically you need to think about what happens if different versions of the code collide somehow. In this case it could be possible that the new version of the voting portal is reading an old ballot style.
* This PR changes the way the ballot looks like and thus the change should be spread over the ballot verifier (in the future we'd want to avoid code duplication). Please ensure this works well in the ballot verifier.
* Note that in the review screen there should be some padding/separation between the warnings and the candidates.
* This doesn't work right away because the sequent-core-0.1.0.tgz packages were not updated, how to fix that is in the README. I've fixed it because we need to merge this but I mention for the future.
* When the voter first sees the contest, the message shouldn't appear, it should be hidden until the voter makes any selection. This behaviour is already implemented here for a similar warning: https://github.com/sequentech/backend-services/blob/761f9947040dfc2c516ab4dcf5dab67f0d0ef099/packages/voting-portal/src/components/InvalidErrorsList/InvalidErrorsList.tsx#L65
* What we actually want is to be able to configure the behaviour of this and other features, for example sometimes the admin user will want this feature to show only the banner/alert as you did. Or sometimes the user will also want to force a confirm dialog when the voter clicks next.
* In order to do that in a generic way, we should create a struct that contains all the PolicyCheck features, something like:

```
interface PolicyCheck {
   confirmation_dialog?: boolean
   not_allowed?: boolean
   explicit_invalid?: boolean
   implicit_invalid?: boolean
}

And then include in the contest presentation something like:

interface ContestPresentation {
   undervote?: PolicyCheck, 
   overvote?: PolicyCheck, 
   selected_min?: PolicyCheck …
}
```

Then the voting-portal can use this information to for example ascertain whether to show a confirmation_dialog or to block the "next" button in the different situations. Also we need an interface in the admin portal to configure these.

Final note: I understand we should have refined the ticket way more than
 we did, and this first approach is nevertheless useful so thanks for 
your good work!

**Comment by OmerN-Moveo** [comment]
Hi @Findeton,
Just to address your notes here so we have everything in-check.

* We prefer not to use booleans, and use other structures instead (for example enums), as they are more easily extensible.
- Got it no problem - if you could please allaborate on the desired behavior of each enum value - for example in the not_allowed field should the next button be disabled alongside the alert being shown?

* Now that we have multiple deployments, we need to take backward-compatibility and graceful degradation seriously. Basically you need to think about what happens if different versions of the code collide somehow. In this case it could be possible that the new version of the voting portal is reading an old ballot style.
- I have checked it compiles and runs - I have resolved in the original PR a resolution revolving a type issue. Everything seems to work fine, if theres any additional logic I should know please feel free to let me know.
- Also regarding backwards compatibility since the struct defininition for the under_vote_alert value is an Option<bool> it wiuld be compatible with different old_ballot design structures.

* This doesn't work right away because the sequent-core-0.1.0.tgz packages were not updated, how to fix that is in the README. I've fixed it because we need to merge this but I mention for the future.
- I have went through the steps in the README.md inside the packages dir - ## Update `sequent-core`, 
and I see the .tgz packages updating - I have opened a new PR resolving the critical issues initially so if you could take a look that the .tgz is updated correctly and there wasn't any issues on my end that would be great. (The PR will be the 2nd under Main PRs in this ticket)


* When the voter first sees the contest, the message shouldn't appear, it should be hidden until the voter makes any selection. This behaviour is already implemented here for a similar warning
- Resolved in the new PR

* What we actually want is to be able to configure the behaviour of this and other features, for example sometimes the admin user will want this feature to show only the banner/alert as you did. Or sometimes the user will also want to force a confirm dialog when the voter clicks next.
In order to do that in a generic way, we should create a struct that contains all the PolicyCheck features...
- No problem - I got your desired behaviour overall but would love some more clarity on the specific behaviour of each use case + any additional presentation configuration we want to implement this on (Or just set the infrastructure and just convert under_vote to use it).


Thanks in advance.

**Comment by edulix** [comment]
@OmerN-Moveo please update the subtasks list, by adding any subtasks there and checking them while you do them. Other than that, great work!
