### ISSUE TITLE
Check encryption variables on ballot verifier

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#105]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

new-ballot-verifier: we should check that the constant encryption variables correspond to the ones used in verificatum/strand. See https://github.com/sequentech/sequent-core/pull/16#discussion_r1212182574

### Tasks

```[tasklist]
# Tasks
- [ ] Update strand to export/publish constants.
- [ ] Update sequent-core to use the new version of strand.
- [ ] Check constants on the auditable ballot and show error if they don't match.
```

```[tasklist]
# Master PRs
- [ ] strand
- [ ] sequent-core
```

```[tasklist]
# Stable PRs
- [ ] 
```

**Comment by edulix** [comment]
We are now targeting on using the verifier with the 2nd-gen so this is not needed
