### ISSUE TITLE
🐞 Link on blank vote

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#1058]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

In 1st gen, if the election allows blank vote and the first candidate has a link, the link will show up in the blank vote in the review screen.

<img width="1207" alt="Screenshot 2024-06-03 at 15 02 36" src="https://github.com/sequentech/meta/assets/3913223/a1583891-818a-4f02-bf0b-0f6a0bfe4f4e">

### Expected Behavior

No link on blank vote

### Steps To Reproduce

-

### Environment

- **OS**: Mac OS X Ventura
- **Web browser**: Google Chrome 112.0.5615.137 (Official Build) (arm64)
- **Sequent Platform Version**: 10.0.0

### Tasks

```[tasklist]
# Tasks
- [ ] Issue has been triaged
- [ ] Successful replication of the defect
- [ ] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/voting-booth/pull/447
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/voting-booth/pull/446
```
