### ISSUE TITLE
🐞 Allow to log out from the voting portal error screen

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1059]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

If you get an error screen in voting portal, there's no button to log out. But it turns out that logging out might be needed, sometimes, to resolve the error.
![image](https://github.com/sequentech/meta/assets/81968/dfec12a7-d889-4879-8021-dedad983c79c)

### Expected Behavior

Don't show the normal header with the profile icon in the top right. Instead, show there a Logout button, which should erase all cookies related to login.

### Steps To Reproduce

-

### Environment

-

### Screenshot

![Image](https://github.com/sequentech/meta/assets/171477957/60f71fdf-cbe2-411f-b6f3-c319f9c5ca8b)

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [x] Create header error variant enum to differ header behavior in ui-essentials
- [x] Create a header variant where only the logout button is rendered
- [x] Have the logout button clear all cookies and redirect user
- [x] Handle keycloak uninitialized issue - where the keycloak logout function is unavailable
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/485
```

**Comment by edulix** [comment]
@OmerN-Moveo please update the subtasks list, by adding any subtasks there and/or checking them while you do them. Other than that, great work!
