### ISSUE TITLE
✨ Release 8.0.0

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#106]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

New major release.

### Tasks

```[tasklist]
# Tasks
- [x] Tag the release
- [x] Test the release
- [x] Deploy release in 8xx deployment
- [x] Deploy release in demo
- [x] Deploy release in web-demo
- [x] Remove old branches (6.x.x, 7.1.x, 7.2.x, 7.3.x)
- [ ] Create releases with automatic release notes in github
```

```[tasklist]
# Master PRs
- [ ] 
```

```[tasklist]
# Stable PRs
- [ ] Task 1
```

**Comment by edulix** [comment]
There seems to be an issue with release notes so I'll tag and deploy today, resolve those issues and create the release notes tomorrow
