### ISSUE TITLE
🐞 Cache-policy not set in JWKS in S3

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1060]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

Currently, when importing an election event, a new key should be added to JWKS file so that hasura can use it. But hasura only gets the new keys after cache expiration, and the file has no cache expiration.

We should fix that using indication of https://chatgpt.com/share/e/b7eb16ea-f095-4578-a58d-c74730997d80 in `s3.rs` function `upload_file_to_s3()`, we should add an `cache_control: Option<u16>` header there and use it when importing elections events or creating new election events (`upsert_keycloak_realm()` function)

### Expected Behavior

-

### Steps To Reproduce

-

### Environment

-

### Tasks

```[tasklist]
# Tasks
- [x] Add the cache policy for the jwks files as an env var
- [x] Modify the upload_file_to_s3 and add the cache policy when it passed
- [x] Test it
- [x] Add the env var to the infrastructure and gitops repos
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/488
- [ ] https://github.com/sequentech/gitops/pull/368
- [ ] https://github.com/sequentech/beyond/pull/48
```

### Screenshots

![Image](https://github.com/sequentech/meta/assets/33923561/8b6e6d3f-7782-4e0e-94b6-f3648bde9bb6)
