### ISSUE TITLE
🐞 Fix  account context menu in voting portal

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1061]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

Account menu for voters in voting portal is broken:
<img width="634" alt="image" src="https://github.com/sequentech/meta/assets/81968/3b65df4a-f8b0-44a6-8c7b-c41a0c36fa14">

### Expected Behavior

It should look similar to account menu in admin portal:
<img width="634" alt="image" src="https://github.com/sequentech/meta/assets/81968/ac6107db-2fd2-4b2d-852a-9ff639cd8c1f">

### Steps To Reproduce

-

### Environment

-

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Implement no user profile when no username & Email is forwarded
- [x] If Email/Username is empty string dont render block
- [x] Create better Loader reusable component
- [x] Implement lazy loading
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/513
```

#Screenshot

![Image](https://github.com/sequentech/meta/assets/171477957/59af1143-11b5-40e7-a3ee-c9e1954e0a27)
