### ISSUE TITLE
🐞 invalid vote policy  (not allowed) isn't working

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#1062]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

invalid vote policy  (not allowed) isn't working.

### Expected Behavior

-

### Steps To Reproduce

[Example](https://voting-portal-staging.sequent.vote/tenant/90505c8a-23a9-4cdf-a26b-4e19f6a097d5/event/f[…]lection/abdc527e-be1f-4a06-998d-0929f28d72f8/review)

### Environment

-

### Tasks

```[tasklist]
# Tasks
- [x] Successful replication of the defect
- [x] Change error filtering logic and seperate between alerts rendering and next button dialog show
- [x] Change show dialog logic to accept different policy case
- [x] Implement Logic in wasm
- [x] Fix alerts and errors and state handlers
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/507
```

### Screenshot

![Image](https://github.com/sequentech/meta/assets/171477957/76035765-79d8-4637-9c28-be312912082b)
