### ISSUE TITLE
✨ Hierarchical areas, results consolidation

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#1063]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Hierarchical areas, results consolidation

### Possible Implementation

```[tasklist]
# Implementation
- [x] Areas should either be roots or have parent areas. The number of steps to go from an area to their root area is their level.
- [x] There should be a unique ballot style for each area, independently of their level.
- [x] Users should be able to assign contests to any area at any level.
- [x] When you assign a contest to an area, the contest will appear in the ballot styles of that area and of any shallower levels (lower number).
- [ ] If a contest is assigned to a level, it cannot be assigned to areas of shallower levels.
- [ ] If a contest is assigned to a level, for the areas at that level there will be only one result in the tally. For areas of shallower levels there will be the results for that shallower level and also the consolidation that includes the deeper levels.
```

### Tasks

# Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Main PRs
- [ ] PR 1
```

**Comment by edulix** [comment]
Duplicate of #1020
