### ISSUE TITLE
✨ Admin Portal - Export Logs

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1087]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Implement the Export Logs for the Election Event Logs. The export button is already shown in the Admin Portal. It should be implemented as a background task that happens in background, the export logs is created as CSV file uploaded to S3, the frontend should pool like in other cases until this is fixed, and then download the S3 file when available. Add also a dialog confirming the user wants to do an export.

Basically, it should behave and be implemented in a similar way to how we implement Election Event > Data > Export.

### Tasks

# Screenshots

The integration where this feature should be hooked in the Admin Portal UI:
<img width="1440" alt="image" src="https://github.com/sequentech/meta/assets/81968/a35a32a1-abe9-4c18-b965-becf7aae68ee">

```[tasklist]
# Tasks
- [x] Create hasura action to trigger harvest
- [x] Create harvest endpoint to trigger windmill action
- [x] Create windmill action to store file in S3
- [x] Create UI Logic in Admin Portal
- [x] Update downloadUrl ui-essentials function to download instead of open new window
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/500
```

### Additional context

# Video

https://github.com/sequentech/meta/assets/171477957/acf6cbd5-17b3-4f6c-8c4a-381fb3500c4a

_No response_

**Comment by OmerN-Moveo** [comment]
@edulix I filtered out the document option from the method options
But I see the document option is seen in other places such as election-receipts 
Let me know if you want to remove the document from the enum or this is indeed intended as a non-voter communication method.


![Image](https://github.com/sequentech/meta/assets/171477957/1575bdd0-0752-459d-9856-c07079c09bdf)
