### ISSUE TITLE
✨ Add unit tests to our Keycloak modules

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1088]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Add unit tests to our Keycloak modules. Also add a Github Action that runs these unit tests.

### Tasks

```[tasklist]
# Tasks
- [x] Unit testing for AwsSesEmailSenderprovider, DummyEmailSenderProvider
- [x] Unit Testing for Module: Conditional Authenticators, finished: ConditionalEmailVerifiedTest, ConditionalHasUserAttributeAuthenticatorTest, ManualVerificationTokenTest, RemoveUserAttributeTest
- [x] Keycloak Extensions, all modules test
- [x] Add Github Actions for Unit Testing - Pom Files restored, might add to code lines changed count
- [x] Fixing Github Action
- [x] Clear dead codes, and other warnings
- [x] Add formator to github actions for java
- [x] Updating format-code run task to apply also linting for java
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/496
```
