### ISSUE TITLE
✨ Onboarding/enrollment URL for voters

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1093]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Add registration support to the platform. See the subtasks below.

### Tasks

```[tasklist]
# Tasks
- [x] Add a `/action/enroll` path to voting portal that should call to `await keycloak.login(action: 'register')` for enrollment.
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/616
```

### Screenshots

https://github.com/user-attachments/assets/ffe29c28-41a0-46a2-8ea8-57772a776e1b

**Comment by yvwbimpong** [comment]
https://github.com/user-attachments/assets/ffe29c28-41a0-46a2-8ea8-57772a776e1b
