### ISSUE TITLE
🐞 Increase default pagination size

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#1095]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

Page size is 10.

### Expected Behavior

Default page size is 10.

### Steps To Reproduce

-

### Environment

- **OS**: Mac OS X Ventura
- **Web browser**: Google Chrome 112.0.5615.137 (Official Build) (arm64)
- **Sequent Platform Version**: 10.0.0

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [x] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/iam/pull/347
- [ ] https://github.com/sequentech/admin-console/pull/428
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/iam/pull/346
- [ ] https://github.com/sequentech/admin-console/pull/427
```

**Comment by sergiydmukhinepi** [comment]
@Findeton It looks like the default value, but in the voting booth (census request) you set the number of items explicitly.

**Comment by edulix** [comment]
Seems like this was merged already so closing it
