### ISSUE TITLE
🐞 Admin Portal - Tally - Text Editable checkbox

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1097]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

When clicking or double clicking in the checkbox to choose the elections to be tallied in the Tally Ceremony, it turns the checkbox:
<img width="1382" alt="image" src="https://github.com/sequentech/meta/assets/81968/797f69da-0ac7-49f8-a619-9e717d94dcda">

In an editable field with text:
<img width="1382" alt="image" src="https://github.com/sequentech/meta/assets/81968/152d6d9c-7cea-4d35-a474-05374568a814">

Also happens in the same widget, in the second screen of the tally:
<img width="1382" alt="image" src="https://github.com/sequentech/meta/assets/81968/92562617-e7f0-4f44-be37-1fda1a1f6074">

### Expected Behavior

It should not happen and remain a normal checkbox.

### Steps To Reproduce

-

### Environment

-

### Tasks

```[tasklist]
# Tasks
- [x] Successful replication of the defect
- [x] Fix issue
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/504
```
