### ISSUE TITLE
🐞 Admin Portal - Voters - Send Communications should not have Document as method

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1100]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.

### Current Behavior

Send Communications to voters (or users) should not have Document as method, that should be hidden. But it shows below:
<img width="1439" alt="image" src="https://github.com/sequentech/meta/assets/81968/a9bd0c78-20c7-4880-8084-e8c6ea26a5d9">

### Expected Behavior

-

### Tasks

```[tasklist]
# Tasks
- [x] Successful replication of the defect
- [x] Filter document type for voters communication method
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/501
```
#Screenshot

![Image](https://github.com/sequentech/meta/assets/171477957/ec10d5f0-3393-41d7-9fe5-d61e72e3d372)

```
