### ISSUE TITLE
✨ Admin Portal - Publish - improve UI performance

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1109]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Improve performance of the publish screen, that is slow to render (backend is not here at play):
 
<img width="1440" alt="image" src="https://github.com/sequentech/meta/assets/81968/5c2953bf-7029-462c-9110-d3375ffd0366">

### Possible Implementation

Add a "Show All" button when there are too many lines.

Right now we have added `...` as the last line when truncating the view. In the screenshot below it's truncated after 10 lines for testing, but we will use 500 lines by default:
<img width="1440" alt="image" src="https://github.com/sequentech/meta/assets/81968/b6c47090-a749-4c7b-833a-98487c1b052e">

### Tasks

```[tasklist]
# Tasks
- [x] Implement a basic truncate of the lines being rendered
- [x] Add a show all button below, when lines have been truncated
- [x] Move MAX_DIFF_LINES to an env var
- [x] Create Dialog warning users from untruncate operation
- [x] Add limit field to publication fetching to limit ballotStyles
- [x] Add function to fetch all publication ballotStyles- alerting user that this may cause browser render to cause inactivity
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/498
- [ ] https://github.com/sequentech/step/pull/506
- [ ] https://github.com/sequentech/gitops/pull/392
- [ ] https://github.com/sequentech/beyond/pull/51
```

### Screenshots

![Image](https://github.com/sequentech/meta/assets/171477957/d0af8379-1049-40e6-9c8c-a4ae18c0749c)
![Image](https://github.com/sequentech/meta/assets/171477957/a421fc78-f259-475b-9e5e-178194915992)
![Image](https://github.com/sequentech/meta/assets/171477957/84c3371d-d464-41ae-b6bb-9acaf47ce291)

#Video

https://github.com/sequentech/meta/assets/171477957/e5d4970d-0c12-41f0-a7ae-9607f830f875

### Additional context
In order to easily see this you can change the default MAX_DIFF_LINES ?? 
To be a low number like 10.
It is set inside DiffView.tsx

_No response_
