### ISSUE TITLE
✨ Admin Portal - Area - Use `AutocompleteArrayInput` in EditArea Contests selection

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1125]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Admin Portal - Area - Use `AutocompleteArrayInput` in EditArea Contests selection:

https://marmelab.com/react-admin/AutocompleteArrayInput.html

### Possible Implementation

-

### Screenshots

<empty>

```[tasklist]
# Tasks
- [x] Switch to AutocompletArrayInput Component
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/502
```

### Additional context

#Screenshot

![Image](https://github.com/sequentech/meta/assets/171477957/7c0589a0-e8b7-4d36-96ba-1ed2a51e10ef)

_No response_
