### ISSUE TITLE
🐞 Add public demo key to infrastructure repos

### ISSUE THREAD

**Issue by omri81** [sequentech/meta#1126]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.

### Current Behavior

Env var public demo key is not be added to infrastructure repos.

### Expected Behavior

Env vars should be added to infrastructure repos.

### Tasks

```[tasklist]
# Tasks
- [x] Add to beyond repo
- [x] Add to gitops repo
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/beyond/pull/50
- [ ] https://github.com/sequentech/gitops/pull/391
```
```

**Comment by omri81** [comment]
Parent issue:

**Comment by angelAtSequent** [comment]
From what I see... is it ok to have the same public key in all environments/installations? Wouldn't it make more sense to have a different key for each environment? At least for production

**Comment by edulix** [comment]
Yes it's ok, it's a demo public key.

**Comment by edulix** [comment]
> From what I see... is it ok to have the same public key in all environments/installations? Wouldn't it make more sense to have a different key for each environment? At least for production

Yes it is. I've merged the original ticket https://github.com/sequentech/meta/issues/575 and approved these changes. I'll let @angelAtSequent  and @torgus manage merging this one. We can speak about how to do it later today.
