### ISSUE TITLE
🐞 CICCP deployment issue windmill AWS_REGION is wrong

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1127]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.

### Current Behavior

AWS_REGION env var for windmill service is set to `us-east-1` but it should be `eu-west-1`:

```
2024-06-13T22:42:57.553661107Z │  │  ├──759ms ERROR error=Error uploading file to S3
2024-06-13T22:42:57.553664414Z │  ├──┘
2024-06-13T22:42:57.553696449Z │  ├──760ms ERROR error=Error uploading file to s3
2024-06-13T22:42:57.553707592Z ├──┘
2024-06-13T22:42:57.554604912Z ├──  1s  ERROR error=Anyhow(Error uploading file to s3
2024-06-13T22:42:57.554616313Z │  
2024-06-13T22:42:57.554619907Z │  Caused by:
2024-06-13T22:42:57.554623437Z │      0: Error uploading file to S3
2024-06-13T22:42:57.554626539Z │      1: service error
2024-06-13T22:42:57.554629575Z │      2: unhandled error (AuthorizationHeaderMalformed)
2024-06-13T22:42:57.554633041Z │      3: Error { code: "AuthorizationHeaderMalformed", message: "The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-1'", aws_request_id: "CNY9N9YBCY03GQ5Q", s3_extended_request_id: "P7UIwMedc2cvHSPyv6F4JJ3cYkn5w4xLWvLG1alItwz6mwmA/J+K4zzShtyxzbQvHhxMacSdObc=" })
```

This is also confirmed in openlens env vars view:

<img width="725" alt="image" src="https://github.com/sequentech/meta/assets/81968/2d5dd245-cd58-409e-bc49-82b52906193f">

### Expected Behavior

It should be corrected. Please also comment how you fixed it and where. It might be also incorrectly set in other pods and environments.

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [ ] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/gitops/pull/390
```
```

**Comment by angelAtSequent** [comment]
The issue was not to override the default values present on different helm charts.

- AWS_REGION: Defaulted to us-east-1.
- repository (ecr - container images): Defaulted to the ECR available in us-east-1.

The 1st one (AWS_REGION) caused AWS signature to be invalid on windmill components. The 2nd one accelerates a lot the rollout of new versions. Nothing critical.

You can find these default values here:

- https://github.com/sequentech/beyond/blob/main/helm-charts/windmill/values.yaml#L8
- https://github.com/sequentech/beyond/blob/main/helm-charts/windmill/values.yaml#L92
- https://github.com/sequentech/beyond/blob/main/helm-charts/frontend/values.yaml#L79

among others
