### ISSUE TITLE
✨ Deploy the 1nd gen system for SECOT

### ISSUE THREAD

**Issue by lnabergoi** [sequentech/meta#1129]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Deploy the last release of the 1nd gen system in AWS in EUROPE

USE the following URL: secot.sequent.vote

### Tasks

# Screenshots

<empty>

```[tasklist]
# Tasks
- [x] Deploy the environment
- [x] Check Admin Portal Login
- [x] Check Emails
- [ ] Check SMS
- [ ] Trustee ceremony
- [x] Tally
```

```[tasklist]
# Main PRs

```

**Comment by Findeton** [comment]
@lnabergoi @edulix I've been unable to make sms work, although I copied the config from the `olyusei` config.
