### ISSUE TITLE
🐞 Fix css issues on admin console

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#113]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Current Behavior

When creating an election, on the questions tab:
- The title is overlapped.
- Candidates look strange on mouseover.

### Expected Behavior

When creating an election, on the questions tab:
- The title is not overlapped or has a solid background.
- Candidates look good on mouseover.

### Steps To Reproduce

<img width="1064" alt="Screenshot 2023-06-08 at 11 53 32" src="https://github.com/sequentech/meta/assets/3913223/340604a6-797f-4ec5-a23a-35e394c7a641">

### Environment

```markdown
- OS:
- Web browser:
```

### Tasks

```[tasklist]
# Tasks
- [ ] Fix questions title
- [ ] Fix candidates mouseover
```

```[tasklist]
# Master PRs
- [ ] 
```

```[tasklist]
# Stable PRs
- [ ] Task 1
```
