### ISSUE TITLE
🐞 Admin Portal - Fix Area Lookup in multiple places

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1130]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.

### Current Behavior

Admin Portal - Area Lookup in multiple places:
- Tally Sheets
- Edit Area

Doesn't work when there are many areas because of pagination.

### Expected Behavior

Should work well:
- should allow to filter by typing and then selecting a matching area
- Should not allow to select itself
- Should allow to filter with a debounce period
- Should filter correctly even with long area list (import this election event for testing: 
[export-election-event-d6f7fb00-ba29-46da-af1b-12194ef027f1.json](https://github.com/user-attachments/files/15856668/export-election-event-d6f7fb00-ba29-46da-af1b-12194ef027f1.json)
)
- when filtering it should not have strange behaviors like the text changing unexpectedly

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [x] Adding name filter to areas fetch
- [x] add debounce to autocomplete inputs
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/509
```

# Video

https://github.com/sequentech/meta/assets/171477957/fe519fc3-0a72-467c-abd4-b24267bf7238
