### ISSUE TITLE
✨ Create Graphql documentations 

### ISSUE THREAD

**Issue by omri81** [sequentech/meta#1148]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Create a documentation for the graphql apis 

### Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] Search for the best available free open source documentation generator
- [ ] implement initial documentation 
```

```[tasklist]
# Main PRs
- [ ] PR 1
```
