### ISSUE TITLE
🐞 Admin Portal - Small Issues related to Key Ceremony

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1157]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.

### Current Behavior

There's some issues with the key ceremony that need to be resolved. See a recording below:

https://github.com/sequentech/meta/assets/81968/1729ae46-8f9c-48bc-b93e-76d7b2f05640

### Expected Behavior

These issues should be resolved/improved.

### Screenshots

This is how it looks after fixing:

<img width="1440" alt="image" src="https://github.com/sequentech/meta/assets/81968/4e5455f2-5819-4aa5-91ef-6854c62ee2ea">

### Tasks

```[tasklist]
# Tasks
- [x] Sometimes the message `Added message Configuration for batch 0` is repeteated
- [x] The log messages should mention the trustee number, otherwise look repeated. For example `Added message ConfigurationSigned for batch 0` should be `Trustee #0: Added message ConfigurationSigned for batch 0`
- [x] Sometimes the Key Ceremony Screen shows some trustee without having generated the Key Fragment, but still this trustee can actually download and check the fragment, and after that this checkmark is fixed.
- [ ] Add tests for this behavior
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/516
```

**Comment by xalsina-sequent** [comment]
Task 1:
The message were repeated due to the fact that the function to check new logs was appending all logs. If the process took a long time to finish (for example trustees not generating key fragments) the logs were constantly duplicating. 

I've added a fix by filtering out the old logs by checking using the timestamp since last update.

Task 2:
I've set the message serializers to use the message sender. For trustees I'm setting the sender name by tanking the TRUSTEE_NAME env variable.

Task 3:
The data for the ceremony stops updating as soon as the election_event gets a public key.
I've to check if I can add an additional contition so it keeps updating or if I update the ceremony status inside each trustee when the fragment is generated.
