### ISSUE TITLE
✨ Java code linting and 80 chars max

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1177]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Incorporate Java Code into our code linting facilities: Github Actions, Codespaces, VS Code Tasks

### Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] Check linting in the `Lint & Prettify` Github Action
- [ ] Ensure code linting can easily happen within the VSCode Devcontainer: the linting binary is installed etc
- [ ] Add Java code linting in the VScode `tasks.shared.json` task called `format.code`
- [ ] Change code linting to always be (in all languages) at 80 characters instead of current 100 characters per line
```

```[tasklist]
# Main PRs
- [ ] PR 1
```

**Comment by edulix** [comment]
Already done
