### ISSUE TITLE
✨ Release 8.0.1

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#118]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

New patch release.

### Tasks

```[tasklist]
# Tasks
- [x] Tag the release
- [x] Create releases with automatic release notes in github
- [x] Test the release
- [x] Deploy release in 8xx deployment
- [x] Deploy release in demo
- [x] Deploy release in web-demo
```

```[tasklist]
# Master PRs
```

```[tasklist]
# Stable PRs
```
