### ISSUE TITLE
🐞 add census data second batch will not be executed

### ISSUE THREAD

**Issue by ElectricPaperInformationssystemeGmbH** [sequentech/meta#119]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Current Behavior

Regardless of the size of the parameter sequent_ui.census_import_batch, the first x-voters from the first batch will be added. The second batch no longer starts.

### Expected Behavior

All voters will be added sequentially in batches to the census data

### Steps To Reproduce

1. create some election with sequent_ui.census_import_batch = 1000
    json to create the election 
    https://gist.github.com/ElectricPaperInformationssystemeGmbH/fcda9bbb19797cd711a98f37e7abf1bc
2. try to add more thane 1000 voter at once as csv
csv file https://gist.github.com/ElectricPaperInformationssystemeGmbH/ba67acaa443262d6acc6b379bd5f9143

### Environment

```markdown
- OS:
- Web browser:
```

### Tasks

```[tasklist]
# Tasks
- [x] Reduce default page size for the census upload from 500 to 200.
- [x] Increase nginx proxy default timeout from 1 minute to 2 minutes.
- [x] Increase http post query default timeout for census upload to 2 minutes.
- [x] Add config variable to config.yml (`nginx_timeout_secs`) and SequentConfig.js to configure the timeouts aforementioned.
- [x] Pre-emptively call `ping` to renew the auth token in admin-console before each census upload page call to avoid race condition.
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/deployment-tool/pull/342
- [ ] https://github.com/sequentech/common-ui/pull/322
- [ ] https://github.com/sequentech/admin-console/pull/384
- [ ] https://github.com/sequentech/documentation/pull/124
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/documentation/pull/127
- [ ] https://github.com/sequentech/admin-console/pull/387
- [ ] https://github.com/sequentech/common-ui/pull/329
- [ ] https://github.com/sequentech/deployment-tool/pull/344
```
