### ISSUE TITLE
✨ Ability to split Ballot contest in different Pages inside the same election

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1197]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion
Project Reference: https://sequentech.atlassian.net/browse/COM-1521

Ability to split Ballot contest in different Pages inside the same election

### Screenshots

https://github.com/user-attachments/assets/446e3b31-c0c5-4813-b301-c85d5e904f1a

https://github.com/user-attachments/assets/d43fc570-615b-4a4b-96ae-7e7bed5c5ccd

<empty>

```[tasklist]
# Tasks
- [x] Add the option to the election config presentation section [rust, backend]
- [x] Add the option to the election ballot style [rust, backend]
- [x] Implement the pagination in the voting portal
- [x] Implement the option in the admin portal - election data
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/575
```
