### ISSUE TITLE
✨ Improve Login and Registration UI to to match the Voting Portal UI

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1198]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Improve Login and Registration UI to to match the Voting Portal UI. It should look as close as [this figma design](https://www.figma.com/design/bQBFY8aUszCwaTp9mPuOq0/2023-03-02-mock-1---1st-Gen-Sequent-Voting-Booth-Upgrade-(Edu-changes)-(Copy)?node-id=1831-1031&t=3us6uuCa7HtDI8cF-1) below.

The implementation needs to be performed as the sequent-theme in keycloak extensions. 

### Screenshots

Login desktop:

![127 0 0 1_8090_realms_tenant-90505c8a-23a9-4cdf-a26b-4e19f6a097d5-event-b9cfcae8-8173-4ec1-930a-8c4cc926d947_login-actions_authenticate_client_id=voting-portal tab_id=rCGCAGW2Nk0(iPad Air)](https://github.com/sequentech/meta/assets/173030604/2b6bd444-23cf-45b3-9cd0-8a2f78cf36a5)

![127 0 0 1_8090_realms_tenant-90505c8a-23a9-4cdf-a26b-4e19f6a097d5-event-b9cfcae8-8173-4ec1-930a-8c4cc926d947_login-actions_registration_client_id=voting-portal tab_id=rCGCAGW2Nk0(iPad Air)](https://github.com/sequentech/meta/assets/173030604/d7bca886-eea6-45a0-9116-ff50e790c0e0)

![127 0 0 1_8090_realms_tenant-90505c8a-23a9-4cdf-a26b-4e19f6a097d5-event-b9cfcae8-8173-4ec1-930a-8c4cc926d947_login-actions_registration_client_id=voting-portal tab_id=rCGCAGW2Nk0(iPad Air) (1)](https://github.com/sequentech/meta/assets/173030604/9dccc89a-c447-43ce-b7f9-8876164eafa4)

Login mobile:

![127 0 0 1_8090_realms_tenant-90505c8a-23a9-4cdf-a26b-4e19f6a097d5-event-b9cfcae8-8173-4ec1-930a-8c4cc926d947_login-actions_authenticate_client_id=voting-portal tab_id=rCGCAGW2Nk0(iPhone SE)](https://github.com/sequentech/meta/assets/173030604/4d544d64-918e-4d4b-906d-54cc3bf88348)

![127 0 0 1_8090_realms_tenant-90505c8a-23a9-4cdf-a26b-4e19f6a097d5-event-b9cfcae8-8173-4ec1-930a-8c4cc926d947_login-actions_registration_client_id=voting-portal tab_id=rCGCAGW2Nk0(iPhone SE)](https://github.com/sequentech/meta/assets/173030604/4dfe32d0-2832-4b5f-ac55-681bb997a4e6)

![127 0 0 1_8090_realms_tenant-90505c8a-23a9-4cdf-a26b-4e19f6a097d5-event-b9cfcae8-8173-4ec1-930a-8c4cc926d947_login-actions_registration_client_id=voting-portal tab_id=rCGCAGW2Nk0(iPhone SE) (1)](https://github.com/sequentech/meta/assets/173030604/2c4d0183-6dde-4c0c-b416-99c4fa1fd060)

```[tasklist]
# Tasks
- [x] Get as close as possible using only css
- [x] Added footer to Keycloak sequent theme
- [x] Improved look of language dropdown
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/530
```

**Comment by xalsina-sequent** [comment]
You can customize the logo using the following customCss

> :root '{' '#'kc-header-wrapper '{' background-image: url'(''https://upload.wikimedia.org/wikipedia/commons/7/73/Commission_on_Elections_%28COMELEC%29.svg'')' !important; '}'

**Comment by xalsina-sequent** [comment]
You can constumize the background with the following loginCustomCss:

> .login-pf body '{' background-image: url(''https://www.colegiocaminos.es/Recursos/Controles/Imagen.aspx?Ruta=/Adjuntos/CICCP/Documentos/GaleriaImagenes/ae1a755a-8f1c-44cc-8e55-a9233495bb27/f70893dc-8192-473e-a537-c1ff0e621ea4.jpg'') !important; '}'

![127 0 0 1_8090_realms_tenant-90505c8a-23a9-4cdf-a26b-4e19f6a097d5-event-b9cfcae8-8173-4ec1-930a-8c4cc926d947_login-actions_authenticate_execution=e8ebf763-31c1-45e4-b127-ce679f5a2beb client_id=voting-portal tab_id=rCGCAGW2Nk0(Nest Hub)](https://github.com/sequentech/meta/assets/173030604/44c7a3f5-0be2-417a-b75a-96108a23a214)

**Comment by Findeton** [comment]
Example with comelec logos and this `loginCustomCss` config:

```:root '{' '#'kc-header-wrapper '{' background-image: url'(''https://upload.wikimedia.org/wikipedia/commons/7/73/Commission_on_Elections_%28COMELEC%29.svg'')' !important; '}' '}' .login-pf body '{' background-image: linear-gradient(1deg, #ffffff, transparent), url(''https://filipinotimes.net/wp-content/uploads/2021/08/COMELEC-scaled.jpg'') !important; '}'```



![Image](https://github.com/sequentech/meta/assets/3913223/5cb26f80-fc95-4306-b289-923ac3df297c)
