### ISSUE TITLE
✨ Improve Voter Profile UI to match Voting portal UI

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1199]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Improve Voter Profile UI to match Voting portal UI. 

### Video

https://github.com/user-attachments/assets/301455dc-ee35-4ee9-9398-fd3deee42931

```[tasklist]
# Tasks
- [x] Re-enable User Profile in Voting Portal Realms ensuring that it works
- [x] Change in beyond repo for the default election event realms config if needed
- [x] Improve Voter Profile UI to match Voting portal UI
- [x] Add draft for react implementation of account page
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/561
- [ ] https://github.com/sequentech/beyond/pull/58
```
