### ISSUE TITLE
✨ Admin-console: Activity log format improvement

### ISSUE THREAD

**Issue by ElectricPaperInformationssystemeGmbH** [sequentech/meta#121]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

data format should show correct date

### Possible Implementation

* Show the date instead of "time ago" and in UTC timezone.
* Modify the table to adjust the body to the header, so that the executer/receiver ids are shown and the date/description are on the right place.

### Screenshots/Implementation

![Image](https://github.com/sequentech/meta/assets/3913223/a229bac3-52a2-4a5e-8a33-0c7c61489478)

### Tasks

```[tasklist]
# Tasks
- [x] Fix log date format.
- [x] Implementation approved by client.
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/admin-console/pull/394
```

**Comment by edulix** [comment]
Can you please add a screenshot of the issue with the Child-Id?

**Comment by ElectricPaperInformationssystemeGmbH** [comment]
> Can you please add a screenshot of the issue with the Child-Id?

already solved. I deleted the parameter __event_id__ from our translation. So it will not appears any more

**Comment by Findeton** [comment]
Hi @ElectricPaperInformationssystemeGmbH please review the screenshot/implementation section.

**Comment by ElectricPaperInformationssystemeGmbH** [comment]
The implementation looks good. Reviewed, thank you.
