### ISSUE TITLE
✨ Admin Multitenancy improvement

### ISSUE THREAD

**Issue by xalsina-sequent** [sequentech/meta#1215]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Here are some improvement to be made to Admin portal

### Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] Add an additional login view to be able to enter a tenant by specifying the TENANT_NAME in a field.
- [ ] Set the new tenant admin password to a random temporal value.
- [ ] Improve the creation of new tenants
```

```[tasklist]
# Main PRs
- [ ] PR 1
```
