### ISSUE TITLE
🐞 Tally sheets errors

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#1216]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.

### Current Behavior

Errors in the tally sheets, described in the tasks list.

### Screenshots

![Image](https://github.com/sequentech/meta/assets/3913223/7775ce48-6489-4bc5-bfd2-fdf2fd48942c)

### Tasks

```[tasklist]
# Tasks
- [x] Number of valid votes should be an input and not automatic. Also fix its validation.
- [x] Census should be an input and not automatic. Also it shouldn't be aggregated to the total census.
- [x] Aggregates for tally sheets don't seem to work on tallies.
- [x] Aggregates for children areas are not calculated when there's only one child.
- [x] Tar gz file extension should be .tar.gz and not .tar_gz.
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/526
```
