### ISSUE TITLE
✨ Deploy the 2nd gen system for UPV

### ISSUE THREAD

**Issue by lnabergoi** [sequentech/meta#1229]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Deploy the last release of the 2nd gen system in AWS in EUROPE

USE the following URL: upv.sequent.vote

Deploy 6 Trustees servers

### Screenshots

<empty>

```[tasklist]
# Tasks
- [x] Deploy the environment
- [x] Check Admin Portal Login
- [ ] Check Emails
- [ ] Trustee ceremony
- [ ] Tally
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/gitops/pull/462
- [ ] https://github.com/sequentech/step/pull/538
- [ ] https://github.com/sequentech/step/pull/539
```

**Comment by angelAtSequent** [comment]
Environment deployed, 

waiting for feedback from @Findeton

**Comment by angelAtSequent** [comment]
I've deployed 4 more trustees as kubernetes pods.
Im not sure how to properly make them working, i mean... Do we need to modify the database (hasura) somehow?

**Comment by angelAtSequent** [comment]
> I've deployed 4 more trustees as kubernetes pods. Im not sure how to properly make them working, i mean... Do we need to modify the database (hasura) somehow?

I've inserted the trustee information (from aws secrets-manager) to hasura (trusstee table).
Not sure if that's the right procedure,
