### ISSUE TITLE
🐞 immudb on Staging not working properly

### ISSUE THREAD

**Issue by angelAtSequent** [sequentech/meta#1230]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.

### Current Behavior

Staging environment is not working properly because immudb is unable to run stable.
This is due to a bug introduced on the immudb release `1.9DOM2`.
As suggested by its main contributor, it would be nice to backup the DB content, destroy the immudb instance, then restore the content from the backup: https://github.com/codenotary/immudb/issues/1997 on a new immudb instance running 1.9.3

### Expected Behavior

We must recover this environment, its broken because of immudb not working properly

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [x] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [x] https://github.com/sequentech/gitops/pull/327
```

**Comment by angelAtSequent** [comment]
Finally opted to cleanup the immudb instance recreating the buckets. Was impossible to recover it.
More information: https://github.com/codenotary/immudb/issues/1997

**Comment by angelAtSequent** [comment]
Staging is back online

**Comment by angelAtSequent** [comment]
[dump-staging-immudb.tar.gz](https://github.com/user-attachments/files/16094884/dump-staging-immudb.tar.gz)
I leave here the dump before purging the bucket where immudb stored the database content. Just in case we need it... (don't think so tbh)
