### ISSUE TITLE
✨ Purgue all immudb volume snapshots

### ISSUE THREAD

**Issue by angelAtSequent** [sequentech/meta#1233]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

It would be nice to save some cost to purgue all (or almost all) immudb snapshots.
Why? Because we've migrated immudb to run on top of S3. S3 already has a huge degree of trust, to enhance its resiliency we replicate to a secondary region the content of the bucket used to run immudb. So its almost impossible to lose data.

### Possible Implementation

Go directly to AWS to the different regions and look for immudb snapshots.
Ask @edulix if we should keep some of them just because of audit proposses.

### Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] Ask @edulix for confirmation
- [ ] Clean up EBS Volume Snapshots on AWS
```

```[tasklist]
# Main PRs
- [ ] PR 1
```
