### ISSUE TITLE
✨ Improve UI of Inetum Authenticator

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1235]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Improve UI of Inetum Authenticator

### Screenshots

https://github.com/sequentech/meta/assets/173030604/a432f758-1327-4312-83fc-8722f3863bc4

```[tasklist]
# Tasks
- [x] Using sequent theme as the main layout
- [x] Making inetum authenticator responsive
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/550
```
