### ISSUE TITLE
✨ Admin-console: Automated voting period start/stop support

### ISSUE THREAD

**Issue by ElectricPaperInformationssystemeGmbH** [sequentech/meta#124]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

We need a way to start and stop elections on a timed basis.

### Possible Implementation

The implementation will use a new field in the authevent called `scheduled_events` to set the start and stop dates of an election, and possibly using it also for other scheduled events later on.

## Implementation description

Changes in the election dashboard:
![image](https://github.com/sequentech/meta/assets/81968/b7c9fab1-a272-4d74-a7da-d3fcd99866bf)

New Configure Scheduled Events dialog:
<img width="691" alt="image" src="https://github.com/sequentech/meta/assets/81968/3f1ba593-2cad-4a9d-b08e-f758bccfc12c">

Datetime selector:
<img width="691" alt="image" src="https://github.com/sequentech/meta/assets/81968/b2cc4ad6-4458-41ed-8573-8c3b271fd51e">

Notification of change of successful scheduled events selector:
<img width="1064" alt="image" src="https://github.com/sequentech/meta/assets/81968/6b921393-8c6a-4994-a603-800ebe5f5959">

Changes reflected in the activity log:
<img width="1064" alt="image" src="https://github.com/sequentech/meta/assets/81968/9cd59a43-165d-400d-84cf-b5679823bdef">

### Tasks

```[tasklist]
# Tasks
- [x] iam: Develop API to set/unset election start/stop election json date, including support for parent/children elections
- [x] ballot-box: admin console command to set start/stop dates
- [x] common-ui: Update Election Creation JSON to send the start/stop date to IAM
- [x] admin-ui: log revoked/set scheduled events in activity log
- [x] admin-ui: Update Dashboard to show start and stop election dates
- [x] admin-ui: Add action to set scheduled events (start/stop automation)
- [x] deployment: ensure deployments accommodates for long scheduled events
- [x] Documentation: election json update for how start/stop automation works
- [x] Documentation: add guide for scheduled events configuration
- [x] Implementation approved by client
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/iam/pull/297
- [ ] https://github.com/sequentech/documentation/pull/134
- [ ] https://github.com/sequentech/ballot-box/pull/179
- [ ] https://github.com/sequentech/common-ui/pull/344
- [ ] https://github.com/sequentech/admin-console/pull/398
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/ballot-box/pull/177
- [ ] https://github.com/sequentech/common-ui/pull/342
- [ ] https://github.com/sequentech/admin-console/pull/395
```

**Comment by edulix** [comment]
Suggestion: Within the scope of this ticket, I would suggest to implement an Action in the Election Dashboard to be able to change the start or stop date. Otherwise, maybe for some operational reason the start and/or stop date needs to change and you wouldn't be able to do it, it would still be automated to the wrong date.

**Comment by markgrafd** [comment]
Please use separate date-time-pickers for both start and stop and allow both start and stop to be disabled or reset. It should be possible to use the time control independently of the generation of the election.

Optionally, it should also be possible to allow and start the tally automatically. Maybe you build this in later or implement it directly if this reduces the overall effort.

**Comment by edulix** [comment]
@ElectricPaperInformationssystemeGmbH please review and accept the implementation section or give us feedback before we merge the ticket.

**Comment by ElectricPaperInformationssystemeGmbH** [comment]
@edulix What about the start and stop parameters from the election config json file? Can the parameters be used to control scheduled start and stop?
https://sequentech.github.io/documentation/docs/general/reference/election-creation-json#election-start_date

**Comment by edulix** [comment]
> @edulix What about the start and stop parameters from the election config json file? Can the parameters be used to control scheduled start and stop? https://sequentech.github.io/documentation/docs/general/reference/election-creation-json#election-start_date

We didn't change the meaning of those really because it would become a larger scope and increase the effort. Basically those fields:
- remain unused during election creation 
- remain being set-automatically/updated as the last start_date and last stop_date when those events happen
- remain used by the election results PDF to be shown as the actual start and stop dates
- remain settable manually using the ./admin.py `ballot-box` admin script
- are not used to actually schedule start or stop, since these fields belong to the ballot-box and the scheduler is in the IAM

**Comment by ElectricPaperInformationssystemeGmbH** [comment]
Ok, so basically we can schedule the start and stop election from the admin dashboard manually. I'm ok with this

**Comment by edulix** [comment]
You can, but you can also schedule it using the `"scheduled_events"` field in the election json. Merging it and I'll paste a link to the documentation here for details once merged.

**Comment by ElectricPaperInformationssystemeGmbH** [comment]
Ok, reviewed
