### ISSUE TITLE
✨ Multiple text fields support for write-ins

### ISSUE THREAD

**Issue by ElectricPaperInformationssystemeGmbH** [sequentech/meta#125]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

It should be possible to display fields separately (list name, first name, last name)

### Possible Implementation

Add a new json `write_in_config` field in the question`extra_options` json. It should have these components:
- `fields`. An array of extra fields for all write-ins. Each field should have these components: `id` (text name), `placeholder` (text), an optional `placeholder_i18n` for translations, and `min` /  `max` fields for the size of the extra field (not related to the encoding limits), and similar optional fields for the input `label`/`label_i18n` and for the help text `help`/`help_i18n`.
- `template`. Template to be used to create the final write-in interpolating the values of the write-in fields. For example `"{last_name};{first_name}"`

This configuration will apply to all write-in fields in the question.

Once the ballot is casted, the write in to be shown is the templated one with the interpolated values (the write-in has to be represented as a single string in the system in the end), so we don't need to parse the values from the templated string. However if the user wants to go back to edit the ballot from the review screen they should be able to do so, so the values should be saved in memory as long as the user hasn't cast their ballot yet.

The system has a limitation on the number of characters that can be used for write-ins, and this currently means that the write-in field goes yellow when the user approaches this limit and red when it's surpassed. This feature should be preserved with these write-in extra fields.

![Image](https://github.com/sequentech/meta/assets/3913223/d30e1589-0e80-4cc4-86f3-9727824613bc)

### Tasks

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/ballot-box/pull/171
- [ ] https://github.com/sequentech/voting-booth/pull/350
- [ ] https://github.com/sequentech/documentation/pull/125
```

```[tasklist]
# Stable PRs (9.x.0)
- [ ] https://github.com/sequentech/ballot-box/pull/172
- [ ] https://github.com/sequentech/voting-booth/pull/352
- [ ] https://github.com/sequentech/documentation/pull/126
```

**Comment by edulix** [comment]
Suggestion: We can implement this, having a configurable number of fields, with a i18n placeholder for each. The limitation is that each write-in internally are represented by a single string (similar to a candidate's name), so one way to encode these fields in a generic way is to also let you provide a template where you say `encode this candidate as "{last_name};{first_name}"` for example.
