### ISSUE TITLE
🐞 Creation of keys ceremonies does not update correctly for trustees

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1258]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.

### Current Behavior

When a trustee enters a key ceremony that is not ready to download the key it shows up like below:
<img width="682" alt="image" src="https://github.com/sequentech/meta/assets/81968/285b2cd9-b9e6-49c6-95bc-629d132e8d5d">

- It shows the breadcrumb as finished, but it should be showing as "Start"
- After the keys have generated, it does update the table and shows the "Key fragment generated" as checked, and it updates the logs, but it still says at the top "Waiting for key generation" and it does not allow to continue.

### Expected Behavior

Fix the issues mentioned.

### Screenshots:

https://github.com/user-attachments/assets/5e0fef67-96a3-4ce1-8b44-341501d8b1e3

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [x] Successful defect resolution merged
- [x] fix breadcrumb when generating ke
- [x] remove "Waiting for key generation" alert when key has been generated
- [x] Add next button to status page - make it disable until the keys are generated
- [x] Make sure that the next button is only there before the trustee has done all the steps
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/548
```
