### ISSUE TITLE
✨ Admin-console: Show only actions available according to user permissions

### ISSUE THREAD

**Issue by ElectricPaperInformationssystemeGmbH** [sequentech/meta#127]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

It should be possible to hide certain functions (such as activity log)
At least we need to be able to disable some UIs if the user didn't have permissions to see those region (such as activity log)

### Implementation Proposal

* In general actions and sections that the user can't access/do shouldn't appear in their screen.
* For example in the `Dashboard` for an election in the admin console, the actions menu should only show menu items that the user can perform, and if there's none the action menu shouldn't be visible at all.
* In a similar fashion the buttons on the breadcrum for the different election states on the dashboard should only be visible if enabled.
* Another example, in the `Basic details` section of the election, the `Edit social` button should only be visible if the user has permissions for that action.
* Regarding the `Activity log`, there's currently no permission that enables looking at the dashboard but at the same time hiding/disabling the activity log. Instead, we will remove the `view` permission from the activity log. Note that this is a **breaking change.**
* Add documentation on the different permissions.

### Implementation screenshots/loom

Screenshot for a limited user with only `view|allow-tally` permission. As you can see the only visible action is allow tally, they cannot start/ stop create elections or view the census/activity log.

![Image](https://github.com/sequentech/meta/assets/3913223/e5252527-9128-4882-9e26-5ecff7b92b87)

Loom:

<div>
    <a href="https://www.loom.com/share/4bfc4acbbfbb4308b1205c63ab21648a">
      <p>Role-Based Logging for Election Manager - Watch Video</p>
    </a>
    <a href="https://www.loom.com/share/4bfc4acbbfbb4308b1205c63ab21648a">
      <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/4bfc4acbbfbb4308b1205c63ab21648a-with-play.gif">
    </a>
  </div>

### Tasks

```[tasklist]
# Tasks
- [x] Define implementation proposal.
- [x] Refactor screens/actions to show them only if the user has permissions.
- [x] Remove "view" permission for activity log, fix "launch tally" action when user doesn't have such permission.
- [x] Documentation.
- [x] Add screenshots/loom with implementation.
- [x] Client reviews/accepts implementation
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/admin-console/pull/393
- [ ] https://github.com/sequentech/iam/pull/306
- [ ] https://github.com/sequentech/documentation/pull/133
```

**Comment by ElectricPaperInformationssystemeGmbH** [comment]
The implementation looks good. Reviewed, thank you.
