### ISSUE TITLE
🐞 Disable Countdown seconds options to the correct policy input

### ISSUE THREAD

**Issue by omri81** [sequentech/meta#1270]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.

### Current Behavior

When you chose a policy some numbers are irrelevant and are not disabled

### Expected Behavior

numbers input should be disabled to the corresponding policy input

https://github.com/sequentech/meta/assets/33923561/2597e1d1-bc88-453f-b844-8fb9773dfdfd

### Tasks

```[tasklist]
# Tasks
- [x] Disable the inputs when needed
- [x] Add defaults to the numbers from the env config
- [x] Add to Beyond repo
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/541
- [ ] https://github.com/sequentech/beyond/pull/53
```

**Comment by omri81** [comment]
Related issue: #108
