### ISSUE TITLE
✨ Deploy the 2nd gen system for Drewnorth

### ISSUE THREAD

**Issue by lnabergoi** [sequentech/meta#1274]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Deploy the last release of the 2nd gen system in AWS in **CANADA**

USE the following URL: Drewnorth.sequent.vote

Deploy 3 Trustees servers

### Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] Deploy the environment
- [ ] Check Admin Portal Login
- [ ] Check Emails
- [ ] Trustee ceremony
- [ ] Tally
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/gitops/pull/588
```

**Comment by edulix** [comment]
this was done
