### ISSUE TITLE
✨ Voting Portal > Review Screen > Cast Vote Confirm Modal

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1275]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Under Voting Portal > Review Screen, Add a modal when clicking Cast vote to confirm. This should be an optional dialog, enabled only if a specific option is enabled in this election in the admin portal.

Client requirement: "If click CAST YOUR BALLOT, the system shall display warning message that his/her vote will no longer be edited once confirm the action with an option to cancel and remain in the Review Screen."

### Possible Implementation

This should be a boolean flag that is under election presentation and published in the ballot style.

### Retrocompatibility

By default, this should not be enabled. Also, an election might have been published with an old version of the ballot design that does not have this option defined, and this should be interpreted as a default "do not show this warning".

### Screenshots

https://github.com/user-attachments/assets/1ca4b22b-c33a-46f3-9a55-deca2ea36ac5

https://github.com/user-attachments/assets/714e8e5a-bfb6-405e-aaf6-14611b2e01f5

<empty>

```[tasklist]
# Tasks
- [x] Add the option to the election config presentation section [rust, backend]
- [x] Add the option to the election ballot style [rust, backend]
- [x] Implement the warning in the voting portal
- [x] Implement the warning in the admin portal
- [x] Check if working for existing old elections
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/570 
```
