### ISSUE TITLE
🐞 Admin Portal: Unexpected sidebar behavior on active/archived changes

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1279]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.

### Current Behavior

Unexpected sidebar behavior on active/archived changes. Basically, sidebar should always be listing currently active election event. See the task list of small issues below and the screen recording.

https://github.com/sequentech/meta/assets/81968/d4c40791-8ab2-47a6-bf41-b188060af454

### Expected Behavior

Should work as expected.

### Tasks

```[tasklist]
# Tasks
- [ ] When loading a specific election event, the sidebar should notice if it's active or archived, and automatically show the Active or Archived tab accordingly.
- [ ] When archiving an election event, the sidebar tab should automatically change to "Active".
- [ ] When unarchiving an election event, the sidebar tab should automatically change to "Archived".
```

```[tasklist]
# Main PRs
- [ ] PR 1
```
