### ISSUE TITLE
🐞 Admin Portal > Sidebar: strange hover and underline behavior

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1280]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.

### Current Behavior

On the Admin Portal > Sidebar, there's strange hover and underline behavior on items (all kinds: election events, elections, contests, candidates). Please fix it.

https://github.com/sequentech/meta/assets/81968/5af02480-d6c1-44d6-952b-98c386f09fe3

### Expected Behavior

The underline and three dots should work as expected.

### Screenshots: 

https://github.com/user-attachments/assets/0227eac0-bf2c-4dfc-a416-e1ebc7623abd

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [x] Successful defect resolution merged
- [x] Hover - display 3 dots and underline together
- [x] change the state when clicking on the element - should display underline and 3 dots
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/558
```
