### ISSUE TITLE
✨ Keycloak: implement multiple improvements in login/registration

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1281]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Implement multiple improvements and changes in the registration and login.

### Possible Implementation

- UI for html5-tel field: If attribute is set to html5-tel a script is added to use intl-tel-input library: https://github.com/jackocnr/intl-tel-input/tree/master
- Autocomplete is now configurable in a user profile attribute as a custom attribute annotation. By default is off. You can use autocomplete html values to define the field: https://www.w3schools.com/tags/att_input_autocomplete.asp

### Screenshots

Telephone configuration:

![Captura de pantalla 2024-07-15 a les 11 42 44](https://github.com/user-attachments/assets/741b889e-3503-446a-a5d2-6f028a94efc5)

Telephone as seen in the form

<img width="594" alt="Captura de pantalla 2024-07-18 a les 11 21 33" src="https://github.com/user-attachments/assets/4332af83-e0be-498a-b0d6-d5d864fadbd9">

<img width="456" alt="Captura de pantalla 2024-07-18 a les 11 24 43" src="https://github.com/user-attachments/assets/9b9937c5-a75f-4f2b-b071-7dd1c03f1b9a">

Example of enabling autocomplete for a first name field:

<img width="796" alt="Captura de pantalla 2024-07-18 a les 11 18 02" src="https://github.com/user-attachments/assets/5861ba72-5e7c-4be8-9983-c99dc7d8bffe">

Deferred Registration User Profile Creation has now a new user lookup config:

<img width="600" alt="Captura de pantalla 2024-07-31 a les 19 34 07" src="https://github.com/user-attachments/assets/546313b3-05e5-4956-a0c3-954a7a143c45">

Deferred Registration User Profile Creation can now validate if user has some unset attributes:

<img width="635" alt="Captura de pantalla 2024-07-31 a les 19 35 37" src="https://github.com/user-attachments/assets/c86381dd-b4af-4035-99ce-8454d085fe85">

Deferred Registration User Profile Creation can now check if certain attributes are not set for any other users:

<img width="635" alt="Captura de pantalla 2024-07-31 a les 19 37 19" src="https://github.com/user-attachments/assets/96339db0-57d1-4047-b042-cd1829eabe8b">

Now we can create a user attribute that can disable or enable other attributes:

https://github.com/user-attachments/assets/e1c68d44-045e-47d5-9d77-759fefca5b35

To set it up it requires a special annotation in the user profile attribue:

<img width="794" alt="Captura de pantalla 2024-07-31 a les 19 42 21" src="https://github.com/user-attachments/assets/5cb7d657-014d-4733-bc29-812a41f30f4b">

We can configure an user attribute to filter other attributes during registration:

https://github.com/user-attachments/assets/a4e8ef6e-7692-4118-b594-c17f58c7fc9b

To set it up all we need is to configure this annotation for the attribute:

<img width="809" alt="Captura de pantalla 2024-07-31 a les 19 46 44" src="https://github.com/user-attachments/assets/1b815a4d-08e3-45f6-8f3c-b47231d43bc0">

Added a new configuration for Lookup User from Authentication Notes to decide if an user will login automatically login after registration:

<img width="364" alt="Captura de pantalla 2024-07-31 a les 19 49 49" src="https://github.com/user-attachments/assets/42de8cad-ef89-49d3-b783-1636cec5be1f">

When disabled it will show this screen after the registration is complete and allow you to go back and login:

<img width="1133" alt="Captura de pantalla 2024-07-31 a les 19 53 03" src="https://github.com/user-attachments/assets/10701936-dc0e-4e98-b63a-a77a60be80d4">

Inetum authenticator now has a new config to validate the submitted data against inetum data:

<img width="631" alt="Captura de pantalla 2024-07-31 a les 19 22 07" src="https://github.com/user-attachments/assets/fd63a224-a77f-4571-9430-0f7aec0dd7a8">

You can set an annotation to add a confirmation input on an attribute, the attribute value will define the label:

<img width="808" alt="Captura de pantalla 2024-07-31 a les 23 42 05" src="https://github.com/user-attachments/assets/dde0504b-9435-44bd-9996-cba333fe395b">

Confirm attribute gets validated in Deferred Registration User Profile Creation

<img width="469" alt="Captura de pantalla 2024-07-31 a les 23 38 49" src="https://github.com/user-attachments/assets/e12ddaaa-fa5b-41fd-a2f4-d708a518031b">

```[tasklist]
# Tasks
- [x] Registration: Implement nice UI for html5-tel field. It should show a selector for the country code and it should automatically detect the default country based on location.
- [x] Registration: Set autocomplete off in all registration and login fields.
- [x] DeferredRegistrationUserCreation: Creation: Add support for user lookup on specific fields, using normalized form (all upper case, trimmed), and set the found related user-id in an auth note.
- [x] DeferredRegistrationUserCreation: Lookup that specific list of fields are not present, not set or null in the lookedup user (normalized, upper case, trimmed).
- [x] DeferredRegistrationUserCreation: Lookup that specific list of fields are not present in any user (normalized, upper case, trimmed).
- [x] DeferredRegistrationUserCreation: Implement alternative Phone and/or Email input
- [x] DeferredRegistrationUserCreation: Implement selector field related to another field, so that it filters the related field. For example if selector field "Post/Embassy" has value "Barcelona", then only options starting with "Barcelona/" will be shown in the "Country" related field.
- [x] DeferredVerifyAuth: Add an authenticator that verifies an email or SMS of a deferred user, if set in an auth note.
- [x] InetumAuthenticator: Improve UI
- [x] LookupAndUpdateUser: Add a toggle config to decide if user should automatically be logged in or should be shown a success screen with configurable html text to show, saying the user should now be able to login.
- [x] UsernamePasswordFormWithExpiry: allow login with email or tlf (configurable)
- [x] InetumAuthenticator: Check if the user id card, first last name, etc matches the one in an auth note, and if not show an error.
- [x] DeferredRegistrationUserCreation: Implement confirm for any attribute. If enabled, the attribute will appear twice in the form and both values should match.
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/552
- [ ] https://github.com/sequentech/step/pull/592
```

**Comment by xalsina-sequent** [comment]
> @xalsina-sequent 2 quick comments:
> 
> * Is easy to do that any attribute with key starting with `html-attribute:` will be set as an html the attribute key being whatever comes in the key name after `html-attribute:` and the value given? I guess that will be even more generic and a quick win.
> * In the telephone widget: Is it easy to show also the telephone prefix (or is it called country code?) once it's selected, next to the flag (to the right side of the flag)?

1) Yes it's possible. If you want I can undo what I did with autocomplete and implement it like that.
2) Yes it's possible, it's part of the configuration. Here is all the things that are possible with that widget: https://intl-tel-input.com/storybook/?path=/docs/intltelinput--separatedialcode

**Comment by edulix** [comment]
Yes, please go ahead and do it that way :-) And thanks for the link!
