### ISSUE TITLE
🐞 Census menu translations don't always work

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#129]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Current Behavior

Sometimes the actions menu on the election census (admin-console) doesn't show any text. Also if the user changes the language, the text is not translated.

### Expected Behavior

The text on the menu should appear, and if the language is changed it should be translated dynamically.

### Tasks

```[tasklist]
# Tasks
- [x] Move translations from elcensus.js to elcensus.html on admin-console.
```

```[tasklist]
# Master PRs
- [x] https://github.com/sequentech/admin-console/pull/376
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/admin-console/pull/379
```

**Comment by edulix** [comment]
Is this done? If so, please close the ticket (which will automatically move it to Done)
