### ISSUE TITLE
✨ Initial Auditable Votes support

### ISSUE THREAD

**Issue by xalsina-sequent** [sequentech/meta#1291]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Auditable votes need to be added to reports. We will start by adding a validation to mark a vote as auditable if it has been caster after the scheduled closing time.
A new field will be added to reports that show the count of auditable votes.
The auditable votes should be shown also in the admin portal.

### Screenshots

Election reports HTML show the auditable votes:

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/d47e3fd7-5f14-4fe8-b035-f433ec45c08a">

In Admin Portal Candidates Results, the default page size now is 20 and candidates are ordered by default by winning position:
<img width="1076" alt="image" src="https://github.com/user-attachments/assets/a7b105b1-466d-4544-a846-e74009df64dc">

Some other improvements:

https://github.com/user-attachments/assets/78622138-c926-4dd2-8ade-29f5ed71db01

```[tasklist]
# Tasks
- [x] Add a vote validation before mixing that marks vote as auditable. The auditable vote should not be passed through the mixnet.
- [x] Add auditable votes count to reports.
- [x] Add auditable votes to Admin portal.
- [x] Add a call to count how many votes are auditable
- [x] Fix scrolling to bottom in the tally results
- [x] Add horizontal scrolling to tally results tabs
- [x] Fix tables alignment in tally results tables
- [x] Ensure backward compatibility of admin portal results visualization (auditable votes would show as `-`)
- [x] admin portal tally results: bigger page size (20) for candidates, sorting by winning position by default
- [ ] later: ui to see auditable ballots before launching the tally and allowing to do specific things with them
- [ ] later: ui to report auditable ballots
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/554
```
