### ISSUE TITLE
🐞French translation is tagged as English

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#130]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Current Behavior

In the list of languages, the French translation is shown as English. Also the "loading" key is duplicated.

### Expected Behavior

The French translation should read as French.

### Tasks

```[tasklist]
# Tasks
- [x] Fix french translation and duplicated key.
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/common-ui/pull/315
- [ ] https://github.com/sequentech/voting-booth/pull/335
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/common-ui/pull/317
- [ ] https://github.com/sequentech/voting-booth/pull/339
```
