### ISSUE TITLE
🐞Fix documentation link to deployment config

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#132]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Current Behavior

The current documentation includes outdated information on the deployment guide for `config.master.yml`.

### Expected Behavior

Instead of holding a copy of `config.master.yml`, link to the `deployment-tool` file.

### Tasks

```[tasklist]
# Tasks
- [x] Fix documentation link to `config.master.yml` and delete local copy.
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/documentation/pull/120
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/documentation/pull/121
```
