### ISSUE TITLE
✨ Improved Auditable Votes handling

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1324]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Multiple improvements on Auditable Votes handling

### Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] Use the published ballot style related to the contest for the auditable, instead of the data directly from the election table in the database.
- [ ] UI+backend to generate auditable ballots reports. The report should contain the reason why a ballot is marked as such.
- [ ] UI+backend to manage auditable ballots, viewing them,  viewing the reason why a ballot is marked as auditable, and being able to add notes, change their status and even (when possible) move them to countable ballots.
- [ ] Allow the UI to manage auditable ballots to be part of the tally process.
```

```[tasklist]
# Main PRs
- [ ] PR 1
```
