### ISSUE TITLE
✨ Configure readiness probes for windmill

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#1333]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Configure readiness probes for windmill

### Screenshots

<empty>

```[tasklist]
# Tasks
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/beyond/pull/55
- [ ] https://github.com/sequentech/gitops/pull/544
- [ ] https://github.com/sequentech/beyond/pull/56
```
