### ISSUE TITLE
Release 9.0.0

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#134]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

New major release.

### Tasks

```[tasklist]
# Tasks
- [x] Tag the release
- [x] Create releases with automatic release notes in github
- [x] Test the release
- [x] Deploy release in stable <major>xx deployment
- [ ] Deploy release in demo
- [ ] Deploy release in web-demo
```
