### ISSUE TITLE
Security updates

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#135]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Security updates

### Tasks

```[tasklist]
# Tasks
- [x] Security updates
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/voting-booth/pull/343
- [ ] https://github.com/sequentech/admin-console/pull/380
```

```[tasklist]
# Stable PRs (7.4.x)
- [ ] https://github.com/sequentech/voting-booth/pull/344
- [ ] https://github.com/sequentech/admin-console/pull/381
```

```[tasklist]
# Stable PRs (8.0.x)
- [ ] https://github.com/sequentech/voting-booth/pull/345
- [ ] https://github.com/sequentech/admin-console/pull/382
```
