### ISSUE TITLE
🐞 `master` branch should be using `master` version number and not `8.0.0` 

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#136]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Current Behavior

Master branch is using `8.0.0` "version number".

### Expected Behavior

Master branch should use `master` "version number". This happened because I executed wrongly the release script.

### Environment

```markdown
- OS:
- Web browser:
```

### Tasks

```[tasklist]
# Tasks
- [ ] Revert version number commits in master branches
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/voting-booth/pull/338
- [ ] https://github.com/sequentech/election-portal/pull/203
- [ ] https://github.com/sequentech/admin-console/pull/378
- [ ] https://github.com/sequentech/deployment-tool/pull/341
- [ ] https://github.com/sequentech/ballot-verifier/pull/24
- [ ] https://github.com/sequentech/mixnet/pull/19
- [ ] https://github.com/sequentech/misc-tools/pull/54
- [ ] https://github.com/sequentech/election-orchestra/pull/72
- [ ] https://github.com/sequentech/frestq/pull/77
- [ ] https://github.com/sequentech/election-verifier/pull/55
- [ ] https://github.com/sequentech/tally-pipes/pull/103
```

**Comment by Findeton** [comment]
This is incomplete, it's missing the file sequent-ui/templates/SequentConfig.js on `deployment-tool`and its variable `SEQUENT_CONFIG_VERSION`. I'll create another PR for that.

**Comment by Findeton** [comment]
The revert for common-ui was missing so I added [the PR.](https://github.com/sequentech/common-ui/pull/320)
