### ISSUE TITLE
✨ Support client API calls

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#1368]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Support client API calls.

### Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/573
- [ ] https://github.com/sequentech/step/pull/574
```
