### ISSUE TITLE
🐞Fix ui deployment

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#137]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Current Behavior

Ui deployment is broken.

### Expected Behavior

Ui deployment should work.

### Tasks

```[tasklist]
# Tasks
- [x] Revert changes [from this PR ](https://github.com/sequentech/epi/issues/28)
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/common-ui/pull/318
- [ ] https://github.com/sequentech/deployment-tool/pull/340
```

**Comment by edulix** [comment]
You are doing this wrong. Master branch should not be moved to 8.0.0, but the opposite! See https://github.com/sequentech/meta/issues/136

**Comment by edulix** [comment]
I've reset master branch of those two repos to their previous state. To make master work, please go ahead and use the branches in https://github.com/sequentech/meta/issues/136 while we haven't solved the issue (or solve it :-P).
