### ISSUE TITLE
🐞 Missing Snapshot Feature with S3 Backend in immudb Helm Chart

### ISSUE THREAD

**Issue by angelAtSequent** [sequentech/meta#1377]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.

### Current Behavior

We have been using the immudb Helm chart on top of EBS disks, leveraging snapshots to ensure point-in-time backups. Recently, immudb introduced the possibility of using S3 as its backend. However, we inferred that with S3, snapshots were no longer necessary. Unfortunately, this assumption has proven incorrect.

With the introduction of the S3 backend in immudb, the option to create point-in-time snapshots has been overlooked. This feature is crucial for disaster recovery and maintaining data integrity in case of any unforeseen issues. Despite using S3, we still need the capability to revert to a previous state.

There is no apparent method to create or manage snapshots for immudb when using S3 as the backend, leaving a gap in backup and disaster recovery processes.

### Expected Behavior

The immudb Helm chart should support point-in-time snapshots when using S3 as its backend, similar to the functionality available with EBS disks.

Providing snapshots for S3-backed deployments will enhance data security and ensure robust backup strategies, aligning with best practices for data management and recovery.

### Tasks

```[tasklist]
# Tasks
- [x] Modify immudb helmchart
- [x] Test it on a staging cluster
- [x] Modify the required documentation
- [x] Apply on drewnorth
- [x] Apply on ualicante
- [x] Apply on upv
- [x] Apply on comelec
- [x] Apply on staging
- [x] Apply on ua
- [x] Apply on ciccp
- [x] Apply on dev
- [x] Apply on apa
- [x] Apply on qa
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/beyond/pull/59
- [ ] https://github.com/sequentech/gitops/pull/656
- [ ] https://github.com/sequentech/gitops/pull/786
```

**Comment by angelAtSequent** [comment]
Tested on staging (on a different namespace):

Configuration: 
```yaml
snapshot:
  cronSchedule: ""
  dailySnapshot:
    enabled: true
    keep: 2
  enabled: true
  hourlySnapshot:
    enabled: true
    keep: 3
  snapshotClassName: ebs-snapclass
  weeklySnapshot:
    enabled: true
    keep: 3
```

Result:
```bash
$ kubectl get volumesnapshot -n test --show-labels
NAME                              READYTOUSE   SOURCEPVC                 SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS   SNAPSHOTCONTENT                                    CREATIONTIME   AGE    LABELS
immudb-snapshot-20240721-002030   true         immudb-0-immudb-storage                           5Gi           ebs-snapclass   snapcontent-c9504615-6619-4317-93b9-160fb0d4bd15   29h            29h    app.kubernetes.io/instance=immudb,app.kubernetes.io/managed-by=Helm,app.kubernetes.io/name=immudb,app.kubernetes.io/version=1.9.3,helm.sh/chart=immudb-1.26,sequent.io/backup-cadence=daily
immudb-snapshot-20240721-004030   true         immudb-0-immudb-storage                           5Gi           ebs-snapclass   snapcontent-37782942-fa8f-4b63-9f14-03b10f048bef   28h            28h    app.kubernetes.io/instance=immudb,app.kubernetes.io/managed-by=Helm,app.kubernetes.io/name=immudb,app.kubernetes.io/version=1.9.3,helm.sh/chart=immudb-1.26,sequent.io/backup-cadence=weekly
immudb-snapshot-20240722-002030   true         immudb-0-immudb-storage                           5Gi           ebs-snapclass   snapcontent-5720c47e-2a5e-4a86-9380-971f8068c8e9   5h             5h     app.kubernetes.io/instance=immudb,app.kubernetes.io/managed-by=Helm,app.kubernetes.io/name=immudb,app.kubernetes.io/version=1.9.3,helm.sh/chart=immudb-1.26,sequent.io/backup-cadence=daily
immudb-snapshot-20240722-030030   true         immudb-0-immudb-storage                           5Gi           ebs-snapclass   snapcontent-2e1abba1-b36e-4ea4-bb63-415464b9e0db   140m           140m   app.kubernetes.io/instance=immudb,app.kubernetes.io/managed-by=Helm,app.kubernetes.io/name=immudb,app.kubernetes.io/version=1.9.3,helm.sh/chart=immudb-1.26,sequent.io/backup-cadence=hourly
immudb-snapshot-20240722-040030   true         immudb-0-immudb-storage                           5Gi           ebs-snapclass   snapcontent-c07b09cf-d06e-43ed-9413-89f4924b819c   80m            80m    app.kubernetes.io/instance=immudb,app.kubernetes.io/managed-by=Helm,app.kubernetes.io/name=immudb,app.kubernetes.io/version=1.9.3,helm.sh/chart=immudb-1.26,sequent.io/backup-cadence=hourly
immudb-snapshot-20240722-050030   true         immudb-0-immudb-storage                           5Gi           ebs-snapclass   snapcontent-52135d7a-9bd8-4a45-898d-cd085eb0650c   20m            20m    app.kubernetes.io/instance=immudb,app.kubernetes.io/managed-by=Helm,app.kubernetes.io/name=immudb,app.kubernetes.io/version=1.9.3,helm.sh/chart=immudb-1.26,sequent.io/backup-cadence=hourly
```

*Note*: There are no 3 weekly backups because it has been setup just a week ago
