### ISSUE TITLE
🐞 disable election chooser doesn't work in preview

### ISSUE THREAD

**Issue by ElectricPaperInformationssystemeGmbH** [sequentech/meta#138]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Current Behavior

When election chooser is turned off, the page still appears in the preview, but you can't go into the child election.

### Expected Behavior

With the election chooser switched off, the voting process must be started immediately and all child elections are processed sequentially.

### Steps To Reproduce

1. disable__election_chooser_screen = true
2. start preview

### Environment

```markdown
- OS:
- Web browser:
```

### Tasks

```[tasklist]
# Tasks
- [ ] Fix issue in voting-booth.
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/voting-booth/pull/347
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/voting-booth/pull/361
```
