### ISSUE TITLE
🐞 rigid lists: candidates check boxes should not be shown

### ISSUE THREAD

**Issue by ElectricPaperInformationssystemeGmbH** [sequentech/meta#139]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Current Behavior

Candidate check boxes are displayed for rigid lists.

### Expected Behavior

Like in previous Version the check boxes should be hidden 
![image](https://github.com/sequentech/meta/assets/87812708/d3f22d72-47fc-493a-a30c-0ca004665a91)

### Steps To Reproduce

use this configuration in your preview environment
https://gist.github.com/ElectricPaperInformationssystemeGmbH/6aa59db1b48d828b14227bb9ffa399f2#file-rigid_lists_preview_config

Election JSON: https://gist.github.com/Findeton/fe9eba2109de62d7077306fcb4ed5140

### Environment

```markdown
- OS:
- Web browser:
```

### Tasks

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/voting-booth/pull/348
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/voting-booth/pull/360
```
