### ISSUE TITLE
🐞 Voting portal url in admin portal is erroneous

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#1403]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.

### Current Behavior

Voting portal url in admin portal is erroneous

### Expected Behavior

-

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [x] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/gitops/pull/606
```
