### ISSUE TITLE
✨ 0 num allowed revotes should mean infinite

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#1404]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

When the election param `num_allowed_revotes` is 0, it should mean that voters can vote as many times as they want. Right now it means (at least in the voting portal) that they can't vote at all. Fix it, also look into the cast vote API call.

### Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] Implement change in voting-portal.
- [ ] Implement change in harvest (cast vote endpoint).
```

```[tasklist]
# Main PRs
- [ ] PR 1
```
