### ISSUE TITLE
✨ Detect and handle issues with rabbitmq

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#1407]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

If a queue in rabbitmq is stale/full, we should automatically purge/delete the queue. If the connection from windmill/harvest to rabbitmq is broken, the readiness probe should detect it.

### Screenshots

<empty>

```[tasklist]
# Tasks
- [x] Modify readiness probe code to support async fn
- [x] Implement readiness probe for harvest/windmill that tests rabbitmq connection
- [x] Modify deployments to use readiness probe
- [x] Implement monitoring script for checking rabbitmq queues state
- [x] Apply on drewnorth
- [x] Apply on ualicante
- [x] Apply on upv
- [x] Apply on comelec
- [x] Apply on dev
- [x] Apply on staging
- [x] Apply on ua
- [x] Apply on ciccp
- [x] Apply on apa
- [x] Apply on qa
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/581
- [ ] https://github.com/sequentech/beyond/pull/61
- [ ] https://github.com/sequentech/gitops/pull/664
- [ ] https://github.com/sequentech/step/pull/599
- [ ] https://github.com/sequentech/step/pull/601
- [ ] https://github.com/sequentech/gitops/pull/787
- [ ] https://github.com/sequentech/step/pull/607
- [ ] https://github.com/sequentech/gitops/pull/725
```

**Comment by angelAtSequent** [comment]
I'll continue deploying these changes

**Comment by angelAtSequent** [comment]
> I'll continue deploying these changes

### Staging

Missing loki configuration file.
```bash
$ helm upgrade --install loki grafana/loki-stack -n monitoring --values us-east-1/staging/apps/values.loki.yaml
```

Incorrect prometheus release name. Now released with the right name, and the latest configuration
```bash
$ helm delete -n monitoring monitoring
$ helm upgrade --install prometheus prometheus-community/kube-prometheus-stack -n monitoring --values us-east-1/staging/apps/values.prometheus.yaml
```

Updated rabbitmq:
```bash
$ helm upgrade --install rabbitmq oci://registry-1.docker.io/bitnamicharts/rabbitmq -n apps --version 12.6.1 --values us-east-1/staging/apps/values.rabbitmq.yaml
```

**Comment by angelAtSequent** [comment]
> I'll continue deploying these changes

### QA

Updating loki (just in case):
```bash
$ helm upgrade --install loki grafana/loki-stack -n monitoring --values eu-west-1/qa/apps/values.loki.yaml
```

Updating prometheus:
```bash
$ helm upgrade --install prometheus prometheus-community/kube-prometheus-stack -n monitoring --values eu-west-1/qa/apps/values.prometheus.yaml
```

Updating rabbitmq (just in case):
```bash
$ helm upgrade --install rabbitmq oci://registry-1.docker.io/bitnamicharts/rabbitmq -n apps --version 12.6.1 --values us-east-1/staging/apps/values.rabbitmq.yaml
```

**Comment by angelAtSequent** [comment]
> I'll continue deploying these changes

### ciccp

Updating loki (just in case):
```bash
$ helm upgrade --install loki grafana/loki-stack -n monitoring --values eu-west-1/ciccp/apps/values.loki.yaml
```

Updating prometheus:
```bash
$ helm upgrade --install prometheus prometheus-community/kube-prometheus-stack -n monitoring --values eu-west-1/ciccp/apps/values.prometheus.yaml
```

Updating rabbitmq (just in case):
```bash
$ helm upgrade --install rabbitmq oci://registry-1.docker.io/bitnamicharts/rabbitmq -n apps --version 12.6.1 --values eu-west-1/ciccp/apps/values.rabbitmq.yaml
```

**Comment by angelAtSequent** [comment]
Linked to:https://github.com/sequentech/meta/issues/1711

**Comment by angelAtSequent** [comment]
> I'll continue deploying these changes

### ua

Updating loki (just in case):
```bash
$ helm upgrade --install loki grafana/loki-stack -n monitoring --values eu-west-1/ciccp/apps/values.loki.yaml
```

Updating prometheus:
```bash
$ helm upgrade --install prometheus prometheus-community/kube-prometheus-stack -n monitoring --values eu-west-1/ciccp/apps/values.prometheus.yaml
```

Updating rabbitmq:
```bash
$ helm upgrade --install rabbitmq oci://registry-1.docker.io/bitnamicharts/rabbitmq -n apps --version 12.6.1 --values eu-west-1/ciccp/apps/values.rabbitmq.yaml
```

**Comment by angelAtSequent** [comment]
> I'll continue deploying these changes

### comelec

Updating loki (just in case):
```bash
$ helm upgrade --install loki grafana/loki-stack -n monitoring --values us-east-1/comelec/apps/values.loki.yaml
```

Updating prometheus:
```bash
$ helm upgrade --install prometheus prometheus-community/kube-prometheus-stack -n monitoring --values us-east-1/comelec/apps/values.prometheus.yaml
```

Updating rabbitmq:
```bash
$ helm upgrade --install rabbitmq oci://registry-1.docker.io/bitnamicharts/rabbitmq -n apps --version 12.6.1 --values us-east-1/comelec/apps/values.rabbitmq.yaml

```

**Comment by angelAtSequent** [comment]
> I'll continue deploying these changes

### upv

Updating loki (just in case):
```bash
$ helm upgrade --install loki grafana/loki-stack -n monitoring --values eu-west-1/upv/apps/values.loki.yaml
```

Updating prometheus:
```bash
$ helm upgrade --install prometheus prometheus-community/kube-prometheus-stack -n monitoring --values eu-west-1/upv/apps/values.prometheus.yaml
```

Updating rabbitmq:
```bash
$ helm upgrade --install rabbitmq oci://registry-1.docker.io/bitnamicharts/rabbitmq -n apps --version 12.6.1 --values eu-west-1/upv/apps/values.rabbitmq.yaml
```

**Comment by angelAtSequent** [comment]
> I'll continue deploying these changes

### drewnorth

Updating loki (just in case):
```bash
$ helm upgrade --install loki grafana/loki-stack -n monitoring --values ca-central-1/drewnorth/apps/values.loki.yaml
```

Updating prometheus:
```bash
$ helm upgrade --install prometheus prometheus-community/kube-prometheus-stack -n monitoring --values ca-central-1/drewnorth/apps/values.prometheus.yaml
```

Updating rabbitmq:
```bash
$ helm upgrade --install rabbitmq oci://registry-1.docker.io/bitnamicharts/rabbitmq -n apps --version 12.6.1 --values ca-central-1/drewnorth/upv/apps/values.rabbitmq.yaml
```

**Comment by jorgermp** [comment]
I was looking more info about the error message 
`ERROR Deliver failed: protocol error: AMQP soft error: PRECONDITION-FAILED: PRECONDITION_FAILED - delivery acknowledgement on channel 1 timed out. Timeout value used: 1800000 ms. This timeout value can be configured, see consumers doc guide to learn more`
This is a message from RabbitMQ server, but is generated because don't received and ack from consumer
https://stackoverflow.com/questions/53374144/rabbitmq-ack-timeout/67581599#67581599
I found that normally when rabbitmq are restart after 30 min Windmill generate the problem. Many k8s continues with spot instances and maybe when rabbit restart this generate a no correctly connection
