### ISSUE TITLE
🐞 Different issues with queues

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1418]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.

### Current Behavior

Sometimes environments become unresponsive because background tasks do not run.

### Expected Behavior

Background tasks should always work.

### Tasks

```[tasklist]
# Tasks
- [ ] Fix issue in `beyond` the infra code related to rabbitmq pods being recreated in a node in a different region than the related PVC region.
- [ ] Fix issue related to queues where beat messages accumulate.
```

```[tasklist]
# Main PRs
- [ ] PR 1
```

**Comment by edulix** [comment]
Duplicate of #1407
