### ISSUE TITLE
🐞 Can't send email-otp

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#142]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Current Behavior

Error when trying to send email otp.

### Expected Behavior

No error

### Environment

```markdown
- OS:
- Web browser:
```

### Tasks

```[tasklist]
# Tasks
- [x] Check if auth method is otp on resend_auth_code
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/iam/pull/296
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/iam/pull/298
```

**Comment by Findeton** [comment]
This is fixed when the `election.census.config.allow_user_resend` is set to `true`. It probably makes sense to modify the admin console to set that field to true when `email-otp` is selected.
