### ISSUE TITLE
🐞 Duplicated header on election portal

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#144]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Current Behavior

For a brief moment while loading, the header is seen duplicated on election portal (for example on the election page or on login)

### Expected Behavior

Only one header!

### Environment

```markdown
- OS:
- Web browser:
```

### Tasks

```[tasklist]
# Tasks
- [x] Use CSS switch with ng-class rather than ng-if
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/election-portal/pull/205
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/election-portal/pull/207
```
