### ISSUE TITLE
✨ Include Jorge to the list of authorized users in the platform

### ISSUE THREAD

**Issue by angelAtSequent** [sequentech/meta#1440]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

It would be nice having Jorge onboarded in the platform before he actually joins the company.

### Possible Implementation

Add him to the list of authorized users in the different Kubernetes clusters (platform)

### Screenshots

<empty>

```[tasklist]
# Tasks
- [x] Apply on drewnorth
- [x] Apply on ualicante
- [x] Apply on upv
- [x] Apply on comelec
- [x] Apply on dev
- [x] Apply on staging
- [x] Apply on ua
- [x] Apply on ciccp
- [ ] Apply on apa
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/gitops/pull/636
- [ ] https://github.com/sequentech/gitops/pull/657
```

### Additional context

It has been already applied to:

- drewnorth
- ualicante
- upv
- comelec
- dev
- staging
- ua

Pending to be applied on:
- ciccp
- apa

Because the change requires rollout of nodes.

**Comment by edulix** [comment]
Closing this, APA will be deployed and updated later https://github.com/sequentech/meta/issues/1463
