### ISSUE TITLE
✨ Allow creating pre-releases

### ISSUE THREAD

**Issue by angelAtSequent** [sequentech/meta#1441]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

It would be nice having the possibility to create some pre-releases to deploy them on non-production environments. Once tested the release, we can create the final release and deploy it everywhere. This is just a way to mark releases as non-productive.

### Possible Implementation

Change the `step` repository/github actions to allow creating pre-releases.

### Screenshots

<empty>

```[tasklist]
# Tasks
- [x] Change the automation
- [ ] Test the automation
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/585
```
