### ISSUE TITLE
✨ Enable progressive tallies

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#146]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Enable multiple tallies even when the election is still open.

### Tasks

```[tasklist]
# Tasks
- [x] Add the task to the crontab.
- [x] Add the necessary options in admin.py to launch the tally and call it from the cron.
- [x] Add a boolean feature-flag in config.yml that affects ballot-box, SequentConfig, and election-orchestra to enable multiple tallies.
- [x] In the ballot box, allow the process of tallying if there are keys and votes.
- [x] Add an iam_tally function in admin.py to call iam from the parent election.
- [x] Enable multiple tallies from the interface. The admin interface should also check if tallying is allowed.
- [x] In the election orchestra, store the votes that will be tallied in the database and create folders. Use the reset-tally command each time a tally is performed.
- [x] Check if there has been a previous tally in the callback from the director of the election orchestra to the ballot box.
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/admin-console/pull/386
- [ ] https://github.com/sequentech/deployment-tool/pull/343
- [ ] https://github.com/sequentech/iam/pull/300
- [ ] https://github.com/sequentech/ballot-box/pull/173
- [ ] https://github.com/sequentech/election-orchestra/pull/74
- [ ] https://github.com/sequentech/documentation/pull/129
```

```[tasklist]
# Stable PRs
- [ ] Task 1
```
