### ISSUE TITLE
🐞 CICCP Voting portal url in admin portal is erroneous

### ISSUE THREAD

**Issue by angelAtSequent** [sequentech/meta#1462]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.

### Current Behavior

Voting portal url in admin portal is erroneous

### Expected Behavior

*

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [x] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/gitops/pull/660
```

**Comment by angelAtSequent** [comment]
The PR aims to solve an issue observed while deploying a couple of environments in an automated way.

UPV and drewnorth had the same problem, incorrect Voting Portal URLs. This was caused by the automation script im working on because it copies the ciccp environment to then find and replace some hostnames/values here and there.

As far as ciccp had this issue, drewnorth and UPV has it too.
