### ISSUE TITLE
🐞 Admin portal:  unnecessary renders when creating new elections data

### ISSUE THREAD

**Issue by maya-byle** [sequentech/meta#1464]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.

### Current Behavior

The sidebar renders unnecessarily often. 
It refreshes after every operation the admin performs.

### Expected Behavior

The sidebar needs to render with the most updated information, but in a clean way that is not noticeable to the user.

https://github.com/user-attachments/assets/63c23421-d5d7-40bc-b17f-db33c73ae019

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [x] Successful defect resolution merged
- [x] Fixed the sidebar loading behavior
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/587
```
