### ISSUE TITLE
✨ Move immudb in dev from s3 to disk based

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#1466]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Move immudb in dev from s3 to disk based

### Screenshots

<empty>

```[tasklist]
# Tasks
- [x] Deploy in dev
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/gitops/pull/661
```
