### ISSUE TITLE
✨ Create a QA environment

### ISSUE THREAD

**Issue by angelAtSequent** [sequentech/meta#1467]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

It would be nice having a QA environment. Deploy the last release of the 2nd gen system in AWS in Europe.

USE the following URL: qa.sequent.vote

Deploy 2 Trustees servers

### Possible Implementation

Create it using the automation script so we can test it E2E.

### Tasks

```[tasklist]
# Tasks
- [x] Create the environment
- [x] Check Admin Portal Login
- [x] Check Emails
- [x] Trustee ceremony
- [x] Tally
- [x] Ensure monitoring stack is correctly deployed
- [x] Add users to bitwarden: hasura, admin, trustees, etc, shared with QA collection
- [x] Notify QA people of new environment in #bugs slack channel of new QA environment
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/gitops/pull/662
```
