### ISSUE TITLE
🐞 Add Jorge to the KMS admins (Platform | EKS Clusters)

### ISSUE THREAD

**Issue by angelAtSequent** [sequentech/meta#1468]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.

### Current Behavior

Currently, Jorge could interact with the clusters, but in case he would need to interact with the KMS keys, he would have face some issues. 

We need them to be an admin as he is going to be the principal infrastructure/automation engineer.

### Expected Behavior

Jorge could interact without any issue with the KMS keys.

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [x] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/gitops/pull/663
```
