### ISSUE TITLE
✨ css improvement to countdown button

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#147]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

The bottom shadow should remain constant:

![Image](https://github.com/sequentech/meta/assets/3913223/2cbf8a00-a200-4411-8df8-6dbd2bea5d75)

### Tasks

```[tasklist]
# Tasks
- [ ] Fix common-header on common-ui
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/common-ui/pull/325
- [ ] https://github.com/sequentech/common-ui/pull/330
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/common-ui/pull/324
- [ ] https://github.com/sequentech/common-ui/pull/331
```

**Comment by edulix** [comment]
@Findeton please add a screenshot of the before/after, it's not clear the improvement by reading the issue

**Comment by Findeton** [comment]
@Findeton uploaded. I actually tried uploading it like 5 times yesterday but github was acting strange...
