### ISSUE TITLE
🐞 The candidates would not be displayed if write ins active

### ISSUE THREAD

**Issue by ElectricPaperInformationssystemeGmbH** [sequentech/meta#148]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Current Behavior

If writeins is in use the normal candidates will not be shown.

### Expected Behavior

every candidate have to be displayed

### Steps To Reproduce

you can use this preview link https://gist.github.com/edulix/0876c3cc673b99407cf4175f62ae05dc

or view this election https://felix-dev.sequentech.io/booth/34562714/demo-vote

### Environment

```markdown
- OS:
- Web browser:
```

### Tasks

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/voting-booth/pull/357
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/voting-booth/pull/362
```
