### ISSUE TITLE
🐞write-in label not working

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#149]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Current Behavior

Using placeholder instead of label. Related to https://github.com/sequentech/meta/issues/125

### Expected Behavior

The write-in label should work.

### Tasks

```[tasklist]
# Tasks
- [ ] Fix write-in label
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/voting-booth/pull/354
```

```[tasklist]
# Stable PRs
- [ ] Task 1
```
