### ISSUE TITLE
✨ Add html support for write-in extrafield labels/help

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#150]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Enable using html on label/help on write-in extra fields.

### Screenshots

<img width="604" alt="Screenshot 2023-07-18 at 17 05 34" src="https://github.com/sequentech/meta/assets/3913223/b056fcd8-fa8c-4cb6-bad2-e824edc9c5a2">

### Tasks

```[tasklist]
# Tasks
- [x] Use ng-bind-html
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/voting-booth/pull/358
```

```[tasklist]
# Stable PRs
- [ ] voting-booth
```
