### ISSUE TITLE
✨ Implement Delete for Election Event

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1502]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Implement delete for Election Event. It should delete everything related to it.

### Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] Implement delete Election Event API in Harvest
- [ ] Implement delete Election Event API in Windmill
- [ ] Link to delete Election Event in Hasura with appropriate permissions
- [ ] Remove automatic Delete Election Event action in Hasura (the one managed by Hasura)
- [ ] Windmill: Delete Realm
- [ ] Windmill: Delete Bulletin Board
- [ ] Windmill: Delete linked S3 artifacts
- [ ] Windmill: Delete data in Hasura/PostgreSQL
```

```[tasklist]
# Main PRs
- [ ] PR 1
```
