### ISSUE TITLE
🐞 Start Ceremony appears in Cancelled Tallies

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1505]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.

### Current Behavior

Start Ceremony appears in Cancelled Tallies.

https://github.com/user-attachments/assets/d0e66e2d-6059-4ff8-bc14-24c13ff07f2f

### Expected Behavior

Ensure this can only appear in the UI when it should, and not in any other state.

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [x] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] PR 1
```

**Comment by yvwbimpong** [comment]
https://github.com/user-attachments/assets/e08b3487-853c-4061-a844-edd72c11d0c3

**Comment by yvwbimpong** [comment]
https://github.com/user-attachments/assets/e1428849-59de-4668-b130-0e1d5fede947

**Comment by edulix** [comment]
Fixed by #1506
