### ISSUE TITLE
✨ Improvements in beyond repository

### ISSUE THREAD

**Issue by jorgermp** [sequentech/meta#1507]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

We need to have some improvements in beyond repository:

- Better process for create tags for helm charts.
- Move all infra folders to a one folder.
- Ensure that all references from gitops to helm chart must be use tags.
- Move docs from gitops to beyond repository.

### Screenshots

<empty>

```[tasklist]
# Tasks
- [x] Move docs from gitops to beyond
- [x] Move all infra folder to one folder inside the repository, it's necessary check all url in gitops repository are change
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/beyond/pull/62
- [ ] https://github.com/sequentech/gitops/pull/713
- [ ] https://github.com/sequentech/beyond/pull/66
- [ ] https://github.com/sequentech/gitops/pull/841
```

**Comment by jorgermp** [comment]
@edulix I need access to create secrets in repositories for make tests in new release process.
