### ISSUE TITLE
✨ Visualization of write-in fields in Review

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#151]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

The write-in fields in the review screen should appear just like in the voting screen, but non-editable. This should be an option, and the other option would be to just show the final write-in string.

### Tasks

```[tasklist]
# Tasks
- [ ] Implementation
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/voting-booth/pull/363
- [ ] https://github.com/sequentech/documentation/pull/128
```
