### ISSUE TITLE
✨ Initial work on kubernetes support [testing]

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#152]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Initial exploratory work on kubernetes support. This is just a way to test the waters.

### Tasks

```[tasklist]
# Tasks
- [x] Create a new `deployments` repo
- [x] deployments: deploy new k8s cluster with terraform
- [x] deployments: deploy cloudnative-pg k8s operator with helm and terraform 
- [x] deployments:  include how to in the README
- [ ] election-orchestra: Create basic election-orchestra docker image with a `Dockerfile`
- [ ] election-orchestra: use github actions that push new docker images to a container registry on git push
- [ ] election-orchestra: create a helm chart for election-orchestra
- [ ] deployments: deploy the election-orchestra helm chart with terraform 
```

```[tasklist]
# Master PRs
```

**Comment by edulix** [comment]
Leaving this for later
