### ISSUE TITLE
🐞 Inetum authentication badly formatted images and visible scrollbar

### ISSUE THREAD

**Issue by xalsina-sequent** [sequentech/meta#1564]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.

### Current Behavior

Some issues have been found in Inetum authentication, some images are not displayed correctly and a scrollbar is visible in certain resolutions.

Missing images:

Instruction toolbar not correctly displayed in certain resolutions:

<img width="693" alt="Captura de pantalla 2024-08-02 a les 12 22 41" src="https://github.com/user-attachments/assets/b8ba054a-344d-4683-8db9-14493e8c1be2">

### Expected Behavior

The images should be displayed correctly and the scrollbar should not be visible.

### Screenshots

Fixed instructions toolbar:

![Captura de pantalla 2024-08-02 a les 12 25 21](https://github.com/user-attachments/assets/80ca5858-5c4c-41df-a1cf-5d3fdde82fa8)

Fixed missing images:

<img width="1264" alt="Captura de pantalla 2024-08-02 a les 10 40 06" src="https://github.com/user-attachments/assets/f5e942a0-6680-4583-864c-d5f4cd7a8229">

Video with the changes in responsiveness:

https://github.com/user-attachments/assets/06da2bc5-d43a-44cb-9aa0-b6ea28199b8b

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [x] Fixed images that are not diplayed correctly (Missing configuration in Inetum Authenticator)
- [x] Fixed visible scrollbar in certain resolutions (Detected when the page is way wider than tall)
- [x] Fixed Instructions toolbar shows too small in certain resolutions (f.e. 720p)
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/596
```
