### ISSUE TITLE
🐞 Inetum authenticator does not allow to set attributes to check empty

### ISSUE THREAD

**Issue by xalsina-sequent** [sequentech/meta#1576]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.

### Current Behavior

Inetum authenticator gives an error when setting is empty.

### Expected Behavior

Inetum authenticator should be able to be configured without checking attributes.

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [x] Ignore tildes when comparing strings
- [x] Be able to set attributes to check empty
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/597
```
