### ISSUE TITLE
✨ Initial work on voting-portal

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#158]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Create voting-portal repo and initial work for the voting booth of the next generation. Use the [Figma design](https://www.figma.com/file/lVNVX8BwQJjBPk0ZPb0NJ3) as a guideline.

### Possible Implementation

Implementation.

### Tasks

```[tasklist]
# Tasks
- [x] Create `voting-portal` repo.
- [x] Create `Voting Portal 11.0` Milestone.
- [x] Add issues to milestone.
- [x] Copy skeleton for `voting-portal` repo from `new-ballot-verifier` (storybook, nix, github actions, package.json, prettify, gitignore, ui-essentials submodule, sequent-core import...).
- [x] Add example election with 1st-gen format (using `sequent-core` types).
- [x] Add `redux` state for election data and ballot selection.
- [x] Add start screen, voting screen, review screen.
- [x] Add textToHtml with sanitizeHtml (to avoid XSS injection) to `ui-essentials`.
- [x] Add `sleep` method  to `ui-essentials`.
- [x] Add BallotHash component to  to `ui-essentials`.
- [x] Modify Footer to be shorter.
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/voting-portal/pull/1
- [ ] https://github.com/sequentech/ui-essentials/pull/5
```

# Screenshots

Start screen

![Image](https://github.com/sequentech/meta/assets/3913223/715de2df-aef9-4b20-b283-4db4e1a0704e)

Voting screen

![Image](https://github.com/sequentech/meta/assets/3913223/8cd48bb1-1a2a-410e-9417-4ab167c7e5a3)

Review Screen

![Image](https://github.com/sequentech/meta/assets/3913223/fe759e20-5e5e-430f-9469-bd7d32d4fa7f)
