### ISSUE TITLE
✨ Support categories/lists

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#159]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Support grouping answers into categories

### Possible Implementation

Example: https://felix-dev.sequentech.io/booth/34570004/demo-vote

Screenshot from 1st gen:

![Image](https://github.com/sequentech/meta/assets/3913223/fd362415-80ba-4e07-b1eb-6cef89c388c5)

![Image](https://github.com/sequentech/meta/assets/3913223/fe58d3d3-b3d0-497d-ae7f-4a6ecdff0a43)

Similar to 1st-gen

### Tasks

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/ui-essentials/pull/10
- [ ] https://github.com/sequentech/voting-portal/pull/8
```

### Additional context

-
