### ISSUE TITLE
✨ Manual verification template should be a file

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#1598]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

The [manual verification template](https://github.com/sequentech/step/blob/8a67f5ce57499a3527930d4e0575570109f574c4/packages/windmill/src/services/manual_verification.rs#L170) should be a file.

<img width="1020" alt="Screenshot 2024-08-03 at 15 14 27" src="https://github.com/user-attachments/assets/4bda97bb-77bb-4226-b5ad-552e13f45944">

### Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] Create/use a file in .devcontainer/minio/public-assets to replace hardcoded string.
- [ ] Upload file to existing deployments.
- [ ] Check automatic deployment code uploads file.
```

```[tasklist]
# Main PRs
- [ ] PR 1
```

**Comment by edulix** [comment]
dupe of #1610
