### ISSUE TITLE
🐞 Can't create voters

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#1599]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.

### Current Behavior

Can't create voters.

```
INFO POST /create-user application/json:
INFO Matched: (create_user) POST /create-user application/json
┐create_user body=Json(CreateUserBody { tenant_id: "90505c8a-23a9-4cdf-a26b-4e19f6a097d5", election_event_id: Some("e5d570c3-716e-47d5-9ba7-6bf2b332f523"), user: User { id: None, attributes: None, email: Some("felix@sequentech.io"), email_verified: None, enabled: Some(true), first_name: Some("felix"), last_name: None, username: Some("felix"), area: None, votes_info: None } })
├──┐authorize check_super_admin=true, tenant_id_opt=Some("90505c8a-23a9-4cdf-a26b-4e19f6a097d5"), permissions=[VOTER_CREATE]
├──┘
├──┐new 
│  ├──283ms INFO Successfully acquired credentials
├──┘
├──┐create_user realm="tenant-90505c8a-23a9-4cdf-a26b-4e19f6a097d5-event-e5d570c3-716e-47d5-9ba7-6bf2b332f523", user=User { id: None, attributes: None, email: Some("felix@sequentech.io"), email_verified: None, enabled: Some(true), first_name: Some("felix"), last_name: None, username: Some("felix"), area: None, votes_info: None }, attributes=Some({"tenant-id": ["90505c8a-23a9-4cdf-a26b-4e19f6a097d5"]}), groups=Some(["voter"])
│  ├── 99ms ERROR error=HttpFailure { status: 400, body: Some(KeycloakHttpError { error: None, error_message: Some("error-invalid-multivalued-size") }), text: "{\"field\":\"emailAndOrMobile\",\"errorMessage\":\"error-invalid-multivalued-size\",\"params\":[\"emailAndOrMobile\",1,2]}" }
├──┘
┘
INFO Outcome: Success(500 Internal Server Error)
```

### Expected Behavior

-

### Tasks

```[tasklist]
# Tasks
- [ ] Issue has been triaged
- [ ] Successful replication of the defect
- [ ] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/602
```
