### ISSUE TITLE
✨ Improve handling of templates

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1610]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Improve handling of templates

### Possible Implementation

-

### Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] Remove Magic Strings from Manual Verification task
- [ ] Make Manual Verification a configurable template
- [ ] Move All windmill and harvest env vars to structs and Config impl `fn from_env()` like in `database.rs`
- [ ] Migrate all pdf generation to lambda functions
```

```[tasklist]
# Main PRs
- [ ] PR 1
```
