### ISSUE TITLE
🐞 Unable to cast ballot

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1612]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.

### Current Behavior

A voter could not cast a vote. She tried multiple times.

### Expected Behavior

She should be able to cast the vote.

### Tasks

```[tasklist]
# Tasks
- [ ] Find the source of the problem
- [ ] Fix the issue in the code
- [ ] Fix the issue of the frontend visualization of the language selector, it looks bad (see screenshot)
```

```[tasklist]
# Main PRs
- [ ] PR 1
```
