### ISSUE TITLE
✨ Voting Portal -> Ballot List: Improve error handling

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1613]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Error handling in the Ballot List (just after login) should be much better.

### Ballot List Error cases

**Errors:**

1. Voter is not associated with voting area

2. Network error

3. Unable to fetch data (not due to network error)

4. No election event

5. Ballot styles EML error

6. Failure to obtain election from ID

**Alerts:**

1. No elections (could be because the area has no contests)
2. Election event not published

### Screenshots

Error:
<img width="1239" alt="image" src="https://github.com/user-attachments/assets/0410eb77-8f5f-4356-8b5d-274782d52ba2">

Alert:
<img width="1239" alt="image" src="https://github.com/user-attachments/assets/db165db6-69f0-449a-9be2-ba9e0f2ed4db">

```[tasklist]
# Tasks
- [x] Identify all cases where Ballot List would shown an error and LIST them in the section above (`Ballot List Error cases`)
- [x] Create Error Enums in Frontend to fetch different errors
- [x] Detect these error cases in the UI and show different i18n messages for each case
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/606
```
