### ISSUE TITLE
✨ Custom URLs Support

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1614]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Support associating custom URLs for different election event links.

### Possible Implementation

Support configuring the URL for login, and the URL for registration on an election to use a custom URL.

### Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] add a presentation setting hashmap setting for associating specific keys like `login` or `enrollment` to a domain. This should be part of the election event import/export, with a default of `None`.
- [ ] add env vars to support multiple CustomUrl backends: `console`, `cloudflare` related to the deployed environment
- [ ] Implement an API in harvest to check & configure the election event urls, so that when it changes, calls to the deployment to change the custom url
- [ ] implement the UI in Election Event > Data > New section called `Custom URLs` where multiple URLs can be configured (for now 2 urls, login and enrollment)
- [ ] create the PR in beyond & gitops repos
```

```[tasklist]
# Main PRs
- [ ] PR 1
```
