### ISSUE TITLE
🐞 Keycloak registration defects, username, helper text, date format.

### ISSUE THREAD

**Issue by xalsina-sequent** [sequentech/meta#1615]
Project Reference: https://sequentech.atlassian.net/browse/COM-1442

### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.

### Current Behavior

Issues detected at keycloak registration:

1. Hiding username using "Email as username" makes email a required field.
2. Helper text attribute not showing for email.
3. Helper text cannot be configured for password field.
5. Input fields and labels use different font sizes.
6. Password strength bar should be shown.

### Expected Behavior

Here is how it should behave:

1. Username should be able to be hidden without using Keycloak's "Email as username" feature.
2. Helper text should be displayed for email attribute.
3. Helper text should be displayed for password field.
5. Use the same font size for input fields and labels.
6. A password strength bar is shown that measures the quality of the inputted password.

### Screenshots

You can now hide the username using a custom attribute called hidden. Needs to be set to true.

![Captura de pantalla 2024-08-08 a les 10 21 06](https://github.com/user-attachments/assets/ba5a83ce-e4a4-4c7d-9f84-04a80629c6bb)

You can now add a helper text to password adding a custom annotation called "passwordHelperTextBefore" and "passwordHelperTextAfter"to either username or email depending on the value of "email as username"

![Captura de pantalla 2024-08-08 a les 10 22 57](https://github.com/user-attachments/assets/f806f8fa-7a2b-4f29-9cd6-1176c08c7dde)

![Captura de pantalla 2024-08-08 a les 10 24 53](https://github.com/user-attachments/assets/c61ba498-35b2-43c5-86d3-85e6a030f832)

To enable password strength bar you have to add a custom annotation called passwordStrengthBar to either username or email depending on the value of "email as username"

![Captura de pantalla 2024-08-08 a les 10 19 32](https://github.com/user-attachments/assets/09d32661-41ac-4612-9988-bb41fdd5a63e)

Video with password strength indicator.

https://github.com/user-attachments/assets/2f490e51-4f3c-455a-a531-c6ddc073cb85

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [x] Username should be able to not appear on registration without making email as required.
- [x] Display helper text for password.
- [x] Display helper text email.
- [x] Different sized fonts for registration inputs and labels.
- [x] Password strength
- [ ] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/605
```
