### ISSUE TITLE
🐞 Deferred Registration User Profile Creation issues with unique configuration, error reporting and attributes accents and diacritics.

### ISSUE THREAD

**Issue by xalsina-sequent** [sequentech/meta#1616]
Project Reference: https://sequentech.atlassian.net/browse/COM-1442
 
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.

### Current Behavior

Issues for the Deferred Registration User Profile Creation Authenticator:

1. Unique attribute fails when the validated attribute matches the selected user.
2. Not much info is given in the logs when selected attributes does not match any user.
3. It's not clear for the user that the data given in the form did not match any user in the database.

### Expected Behavior

The expected behavior:

1. Unique attribute configuration should ignore selected user.
2. Select user should give more information to logs when user does not match. F.e. display a message that the following attributes did not match any user.
3. Give a clearer message to the user that the data in the form did not match any user in roll.

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [x] Successful defect resolution merged
- [x] Fixed unique attribute configuration
- [x] Given more information in logs for user not matching.
- [x] Better reporting for the user in case the form data does not match any user in the system.
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/615
```
