### ISSUE TITLE
🐞 Chrome library gets stuck rendering

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1629]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.

### Current Behavior

Chrome library gets stuck rendering

### Expected Behavior

It should not get stuck.

### Tasks

```[tasklist]
# Tasks
- [ ] Issue has been triaged
- [ ] Successful replication of the defect
- [ ] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/608
- [ ] https://github.com/sequentech/step/pull/610
```
