### ISSUE TITLE
✨ Voting Portal -> Cast Vote: Improve error handling

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1650]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Error handling in the Cast Vote Screen should be much better.

### Possible Implementation

**Errors:**

1. Network error:
Message: "There was a network problem affecting the request. Please try again later."

2. Unable to fetch data (not due to network error):
Message: "Cannot load election event. Please try again later."

3. No election event:
Message: "Election event doesn’t exist. Please contact support."
![Image](https://github.com/user-attachments/assets/c75257f8-8241-49c7-8b67-034eddc04e8a)

4. Election event is closed
![Image](https://github.com/user-attachments/assets/976146cb-d73a-45f7-960e-35fcee29c797)

5. No ballot style:
Message: "The ballot style is not available. Please contact support."
**After refresh for example**
![Image](https://github.com/user-attachments/assets/dc89121c-3f14-42f2-bf36-7dc409d21df6)

6. state.ballotSelections[electionId] is null:
Message: "The selection state for this election is not present. Please ensure you have selected your choices correctly."

7. No auditable ballot:
Message: "No auditable ballot is available. Please contact support."

8. Inconsistent ballot hash (Error with hashBallot function):
Message: "There was an error related to the ballot hashing process.
ballotId: ${ballotId} is not consistent with auditable Ballot Hash: ${auditableBallot.ballot_hash}.
 Please report this issue to support."

9. Errors with "toHashableBallot" function:
- PARSE_ERROR: "There was an error parsing the ballot. Please try again later or contact support for assistance."
- DESERIALIZE_AUDITABLE_ERROR: "There was an error deserializing the auditable ballot. Please try again later or contact support for assistance."
- DESERIALIZE_HASHABLE_ERROR: "There was an error deserializing the hashable ballot. Please try again later or contact support for assistance."
- CONVERT_ERROR: "There was an error converting the ballot. Please try again later or contact support for assistance."
- SERIALIZE_ERROR: "There was an error serializing the ballot. Please try again later or contact support for assistance."

10.  Unable to cast vote:
Message: "There was an error with graphQL while casting the vote. Please try again later or contact support for assistance."

### Screenshots

<empty>

### Cast Vote Error cases

<empty>

```[tasklist]
# Tasks
- [x] Identify all cases where Cast Vote Screen would shown an error and list them in the section above (Cast Vote Error cases)
- [x] Create Error Enums in backend to return different error keys in the multiple API calls when there's an error
- [x] Detect these error cases in the UI and show different i18n messages for each case
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/613
```
