### ISSUE TITLE
🐞 Ballot Receipt template is not saved correctly

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1651]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.

### Current Behavior

Ballot Receipt template is not saved correctly, SMS is saved a struct instead of as a string:
![image](https://github.com/user-attachments/assets/4d4fc4f2-5b9a-4186-8486-d8f305f7120c)

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/c7ca9739-6d7e-4ce4-8280-e26ab7c6c465">

This means that after assigning a Vote Receipt Document template, the vote receipt is not generated and creates an error:

```
2024-08-06T10:21:03.241515948Z │  ├──┐get_template tenant_id="90505c8a-23a9-4cdf-a26b-4e19f6a097d5", election_event_id="62b148e4-a8bb-48c3-bbb8-f050ea62da9a", election_id="14d2eb61-091c-49ee-8d3f-a4825c8f6eef"
2024-08-06T10:21:03.241520778Z │  │  ├──┐get_election_by_id tenant_id="90505c8a-23a9-4cdf-a26b-4e19f6a097d5", election_event_id="62b148e4-a8bb-48c3-bbb8-f050ea62da9a", election_id="14d2eb61-091c-49ee-8d3f-a4825c8f6eef"
2024-08-06T10:21:03.241524768Z │  │  │  ├──  0ms DEBUG preparing query s466: 
2024-08-06T10:21:03.241528648Z │  │  │  │              SELECT
2024-08-06T10:21:03.241532168Z │  │  │  │                  id,
2024-08-06T10:21:03.241536479Z │  │  │  │                  tenant_id,
2024-08-06T10:21:03.241539969Z │  │  │  │                  election_event_id,
2024-08-06T10:21:03.241543599Z │  │  │  │                  created_at,
2024-08-06T10:21:03.241546959Z │  │  │  │                  last_updated_at,
2024-08-06T10:21:03.241550359Z │  │  │  │                  labels,
2024-08-06T10:21:03.241573990Z │  │  │  │                  annotations,
2024-08-06T10:21:03.241578870Z │  │  │  │                  name,
2024-08-06T10:21:03.241582520Z │  │  │  │                  description,
2024-08-06T10:21:03.241586150Z │  │  │  │                  presentation,
2024-08-06T10:21:03.241589750Z │  │  │  │                  dates,
2024-08-06T10:21:03.241593670Z │  │  │  │                  status,
2024-08-06T10:21:03.241597631Z │  │  │  │                  eml,
2024-08-06T10:21:03.241601171Z │  │  │  │                  num_allowed_revotes,
2024-08-06T10:21:03.241605241Z │  │  │  │                  is_consolidated_ballot_encoding,
2024-08-06T10:21:03.241609161Z │  │  │  │                  spoil_ballot_option,
2024-08-06T10:21:03.241612851Z │  │  │  │                  alias,
2024-08-06T10:21:03.241616561Z │  │  │  │                  voting_channels,
2024-08-06T10:21:03.241620511Z │  │  │  │                  is_kiosk,
2024-08-06T10:21:03.241624321Z │  │  │  │                  image_document_id,
2024-08-06T10:21:03.241628452Z │  │  │  │                  statistics,
2024-08-06T10:21:03.241632342Z │  │  │  │                  receipts
2024-08-06T10:21:03.241636112Z │  │  │  │              FROM
2024-08-06T10:21:03.241641782Z │  │  │  │                  sequent_backend.election
2024-08-06T10:21:03.241645912Z │  │  │  │              WHERE
2024-08-06T10:21:03.241649342Z │  │  │  │                  tenant_id = $1 AND
2024-08-06T10:21:03.241652752Z │  │  │  │                  election_event_id = $2 AND
2024-08-06T10:21:03.241656483Z │  │  │  │                  id = $3;
2024-08-06T10:21:03.241660553Z │  │  │  │              
2024-08-06T10:21:03.241835418Z │  │  │  ├──  0ms DEBUG executing statement s466 with parameters: [90505c8a-23a9-4cdf-a26b-4e19f6a097d5, 62b148e4-a8bb-48c3-bbb8-f050ea62da9a, 14d2eb61-091c-49ee-8d3f-a4825c8f6eef]
2024-08-06T10:21:03.242334115Z │  │  ├──┘
2024-08-06T10:21:03.242346475Z │  │  ├──┐get_communication_template_by_id tenant_id="90505c8a-23a9-4cdf-a26b-4e19f6a097d5", communication_template_id="8c1d99b1-4871-4e35-b74e-f253b80233d7"
2024-08-06T10:21:03.242354965Z │  │  │  ├──  0ms DEBUG preparing query s467: 
2024-08-06T10:21:03.242359136Z │  │  │  │              SELECT
2024-08-06T10:21:03.242362766Z │  │  │  │                  id,
2024-08-06T10:21:03.242366426Z │  │  │  │                  tenant_id,
2024-08-06T10:21:03.242370206Z │  │  │  │                  template,
2024-08-06T10:21:03.242373876Z │  │  │  │                  created_by,
2024-08-06T10:21:03.242377577Z │  │  │  │                  labels,
2024-08-06T10:21:03.242381116Z │  │  │  │                  annotations,
2024-08-06T10:21:03.242384577Z │  │  │  │                  created_at,
2024-08-06T10:21:03.242413498Z │  │  │  │                  updated_at,
2024-08-06T10:21:03.242417898Z │  │  │  │                  communication_method,
2024-08-06T10:21:03.242421667Z │  │  │  │                  communication_type
2024-08-06T10:21:03.242425798Z │  │  │  │              FROM
2024-08-06T10:21:03.242429748Z │  │  │  │                  sequent_backend.communication_template
2024-08-06T10:21:03.242433459Z │  │  │  │              WHERE
2024-08-06T10:21:03.242437128Z │  │  │  │                  tenant_id = $1 AND
2024-08-06T10:21:03.242441099Z │  │  │  │                  id = $2;
2024-08-06T10:21:03.242444868Z │  │  │  │              
2024-08-06T10:21:03.242657946Z │  │  │  ├──  0ms DEBUG executing statement s467 with parameters: [90505c8a-23a9-4cdf-a26b-4e19f6a097d5, 8c1d99b1-4871-4e35-b74e-f253b80233d7]
2024-08-06T10:21:03.243087219Z │  │  ├──┘
2024-08-06T10:21:03.243097010Z │  │  ├──  1ms ERROR error=invalid type: map, expected a string
2024-08-06T10:21:03.243100601Z │  ├──┘
2024-08-06T10:21:03.243103980Z │  ├──  3ms ERROR error=invalid type: map, expected a string
2024-08-06T10:21:03.243107510Z ├──┘
2024-08-06T10:21:03.243376149Z ├──  4ms ERROR error=invalid type: map, expected a string
2024-08-06T10:21:03.243388790Z ┘
2024-08-06T10:21:03.243393150Z ├──  4ms ERROR error=Anyhow(Task failed
2024-08-06T10:21:03.243396940Z │  
2024-08-06T10:21:03.243400639Z │  Caused by:
2024-08-06T10:21:03.243404410Z │      invalid type: map, expected a string
2024-08-06T10:21:03.243493442Z │  
2024-08-06T10:21:03.243522643Z │  Stack backtrace:
2024-08-06T10:21:03.243527784Z │     0: anyhow::error::<impl anyhow::Error>::msg
2024-08-06T10:21:03.243531555Z │     1: tokio::runtime::park::CachedParkThread::block_on
2024-08-06T10:21:03.243535155Z │     2: tokio::runtime::handle::Handle::block_on
2024-08-06T10:21:03.243539095Z │     3: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
2024-08-06T10:21:03.243542795Z │     4: tokio::runtime::task::core::Core<T,S>::poll
2024-08-06T10:21:03.243546555Z │     5: tokio::runtime::task::raw::poll
2024-08-06T10:21:03.243550035Z │     6: tokio::runtime::blocking::pool::Inner::run
2024-08-06T10:21:03.243553535Z │     7: std::sys::backtrace::__rust_begin_short_backtrace
2024-08-06T10:21:03.243557044Z │     8: core::ops::function::FnOnce::call_once{{vtable.shim}}
2024-08-06T10:21:03.243560684Z │     9: std::sys::pal::unix::thread::Thread::new::thread_start
2024-08-06T10:21:03.243564205Z │    10: <unknown>
2024-08-06T10:21:03.243567676Z │    11: <unknown>)
2024-08-06T10:21:03.243571276Z ┘
2024-08-06T10:21:03.243574836Z ERROR Task create_vote_receipt[e78bd599-5f04-4dca-9a5a-fb4f12e8e50c] failed with unexpected error: Task failed
2024-08-06T10:21:03.243603187Z 
2024-08-06T10:21:03.243607827Z Caused by:
2024-08-06T10:21:03.243611627Z     invalid type: map, expected a string
2024-08-06T10:21:03.243614846Z 
2024-08-06T10:21:03.243618297Z Stack backtrace:
2024-08-06T10:21:03.243621997Z    0: anyhow::error::<impl anyhow::Error>::msg
2024-08-06T10:21:03.243625618Z    1: tokio::runtime::park::CachedParkThread::block_on
2024-08-06T10:21:03.243629188Z    2: tokio::runtime::handle::Handle::block_on
2024-08-06T10:21:03.243633207Z    3: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
2024-08-06T10:21:03.243636807Z    4: tokio::runtime::task::core::Core<T,S>::poll
2024-08-06T10:21:03.243640318Z    5: tokio::runtime::task::raw::poll
2024-08-06T10:21:03.243644218Z    6: tokio::runtime::blocking::pool::Inner::run
2024-08-06T10:21:03.243648148Z    7: std::sys::backtrace::__rust_begin_short_backtrace
2024-08-06T10:21:03.243651887Z    8: core::ops::function::FnOnce::call_once{{vtable.shim}}
2024-08-06T10:21:03.243655739Z    9: std::sys::pal::unix::thread::Thread::new::thread_start
2024-08-06T10:21:03.243659528Z   10: <unknown>
2024-08-06T10:21:03.243663509Z   11: <unknown>
2024-08-06T10:21:03.243695129Z INFO Task create_vote_receipt[e78bd599-5f04-4dca-9a5a-fb4f12e8e50c] retrying (1 / 4)
```

It fails here:

```rust
    let communication_template_value: CommunicationTemplateValue =
        serde_json::from_value(communication_template.template)?;
```

Which should have a `.with_context(|| "Error parsing the communication template")?;` instead to have clearer error reporting in the logs.

### Expected Behavior

Ballot Receipt Documents should work. Also please ensure they can be imported and exported in the election event json import/export function.

### Tasks

```[tasklist]
# Tasks
- [ ] Issue has been triaged
- [ ] Successful replication of the defect
- [ ] Successful defect resolution merged
- [ ] Add with_context
```

```[tasklist]
# Main PRs
```

**Comment by edulix** [comment]
Closed, works fine
