### ISSUE TITLE
🐞 400 error after voting

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#1654]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.

### Current Behavior

400 error after voting.

### Expected Behavior

no error

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [x] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/voting-booth/pull/464
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/voting-booth/pull/457
- [ ] https://github.com/sequentech/voting-booth/pull/458
```
