### ISSUE TITLE
✨ KeyCloak: Define and Improve notifications and error screens

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1655]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Project Reference: 1

Keycloak: Define and Improve notifications and error screens.

### Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] DeferredRegistrationUserCreation: Review Figma Design and talk with Luis/Guy to ensure that  If the voter is already validated, the system shall display message, "Your record has already been validated. Thank you."
- [ ] LookupAndUpdateUser: In Success Screen, add a configuration to support sending an Email and/or SMS on Success
```

```[tasklist]
# Main PRs
- [ ] PR 1
```
