### ISSUE TITLE
✨ Keycloak: Add support for Viber/Whatsapp 2FA

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1657]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Project Reference: 15

Add support for Viber/Whatsapp 2FA.

### Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] DeferredRegistrationUserCreation: allow selecting Viber/Whatsapp as preferred Tlf contact method, and save it in auth-notes
- [ ] MessageOTPAuthenticator: Depending on the 2FA message method, allow to send via viber or whatsapp and change the visualization accordingly, following the figma design
- [ ] SmsSenderProvider: Add Whatsapp and Viber Sender providers using AWS Pinpoint or similar
- [ ] Deployment: Ensure this works in AWS deployments
```

```[tasklist]
# Main PRs
- [ ] PR 1
```
