### ISSUE TITLE
✨ KeyCloak: Improve Management of Error Cases during enrollment

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1658]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Project Reference: 18
Project Reference: 19
Project Reference: 20

KeyCloak: Improve Management of Error Cases during enrollment.

### Screenshots

<empty>

### Error list

```[tasklist]
# Tasks
- [ ] Identify  in each authenticator using during enrollment, each potential error and list it in the `Error list` section above 
- [ ] For each error, generate an user event error in keycloak and get/assign a unique error number that is shown to the user
- [ ] For each user error shown to the user, agree with Guy/Luis what is the message to be shown and the UI elements
- [ ] Implement a way to show keycloak events in the admin portal in a tab
```

```[tasklist]
# Main PRs
- [ ] PR 1
```

**Comment by omri81** [comment]
https://github.com/sequentech/step/pull/615
