### ISSUE TITLE
✨ Allow to import data in a zip file with comelec format

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1659]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Project Reference: EMS-3

Allow to import data in a zip file with comelec format (SQL etc). This should be able to execute both from the UI in Import (choosing the format).

### Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] Allow to import data in a zip file with comelec format.
- [ ] (windmill) Allow to import only specific data (only elections but not candidates for example)
- [ ] (admin-portal) Allow to import only specific data (only elections but not candidates for example)
```

```[tasklist]
# Main PRs
- [ ] PR 1
```
