### ISSUE TITLE
✨ Improve Communication Templates

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1660]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Project Reference: EMS-4

Improve Communication Templates

### Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] Implement Preview Function
- [ ] Add support for exporting and importing all templates
- [ ] Prepare templates in compliance with Annex A (collaboration with Luis/A)
```

```[tasklist]
# Main PRs
- [ ] PR 1
```
