### ISSUE TITLE
✨ Allow to Annotate areas to generate specific reports (including tally)

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1661]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Project Reference: EMS-15

Allow to Annotate areas to generate specific reports (including tally).

### Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] Backend: Allow to import and export Areas's annotations
- [ ] Admin Portal: Have an UI with checkboxes to mark an area to generate different types of reports, for example consolidated tally. Talk with Guy/Luis about what reports need checkmarks.
- [ ] Backend: Store the annotations and publish them
- [ ] Velvet: Use Area Annotations to decide if these reports are generated and generate them at that level.
```

```[tasklist]
# Main PRs
- [ ] PR 1
```
