### ISSUE TITLE
✨Admin Portal: Improvements in User Management 

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1663]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Multiple improvements in Admin Portal > User and Roles

### Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] In Users and Roles, the information displayed in the table list shall be the same when adding/ modifying a user
- [ ] Support configuring all keycloak user profile fields when creating or editing an user
- [ ] Support showing, sorting and filtering all user profile fields in user list
- [ ] Move change password to its own action, and move actions to a popup contextual menu for each user. Also, add a checkbox to indicate if the new password is temporary or not.
- [ ] When adding a new role, allow to set the permissions to be added for this role in the form.  
```

```[tasklist]
# Main PRs
- [ ] PR 1
```
