### ISSUE TITLE
✨ Implement full deployment backup/restore

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1664]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Project Reference: https://sequentech.atlassian.net/browse/COM-1471

Implement full deployment backup/restore

### Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] (hasura, harvest, windmill) Implement function in harvest to launch a full system backup/restore
- [ ] (windmill) full postgres databases backup/restore, uploading to s3 encrypted
- [ ] (windmill) full immudb databases backup/restore, uploading to s3 encrypted
- [ ] (windmill) full s3 backup/restore, uploading to s3 encrypted
- [ ] (admin-portal) Add Full Backup/Restore support
```

```[tasklist]
# Main PRs
- [ ] PR 1
```
