### ISSUE TITLE
🐞 Write-in issues

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#1670]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.

### Current Behavior

- If a write-in field has a minimum > 0 and the write-in is selected with some other fields filled in, the empty field is not showing a warning.

### Expected Behavior

-

### Tasks

```[tasklist]
# Tasks
- [x] Show warning for empty write-in field with min > 0.
```

```[tasklist]
# 10.4.x PRs
- [ ] https://github.com/sequentech/voting-booth/pull/459
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/voting-booth/pull/460
```
