### ISSUE TITLE
🐞 Voter portal login fails when using UsernamePasswordFormWithExpiry authenticator in browser flow and login with invalid credentials

### ISSUE THREAD

**Issue by xalsina-sequent** [sequentech/meta#1681]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.

### Current Behavior

![Captura de pantalla 2024-08-09 a les 16 01 32](https://github.com/user-attachments/assets/44edc9b8-2ea8-479f-b0b8-eea837cee89e)

Logs:

`keycloak  | 2024-08-09 14:01:11,670 INFO  [sequent.keycloak.authenticator.forgot_password.UsernamePasswordFormWithExpiry] (executor-thread-25) action()
keycloak  | 2024-08-09 14:01:16,090 INFO  [sequent.keycloak.authenticator.forgot_password.UsernamePasswordFormWithExpiry] (executor-thread-31) action()
keycloak  | 2024-08-09 14:01:16,091 INFO  [sequent.keycloak.authenticator.forgot_password.UsernamePasswordFormWithExpiry] (executor-thread-31) validateForm()
keycloak  | 2024-08-09 14:01:16,091 INFO  [sequent.keycloak.authenticator.forgot_password.UsernamePasswordFormWithExpiry] (executor-thread-31) getUser(): User is null
keycloak  | 2024-08-09 14:01:16,091 INFO  [sequent.keycloak.authenticator.forgot_password.UsernamePasswordFormWithExpiry] (executor-thread-31) getUserFromForm(): start
keycloak  | 2024-08-09 14:01:16,145 INFO  [sequent.keycloak.authenticator.forgot_password.UsernamePasswordFormWithExpiry] (executor-thread-31) validateForm(): invalid form
keycloak  | 2024-08-09 14:01:16,145 WARN  [org.keycloak.services] (executor-thread-31) KC-SERVICES0013: Failed authentication: java.lang.NullPointerException: Cannot invoke "org.keycloak.authentication.FlowStatus.ordinal()" because "status" is null
keycloak  |     at org.keycloak.authentication.DefaultAuthenticationFlow.processResult(DefaultAuthenticationFlow.java:481)
keycloak  |     at org.keycloak.authentication.DefaultAuthenticationFlow.processAction(DefaultAuthenticationFlow.java:152)
keycloak  |     at org.keycloak.authentication.AuthenticationProcessor.authenticationAction(AuthenticationProcessor.java:1011)
keycloak  |     at org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:365)
keycloak  |     at org.keycloak.services.resources.LoginActionsService.processAuthentication(LoginActionsService.java:336)
keycloak  |     at org.keycloak.services.resources.LoginActionsService.authenticate(LoginActionsService.java:328)
keycloak  |     at org.keycloak.services.resources.LoginActionsService.authenticateForm(LoginActionsService.java:393)
keycloak  |     at org.keycloak.services.resources.LoginActionsService$quarkusrestinvoker$authenticateForm_32b8e198ac3110abd1d5774e83a4cf87858129f4.invoke(Unknown Source)
keycloak  |     at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
keycloak  |     at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
keycloak  |     at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
keycloak  |     at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
keycloak  |     at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
keycloak  |     at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
keycloak  |     at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
keycloak  |     at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
keycloak  |     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
keycloak  |     at java.base/java.lang.Thread.run(Thread.java:840)`

### Expected Behavior

![Captura de pantalla 2024-08-09 a les 16 03 04](https://github.com/user-attachments/assets/f197ddbd-3143-45d2-8864-98729a162dd5)

### Tasks

```[tasklist]
# Tasks
- [ ] Issue has been triaged
- [ ] Successful replication of the defect
- [ ] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/619
```
