### ISSUE TITLE
✨ Deploy start on Monday

### ISSUE THREAD

**Issue by jorgermp** [sequentech/meta#1693]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

I need update some components in all environments:
 - RabbitMQ
 - Change nodes from t3 to m6.
 - Enable snapshot to Immudb.

### Screenshots

<empty>

```[tasklist]
# Tasks
- [x] Dev
- [x] QA
- [x] UAlicante
- [x] UA
- [x] Staging
- [x] UPV
- [x] Drewnorth (stop all)
- [x] CICCP (stop all)
- [x] Comelec
```

```[tasklist]
# Main PRs
- [ ] PR 1
```
