### ISSUE TITLE
✨ Ask for Admin password before executing important tasks

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1695]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Project Reference: https://sequentech.atlassian.net/browse/COM-1490
Project Reference: https://sequentech.atlassian.net/browse/COM-1517

Ask for Admin password before executing important tasks

### Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] Investigate the best way to verify the user was asked for password using a keycloak token
- [ ] (harvest, windmill) Implement verification of user password having been asked, in the backend, before publishing an election or election event publication
- [ ] (admin-portal) Implement asking of user password before publication
```

```[tasklist]
# Main PRs
- [ ] PR 1
```
