### ISSUE TITLE
✨ Support limiting IP by country and warnings

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1696]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Project Reference: https://sequentech.atlassian.net/browse/COM-1495
Project Reference: https://sequentech.atlassian.net/browse/COM-1557

Limit voting depending on the IP address of the country of registration or voting can be done from anywhere in the world. OVCS shall generate warnings when multiple votes are cast from the same IP address for COMELEC to analyse.

### Possible Implementation

<empty>

### Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] Feature design
- [ ] Implement backend API to list and set region locks by country, using a multi-backend feature, implementing 2 backends: console and Cloudflare
- [ ] Implemented the Frontend API
- [ ] Ensure IP Address is being saved together with cast votes in the same table (maybe an annotation)
- [ ] Implement a "IP Addresses" Report that shows the top N IP Addresses with more votes cast
- [ ] the Activity Log shall show the ip address of the country where the voting is performed and the location of the voters device
```

```[tasklist]
# Main PRs
- [ ] PR 1
```
