### ISSUE TITLE
✨ Admin Portal > Publish > Support exporting paramers in PDF or Excel

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1697]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Project Reference: https://sequentech.atlassian.net/browse/COM-1518

Admin Portal > Publish > Support exporting paramers in PDF or Excel.

### Possible Implementation

<empty>

### Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] Implement with CSS a Printing mode for Preview of a Publication that shows the new publication with nice tree view, with no diff wiith respect to the previous publication, and with no "show more" but showing all in this mode
- [ ] Add a Print button that prints the page (to PDF or whatever)
```

```[tasklist]
# Main PRs
- [ ] PR 1
```
