### ISSUE TITLE
✨ Admin Portal: Graceful period: don't allow tally

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1705]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Project Reference: https://sequentech.atlassian.net/browse/COM-1579
Project Reference: https://sequentech.atlassian.net/browse/COM-1580
Project Reference: https://sequentech.atlassian.net/browse/COM-1581
Project Reference: https://sequentech.atlassian.net/browse/COM-1610

Add a new type of Tally with a bit different interface, called 
Initialization Report.

### Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] Add an Initialization Report type of tally.
- [ ] Election Event > Data > Advanced: Add "Require Initialization Report" feature, meaning if this is true, election period cannot be open if initialization report has not been generated.
- [ ] Ensure that Initialization Report has different Results configuration than the default and doesn't allow to send results to 3rd-party system  
```

```[tasklist]
# Main PRs
- [ ] PR 1
```
