### ISSUE TITLE
✨ Support Write-Ins

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#171]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Support Write-Ins, including counting bytes left for write-ins (already done for new-ballot-verifier I think).

### Tasks

```[tasklist]
# Tasks
- [x] Implement write-ins for simple case.
- [x] Add Invalid vote.
- [x] Add shuffling policies. 
- [x] Add election chooser screen.
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/ui-essentials/pull/11
- [ ] https://github.com/sequentech/voting-portal/pull/9
- [ ] https://github.com/sequentech/ui-essentials/pull/12
- [ ] https://github.com/sequentech/voting-portal/pull/10
```
