### ISSUE TITLE
🐞 Disable Monitoring for Managed Components (kube-controller-manager & kube-scheduler) on EKS

### ISSUE THREAD

**Issue by angelAtSequent** [sequentech/meta#1715]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.

### Current Behavior

We are currently receiving alerts from Prometheus indicating that the `kube-controller-manager` and `kube-scheduler` are not being detected. These components are essential in a self-managed Kubernetes cluster, but since we are running on Amazon EKS, these components are fully managed by AWS and do not need to be monitored. As a result, these alerts are irrelevant and unnecessary, leading to alert fatigue and potential oversight of more critical alerts.

### Expected Behavior

Prometheus should not raise alerts for the `kube-controller-manager` and `kube-scheduler` on our EKS cluster, as these components are managed by AWS. The monitoring system should focus on components and services that we are responsible for managing, reducing noise and ensuring that relevant alerts are given appropriate attention.

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [x] Successful defect resolution merged
- [x] Update the values.yaml file of the kube-prometheus-stack to exclude the kube-controller-manager and kube-scheduler from monitoring.
- [ ] Redeploy the kube-prometheus-stack with the updated configuration.
- [x] Verify that the alerts for kube-controller-manager and kube-scheduler are no longer being raised in Prometheus.
- [x] Monitor for a short period to ensure that the changes do not unintentionally impact other monitoring functionalities.
```
```[tasklist]
# Redeploy the kube-prometheus-stack with the updated configuration.
- [x] Apply on apa
- [x] Apply on comelec
- [x] Apply on dev
- [x] Apply on staging
- [x] Apply on ua
- [x] Apply on ualicante
- [x] Apply on upv
- [x] Apply on qa
- [ ] Apply on ciccp
- [ ] Apply on drewnorth
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/gitops/pull/829
```

**Comment by angelAtSequent** [comment]
![imagen](https://github.com/user-attachments/assets/24c82a79-3e05-4389-89fd-e5bcbdc28b20)

Left: QA environment with the change applied
Right: ciccp environment without the change applied

**Comment by angelAtSequent** [comment]
Commands executed:

```bash
$ find . -name values.prometheus.yaml -exec yq eval '.defaultRules.rules.kubeControllerManager = false' -i {} \;
$ find . -name values.prometheus.yaml -exec yq eval '.defaultRules.rules.kubeSchedulerAlerting = false' -i {} \;
$ find . -name values.prometheus.yaml -exec yq eval '.defaultRules.rules.kubeSchedulerRecording = false' -i {} \;
$ find . -name values.prometheus.yaml -exec yq eval '.kubeControllerManager.enabled = false' -i {} \;
$ find . -name values.prometheus.yaml -exec yq eval '.kubeScheduler.enabled = false' -i {} \;
```

**Comment by angelAtSequent** [comment]
This change is missing to be applied on two environments:

- drewnorth
- ciccp

They are currently stopped
