### ISSUE TITLE
🐞 Show message about setting up key ceremony before tally ceremony

### ISSUE THREAD

**Issue by yvwbimpong** [sequentech/meta#1716]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.

### Current Behavior

[After importing an election event] Start Tally ceremony for event can be started but results in an error response which is only resolved by starting and completing a keys ceremony

<img width="1792" alt="image" src="https://github.com/user-attachments/assets/c8de8683-77e7-4741-b208-faf647578601">
Can start Tally ceremony even though there is no Keys Ceremony

<img width="1792" alt="image" src="https://github.com/user-attachments/assets/cead585b-1243-4c37-bf34-6f1c14c0cf7e">
Can start Tally ceremony even though there is no Keys Ceremony

<img width="1792" alt="image" src="https://github.com/user-attachments/assets/99985862-661d-4516-b13c-72931a655c9d">
Resulting error due to unavailability of keys ceremony

### Expected Behavior

Cannot attempt to start Tally ceremony when there is no completed keys ceremony.
Better feedback when tally ceremony initiation fails as a result of this

### Screenshots

Message shown when the keys ceremony has not been completed:
<img width="1436" alt="image" src="https://github.com/user-attachments/assets/8feb4f5b-e1c2-41ab-83ce-4615de4c7082">

### Tasks

```[tasklist]
# Tasks
- [x] Disable Start Tally Ceremony button while Key ceremony is not done or show Meaningful error message when failed because of incomplete key ceremony
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/627
```
