### ISSUE TITLE
✨ Tagalog translation

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1722]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Tagalog translation. Use chatgpt or google translate, then hand off to Jojo Perlas <jojo.perlas@sequentech.io> via email the details on how review the translation.

### Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] Tagalog translation for keycloak (maybe it's already there for basic t, but we need to translate all our `keycloak-extensions`
- [ ] Admin Portal
- [ ] Voting Portal
- [ ] Ballot Verifier
- [ ] Initial PR and merge
- [ ] Send translation files to Jojo
- [ ] (Jorge) Initial deployment on Dev Environment
- [ ] (Jojo) Reviewed version by Jojo
- [ ] Final translation PR & Merge
```

```[tasklist]
# Main PRs
- [ ] PR 1
```
