### ISSUE TITLE
✨ Initial IAM setup for voting portal

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#173]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Initial IAM setup. Some links:
- https://betweendata.io/posts/react-keycloak-authentication/
- https://github.com/dasniko/keycloak-reactjs-demo/blob/main/src/index.jsx
- https://khaja.dev/posts/a-sane-starter-for-rapid-prototyping/

### Tasks

```[tasklist]
# Tasks
- [x] Initial `docker-compose.yml` that includes vanilla but working keycloak + backend-services
- [x] Use yarn workspaces for monorepo
- [x] Integrate keycloak.js in test-app
- [x] Use keycloak.js to get user profile
- [x] Integrate voting-portal in the `frontend/` directory
- [x] Integrate a graphql client to get election data from hasura
- [x] Hasura: Use permissions to get only the ballot styles related to the current user when authenticated
- [x] Hasura: Use permissions to allow to upload cast ballot for the current user
- [x] keycloak.js and graphql client: Send Bearer token obtained from hasura.js to hasura
- [x] Hasura: verify Bearer token and get claims from there
- [x] Keycloak: map roles to OIDC claims
- [x] Keycloak: add to the initial keycloak realm: [import a default user]() (edu/edu)
- [x] Deploy frontend service in `docker-compose.yml`
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/backend-services/pull/11
- [ ] https://github.com/sequentech/backend-services/pull/14
```
