### ISSUE TITLE
🐞 Admin Portal: Select sms ballot receipt template on Send Notification view doesn't show real content

### ISSUE THREAD

**Issue by yuvalkom-M** [sequentech/meta#1736]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.

### Current Behavior

![image](https://github.com/user-attachments/assets/dda444de-2411-4c55-b8e3-61df7d91478c)
on Send Notification -> Communication Template, When selecting template alias with sms method, the selected alias dosen't show and the sms message is not present correctly.

### Expected Behavior

The selected alias should be visible and the sms message should present the actual message

### Tasks

```[tasklist]
# Tasks
- [ ] Issue has been triaged
- [ ] Successful replication of the defect
- [ ] Successful defect resolution merged
- [ ] Fix the selected template alias (sms method) not shown
- [ ] add with_context(...) for handling error (#1651 Task)
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/632
```

# Screenshot

![Image](https://github.com/user-attachments/assets/8495c789-8463-4358-81c0-0b4565848d9b)
