### ISSUE TITLE
✨ Cargo Clippy Github Action and VS Run Task

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1747]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Cargo Clippy Github Action and VS Run Task.

### Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] Correct all warnings shown by Cargo Clippy
- [ ] Ensure that all non-test-related code pass the rule `cargo clippy -- -D clippy::panic`
- [ ] Github Action to execute Cargo Clippy
- [ ] Modify the VS Code Run Task `format.code` to run Cargo Clippy 
```

```[tasklist]
# Main PRs
- [ ] PR 1
```
