### ISSUE TITLE
✨ Improve Keycloak flows to comply with requirements

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#175]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Improve flows to comply with requirements.

### Tasks

```[tasklist]
# Tasks
- [ ] Detail a task here for each user flow to implement
- [ ] Decide architecture of how to implement these flow (backend? frontend? both?)
- [ ] Implement User flow 1
- [ ] Implement User flow 2
- [ ] Implement User flow 3..
```

```[tasklist]
# Master PRs
```

**Comment by edulix** [comment]
Closed because I created tickets #293 #294 #295 #296 that superseed this ticket
