### ISSUE TITLE
✨ User management backend integration

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#176]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Expose the user management database models from keycloak to hasura. This should include models required for: users, permissions and roles if any.

### Tasks

```[tasklist]
# Tasks
- [ ] Define DB models
- [ ] Implement DB models in hasura
```

```[tasklist]
# Master PRs
```
