### ISSUE TITLE
✨ Implement hash/ballot encoding on voting portal

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#179]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Implement hash/ballot encoding on voting portal

### Tasks

```[tasklist]
# Tasks
- [x] Use latest version of `strand` in `sequent-core`.
- [x] Implement encrypting a ballot from a `DecodedVoteChoice` into an `AuditableBallot` in `sequent-core`.
- [x] Use the encryption and hash methods from `sequent-core` in the `voting-portal`.
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/strand/pull/94
- [ ] https://github.com/sequentech/strand/pull/93
- [ ] https://github.com/sequentech/sequent-core/pull/19
- [ ] https://github.com/sequentech/ui-essentials/pull/9
- [ ] https://github.com/sequentech/voting-portal/pull/3
```
