### ISSUE TITLE
🐞 Voting booth doesn't shuffle answers (when they're not in a category)

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#183]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Current Behavior

Voting booth doesn't shuffle answers (when they're not in a category)

### Expected Behavior

Voting booth should shuffle answers

### Environment

```markdown
- OS:
- Web browser:
```

### Tasks

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/voting-booth/pull/364
- [ ] https://github.com/sequentech/voting-booth/pull/365
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```
