### ISSUE TITLE
✨ Bulletin Board Definition and initial Docker Compose setup

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#184]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Bulletin Board Definition and initial Docker Compose setup

### Tasks

```[tasklist]
# Tasks
- [x] Bulletin Board initial setup in `backend-services` with docker compose: adding immudb
- [x] Creation of all the issues for BB 11.0 Beta
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/13
```
