### ISSUE TITLE
✨ Admin Portal Initial Design

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#185]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Admin Portal Initial Design for 11.0 beta. Use [@MUI's Figma kit.](https://www.figma.com/community/file/912837788133317724/Material-UI-for-Figma-(and-MUI-X))

### Tasks

```[tasklist]
# Tasks
- [x] Figma for Admin Portal initial design for 11.0 Beta
- [x] Review of the Figma with the team
- [x] Approval of the Figma for Admin Portal initial design
```
