### ISSUE TITLE
✨ Admin Portal Initial Implementation

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#186]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Admin Portal Initial Implementation using react-admin.

### Tasks

```[tasklist]
# Tasks
- [ ] TODO (maybe one task per model?)
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/backend-services/pull/15
```
