### ISSUE TITLE
✨ reimplementation of board backend using immudb

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#187]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Reimplementation of Board backend using immudb in SQL mode.

### Tasks

```[tasklist]
# Tasks
- [x] add `immudb.rs` backend
- [x] Use new `immudb` backend in main.rs binary
- [x] remove `trillian` backend and  `backend/bulletin-board` from the mono-repo
- [x] add get_boards to the backend
- [x] use get_boards in the backend
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/24
```
