### ISSUE TITLE
✨ Expose a immudb REST API through Hasura to show it as resources in admin-portal

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#188]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Expose a immudb REST API through Hasura for usage in react-admin so that it can be accessed using Graphql - i.e. same as everything else

### Implementation

REST API accessible through hasura:

![Image](https://github.com/sequentech/meta/assets/81968/e953645c-4c27-44e1-b28b-aa9c6ef34da4)

<img width="1435" alt="image" src="https://github.com/sequentech/meta/assets/81968/ea18df6a-c273-462d-b2eb-16601ac6c9d3">

### Tasks

```[tasklist]
# Tasks
- [x] Expose a immudb REST API through Hasura
- [x] Integrate as a resource in admin portal
- [x] admin-portal: Add support for pagination and limit
- [x] hasura: add bounds to limit & offset
- [x] hasura: add a simple unit test
- [x] admin-portal, harvest, hasura: add support for sorting columns
- [x] admin-portal: remove delete action from ui
- [x] admin-portal: add support for showing the other available columns
- [x] windmill: create immudb db on election event creation
- [ ] immudb-log-audit: ensure logs go to the correct immudb database
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/34
- [ ] https://github.com/sequentech/backend-services/pull/41
- [ ] https://github.com/sequentech/backend-services/pull/51
- [ ] https://github.com/sequentech/backend-services/pull/52
- [ ] https://github.com/sequentech/backend-services/pull/77
- [ ] https://github.com/sequentech/backend-services/pull/82
- [ ] https://github.com/sequentech/backend-services/pull/83
```

**Comment by edulix** [comment]
Moved remaining task to https://github.com/sequentech/meta/issues/380
