### ISSUE TITLE
✨ Admin Portal - Election Event - Logs

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#189]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Generate admin-portal UI for the logs screens. Base it in the [Figma](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=1078-17859&mode=design&t=FOFl5MWK20fxZmKK-0)

### Tasks

```[tasklist]
# Tasks
- [x] Create immudb view (reusable if we have multiple different logs)
- [x] Add support for searching by specific columns, like datetime and username
- [ ] Add support for exporting in PDF and CSV
- [ ] Admin Portal - Election Event - Logs view
```

```[tasklist]
# Main PRs
- [ ] PR 1
```
