### ISSUE TITLE
✨ S3 Backend for immudb in the docker compose

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#191]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

S3 Backend for immudb in the docker compose
https://docs.immudb.io/1.1.0/operations/specs.html#s3-storage-backend

### Tasks

```[tasklist]
# Tasks
- [ ] Use S3 Backend for immudb in the docker compose
- [ ] Document in the README usage of S3 backend
```

```[tasklist]
# Main PRs
- [ ] PR 1
```

**Comment by edulix** [comment]
Closing this one, it's now handled by the devops guys in other tickets
