### ISSUE TITLE
integrate service that logs pgaudit lines into immudb and expose it through hasura

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#192]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

integrate service that logs pgaudit lines into immudb and expose it through hasura

### Tasks

```[tasklist]
# Tasks
- [x] Use immudb-log-audit and adapt it for integration with pgaudit and postgres
- [x] Add immudb-log-audit to docker-compose
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/30
```
