### ISSUE TITLE
✨ Move Rust immudb-related code to a separate library: immu-rs

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#193]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Move Rust immudb code to a separate library so that it can be reused by the different systems that use it.

### Tasks

```[tasklist]
# Tasks
- [x] Move Rust immudb-related code to a separate library: immu-rs
- [x] Use this library in the different rust modules that need it
```

```[tasklist]
# Main PRs
- [ ] PR 1
```
