### ISSUE TITLE
✨ immurs: add caching support

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#194]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

immurs: add caching support.

### Tasks

```[tasklist]
# Tasks
- [ ] immurs: add caching support
- [ ] Use it in the modules that make sense
```

```[tasklist]
# Main PRs
- [ ] PR 1
```
