### ISSUE TITLE
✨ immu-rs: add verification support

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#195]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

immu-rs: add verification support

### Tasks

```[tasklist]
# Tasks
- [ ] immu-rs: add verification support
- [ ] use it in the modules it makes sense
```

```[tasklist]
# Main PRs
- [ ] PR 1
```
