### ISSUE TITLE
✨ Implement Create Election Event

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#200]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Implement Rust Backend so that when creating an election event, the appropriate backend handling happens:
- Create a Bulletin Board

### Tasks

```[tasklist]
# Tasks
- [x] Add method to immu-board to creat a new board/database.
- [x] Add task to create board to templates.
- [x] Add action to create board to election event resource on admin-portal.
- [x] Save board id on election event.
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/29
```

**Comment by edulix** [comment]
@Findeton suggestion: please move the rusty-celery tasks to a new ticket and put it in the 11.0 milestone

**Comment by Findeton** [comment]
@edulix  done, I'll refine this task https://github.com/sequentech/meta/issues/225
