### ISSUE TITLE
✨ BallotStyle generation backend

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#201]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Create an API endpoint that generates/updates the ballot styles from the data in the database in JSON

### Tasks

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Main PRs
- [x] https://github.com/sequentech/backend-services/pull/37
- [ ] https://github.com/sequentech/backend-services/pull/40
```
