### ISSUE TITLE
✨ Key generation

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#202]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Implement key generation API, that request the generation of keys to the trustees in the Bulletin Board

### Possible Implementation

Steps required for a minimal implementation.

1) An board index must exist
2) Create a new board and add it to the board index
3) Generate an artifact::Configuration
4) Generate a configuration message with braid::protocol2::message::bootstrap_msg
5) Post the message to the board
6) Once complete, retrieve the public key message from the board, this will have statement_kind = "PublicKey", and will have as artifact a serialized artifact::DkgPublicKey

This assumes the trustees have been configured and are running. The configuration artifact also requires the generation of an additional keypair that defines where the ballots will be coming from.

### Tasks

```[tasklist]
# Tasks
- [x] Add docker-compose configuration to run trustees.
- [x] Add postgres/hasura trustees table.
- [x] Add Hashicorp Vault to store protocol manager keys.
- [x] Add Dialog to create keys to `admin-portal`.
- [x] Add harvest task to create keys. Steps:
- [x] Step 1. Check board exists
- [x] Step 2. Check in election event state that keys haven't been created yet.
- [x] Step 3. Create board protocol-manager key.
- [x] Step 4. Create board configuration with protocol-manager and trustees public keys
- [x] Step 5. Save protocol manager key on vault.
- [x] Step 6. Update election event state: keys have been created.
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/32
```
