### ISSUE TITLE
✨ Anonymization process action & basic ui

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#203]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Implement the API backend action that dumps the ballots into the Bulletin Board and signs the request for mixing and decryption of the ballots. Note that this should be able to happen per election, and optionally multiple elections should be requested at once in the API call, and multiple tallies could happen at different times for the same election.

[Figma Design](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=893-903&mode=design&t=ADi32b0Naiq9lmsS-0)

### Tasks

```[tasklist]
# Tasks
- [x] Add rabbitmq to docker compose.
- [x] Add windmill crate to run async tasks.
- [x] Move tasks from harvest to windmill.
- [x] Refactor harvest.
- [x] Refactor existing tasks (create ballot style, set public key, render report).
- [x] Add task to add ballots to immudb.
- [ ] Only insert last ballot from each user?
- [ ] Check if election is stopped?
```

```[tasklist]
# Main PRs
- [x] https://github.com/sequentech/backend-services/pull/70
- [x] https://github.com/sequentech/backend-services/pull/72
- [x] https://github.com/sequentech/backend-services/pull/81
- [ ] https://github.com/sequentech/backend-services/pull/84
```
