### ISSUE TITLE
✨ Implement simple tally backend

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#204]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Implement an API backend endpoint that request and performs the tally of an election.

### Tasks

```[tasklist]
# Tasks
- [x] Write design `doc/design/velvet/README.md`
- [x] Create the Velvet package
- [x] Validate configuration file velvet-config.js
- [x] Create Entities (struct and enum) according to the design documentation
- [x] Use SequentCore Ballot Codec Fixtures
- [x] Create Fixtures for input-dir
- [x] Read input-dir with error handling
- [x] Implement the DecodeBallots pipe
- [x] Implement the DoTally pipe
- [x] Implement ComputeResult pipe
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/68
```
