### ISSUE TITLE
✨ Increase the timeout due to user activity

### ISSUE THREAD

**Issue by markgrafd** [sequentech/meta#205]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Currently, the session timeout can only be set system-wide. For some customers the timeout is too long, for others too short. None of them want to disable the timeout in general, because they consider the security feature useful. However, most of our customers would like the timeout to be extended automatically in case of user activity, e.g. when something is clicked, activated or a page is changed. Feasible?

### Tasks

```[tasklist]
# Tasks
- [x] admin-console: Initial implementation changing `setAuth` to check interactions
- [x] Agree with customer on the scope and behavior
- [x] Acceptance by customer
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/common-ui/pull/406
- [ ] https://github.com/sequentech/voting-booth/pull/462
- [ ] https://github.com/sequentech/iam/pull/354
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/common-ui/pull/399
- [ ] https://github.com/sequentech/voting-booth/pull/451
- [ ] https://github.com/sequentech/iam/pull/349
```

**Comment by sergiydmukhinepi** [comment]
@edulix I think it would be great if you could implement it for both the admin dashboard and the polling booth.

**Comment by sergiydmukhinepi** [comment]
@Findeton Something is wrong. The timer won't reset.
