### ISSUE TITLE
✨ Election turnout overview / graph for election managers

### ISSUE THREAD

**Issue by markgrafd** [sequentech/meta#206]
### Preflight checklist

- [x] #710

### Suggestion

We consistently receive requests from our clients to provide an overview of voter turnout (day/time on quantity) so that election officials' initiatives can be better assessed (Did the reminder make a difference? How can participation be further increased?) Here is an example that many of our clients are familiar with.

![image](https://learn.microsoft.com/de-de/power-bi/visuals/media/power-bi-line-charts/power-bi-line.png)

The first time you visit an election dashboard, the first five child elections are displayed on the graph. However, it must be possible to select the elections to be compared by dropdown. It should be possible to switch between the cumulative and normal (as on the picture) view. 

### Tasks

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# 10.2.x PRs
- [ ] https://github.com/sequentech/iam/pull/334
- [ ] https://github.com/sequentech/admin-console/pull/418
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/iam/pull/336
- [ ] https://github.com/sequentech/admin-console/pull/419
```

**Comment by markgrafd** [comment]
Here is another representation for "turnout today"
![image](https://github.com/sequentech/meta/assets/44897836/17445fd0-8b07-4d6c-b1c2-62672f6fe037)

**Comment by markgrafd** [comment]
Here still another representation as barometer (so far have voted / of total)
![image](https://github.com/sequentech/meta/assets/44897836/d43ae547-43c2-495b-901e-c4ab736a2223)

**Comment by edulix** [comment]
Sergiy suggest to be able to zoom in/out in the graph if the library support it.

**Comment by Findeton** [comment]
![Image](https://github.com/sequentech/meta/assets/3913223/f8c4e8f3-66d7-4497-9964-24289c45c599)

**Comment by markgrafd** [comment]
@Findeton We have lots of child elections in there. Can you please add a "uncheck all" button?

**Comment by sergiydmukhinepi** [comment]
@Findeton Nice and useful feature, but there are some issues we would like to see fixed

**Comment by sergiydmukhinepi** [comment]
Can't recognise numbers on the left axis
![image](https://github.com/sequentech/meta/assets/154313589/07f54775-ea49-48bd-b25a-3b8c7eca2ee4)

**Comment by markgrafd** [comment]
@Findeton: As you can see in the graphic above, it often happens that the right-hand area is displayed but not filled with data. We also absolutely need an "Deselect all" mechanism or "Parent only" in the standard display.
