### ISSUE TITLE
✨ Download election turnout

### ISSUE THREAD

**Issue by markgrafd** [sequentech/meta#209]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

During an ongoing election, our customers regularly ask about voter participation. We need a functionality that allows downloading these numbers in an overview (CSV): voting ID, name, existing voters, total eligible voters from the census, participation (quota).
![image](https://github.com/sequentech/meta/assets/44897836/d825c2cf-f35e-43ed-b5ea-df6f6a2c6558)

The download data should be able to handle the concept of parent and child elections.

### Tasks

```[tasklist]
# Tasks
- [x] Add turnout endpoint.
- [x] (common-ui) Add api call to download turnout to auth api.
- [x] Add dashboard action to download turnout, with translations.
- [x] Implement download turnout action that calls iam and ballot-box to create csv.
```

```[tasklist]
# 10.2.x PRs
- [ ] https://github.com/sequentech/common-ui/pull/387
- [ ] https://github.com/sequentech/iam/pull/344
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/common-ui/pull/389
- [ ] https://github.com/sequentech/iam/pull/345

```

### Screenshots

![Image](https://github.com/sequentech/meta/assets/3913223/c37b1907-6e85-44f9-b5f1-ae5f49d5aa15)

![Image](https://github.com/sequentech/meta/assets/3913223/b7fe65b9-d607-4833-ab29-cd354177bc3a)

**Comment by sergiydmukhinepi** [comment]
@Findeton The entire turnout is taken over for the children's elections if no one has voted.
![image](https://github.com/sequentech/meta/assets/154313589/257a66f5-1d39-41c0-ba96-b094ed995ae9)

![image](https://github.com/sequentech/meta/assets/154313589/fda21f62-f68b-4252-9fa8-97df932b66da)

**Comment by Findeton** [comment]
@sergiydmukhinepi I'm looking into this.

**Comment by Findeton** [comment]
@sergiydmukhinepi it should be fixed now (in 10.4.x)
