### ISSUE TITLE
🐞 pop up election-id to long

### ISSUE THREAD

**Issue by ElectricPaperInformationssystemeGmbH** [sequentech/meta#210]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Current Behavior

The "pop-up" ballot ID covers the language selection and cannot be moved.
![image](https://github.com/sequentech/meta/assets/87812708/2cd800fc-7f8c-40fc-af63-fc34aa703867)

### Expected Behavior

Long lines should be displayed in two lines

### Environment

```markdown
- OS:
- Web browser:
```

### Tasks

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/common-ui/pull/334
- [ ] https://github.com/sequentech/common-ui/pull/335
- [ ] https://github.com/sequentech/voting-booth/pull/378
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/common-ui/pull/336
- [ ] https://github.com/sequentech/voting-booth/pull/379
```

### Implementation screenshots

Minimum screen width for non-mobile. You can see there's no overlap with the language menu:
![Image](https://github.com/sequentech/meta/assets/3913223/b8cd9a0e-9e94-4984-b5cb-ea21b0955edc)

Mobile version:
![Image](https://github.com/sequentech/meta/assets/3913223/888a4a90-f280-4fd1-926f-657bf0c72ac9)

_No response_

**Comment by ElectricPaperInformationssystemeGmbH** [comment]
I don't find the maxwidth optimal, there is always one character left. Can't you take away the maxwidth and arrange the field left-justified on the monitor?
