### ISSUE TITLE
🐞 Responsive wraps for high cumulative votes

### ISSUE THREAD

**Issue by markgrafd** [sequentech/meta#211]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Current Behavior

Many customers have plurality voting with high cumulative numbers for votes. About 50% of these voters vote on mobile devices. Our customers want responsive wraps for the checkboxes on mobile devices, as the display is perceived as "buggy" this way.

![image](https://github.com/sequentech/meta/assets/44897836/7f8f2245-a4d0-4e32-a4ce-88dd2e315d6d)

![image](https://github.com/sequentech/meta/assets/44897836/0537efe7-4545-4904-81f2-b7d53292f795)

### Expected Behavior

The border of the list box should contain all the boxes. The checkboxes should be wrapped so that they display better on mobile devices.

### Environment

```markdown
- OS:
- Web browser:
```

### Implementation

Below you can find a couple images that show how the voting booth looks once fixed. 

**Please note** that although for very small screens we have limited the default CSS to be a two checkbox per row, you can customize that using [`theme_css`](https://sequentech.github.io/documentation/docs/general/reference/election-creation-json/#election-presentation-theme_css) and override and increase the max-width for the checkboxes section to the desired width. The default is `[avb-simultaneous-question-answer-v2] .vertilize-col.answer-glyphicon { max-width: 26%; }`. You can also use  [css `@media` queries](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_media_queries/Using_media_queries) to limit the width in bigger screens.

![Image](https://github.com/sequentech/meta/assets/81968/cb354631-c8f1-4f80-bad8-ce6552905bbe)
![Image](https://github.com/sequentech/meta/assets/81968/01d68868-c939-40e6-86e6-8feb36787169)

### Tasks

```[tasklist]
# Tasks
- [x] Fix the issue
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/voting-booth/pull/368
- [ ] https://github.com/sequentech/voting-booth/pull/372
- [ ] https://github.com/sequentech/voting-booth/pull/418
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/voting-booth/pull/367
- [ ] https://github.com/sequentech/voting-booth/pull/371
- [ ] https://github.com/sequentech/voting-booth/pull/412
```

**Comment by edulix** [comment]
@markgrafd @ElectricPaperInformationssystemeGmbH I added an implementation note in the description, please view/read.

**Comment by markgrafd** [comment]
@edulix Great! Thank you.

**Comment by edulix** [comment]
Reopening, it doesn't work without lists. I attach an example: 
https://gist.github.com/ElectricPaperInformationssystemeGmbH/111999522cc1921e73c4572a32d2c385

**Comment by edulix** [comment]
Please @ElectricPaperInformationssystemeGmbH  test it in branch `feat/meta-211/10.0.x` of the voting-booth and tell me if it works as expected

**Comment by ElectricPaperInformationssystemeGmbH** [comment]
@edulix Unfortunately, the original problem occurs again 
![image](https://github.com/sequentech/meta/assets/87812708/180d8ec4-748d-4a7c-9b63-5f0935844f73)

**Comment by ElectricPaperInformationssystemeGmbH** [comment]
@edulix link is same as you've added before

**Comment by edulix** [comment]
@ElectricPaperInformationssystemeGmbH [the example I mentioned in the comment](https://gist.github.com/ElectricPaperInformationssystemeGmbH/111999522cc1921e73c4572a32d2c385) has only 2 checkboxes per candidate. I've modified it to contain 10. It looks like this in mobile:
<img width="595" alt="image" src="https://github.com/sequentech/meta/assets/81968/aed62cae-8069-476b-a83b-9ae6398a3cde">

I think it's working properly.

**Comment by ElectricPaperInformationssystemeGmbH** [comment]
looks good, thank you
