### ISSUE TITLE
🐞 already voted elections are active in election chooser

### ISSUE THREAD

**Issue by ElectricPaperInformationssystemeGmbH** [sequentech/meta#212]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Current Behavior

The election can still be selected or clicked even though I have already voted.
![image](https://github.com/sequentech/meta/assets/87812708/f4a35103-2eaa-4b28-a47d-2ab41016c5f9)

### Expected Behavior

I would expect all mouse-over effects + button to be deactivated when voting has taken place.

### Environment

```markdown
- OS:
- Web browser:
```

## Implementation

This is how it looks after the fix has been applied, in an election where the voter has already voted and revoting is disabled:

<img width="1216" alt="image" src="https://github.com/sequentech/meta/assets/81968/9f485189-2eb9-4ba1-9045-0f1a7991a5a4">

If changing the vote is allowed, then it would look similar to this:
<img width="1216" alt="image" src="https://github.com/sequentech/meta/assets/81968/7bc56809-358f-4aec-821b-be3c1606bef0">

### Tasks

```[tasklist]
# Tasks
- [x] Fix issue
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/voting-booth/pull/374
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/voting-booth/pull/373
```
