### ISSUE TITLE
🐞 public page is active

### ISSUE THREAD

**Issue by ElectricPaperInformationssystemeGmbH** [sequentech/meta#213]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Current Behavior

Public website is displayed although deactivated in JSON.

### Expected Behavior

if deactivated in json, there have to be no way to display the public election page

### Environment

```markdown
- OS:
- Web browser:
```

### Tasks

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/admin-console/pull/388
- [ ] https://github.com/sequentech/voting-booth/pull/369
- [ ] https://github.com/sequentech/election-portal/pull/208
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/admin-console/pull/389
- [ ] https://github.com/sequentech/voting-booth/pull/376
- [ ] https://github.com/sequentech/election-portal/pull/209
```

**Comment by edulix** [comment]
@Findeton do you have a test election config and link for an election with publicPage=false to test?

**Comment by Findeton** [comment]
@edulix https://felix-dev.sequentech.io/booth/34570017/demo-vote

**Comment by Findeton** [comment]
@edulix this is the json https://gist.github.com/Findeton/8f9b9b662c6917d32adfd89f4964c262

**Comment by edulix** [comment]
@Findeton can you please create an example with smart link authentication? I wonder what happens in that case, since the login page is not valid per-se as a redirection. I'm talking about what happens when you enter https://felix-dev.sequentech.io/election/34570017/public/home

**Comment by Findeton** [comment]
If you go to `/public/home` for an election with smart link and a disabled home page, it will redirect to the login page. You can try it here:

https://felix-dev.sequentech.io/election/34570025/public/home

It's just that the login page will look disabled. (I can't upload a screenshot because github sucks).

**Comment by edulix** [comment]
Right now that link goes to "http://sequent/admin" @Findeton
