### ISSUE TITLE
✨ Create template report system

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#214]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Create template report system

### Possible Implementation
Use [headless chrome](https://github.com/rust-headless-chrome/rust-headless-chrome) like in [html2pdf](https://github.com/ilaborie/html2pdf). Use [handlebars](https://crates.io/crates/handlebars).

### Tasks

```[tasklist]
# Tasks
- [x] Add `templates` rust/rocket service for text/pdf templating.
- [x] Add service to docker compose.
- [x] Test css config (ie page layout)
- [x] Upload the media to AWS S3 compatible API
- [x] Deploy minio in docker-compose and use it as the self-contained S3 compatible layer
- [x] Connect the API endpoint to a hasura action
- [x] Create Election Media database model, storing the media url
- [x] Show the Election Media resource in the Admin UI
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/backend-services/pull/23
```
