### ISSUE TITLE
✨ Basic election reports support

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#215]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Add support for election reports.

### Tasks

```[tasklist]
# Tasks
- [ ] Rust code to  perform the generation of participation reports with chromium-headless, mustache for templating and data provided using graphql, generating the reports in HTML and PDF formats.
- [ ] Generate an API endpoint for requesting the generation of a participation report as a scheduled job.
- [ ] Make the API for background tasks a different service at a different endpoint, with a different binary, in docker-compose, and make it available through a hasura action for now.
- [ ] Storage of the report in S3-compatible, using minio in docker-compse so that it's self contained.
```

```[tasklist]
# Master PRs
- [ ] PR 1
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```

**Comment by edulix** [comment]
mm @Findeton wasn't this already done?
