### ISSUE TITLE
✨ ivr-lambdas: add support for parent-children elections

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#216]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

add support for parent-children elections

### Tasks

```[tasklist]
# Tasks
- [x] add support for parent-children elections: authenticate_voter
- [x] add support for parent-children elections: cast_vote
- [x] deploy the new version in aws lambda
- [x] add support for parent-children elections: aws connect
```
