### ISSUE TITLE
✨ Add support for uploading election media

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#217]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Add support for uploading election related media

### Tasks

```[tasklist]
# Tasks
- [ ] Add API endpoint to upload election event related media
- [ ] Upload the media to AWS S3 compatible API
- [ ] Connect the API endpoint to a hasura action
- [ ] Create Election Media database model, storing the media url
- [ ] Show the Election Media resource in the Admin UI
- [ ] Add support for storing the media in the election configuration, candidate configuration etc
```

```[tasklist]
# Main PRs
- [ ] PR 1
```

**Comment by edulix** [comment]
already implemented
