### ISSUE TITLE
✨ Add election start/pause/resume/stop actions

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#218]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Add election start/pause/resume/stop actions

### Tasks

```[tasklist]
# Tasks
- [ ] Add election start/pause/resume/stop actions in API endpoint
- [ ] Expose API endpoint through hasura
- [ ] Add Admin UI support for those actions
```

```[tasklist]
# Main PRs
- [ ] PR 1
```
