### ISSUE TITLE
🐞 alternative auth method json param

### ISSUE THREAD

**Issue by ElectricPaperInformationssystemeGmbH** [sequentech/meta#219]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Current Behavior

icon is a required parameter in census.alternative_auth_method
Description of the parameter is missing.

### Expected Behavior

This must be visible in the documentation
https://sequentech.github.io/documentation/docs/general/reference/election-creation-json/#census-alternative_auth_methods

### Environment

```markdown
- OS:
- Web browser:
```

### Tasks

```[tasklist]
# Tasks
- [x] Perform the doc fix
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/documentation/pull/130
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```
