### ISSUE TITLE
🐞 child election with bigger title in election chooser

### ISSUE THREAD

**Issue by ElectricPaperInformationssystemeGmbH** [sequentech/meta#220]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Current Behavior

if the name of an election is a bit long. The Button start election will be shown in two rows
![image](https://github.com/sequentech/meta/assets/87812708/d053297e-20a4-4ba4-b5bf-be89e3864f9b)

### Expected Behavior

The button should be shown in one line

### Environment

```markdown
- OS:
- Web browser:
```

## Implementation details

<img width="1196" alt="image" src="https://github.com/sequentech/meta/assets/81968/f7ee016a-69ec-49b1-9411-b25d60b422b6">

### Tasks

```[tasklist]
# Tasks
- [x] Fix issue
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/voting-booth/pull/370
- [ ] https://github.com/sequentech/voting-booth/pull/382
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/voting-booth/pull/377
- [ ] https://github.com/sequentech/voting-booth/pull/383
```

**Comment by edulix** [comment]
@Findeton please add a couple of screenshots in the description of the ticket in a "Implementation" section of how it will look in both mobile and desktop once fixed. A link to an example should also be helpful.
