### ISSUE TITLE
🐞 smartlink as alternative auth method

### ISSUE THREAD

**Issue by ElectricPaperInformationssystemeGmbH** [sequentech/meta#221]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Current Behavior

If smartlink is not the main authentication method, the login page is displayed first, then nothing happens. Only when you switch to the smartlink tab will you be authenticated.

### Expected Behavior

Smartlink auth method must appear seamless to a voter. Without any user interaction

### Steps To Reproduce

https://gist.github.com/ElectricPaperInformationssystemeGmbH/2e5d6abc8bc7f70b2ac9ebb4ef054066

### Environment

```markdown
- OS:
- Web browser:
```

### Tasks

```[tasklist]
# Tasks
- [x] Fix issue
- [ ] Confirmation of fix by reporter
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/common-ui/pull/392
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/common-ui/pull/390
```

**Comment by edulix** [comment]
@sergiydmukhinepi I've fixed the issue, please review:
- smartlink tab is disabled as an alternative method, naturally, as it cannot possibly work, just as before
- You can use smart link authentication by changing the smart link integration endpoint from being on `/public/login?auth-token=foo` to `/public/login-alt/smart-link?auth-token=foo`. Something like https://10xx.sequentech.io/election/75/public/login-alt/smartlink?auth-token=khmac:%2F%2F%2Fsha-256;8e0b1b553c29046cf5988a0e24d6ce276f6d14d27918da5d219b634970c3f706%2Fexample@sequentech.io:AuthEvent:150017:vote:1620805691

**Comment by sergiydmukhinepi** [comment]
Thank you, it works.

**Comment by edulix** [comment]
Awesome!
