### ISSUE TITLE
🐞 alternative auth methods: switch back to smartlink tab fails

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#222]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Current Behavior

alternative auth methods: switch back to smartlink tab fails.

### Expected Behavior

should switch back from pin-tan (email-password plus custom extra fields) to smartlink

### Environment

```markdown
- OS:
- Web browser:
```

### Tasks

```[tasklist]
# Tasks
- [x] Fix the issue
- [x] Adding missing documentation on how to send alternative auth urls in messages to voters
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/documentation/pull/131
- [ ] https://github.com/sequentech/common-ui/pull/337
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/common-ui/pull/333
```
