### ISSUE TITLE
🐞 Answer column size not applied when not using categories

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#223]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Current Behavior

[Answer column size](https://sequentech.github.io/documentation/docs/general/reference/election-creation-json#question-extra-answer_columns_size) is not applied when not using categories

### Expected Behavior

It should be applied.

### Environment

```markdown
- OS:
- Web browser:
```

### Tasks

```[tasklist]
# Tasks
- [x] Fix issue
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/voting-booth/pull/375
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/voting-booth/pull/366
```

**Comment by edulix** [comment]
@Findeton please review and then merge and create the PR for master too. I think the gap calculation is incorrect,
[this](https://github.com/sequentech/voting-booth/blob/master/avBooth/booth-directive/booth-directive.less#L372) works better (no gap at the third element) with `[av-booth] .flex-col-4 { flex-basis: calc(33.33% - 16px*2/3); }`, for example. Same I guess with other sizes?
