### ISSUE TITLE
✨ Voting Booth: Security confirmation checkbox support

### ISSUE THREAD

**Issue by markgrafd** [sequentech/meta#224]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Our customers request a verification under oath or a security confirmation before the ballot can be filled out. The check mark should activate the "Start voting" button.

![image](https://github.com/sequentech/meta/assets/44897836/a1aebab9-86c0-40b1-ab30-5fd6ec46fe39)

Text: I hereby certify that I have read and understood the instructions for voting, and I affirm to the election administration in lieu of oath that I personally fill out the ballot or that I mark the ballot as an auxiliary person in accordance with the will of the voter.

### Suggested Implementation

The addition of the following election level fields:
- `mandatory_acceptance_tos_html` containing the basic-html text to be displayed.
- `mandatory_acceptance_tos_html_i18n` to support translations of the previous field.

If `mandatory_acceptance_tos_html` is set, then a checkbox will appear containing the configured text, and the `Start voting`button will be disabled unless that checkbox is checked. 

**Important:** Please note that in this suggested implementation this checkbox is implemented in the javascript client of the voting booth. This means that the fact that the voter clicked in this checkbox  is not reflected in any manner to the data received in the backend from the voter.

### Implementation details

This is how it looks when set:

<img width="1254" alt="image" src="https://github.com/sequentech/meta/assets/81968/4f8eda46-9d16-4cba-b939-099d910b299a">

And when checkbox checked:

<img width="1254" alt="image" src="https://github.com/sequentech/meta/assets/81968/6d547fb1-cfa3-4d6f-92af-9c1781497a93">

In mobile:

<img width="716" alt="image" src="https://github.com/sequentech/meta/assets/81968/1aae0e41-7c2a-42b6-a34e-e106088eec14">

Additionally, the text supports basic html and translations using the `mandatory_acceptance_tos_html_i18n` parameter. 

### Tasks

```[tasklist]
# Tasks
- [x] suggested-implementation: identify requirements and produce a suggested implementation
- [x] client-approval: Receive client approval for the suggested implementation
- [x] implementation: Develop the suggested implementation
- [x] documentation repo: Write the documentation related to the suggested implementation
- [x] final-client-approval-request: document the actual implementation and request final implementation approval
- [x] final-client-approval: obtain final implementation approval
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/documentation/pull/140
- [ ] https://github.com/sequentech/ballot-box/pull/184
- [ ] https://github.com/sequentech/voting-booth/pull/417
- [ ] https://github.com/sequentech/common-ui/pull/372
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/ballot-box/pull/181
- [ ] https://github.com/sequentech/voting-booth/pull/411
- [ ] https://github.com/sequentech/common-ui/pull/370
```

**Comment by ElectricPaperInformationssystemeGmbH** [comment]
Logical check would be ok

**Comment by edulix** [comment]
@ElectricPaperInformationssystemeGmbH please review implementation details and confirm approval or request changes or any other information

**Comment by ElectricPaperInformationssystemeGmbH** [comment]
@edulix strange border is around the check box 
![image](https://github.com/sequentech/meta/assets/87812708/08efcf5b-f176-46f0-9eb8-8d9b3727593e)

**Comment by ElectricPaperInformationssystemeGmbH** [comment]
@edulix button mouse hover and click effect (shadow) is there if the check box deactivated
![image](https://github.com/sequentech/meta/assets/87812708/b8a4e441-41fe-45cd-a4ac-e7bf7eee657a)

**Comment by ElectricPaperInformationssystemeGmbH** [comment]
@edulix one line text not in the middle
![image](https://github.com/sequentech/meta/assets/87812708/5b877b66-636c-45d6-9de1-fb05239b3432)

**Comment by edulix** [comment]
I've fixed the issues.

This is how the text looks when it's small (one line) and the checkbox is unchecked:
<img width="480" alt="image" src="https://github.com/sequentech/meta/assets/81968/3512380c-7a93-481f-b120-85824ed3af4c">

This how it looks when the text is multiline and checkbox is checked:
<img width="502" alt="image" src="https://github.com/sequentech/meta/assets/81968/e9057332-c1b5-4d1e-84ce-4b6e3d2befa2">

This is the highlight and mouse-hover process. Doesn't have a mouse-over shadow when the button is disabled, and when clicked and disabled it highlights the mandatory security checkbox elements (input + text) in red:

https://github.com/sequentech/meta/assets/81968/0253b091-7e97-4885-82f6-d47b3e70b2c0

**Comment by ElectricPaperInformationssystemeGmbH** [comment]
looks good, thank you
