### ISSUE TITLE
✨ Use rusty-celery for background jobs

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#225]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Use rusty-celery for background jobs, for example for the Create a Bulletin Board task

### Tasks

```[tasklist]
# Tasks
- [x] Add rabbitmq to docker-compose
- [x] Add a new rusty-celery background worker to docker-compose
- [x] Migrate to rusty-celery the action to create the electoral board
- [x] Use a rusty-celery for other actions that should be run in a background job
- [x] Add service-account to hasura/keycloak and openid client_credentials auth to windmill.
- [x] Add task execution model doc.
- [x] Test pre-fetch count.
- [x] Add beat binary, with config for queue (ack_late) and prefetch count.
```

```[tasklist]
# Main PRs
- [x] https://github.com/sequentech/backend-services/pull/75
- [x] https://github.com/sequentech/backend-services/pull/76
- [x] https://github.com/sequentech/backend-services/pull/78
- [ ] https://github.com/sequentech/backend-services/pull/79
```
