### ISSUE TITLE
Security updates

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#230]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Security updates

### Tasks

```[tasklist]
# Tasks
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/common-ui/pull/323
- [ ] https://github.com/sequentech/common-ui/pull/339
- [ ] https://github.com/sequentech/voting-booth/pull/380
- [ ] https://github.com/sequentech/election-portal/pull/210
- [ ] https://github.com/sequentech/admin-console/pull/390
- [ ] https://github.com/sequentech/iam/pull/303
- [ ] https://github.com/sequentech/tally-pipes/pull/106
- [ ] https://github.com/sequentech/tally-pipes/pull/105
- [ ] https://github.com/sequentech/election-orchestra/pull/76
- [ ] https://github.com/sequentech/election-orchestra/pull/77
- [ ] https://github.com/sequentech/frestq/pull/81
- [ ] https://github.com/sequentech/frestq/pull/80
- [ ] https://github.com/sequentech/release-tool/pull/45
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/common-ui/pull/338
- [ ] https://github.com/sequentech/common-ui/pull/340
- [ ] https://github.com/sequentech/voting-booth/pull/381
- [ ] https://github.com/sequentech/election-portal/pull/211
- [ ] https://github.com/sequentech/admin-console/pull/391
- [ ] https://github.com/sequentech/iam/pull/304
- [ ] https://github.com/sequentech/tally-pipes/pull/107
- [ ] https://github.com/sequentech/election-orchestra/pull/78
- [ ] https://github.com/sequentech/frestq/pull/82
- [ ] https://github.com/sequentech/release-tool/pull/44
```
