### ISSUE TITLE
Release 9.1.0

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#231]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

New minor release.

### Tasks

```[tasklist]
# Tasks
- [x] Tag the release
- [x] Create releases with automatic release notes in github
- [x] Test the release
- [x] Deploy release in stable <major>xx deployment
- [x] Deploy release in demo
- [x] Deploy release in web-demo
```
