### ISSUE TITLE
✨ Ensure feasibility and correct usage of ECC Elgamal

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#232]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Ensure feasibility and correct usage of ECC Elgamal

### Tasks

```[tasklist]
# Tasks
- [x] Support restricted character sets for write-ins in ballot codec
- [x] Merge branch
- [ ] Review the work done
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/43
```

**Comment by ruescasd** [comment]
I suggest we use a standard base conversion method to obtain integer bytes. 

https://docs.rs/num-bigint/latest/num_bigint/struct.BigUint.html#method.to_radix_le

Since we use a base conversion, the resulting bytes cannot be implementation dependent.

**Comment by edulix** [comment]
Isn't this already done? If so, please mark it as merged and close the ticket.
