### ISSUE TITLE
🐞 Accordion doesn't work as is-js is not loaded

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#233]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Current Behavior

Accordion doesn't work as is-js is not loaded

### Expected Behavior

Don't use is-js, replace it with our code.

### Environment

```markdown
- OS:
- Web browser:
```

### Tasks

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/voting-booth/pull/384
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/voting-booth/pull/385
```
