### ISSUE TITLE
✨ Voter eligibility check

### ISSUE THREAD

**Issue by markgrafd** [sequentech/meta#234]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

![image](https://github.com/sequentech/meta/assets/44897836/121c48f3-9023-4042-ab8f-04f528ab17ed)

We need an online voter eligibility verification feature. Currently we use a parameterized URL for this. This function should be added to the standard.

See: https://demo.gremienwahlen.de/booth/success_static.html?children=%5B%7B%22auth-event-id%22%3A%20596%2C%20%22num-successful-logins-allowed%22%3A%201%2C%20%22num-successful-logins%22%3A%200%2C%20%22can-vote%22%3A%20true%7D%2C%20%7B%22auth-event-id%22%3A%20597%2C%20%22num-successful-logins-allowed%22%3A%20-1%2C%20%22num-successful-logins%22%3A%200%2C%20%22can-vote%22%3A%20false%7D%2C%20%7B%22auth-event-id%22%3A%20598%2C%20%22num-successful-logins-allowed%22%3A%20-1%2C%20%22num-successful-logins%22%3A%200%2C%20%22can-vote%22%3A%20false%7D%2C%20%7B%22auth-event-id%22%3A%20599%2C%20%22num-successful-logins-allowed%22%3A%20-1%2C%20%22num-successful-logins%22%3A%200%2C%20%22can-vote%22%3A%20false%7D%2C%20%7B%22auth-event-id%22%3A%20600%2C%20%22num-successful-logins-allowed%22%3A%20-1%2C%20%22num-successful-logins%22%3A%200%2C%20%22can-vote%22%3A%20false%7D%2C%20%7B%22auth-event-id%22%3A%20601%2C%20%22num-successful-logins-allowed%22%3A%201%2C%20%22num-successful-logins%22%3A%200%2C%20%22can-vote%22%3A%20true%7D%2C%20%7B%22auth-event-id%22%3A%20602%2C%20%22num-successful-logins-allowed%22%3A%20-1%2C%20%22num-successful-logins%22%3A%200%2C%20%22can-vote%22%3A%20false%7D%2C%20%7B%22auth-event-id%22%3A%20603%2C%20%22num-successful-logins-allowed%22%3A%20-1%2C%20%22num-successful-logins%22%3A%200%2C%20%22can-vote%22%3A%20false%7D%2C%20%7B%22auth-event-id%22%3A%20604%2C%20%22num-successful-logins-allowed%22%3A%20-1%2C%20%22num-successful-logins%22%3A%200%2C%20%22can-vote%22%3A%20false%7D%2C%20%7B%22auth-event-id%22%3A%20605%2C%20%22num-successful-logins-allowed%22%3A%20-1%2C%20%22num-successful-logins%22%3A%200%2C%20%22can-vote%22%3A%20false%7D%2C%20%7B%22auth-event-id%22%3A%20606%2C%20%22num-successful-logins-allowed%22%3A%20-1%2C%20%22num-successful-logins%22%3A%200%2C%20%22can-vote%22%3A%20false%7D%2C%20%7B%22auth-event-id%22%3A%20607%2C%20%22num-successful-logins-allowed%22%3A%20-1%2C%20%22num-successful-logins%22%3A%200%2C%20%22can-vote%22%3A%20false%7D%2C%20%7B%22auth-event-id%22%3A%20608%2C%20%22num-successful-logins-allowed%22%3A%20-1%2C%20%22num-successful-logins%22%3A%200%2C%20%22can-vote%22%3A%20false%7D%5D

### Possible Implementation

Forward to a parameterized URL. Standard Logo. Integrated in Angualar, the page should be customizable by us.

### Implementation

Added a query param to the login. When present, the login will redirect ot the query screen. The screen has configurable title/description(html)/footer, including possible translations.

For example, if the login url is:

`https://example.com/election/<election-id>/public/login`

The url can be modified to redirect to the query screen like this:

`https://example.com/election/<election-id>/public/login?query=true`

###  Implementation Screenshots

![Image](https://github.com/sequentech/meta/assets/3913223/cae9eddd-f4e4-49e5-a802-bac42f5db2bd)

### Tasks

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/voting-booth/pull/461
- [ ] https://github.com/sequentech/ballot-box/pull/209
- [ ] https://github.com/sequentech/common-ui/pull/408
- [ ] https://github.com/sequentech/admin-console/pull/435
- [ ] https://github.com/sequentech/iam/pull/353
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/voting-booth/pull/454
- [ ] https://github.com/sequentech/ballot-box/pull/208
- [ ] https://github.com/sequentech/common-ui/pull/403
- [ ] https://github.com/sequentech/admin-console/pull/434
- [ ] https://github.com/sequentech/common-ui/pull/405
- [ ] https://github.com/sequentech/iam/pull/352
```
