### ISSUE TITLE
✨ Add italian language support

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#235]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Add italian translations

### Tasks

```[tasklist]
# Tasks
- [x] misc-tools: Add tool to easily import translations from POEditor
- [x] documentation: Add documentation on how to export from POEditor
- [x] Add italian translations
- [x] Test italian translations
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/misc-tools/pull/55
- [ ] https://github.com/sequentech/documentation/pull/136
- [ ] https://github.com/sequentech/common-ui/pull/343
- [ ] https://github.com/sequentech/voting-booth/pull/392
- [ ] https://github.com/sequentech/admin-console/pull/396
- [ ] https://github.com/sequentech/election-portal/pull/213
- [ ] https://github.com/sequentech/deployment-tool/pull/345
```
