### ISSUE TITLE
✨ voting-portal: add error handling support

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#237]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Voting Booth should handle different kinds of errors gracefully and show a proper UI informing the voter.

### Tasks

```[tasklist]
# Tasks
- [x] Handle authentication state error
- [x] Voting Portal: add error handling support
- [x] Voting Portal: Election Chooser: Show an `<Empty />` similar looking to what we do in resources in Admin Portal when there's no election to choose
- [x] Handle error from apollo queries
- [x] Add a generic error screen
- [x] Remove ellipsis for Ballot Hash
- [x] Handle error from wasm api calls
- [x] Always reload state from election chooser
- [x] Store back to election chooser link from the current context
- [x] Handle max_votes per election - sync with Enric
- [x] App version in the header from Settings
- [x] after casting ballot -> forget selections
- [x] Add minimum width for Logo in the header
- [x] Remove fixtures
- [x] Reset ballot selection as soon as possible in the flow
- [x] Show election voting status in the election chooser
- [x] If entering in an url of an election and the election is closed, redirect to election chooser
- [x] make header  responsive ui-essentials
- [x] Expired session
- [x] Remove election results button
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/259
- [ ] https://github.com/sequentech/backend-services/pull/267
- [ ] https://github.com/sequentech/backend-services/pull/268
- [ ] https://github.com/sequentech/backend-services/pull/274
```

### Additional context

Generic error page:
404:
![Image](https://github.com/sequentech/meta/assets/1632391/e5474dc2-d055-4957-8479-06134de0026a)
Other:
![Image](https://github.com/sequentech/meta/assets/1632391/09e41de1-c5de-4976-acaf-12eb9ef3a885)

Empty election list:
![Image](https://github.com/sequentech/meta/assets/1632391/86f32bf7-2637-48ac-831b-88f9ccbd5471)

**Comment by edulix** [comment]
@Findeton  It's my understanding that you might already have done this. Please review and if so close this as done.

**Comment by Findeton** [comment]
@edulix this should be an easy task but no, it's not done yet.
