### ISSUE TITLE
✨ Adapt ballot verifier to 2nd-gen

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#238]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Currently the ballot verifier is not integrated with 2nd-gen. We need to fix that.

### Tasks

```[tasklist]
# Tasks
- [ ] Include ballot-verifier in the mono-repo
- [ ] Adapt ballot-verifier to 2nd-gen rust
```

```[tasklist]
# Main PRs
- [ ] PR 1
```
