### ISSUE TITLE
✨ Adapt sequent-core, ballot-verifier, harvest, voting-booth to 2nd-gen

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#239]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Some of the code in sequent-core is still related to 1st-gen, but it needs to be adapted to 2nd-gen.

### Tasks

```[tasklist]
# Tasks
- [x] Adapt `sequent-core` to use elliptic curves.
- [x] Fix `sequent-core` tests, and add some more tests.
- [x] Fix decoding bug on `sequent-core`.
- [x] Refactor `ballot-codec.rs` in `sequent-core` by splitting it into multiple files.
- [x] Update `voting-portal` to use elliptic curves.
- [x] Update `ballot-verifier` to use elliptic curves.
- [x] Update  Auditable Ballot to serialize with Borsh.
- [x] Update Auditable Ballot to include ciphertexts from multiple contests.
- [x] Update `voting-booth` to show errors like in the `ballot-verifier`.
- [x] Update `voting-booth` to consider the write-ins space.
```

```[tasklist]
# Main PRs
- [x] https://github.com/sequentech/backend-services/pull/49
- [ ] https://github.com/sequentech/backend-services/pull/69
```
