### ISSUE TITLE
✨ Strand Link to OpenSSL

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#242]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Link to BoringSSL in strand

### Tasks

```[tasklist]
# Tasks
- [ ] Link to BoringSSL in strand
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/43
```

**Comment by edulix** [comment]
@ruescasd it's my understanding that you mentioned yesterday in the weekly that this one is done. If so, please mark as done - or if you are working on it, move it to in-progress.
