### ISSUE TITLE
✨ Support custom CSS for keycloak realm login UI

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#245]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Support custom CSS for keycloak realm login UI. For now, this will be implemented by (ab)using a i18n translation string `customCSS` to be used for getting this css onto the keycloak login pages when using sequent themes.

### Tasks

```[tasklist]
# Tasks
- [ ] Support custom CSS for keycloak realm login UI 
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/368
```
