### ISSUE TITLE
✨ Implement Keys ceremonies UI & backend

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#246]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Implement Keys and Opening ceremonies UI according to Figma:

**Keys**
- [Admin Portal - Election Event - Keys Generation](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=1932-24940&mode=design&t=z9YOF6WSsNcnaYUG-0)
- [Admin Portal - Election Event - Keys Generation - confirmation dialog](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=1932-27943&mode=design&t=z9YOF6WSsNcnaYUG-0)
- [Admin Portal - Election Event - Keys Generation - Progress](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=1932-28567&mode=design&t=z9YOF6WSsNcnaYUG-0)
- [Admin Portal - Election Event - Key Ceremony - Final state](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=1932-29533&mode=design&t=z9YOF6WSsNcnaYUG-0)

### Implementation Details: Screens

<img width="1440" alt="image" src="https://github.com/sequentech/meta/assets/81968/212715c6-e8c9-4603-9664-2b8854e7e121">

<img width="1440" alt="image" src="https://github.com/sequentech/meta/assets/81968/22a135c5-8831-4daf-bd45-627a6832ac5e">

<img width="896" alt="image" src="https://github.com/sequentech/meta/assets/81968/67df29e6-0312-4b48-b2ee-feea8677c66b">

<img width="1440" alt="image" src="https://github.com/sequentech/meta/assets/81968/ba69f3a5-aaea-4f09-8c2b-1400033ecf62">

<img width="1440" alt="image" src="https://github.com/sequentech/meta/assets/81968/327c19b2-f396-443c-a63a-488ca803ae85">

### Tasks

```[tasklist]
# Tasks: Keys
- [x] Define required endpoints
- [x] Create mock endpoints in Harvest
- [x] Create mock endpoints in Hasura
- [x] Harvest & windmill: implement `/create-key-ceremony`
- [x] Harvest & windmill: connect `/create-key-ceremony` with create-keys to actually create the keys
- [x] Harvest & windmill: update status of latest `keys_ceremony` when assigning election event public_key in windmill
- [x] Harvest & windmill: implement `/check-private-key`
- [x] Harvest & windmill: implement `/get-private-key`
- [x] Implement `windmill::services::protocol_manager::get_trustee_encrypted_private_key`
- [x] Screen: [Admin Portal - Election Event - Keys Generation](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=1932-24940&mode=design&t=z9YOF6WSsNcnaYUG-0)
- [x] Screen: [Admin Portal - Election Event - Keys Generation - confirmation dialog](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=1932-27943&mode=design&t=z9YOF6WSsNcnaYUG-0)
- [x] Screen: [Admin Portal - Election Event - Key Ceremony - Final state](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=1932-29533&mode=design&t=z9YOF6WSsNcnaYUG-0)
- [x] Screen: [Admin Portal - Election Event - Key Ceremony - Final state](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=1932-29533&mode=design&t=z9YOF6WSsNcnaYUG-0): State as Chip
- [x] Screen: [Admin Portal - Election Event - Keys Generation - Progress](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=1932-28567&mode=design&t=z9YOF6WSsNcnaYUG-0)
- [x] UI: Support only one ceremony, not allowing to create more than one
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/139
- [ ] https://github.com/sequentech/backend-services/pull/157
- [ ] https://github.com/sequentech/backend-services/pull/162
```
