### ISSUE TITLE
✨ Election Event - Dashboard

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#248]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Admin-portal: Implement Election Event Configuration UI according to [Figma design screen: Admin Portal - Base](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=893-7293&mode=design&t=zC3uedpaOFjE5fcO-0)

### Tasks

```[tasklist]
# Tasks
- [x] Fix theme, create admin theme, fix admin layout.
- [x] Fix election events filter in voting-portal.
- [x] Implement Election Events Sidebar
- [x] Election event dashboard: stepper
- [x] Implement images for elections
- [x] Sidebar: add creation resources
- [x] Improve treemenu for resources navigation
- [x] Add vertical scroll in the sidebar
- [x] Update action toggle sidebar to by sticky
- [x] Remove Resources
- [x] Archive Election Events
- [x] Implement Permissions
- [x] Dashboard for Elections
- [x] Reactivity after creating a new Election Event
- [x] Add refresh data in the sidebar and dashboard
- [x] Dashboard display total votes
- [x] Make Expanding tree leave in the sidebar only for new created items
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/86
- [ ] https://github.com/sequentech/backend-services/pull/89
- [ ] https://github.com/sequentech/backend-services/pull/93
- [ ] https://github.com/sequentech/backend-services/pull/104
- [ ] https://github.com/sequentech/backend-services/pull/113
- [ ] https://github.com/sequentech/backend-services/pull/127
- [ ] https://github.com/sequentech/backend-services/pull/128
- [ ] https://github.com/sequentech/backend-services/pull/132
- [ ] https://github.com/sequentech/backend-services/pull/136
- [ ] https://github.com/sequentech/backend-services/pull/155
- [ ] https://github.com/sequentech/backend-services/pull/170
```
