### ISSUE TITLE
✨ Implement ballot locator functionality

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#249]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Implement ballot locator functionality

### Tasks

```[tasklist]
# Tasks
- [x] Add ballotId in Hasura table cast_vote
- [x] Implement ballot locator functionality in election chooser and review screen
- [x] Query for the ballot by ballotId
- [x] Display the result
- [x] Put the CTA to the right (Click to Vote)
- [x] Add a Stepper to the ballot locator screen
- [x] Display the ballot content
- [x] Validate the ballot id input
- [x] Improve the style of the message (green / red)
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/247
```

#### 1st Iteration
Elections screen:
![Image](https://github.com/sequentech/meta/assets/1632391/f258615f-a044-43e7-a3d6-bdfbfb33feee)

Ballot locator:

![Image](https://github.com/sequentech/meta/assets/1632391/32617b3b-1844-439b-928d-42dded209481)

![Image](https://github.com/sequentech/meta/assets/1632391/55f8df7d-694e-41f2-bc99-a2c2458d8d68)

![Image](https://github.com/sequentech/meta/assets/1632391/1d257dce-a308-4fc0-adca-c57240905af6)

![Image](https://github.com/sequentech/meta/assets/1632391/8abef596-35ba-45d8-a897-0f06473abe06)

#### 2nd Iteration

![Image](https://github.com/sequentech/meta/assets/1632391/0c021e6e-a5e0-4f58-8548-6e16c7bbba4b)

![Image](https://github.com/sequentech/meta/assets/1632391/68b0ca45-8960-47d9-96a8-c4eea496d774)

![Image](https://github.com/sequentech/meta/assets/1632391/da8c9a24-1943-42d6-8280-32cdf05e87ce)

![Image](https://github.com/sequentech/meta/assets/1632391/4f1d8bd1-ba91-457a-bd12-a96c487d8daf)

![Image](https://github.com/sequentech/meta/assets/1632391/0b8ed1a3-fc2f-4c96-8aa0-2d565a07776d)

TreeMenu sidebar visibility:

![Image](https://github.com/sequentech/meta/assets/1632391/b90c7553-830f-4a4a-862c-7c92588bc966)

**Comment by Findeton** [comment]
@KNTH01 I'm fixing the following things (then I'll merge for the demo):

1. Previously when you clicked anywhere in the election, it would enter the election. Also it would change the cursor on mouseover. These changes are a regression because they removed this functionality.
2. In the ballot locator screen, it should find the ballot also when you simply press Enter.
3. In the ballot locator screen, the found ballot content should be in a box.
4. In the ballot locator screen, the back button should have an arrow.

**Comment by Findeton** [comment]
Can't upload images to github as it keeps failing (stupid M$).

https://i.imgur.com/zzXdAie.png

https://i.imgur.com/3Mg9KmI.png
