### ISSUE TITLE
✨ Assign permissions to initial roles

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#252]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Assign permissions to initial roles

### Tasks

```[tasklist]
# Tasks
- [ ] Define basic roles and what are their permissions
- [ ] Hasura: Assign the permissions to each role
- [ ] Ensure there's a way for the frontend to know the permissions of the role the current user has (maybe API?)
```

```[tasklist]
# Main PRs
- [ ] PR 1
```

**Comment by edulix** [comment]
we already have this
