### ISSUE TITLE
Security updates

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#254]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Security updates

### Tasks

```[tasklist]
# Tasks
- [x] Perform the security updates
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/ballot-box/pull/180
```
