### ISSUE TITLE
✨ Refresh & document OIDC support

### ISSUE THREAD

**Issue by ElectricPaperInformationssystemeGmbH** [sequentech/meta#256]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Ensure the openID auth method works for simple election as well for parent child.

### Suggested Implementation

From what I have found, the following things are missing and should be added:
- Authentication should only be allowed to people in the census, but currently it just asumes anyone that has been authenticated by the OIDC Provider to be also authorized, automatically adding them to the census if they are not included. We need to change that, so that Authorization is performed by the IAM instead. 
- Adding people to the census doesn't work in openid-connect (since it asumes authorization is performed by the 3rd-party OIDC provider).
- Ensure support for open registration still works (which is the current behavior).
- OIDC Providers will be configurable per election.
- Ensure alternative auth-methods support works.
- The login screen styles are not working well. They should look similar to what can be seen below. Note that the icon and text for the button depend on the OIDC Provider configuration, and that there would be one button per provider. Additionally, we're adding a customizable login description that was not there before.
![Image](https://github.com/sequentech/meta/assets/81968/99be657e-b455-41ec-a349-0a97387e5adc)

### Implementation details

The authentication screen looks like the following:
<img width="1419" alt="image" src="https://github.com/sequentech/meta/assets/81968/1d2d1cc4-5786-4216-94d9-cb63847973cb">

Once the voter clicks on the Google authentication provider, then the following screen appears:
<img width="1419" alt="image" src="https://github.com/sequentech/meta/assets/81968/d374cefd-7e98-4dab-8e3a-ae12569c2136">

After authentication in the OIDC Provider, the user is redirected back to Sequent Platform. Sequent Platoorm  automatically verifies the identity and performs authorization, redirecting to the voting booth if everything checks out:
<img width="1419" alt="image" src="https://github.com/sequentech/meta/assets/81968/8b131369-49f5-4c74-907e-f084c3aab4b7">

This is how an election with Alternative authentication methods (and parent-children elections) look like when showing an OIDC specific authentication error:
<img width="1419" alt="image" src="https://github.com/sequentech/meta/assets/81968/831d0e3c-5e2f-499a-b36e-63c06a03d8b1">

### Tasks

```[tasklist]
# Tasks
- [x] testing: configure OIDC in a development deployment
- [x] testing: use OIDC in a development deployment and successfully authenticate
- [x] gap-analysis: identify implementation gaps and produce a suggested implementation
- [x] client-approval: Receive client approval for the suggested implementation
- [x] implementation: Cover the identified gaps by delivering suggested implementation
- [x] documentation repo: Add a OIDC authentication guide
- [x] final-client-approval-request: document the actual implementation and request final implementation approval
- [x] final-client-approval: obtain final implementation approval
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/deployment-tool/pull/351
- [ ] https://github.com/sequentech/iam/pull/327
- [ ] https://github.com/sequentech/documentation/pull/139
- [ ] https://github.com/sequentech/common-ui/pull/367
- [ ] https://github.com/sequentech/admin-console/pull/408
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/deployment-tool/pull/350
- [ ] https://github.com/sequentech/iam/pull/326
- [ ] https://github.com/sequentech/common-ui/pull/363
- [ ] https://github.com/sequentech/admin-console/pull/407
```

**Comment by edulix** [comment]
@ElectricPaperInformationssystemeGmbH please review and comment here if you accept the suggested implementation or require any changes.

**Comment by ElectricPaperInformationssystemeGmbH** [comment]
> Authentication should only be allowed to people in the census, but currently it just asumes anyone that has been authenticated by the OIDC Provider to be also authorized, automatically adding them to the census if they are not included. We need to change that, so that Authorization is performed by the IAM instead.

Don't forget to handle the "open registration", I think in this case the existing behaviour is ok.

>Adding people to the census doesn't work in openid-connect (since it asumes authorization is performed by the 3rd-party OIDC provider).

Does this mean that if I wanted to use json census, it would not work? So this is following from the previous point.

>OIDC Providers are configured in the deployment, not in the election. I think this is fine, but just wanted to make it clear. One could also perhaps do something similar as we do with trustees/authorities: let the election configuration include a list of the names of the OIDC providers to be used in the election. Please let me know what you think.

That would be a solution. In my opinion, it would be more flexible if the OIDC configuration could be defined per election. Just like we define SharedSecret. I understand that this means more work, but I think this is the right way to go so that we don't come back to this issue in the future.

>The login screen styles are not working well. They should look similar to what can be seen below. Note that the icon and text for the button depend on the OIDC Provider configuration, and that there would be one button per provider. Additionally, we're adding a customizable login description that was not there before.

Don't forget to support alternative authentication methods.

**Comment by edulix** [comment]
@ElectricPaperInformationssystemeGmbH I've reflected the changes you proposed in the suggested implementation.

Also, answering your question: you are right, open registration is the only currently working mode, and as such it doesn't currently supporting adding people to the census manually - but we'll fix that.

**Comment by edulix** [comment]
@ElectricPaperInformationssystemeGmbH please review implementation details to approve and merge or request changes or clarifications

**Comment by ElectricPaperInformationssystemeGmbH** [comment]
@edulix looks good
