### ISSUE TITLE
🐞 Spinning cog jumps during tally in admin-console

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#258]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Current Behavior

During the tally process, the spinning cog jumps around.

### Expected Behavior

During the tally process, the spinning cog progresses to the next state.

### Environment

```markdown
- OS:
- Web browser:
```

### Tasks

```[tasklist]
# Tasks
- [x] Implement fix
```

```[tasklist]
# Master PRs
- [x] https://github.com/sequentech/admin-console/pull/400
- [ ] https://github.com/sequentech/admin-console/pull/401
```
