### ISSUE TITLE
🐞 Resend auth codes in email-otl or sms-otp doesn't work in alt-auth-method

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#260]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Current Behavior

Resend auth codes in email-otl or sms-otp doesn't work in alt-auth-method

### Expected Behavior

Should work

### Environment

```markdown
- OS:
- Web browser:
```

### Tasks

```[tasklist]
# Tasks
- [x] Fix issue
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/common-ui/pull/346
- [ ] https://github.com/sequentech/iam/pull/308
- [ ] https://github.com/sequentech/iam/pull/309
- [ ] https://github.com/sequentech/iam/pull/319
- [ ] https://github.com/sequentech/common-ui/pull/350
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/iam/pull/307
- [ ] https://github.com/sequentech/common-ui/pull/345
- [ ] https://github.com/sequentech/iam/pull/310
- [ ] https://github.com/sequentech/iam/pull/313
- [ ] https://github.com/sequentech/common-ui/pull/347
```
