### ISSUE TITLE
🐞 Bogus UI when loading voting booth without credentials

### ISSUE THREAD

**Issue by ElectricPaperInformationssystemeGmbH** [sequentech/meta#262]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Current Behavior

When entering the path `/booth/<election-id>/vote` without having logged in (without user credentials), errors happen (shown in the debug console) and an invalid and unexpected erroneous UI appears to the voter. 
![MicrosoftTeams-image (1)](https://github.com/sequentech/meta/assets/87812708/141f665b-55e6-4839-8dae-5a90947a4cfd)

### Expected Behavior

A proper error page explaining that no credentials were found should appear to the visitant.

### Implemented solution

The error page is now shown instead, and the `Go back` button goes to the `ConfigService.defaultRoute`. Here is a screenshot:
<img width="1289" alt="image" src="https://github.com/sequentech/meta/assets/81968/7518d507-de04-49ff-af26-3e95279ff1e4">

### Environment

```markdown
- OS:
- Web browser:
```

### Tasks

```[tasklist]
# Tasks
- [x] Reproduce issue
- [x] Fix issue
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/voting-booth/pull/399
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/voting-booth/pull/398
```

**Comment by edulix** [comment]
@ElectricPaperInformationssystemeGmbH I have not been able to replicate this error. Please provide a way to replicate this issue:
- a minimal election configuration that shows the issue. As minimal as possible, to ensure that the error is related to one of the few features used.
- detailed steps of how to reproduce it

I tried to:
- create an election with `presentation.extra_options`  jut being `"success_screen__redirect__url": "http://google.es",        "disable__public_home": true` and the issue didn't happen to me, I was redirected successfully.
- reproduce the issue using the demo booth of https://vnext.gremienwahlen.de/booth/101/demo-vote (one of the children elections in the screenshot) and I couldn't - when I clicked finish, I was redirected to EPI website successfully. 
- I tried to copy the presentation.extra_options from mentioned election 101 above (which includes other configuration settings than redirect url and disabled public home)  in a new election configuration, and also failed to replicate.

**Comment by edulix** [comment]
@ElectricPaperInformationssystemeGmbH thank you very much! that probably should be fixed, but I think it's a different issue: in v10 the demo voting booth is not https://vnext.gremienwahlen.de/booth/100/vote  but https://vnext.gremienwahlen.de/booth/100/demo-vote . And with this second link, things seem to work? If the behavior is also failing after after authentication, then please provide a minimal election.json config so we can replicate in our environment.

**Comment by ElectricPaperInformationssystemeGmbH** [comment]
@edulix ok, I think this is the main problem. Sorry about that, I was misinformed.

**Comment by edulix** [comment]
No worries, you actually detected a bug since it's failing to show a valid error message or redirect anywhere and in the console log there is an exception being thrown which generates that. I'll still fix it :-)
