### ISSUE TITLE
🐞 Selection state of a write-ins answer should not be changed when inputting with space key in the input type text

### ISSUE THREAD

**Issue by ElectricPaperInformationssystemeGmbH** [sequentech/meta#263]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Current Behavior

For write-ins, space sets the checkbox, so if you check it first and then type the name, the checkbox will be unchecked again

### Expected Behavior

Text field should be focused, without to send actions to checkbox

### Environment

```markdown
- OS:
- Web browser:
```

### Tasks

```[tasklist]
# Tasks
- [x] Replicate issue
- [x] Fix issue
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/voting-booth/pull/397
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/voting-booth/pull/396
```
