### ISSUE TITLE
🐞disable election chooser option is not working

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#264]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Current Behavior

During the tally process, the spinning cog jumps around.

### Expected Behavior

When the election is configured with `disable__election_chooser_screen`, it only works on the demo/preview.

### Environment

```markdown
- OS:
- Web browser:
```

### Tasks

```[tasklist]
# Tasks
- [x] Implement fix
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/voting-booth/pull/393
```

```[tasklist]
# 10.0.x PRs
- [ ] https://github.com/sequentech/voting-booth/pull/394
```
