### ISSUE TITLE
🐞 Login allowed with election closed

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#265]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Current Behavior

Login allowed with election closed:
- (election-portal) Login page url should redirect to some other route (public site or default url)
- (iam) Login should only work when election is started (bug introduced by https://github.com/sequentech/meta/issues/260 )

### Expected Behavior

Should work as expected

### Environment

```markdown
- OS:
- Web browser:
```

### Tasks

```[tasklist]
# Tasks
- [x] Fix issue
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/iam/pull/312
- [ ] https://github.com/sequentech/election-portal/pull/215
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/election-portal/pull/214
- [ ] https://github.com/sequentech/iam/pull/311
```
