### ISSUE TITLE
Support HTML format when sending email auth-codes

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#27]
Currently the IAM sending of emails only supports plain-text. We need to support sending emails with *both and at the same time* plain-text and html-email (it works as two alternative representations of the same email). Please take a look at [django send_mail call](https://docs.djangoproject.com/en/4.1/topics/email/#send-mail).

We should develop the feature so that it's backwards compatible in the IAM API if possible. 

This requires changes in different places:

## Tasks
- IAM
  - [x] add an extra field `html_message` to the auth-event config, next to the [`msg` field](https://sequentech.github.io/documentation/docs/general/reference/election-creation-json#census-config-msg), along with corresponding unit tests. If html_message is empty or null, then it's not used.
  - [x] add an extra field `html_message` to the IAM [CensusSendAuth view](https://github.com/sequentech/iam/blob/master/iam/api/views.py#L2124), next to the `msg` field, along with corresponding unit tests.
- Admin Console
  - [x] Allow to configure both plain-text and HTML email body when sending email codes both from the dashboard and in the census tab to specific voters, and configure it to actually integrate with the IAM backend properly.
  - [x] Allow to configure both plain-text and HTML email body when creating the election.  
  - [x] Show a preview of the html message before sending it.
- Documentation
  - [x] Document these changes in the [Election Creation JSON documentation](https://sequentech.github.io/documentation/docs/general/reference/election-creation-json#census-config-msg).
  - [x] Gate this feature behind a configuration field in `deployment-tool`, `iam`, and `admin-console`.
  - [x] Add an optional field to contracts in the `iam`.

## PRs

Note: **Substitute** each item with the link to each PR for each repo when it exists:

- https://github.com/sequentech/deployment-tool/pull/302
- https://github.com/sequentech/iam/pull/233
- https://github.com/sequentech/admin-console/pull/304
- https://github.com/sequentech/documentation/pull/88
- https://github.com/sequentech/common-ui/pull/244

## 6.1.x PRs
- https://github.com/sequentech/common-ui/pull/245
- https://github.com/sequentech/admin-console/pull/305
- https://github.com/sequentech/iam/pull/234
- https://github.com/sequentech/deployment-tool/pull/303

**Comment by edulix** [comment]
I suspect that the PRs for 6.1.x branch are needed, otherwise what else is required to move this to Done @Findeton ?

**Comment by Findeton** [comment]
@edulix  yes that's correct. I've updated the ticket to include the 6.1.x prs.
