### ISSUE TITLE
Can't start election on v10

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#274]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Current Behavior

Can't start election on version 10.0.0, it gives an error.

### Expected Behavior

I should be able to start election.

### Environment

```markdown
- OS:
- Web browser:
```

### Tasks

```[tasklist]
# Tasks
- [ ] Fix default return on method `allow_set_status`.
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/iam/pull/317
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/iam/pull/316
```
