### ISSUE TITLE
🐞 List layout issues

### ISSUE THREAD

**Issue by markgrafd** [sequentech/meta#276]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Current Behavior

We have noticed some unsightly display in list elections:

1. List layout with 4 columns is wrapped randomly if the text of a list is too long. We would prefer a fixed width with text wrapping.
![image](https://github.com/sequentech/meta/assets/44897836/f87da9f7-d0c7-43ca-8207-ef815e725768)

2. In lists that are divided into two columns, the right column is not left-aligned
![image](https://github.com/sequentech/meta/assets/44897836/0aa9f916-bd13-413f-aafb-90c63375bcdd)

3. Bound lists are displayed centered and therefore run over the frame on the left and right. We would prefer a left-justified display with fixed width and text wrapping. 
![image](https://github.com/sequentech/meta/assets/44897836/666262de-57b8-4801-a9e7-56a6d5a9b665)

4. Candidate names in bound lists are wrapped even though there is still white space. 
![image](https://github.com/sequentech/meta/assets/44897836/cb5043d7-d643-4eaa-8db3-fd683c3819d4)

### Expected Behavior

We would prefer the list names to be left-aligned and also have text wrapping. For bound lists we would like to reduce the white space between the candidates a bit. Multi-column lists should be left-aligned in all columns.

### Environment

```markdown
- OS:
- Web browser:
```

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [x] Successful defect resolution merged
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/voting-booth/pull/410
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/voting-booth/pull/409
```

**Comment by edulix** [comment]
Thanks for the report @markgrafd with detailed screenshots. Can you please provide some election.json config to easily replicate the issue?

**Comment by edulix** [comment]
Thanks for the report. Let me go through the different issues:

## Issue 1

I have been able to replicate issue only with screen size less than 1200px, but nevertheless:

Before:
![image](https://github.com/sequentech/meta/assets/81968/6338356d-c346-4644-8b5d-e5632b0206df)

After applying the fix, the four columns are shown:
<img width="1228" alt="image" src="https://github.com/sequentech/meta/assets/81968/006ae477-95a2-4a37-a02d-bcec1e85a26f">

## Issue 2

I have not been able to replicate the issue, so probably it's related to some specific custom css you apply to your elections. Please @ElectricPaperInformationssystemeGmbH (Sergiy) try to replicate the issue in the demo environment:

<img width="1228" alt="image" src="https://github.com/sequentech/meta/assets/81968/3652a1a6-f4c2-439e-9ad2-d2b7b3abb1f9">

## Issue 3

I have been able to replicate issue:

Before:
<img width="1228" alt="image" src="https://github.com/sequentech/meta/assets/81968/ab6e5535-8d9e-4748-95c6-d70ca375219b">

After applying the fix, the text wrapping happens correctly:
<img width="1228" alt="image" src="https://github.com/sequentech/meta/assets/81968/006ae477-95a2-4a37-a02d-bcec1e85a26f">

Please note that depending on the size of the text there might be multiple lines and this would mess up the vertical alignment of the candidates. There's no easy fix for that, other than trying to set a minimum height for the header...

## Issue 4

I cannot easily replicate that - I'd suggest to try to replicate it in our demo environment @ElectricPaperInformationssystemeGmbH (Sergiy).

I believe this is mainly related to our default which is to always leave space for the image. I reduced the default padding to the right too. It's also related to the custom css that moves that to the right in EPI election's css styles. You can use the following css excerpt to hide the candidate image div in the election:

```css
[avb-review-ballot-v2] .vertilize-wrapper .vertilize .vertilize-col.answer-image, [avb-simultaneous-question-answer-v2] .vertilize-wrapper .vertilize .vertilize-col.answer-image, [avb-simultaneous-questions-v2-screen] .vertilize-wrapper .vertilize .vertilize-col.answer-image { display: none; }
``` 

Explanation: leaving always the space for the candidate image was an explicit design decision so it's not a bug. The motivation was the fact that sometimes there might be an election where some candidates do have an image and others don't, so to align the name of the candidates correctly we left it always on, knowing that this can be easily fine-tuned with css if we want to hide it - which is exactly the solution we provided you above.

Before:
<img width="1228" alt="image" src="https://github.com/sequentech/meta/assets/81968/3b80860b-ac9a-41cd-a191-5c4d76a186cf">

After:
<img width="1228" alt="image" src="https://github.com/sequentech/meta/assets/81968/0dc6f0c7-5e98-418c-a047-cf094dd5f660">

Please let us know if this makes sense so we can merge it.

**Comment by markgrafd** [comment]
@edulix Thank you very much. Please have a look at: https://vnext.gremienwahlen.de/booth/3505/demo-vote In the second ballot there is much white space and the elements are not alligned properly. We know that this is a responsive display and is therefore difficult to handle. In any case, it's really nice that the list names now wrap around. We should refrain from fixed heights. We would still be happy if you could merge this, but maybe you can reduce the white space a bit more. It is also strange to us why individual elements are shifted so far. 
![image](https://github.com/sequentech/meta/assets/44897836/cded9e28-ebcb-46a0-8a86-9c2cbb55aa76)

**Comment by edulix** [comment]
THanks for the review @markgrafd . As I mentioned for issue 3 in my comment, this is related to the space left for the image of the candidate, and this is by design for the reasons mentioned in my comment too. BUT you guys can hide that with the election custom_css, as also mentioned. Here is how it looks, in the same link you provided but applying (manually, using Chrome DevTools) the custom css fix:


![Image](https://github.com/sequentech/meta/assets/81968/be814073-5895-42f8-a4c5-799640597dea)

**Comment by markgrafd** [comment]
@edulix That looks much better. Thank you very much for the hint. We will keep an eye on that. Feel free to close this ticket.
