### ISSUE TITLE
🐞 Adding a voter with not required auth extra fields doesn't work

### ISSUE THREAD

**Issue by ElectricPaperInformationssystemeGmbH** [sequentech/meta#277]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Current Behavior

Trying to add voter, filled only with the required fields doesn't work
This error appears 
![image](https://github.com/sequentech/meta/assets/87812708/a8412f47-a098-4b23-9fe2-9c8321a694eb)

### Expected Behavior

The private and non required fields should not appear in the voter add dialogue. Or maybe hide those fields in some kind of drop down ui.
Only required fields for authentication should be mandatory when creating new voters.
All this of course applies to manual adding of voters, css and json import of census.

### Steps To Reproduce

1. create election https://gist.github.com/ElectricPaperInformationssystemeGmbH/00e064df4eac8e1cbf23072758ffe959
2. try to add voter, filled only with the email field

### Environment

```markdown
- OS:
- Web browser:
```

### Tasks

```[tasklist]
# Tasks
- [x] Bugfix
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/admin-console/pull/406
```

```[tasklist]
# Stable PRs
- [x] https://github.com/sequentech/admin-console/pull/405
```

**Comment by edulix** [comment]
One comment: we are implementing this bugfix, but just to be clear we are not changing the UI as commented here. What I've implemented is that you can just add the census as expected, with the optional fields not set.

Even though we know the UI is not the most user-friendly, changing the UI would be out of the scope of a bugfix.
