### ISSUE TITLE
Security updates

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#279]
### Tasks

```[tasklist]
# Tasks
- [ ] Perform the security updates
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/common-ui/pull/352
- [ ] https://github.com/sequentech/voting-booth/pull/403
- [ ] https://github.com/sequentech/election-portal/pull/217
- [ ] https://github.com/sequentech/admin-console/pull/403
- [ ] https://github.com/sequentech/iam/pull/321
- [ ] https://github.com/sequentech/election-orchestra/pull/80
- [ ] https://github.com/sequentech/frestq/pull/84
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/common-ui/pull/353
- [ ] https://github.com/sequentech/voting-booth/pull/404
- [ ] https://github.com/sequentech/election-portal/pull/218
- [ ] https://github.com/sequentech/admin-console/pull/404
- [ ] https://github.com/sequentech/iam/pull/322
- [ ] https://github.com/sequentech/election-orchestra/pull/81
- [ ] https://github.com/sequentech/frestq/pull/85
```
