### ISSUE TITLE
Release 10.0.1

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#280]
### Tasks

```[tasklist]
# Tasks
- [x] Tag the release
- [x] Create releases with automatic release notes in github
- [x] Test the release
- [x] Deploy release in stable <major>xx deployment
- [ ] Deploy release in demo
- [ ] Deploy release in web-demo
```
