### ISSUE TITLE
🐞 500 after vote has been casted

### ISSUE THREAD

**Issue by ElectricPaperInformationssystemeGmbH** [sequentech/meta#282]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

The error 500 is displayed for a short time directly after the ballot is cast and then we are immediately logged out and redirected to the login page.

### Expected Behavior

Success screen must be shown

### Steps To Reproduce

ballot-box.log: https://gist.github.com/ElectricPaperInformationssystemeGmbH/3f42542d03140bcd0079f21b2ec18197
condig.json: https://gist.github.com/ElectricPaperInformationssystemeGmbH/700be6847bcc8f21d6c3de38f795b231
video: https://github.com/sequentech/meta/assets/87812708/37302dc7-e784-4d5f-9aa3-0ec5bfe7d5c7

### Environment

- **OS**: Mac OS X Ventura
- **Web browser**: Google Chrome 112.0.5615.137 (Official Build) (arm64)
- **Sequent Platform Version**: 10.0.0

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [ ] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/voting-booth/pull/406
- [ ] https://github.com/sequentech/common-ui/pull/355
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/voting-booth/pull/405
- [ ] https://github.com/sequentech/common-ui/pull/354
```
