### ISSUE TITLE
🐞 Sending census auth codes is not done in async manner

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#284]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

Sending census auth codes is not done in async manner

### Expected Behavior

It should be async and write the number of users related to this in the log

### Steps To Reproduce

TBD

### Environment

- **Sequent Platform Version**: 10.0.0

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [x] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/iam/pull/324
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/iam/pull/323
```
