### ISSUE TITLE
🐞 switching between translations with custom texts doesn't work

### ISSUE THREAD

**Issue by ElectricPaperInformationssystemeGmbH** [sequentech/meta#287]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

German texts are displayed correctly, but when switching to English, standard texts are displayed.

If you change English back to German, the standard texts are displayed again instead of custom German translations.

### Expected Behavior

custom translations will be always displayed

### Steps To Reproduce

https://gist.github.com/ElectricPaperInformationssystemeGmbH/5c231192e5029af5878797cbd35a5390
https://vnext.gremienwahlen.de/booth/2/demo-vote

### Environment

- **Sequent Platform Version**: 10.0.01

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [x] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [x] https://github.com/sequentech/common-ui/pull/357
```

```[tasklist]
# Stable PRs
- [x] https://github.com/sequentech/common-ui/pull/356
```
