### ISSUE TITLE
✨ Merging crypto branch for the purposes of alpha 1

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#289]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Merging crypto branch for the purposes of alpha 1

### Tasks

```[tasklist]
# Tasks
- [ ] Merge the branch
- [ ] Resolve the conflicts
```

```[tasklist]
# Main PRs
- [ ] PR 1
```
