### ISSUE TITLE
🐞 Parent-children elections always request all children, even if voter can only vote in one

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#290]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

Parent-children elections seem to be requesting all children to the ballot-box when the voting booth loads. This can result in many more requests than required.

### Expected Behavior

Only children elections where the voter can vote should be requested, at most. Or maybe even only the current election if possible.

### Steps To Reproduce

1. In the Admin Portal, click in `New Election` in the sidebar, then click in `Create Election`.
2. Click in `Actions` button and then click in `Edit JSON` in the popup menu and paste the following election configuration json into the modal dialog and accept (change the trustee server names appropriately): 
[election.json](https://github.com/sequentech/meta/files/13039210/election.json)
3. Then click in `Actions` button and create the election.
4. Start the election, send credentials to the voter, and enter the login screen as a voter.
5. Open the Chrome DevTools or equivalent and filter by XHR requests.
6. Login, and see that the frontend is requesting not only the children elections in which the voter can vote, but also the one in which the voter cannot. See the screenshot below: voter can only vote in students election with id xx31, but the frontend is also requesting professors election xx32.
<img width="1437" alt="image" src="https://github.com/sequentech/meta/assets/81968/ecbd37f6-294d-4052-8418-a3589ba46696">
 

### Environment

- **Sequent Platform Version**: 10.0.1

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [x] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/voting-booth/pull/408
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/voting-booth/pull/407
```
