### ISSUE TITLE
✨ Update Ballot Style definitions

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#292]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Current Ballot Style definitions are based on 1st gen definitions. Use 2nd gen definitions

### Tasks

```[tasklist]
# Tasks
- [x] Update sequent-core.
- [x] Update voting-portal.
- [x] Update ballot verifier.
- [x] Update windmill task for creating ballot styles.
- [x] Update admin-portal.
- [x] Update harvest for creating ballot styles task.
```

```[tasklist]
# Master PRs
- [x] https://github.com/sequentech/backend-services/pull/73
- [ ] https://github.com/sequentech/backend-services/pull/74
```
