### ISSUE TITLE
✨  Admin Portal - Settings - Communication Templates

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#293]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Admin-portal: Implement Settings UI according to:

- [Admin Portal - Communication Templates](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=940-67008&mode=design&t=rlnbwUCqRe1sphsA-0)
- [Admin Portal - Settings - Communication Templates - Create Edit](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=940-67407&mode=design&t=rlnbwUCqRe1sphsA-0)
- [Admin Portal - Settings - Communication Templates - Create Edit 2](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=940-71681&mode=design&t=rlnbwUCqRe1sphsA-0)

### Screenshots

![Image](https://github.com/sequentech/meta/assets/164689/2b7572ee-f73e-4b08-a5dd-d4631bd5f83c)

![Image](https://github.com/sequentech/meta/assets/164689/618338e7-ef41-4f42-97cf-ad43e920757f)

![Image](https://github.com/sequentech/meta/assets/164689/fc834c4a-4d77-4a52-b4e7-a836b7e4e394)

![Image](https://github.com/sequentech/meta/assets/164689/ac5541a4-92a7-413d-a6d5-038d457f12ef)

- Elections recipts

![Image](https://github.com/sequentech/meta/assets/164689/514c0a24-fb18-4838-8965-87933764c3a1)

- Users/Voters

![Image](https://github.com/sequentech/meta/assets/164689/ef1fad83-1c83-48b3-a7aa-3433ef929d4c)

- Default values

![Image](https://github.com/sequentech/meta/assets/164689/b5800a4d-e5b6-4e58-831e-3382c0d4584d)

_No response_

### Tasks

```[tasklist]
# Tasks
- [x] UI: [Admin Portal - Communication Templates](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=940-67008&mode=design&t=rlnbwUCqRe1sphsA-0)
- [x] UI: [Admin Portal - Settings - Communication Templates - Create Edit](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=940-67407&mode=design&t=rlnbwUCqRe1sphsA-0)
- [x] UI: [Admin Portal - Settings - Communication Templates - Create Edit 2](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=940-71681&mode=design&t=rlnbwUCqRe1sphsA-0)
- [x] Backend: add hasura table `communication_template`
- [x] Create communication template resource route list, creat and edit
- [ ] Modify Route Resource to Custom route and add 2 resource difference with email and sms
- [ ] UI Send notification: allow to choose an existing template. 2 places: send voter a message, and send receipts.
- [x] refactored create template screen
- [x] add update template screen
- [x] add update template query
- [ ] review permissons
- [x] implement templates in election receipts
- [x] create new field receipts in election
- [x] implement templates in voters
- [x] implement templates in users
- [x] add default values (default template values)
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/168
- [ ] https://github.com/sequentech/backend-services/pull/223
- [ ] https://github.com/sequentech/backend-services/pull/280
```
