### ISSUE TITLE
✨ Security question custom authenticator

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#294]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Implement a modified version of the [“secret question” authenticator](https://wjw465150.gitbooks.io/keycloak-documentation/content/server_development/topics/auth-spi.html) to use a user profile attribute(s) for authentication, and apply some comparator (equal to & last 4 characters). Maybe use an authenticator addable exec action (like in the [sms authenticator from daniko](https://github.com/dasniko/keycloak-2fa-sms-authenticator)) to configure which user attributes to verify.

### Tasks

```[tasklist]
# Tasks
- [x] Implement Security Question Authenticator
- [x] Implement Security Question Required Action
- [x] Auto-add Security Question authenticator when 2FA credentials are missing
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/96
```
