### ISSUE TITLE
✨ Use hasura action handler for receiving cast-votes

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#297]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Use hasura action handler for receiving cast-votes. This endpoint should validate its structure and signature, and then save it in the database.

### Tasks

```[tasklist]
# Tasks
- [x] only allow to cast votes if the election is open and the event is also open and is not archived
- [x] Add support for election state
- [x] check config to only allow casting as many ballots as set in the config. Talk with Edu.
- [x] add info to the electoral, `post_cast_vote_error` and `post_cast_vote` when appropriate
- [x] check that the election is being voted by the right channel: if it's an election for voting online, then the voting client should be `voting-portal`, if it's onsite, it should be.. `onsite-voting-portal` etc. Also save the channel associated to the vote in a column in `cast_vote`(probably needs to be created).
- [x] Verify proof of plaintext knowledge
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/300
- [ ] https://github.com/sequentech/backend-services/pull/302
```

**Comment by ruescasd** [comment]
Reminder to ensure that the implementation for this:

add info to the electoral, `post_cast_vote_error` and `post_cast_vote` when appropriate

must be changed to not cause a failure due to an error in posting to the electoral log. errors posting to the electoral log should only be logged. the current implementation errors out even though the vote casting has completed (transaction of inserted vote committed)

**Comment by ruescasd** [comment]
Adding popk validation on the server side:

https://github.com/sequentech/backend-services/commit/a8d5044817add2de5407991649d61c706a7eb98e
