### ISSUE TITLE
✨ Select languages per election

### ISSUE THREAD

**Issue by ElectricPaperInformationssystemeGmbH** [sequentech/meta#306]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

It should be possible to define the languages to be displayed to a voter during the creation of an election. For example, the application is deployed with de, en, es, fr and the json file only contains de, en. This means that only these two languages are displayed to the voter.
This must also be available in the preview.

### Implementation suggestion

We'll add a `election.presentation.i18n_languages_conf` configuration setting to the election for configuring the
languages settings. An example of this settings can be seen below:

```javascript
{
    "presentation": {
        // per election language configuration
        "i18n_languages_conf": {
            // default language if anything else is equal
            "default_language": "en",
            // if set to `false`, we'll match browser settings with available 
            // languages to decide which language to load by default. If set 
            // to `true`, then we won't detect any browser language preferences
            // and we'll always load the previously defined `default_language`
            // by default.
            "force_default_language": false,
            // available languages for this election
            "available_languages": [
                "en",
                "es"
            ]
        }
    }
}
```

This should be compatible with different configuration for parent and children elections so that the parent election might have a different setting than the children election.

For example, it might be that the parent election supports both `English` and `Spanish` and loads `English` by default. However, when the voter selects the child election in which to vote, then the child election `i18n_languages_conf`
setting is loaded and this child election only supports `Spanish`, so the whole system switches to `Spanish` automatically.

Limitation: if the voter goes back to the election chooser, the parent election's `i18n_languages_conf` configuration is loaded again, and since it supports `Spanish` and `Spanish` is the currently selected language, the current language will keep being `Spanish`.

### Tasks

```[tasklist]
# Tasks
- [x] suggested-implementation: identify requirements and produce a suggested implementation
- [x] client-approval: Receive client approval for the suggested implementation
- [x] implementation: Develop the suggested implementation
- [x] documentation repo: Write the documentation related to the suggested implementation
- [x] final-client-approval-request: document the actual implementation and request final implementation approval
- [x] final-client-approval: obtain final implementation approval
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/documentation/pull/141
- [ ] https://github.com/sequentech/ballot-box/pull/183
- [ ] https://github.com/sequentech/voting-booth/pull/416
- [ ] https://github.com/sequentech/common-ui/pull/371
- [ ] https://github.com/sequentech/election-portal/pull/220
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/ballot-box/pull/182
- [ ] https://github.com/sequentech/voting-booth/pull/413
- [ ] https://github.com/sequentech/common-ui/pull/369
- [ ] https://github.com/sequentech/election-portal/pull/219
```

**Comment by ElectricPaperInformationssystemeGmbH** [comment]
looks good for me

**Comment by edulix** [comment]
Implemented @ElectricPaperInformationssystemeGmbH , ready for approval
