### ISSUE TITLE
🐞 Old PostgreSQL backups not being removed and rotated

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#309]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

WAL backups are not being removed and default backup config retains too many backups.

### Expected Behavior

Should be fixed.

### Steps To Reproduce

-

### Environment

- **Sequent Platform Version**: 10.0.2

### Tasks

```[tasklist]
# Tasks
- [ ] Issue has been triaged
- [ ] Successful replication of the defect
- [ ] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] PR 1
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/deployment-tool/pull/348
```
