### ISSUE TITLE
🐞 Sending credentials to an email-otp auth-method sends empty subject email

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#310]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

Sending credentials to an email-otp auth-method sends empty subject email

### Expected Behavior

Should work

### Steps To Reproduce

-

### Environment

- **Sequent Platform Version**: 10.0.2

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [ ] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] PR 1
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/common-ui/pull/358
```
