### ISSUE TITLE
🐞 title layout on review page

### ISSUE THREAD

**Issue by ElectricPaperInformationssystemeGmbH** [sequentech/meta#311]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

The title of the review page is displayed under the broad crumbs bar when the browser window is narrow and [audit ballot disabled](https://sequentech.github.io/documentation/docs/general/reference/election-creation-json/#election-presentation-options-disable_voting_booth_audit_ballot).

### Expected Behavior

The title should be fully visible

### Steps To Reproduce

![image](https://github.com/sequentech/meta/assets/87812708/b740f4f1-8eba-4799-9c36-53983786a855)
https://demo.sequentech.io/admin/dashboard/13453647

### Environment

- **Sequent Platform Version**: 10.0.2

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [x] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/voting-booth/pull/420
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/voting-booth/pull/419
```
