### ISSUE TITLE
✨ velvet: Performance benchmarks

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#313]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

We should have performance benchmarks for velvet, and have them integrated into Github Actions to be run automatically.

### Tasks

```[tasklist]
# Tasks
- [ ] Add performance benchmarks to velvet.
- [ ] Integrate benchmarks into Github Actions.
```

```[tasklist]
# Master PRs
- [ ] PR 1
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```
