### ISSUE TITLE
🐞 default translation appears when switching language for the first time

### ISSUE THREAD

**Issue by ElectricPaperInformationssystemeGmbH** [sequentech/meta#315]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

it's basically the same problem as https://github.com/sequentech/meta/issues/287. It only appears in the preview with json as parameter. The default language is ok, but when you switch to english, the default translations are shown. Switching the language back will show the correct translation.  You can use this link https://gist.github.com/ElectricPaperInformationssystemeGmbH/09dfea5afd03981508e2ee17b4ff27f0. Select the option and go to the next page, then try to change the language.

### Expected Behavior

languages should be switched immediate. 

### Steps To Reproduce

https://github.com/sequentech/meta/assets/87812708/5c4198b4-c88a-4f7c-8abd-34ec77420fb0

at the 20 sec look at the first column
afterwards go to the 31 sec

### Environment

- **OS**: Mac OS X Ventura
- **Web browser**: Google Chrome 112.0.5615.137 (Official Build) (arm64)
- **Sequent Platform Version**: 10.0.2

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [x] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/common-ui/pull/361
- [ ] https://github.com/sequentech/common-ui/pull/374
- [ ] https://github.com/sequentech/voting-booth/pull/422
- [ ] https://github.com/sequentech/common-ui/pull/376
- [ ] https://github.com/sequentech/voting-booth/pull/424
- [ ] https://github.com/sequentech/election-portal/pull/222
- [ ] https://github.com/sequentech/admin-console/pull/412
- [ ] https://github.com/sequentech/common-ui/pull/378
- [ ] https://github.com/sequentech/voting-booth/pull/426
- [ ] https://github.com/sequentech/election-portal/pull/224
- [ ] https://github.com/sequentech/deployment-tool/pull/353
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/common-ui/pull/360
- [ ] https://github.com/sequentech/common-ui/pull/373
- [ ] https://github.com/sequentech/voting-booth/pull/421
- [ ] https://github.com/sequentech/common-ui/pull/375
- [ ] https://github.com/sequentech/voting-booth/pull/423
- [ ] https://github.com/sequentech/election-portal/pull/221
- [ ] https://github.com/sequentech/admin-console/pull/411
- [ ] https://github.com/sequentech/common-ui/pull/377
- [ ] https://github.com/sequentech/voting-booth/pull/425
- [ ] https://github.com/sequentech/election-portal/pull/223
- [ ] https://github.com/sequentech/deployment-tool/pull/352
```

**Comment by ElectricPaperInformationssystemeGmbH** [comment]
unfortunately we have found another issue regarding this ticket. When you enter the preview voting booth, the default translations are displayed. This time the problem comes in preview when you create an election in the dashboard.
![Screenshot 2023-11-24 084838](https://github.com/sequentech/meta/assets/87812708/9aeab4c2-264b-486a-aafb-3807b4258c06)
![Screenshot 2023-11-24 084901](https://github.com/sequentech/meta/assets/87812708/09bd3b4d-aa10-4326-8f83-158a3ebf2de9)

**Comment by ElectricPaperInformationssystemeGmbH** [comment]
@edulix Last issue also appears in the demo voting booth

**Comment by edulix** [comment]
Sorry for the delay and the issue. I'm on it right now, will keep you updated.

**Comment by edulix** [comment]
I've pushed the tentative fix in branch `fix/meta-315/10.1.x` (PR https://github.com/sequentech/voting-booth/pull/421 ). I've already talked it with Sergiy: before we merge the fix and do a patch release he will test it later today to ensure it's really fixed for your use-case.

**Comment by ElectricPaperInformationssystemeGmbH** [comment]
@edulix German and English are used in one election. Language selection shows English twice
![image](https://github.com/sequentech/meta/assets/87812708/1da5bdd4-b9df-4a7e-b88a-5c7eb5c1e818)

**Comment by ElectricPaperInformationssystemeGmbH** [comment]
the link name "More information" is not translated 
![image](https://github.com/sequentech/meta/assets/87812708/2f9a03a9-5d44-4231-9b23-a340d6ee38ba)

**Comment by edulix** [comment]
I've been trying to replicate the issue in a clean environment but I haven't been able to do it. In our environment, it seems to be working. 

I understand that with your changes it still doesn't work and we want to support you, I'm trying to understand the changes you apply to find what is the source of the issue.

**Comment by sergiydmukhinepi** [comment]
Wir haben immer Probleme mit dem Ticket. Diesmal funktionieren die Wahlen in einer Sprache. Die Wahlkabine wird immer in Englisch angezeigt und nicht in der Sprache, die in der JSON-Konfiguration eingestellt ist. Sobald ich alle benutzerdefinierten Übersetzungen (i18n_override) entfernt habe, funktioniert es.
![image](https://github.com/sequentech/meta/assets/154313589/ee3d7e8a-1efa-4437-b731-b0310a356f47)


Zweites Problem, wenn ich eine zweite Sprache in i18n_languages_conf.available_languages hinzufüge, wird Englisch zweimal in der Sprachauswahl angezeigt.
![image](https://github.com/sequentech/meta/assets/154313589/cc00995e-5b20-4c03-b29f-14f20b05cf25)

**Comment by sergiydmukhinepi** [comment]
@edulix I forgot to mention that the error occurs in preview and demo. If the election is created, I have not tried it.

**Comment by edulix** [comment]
Reopened again since there was an issue with admin-portal
