### ISSUE TITLE
✨ voting-portal: Add translations support

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#318]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Add translations to voting-portal

### Tasks

```[tasklist]
# Tasks
- [x] Ballot Style: Modify interfaces in `sequent-core` to enable translations.
- [x] Add translations support in `voting-portal`.
- [x] Add election/event support/configuration in `admin-portal`.
- [x] build translate function for election
- [x] build translate function for contest and candidates
- [x] implement translations in start screen
- [x] implement translations in progress screen
- [x] implement translations in voting screen
- [x] review all local translations
- [x] move translate functions to ui-essentials
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/backend-services/pull/244
- [ ] https://github.com/sequentech/backend-services/pull/321
```
