### ISSUE TITLE
🐞 Fix translations

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#320]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Translations are not working

### Tasks

```[tasklist]
# Tasks
- [ ] [Revert PR](https://github.com/sequentech/meta/issues/315)
- [ ] Implement fix.
```

```[tasklist]
# 10.0.x PRs
- [ ] https://github.com/sequentech/common-ui/pull/364
- [ ] https://github.com/sequentech/common-ui/pull/366
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/common-ui/pull/365
- [ ] https://github.com/sequentech/common-ui/pull/368
```
