### ISSUE TITLE
✨ Beat recurrent tasks

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#321]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Automatically set public key, create board/keycloak config. Add postgres distributed lock.

### Possible Implementation

There are three types of realms that we need:
- Superadmin. This is for super-admins that can have access to everything.
- Tenant. This manages admins for a specific tenant.
- Election event. This manages voters for an election event within a tenant.

Note that the name of the realms should include the type, not only the id. Also in case of the election event it should also include the id of the tenant as the election event ids are only unique within the tenant.

### Tasks

```[tasklist]
# Tasks
- [x] Automatically set public key
- [x] Automatically create immudb board
- [x] Automatically create new keycloak realm and config (permissions and roles).
- [x] Add postgres distributed lock.
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/backend-services/pull/94
```
