### ISSUE TITLE
✨ Admin Portal - Election Event - Data/Areas/Areas New

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#322]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Admin-portal: Implement Election Event Configuration UI according to:
-  [Admin Portal - Election Event - Data](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=899-53736&mode=design&t=zC3uedpaOFjE5fcO-0)
- [Admin Portal - Election Event - Areas](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=919-61378&mode=design&t=kx7RX8IWgziCJhz9-0)
- [Admin Portal - Election Event - Areas New](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=926-63154&mode=design&t=rlnbwUCqRe1sphsA-0)

### Tasks

```[tasklist]
# Tasks
- [x] Prepare the Data tab and i18n for the edit
- [x] Add Accordion component in Data tab
- [x] Add form fields to Data tab
- [x] Prepare the Areas tab and i18n for the edit
- [x] Add form fields to Areas tab
- [x] Add New Areas drawer
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/backend-services/pull/95
```
