### ISSUE TITLE
✨ Admin Portal - Election Event - Voters

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#323]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Admin-portal: Implement Election Event Configuration UI according to:
-  [Admin Portal - Election Event Configuration - Voters List](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=959-72403&mode=design&t=rlnbwUCqRe1sphsA-0)
- [Admin Portal - Election Event Configuration - Send Voters Notifications](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=960-74429&mode=design&t=rlnbwUCqRe1sphsA-0)
- [Admin Portal - Election Event Configuration - Communication](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=960-77408&mode=design&t=rlnbwUCqRe1sphsA-0)
- [Admin Portal - Election Event Configuration - Send Communication](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=960-78229&mode=design&t=rlnbwUCqRe1sphsA-0)
- [Admin Portal - Election Event Configuration - Voters Data](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=960-79704&mode=design&t=rlnbwUCqRe1sphsA-0)
- Assign Area

Dependency: https://github.com/sequentech/meta/issues/335

### Screenshots

The list of voters shows a mail-icon action to send notification to the voter:

<img width="1437" alt="image" src="https://github.com/sequentech/meta/assets/81968/d9415c23-e614-4d1e-ae47-36fac5382987">

When you click in the envelope, this is the Send voter notification drawer:
<img width="1437" alt="image" src="https://github.com/sequentech/meta/assets/81968/a5357b7c-2772-452b-bf6b-2e6a1b8835ff">

When you click in the Send Notification button, it shows a success notification:
<img width="1437" alt="image" src="https://github.com/sequentech/meta/assets/81968/8fe692ae-b9a3-4109-9b1e-67c9d22006a0">

Add a SEND button to send notification to everyone:
![Image](https://github.com/sequentech/meta/assets/1632391/3a2a5901-a7e1-4cd7-bf47-3a0552588ed2)

Add a bulk action to send to selected voters:
<img width="1439" alt="image" src="https://github.com/sequentech/meta/assets/81968/08d2c934-2f9f-4d3e-9471-bf24aa13fcb5">

A confirmation dialog to delete selected voters:
<img width="1439" alt="image" src="https://github.com/sequentech/meta/assets/81968/d3932ef5-8cf3-49f1-8889-424e69fc0313">

It will open the drawer with the correct selection:
![Image](https://github.com/sequentech/meta/assets/1632391/725a164b-a0af-481e-9962-bf7fcfe26959)

Sending emails/sms now updates the counts:
<img width="1435" alt="image" src="https://github.com/sequentech/meta/assets/81968/842c79a5-0d85-49b6-b7a0-dbb4abf28a7a">

### Tasks

```[tasklist]
# Tasks
- [x] refactor the voters list
- [x] prepare edit voters mutation
- [x] add the edit form in the drawer
- [x] build the edit form
- [x] add areas to form
- [x] add main basic fields to form
- [x] add the rest of attributes object to form
- [x] added types to al entities in create/edit
- [x] voting channels linked to settings
- [x] UI Send notification: connect send notification to backend through hasura
- [x] UI Send notification: make RichText Editor work/show-up
- [x] UI Send notification: allow to send to multiple voters
- [x] UI Send notification: navbar send notification (to all voters)
- [x] Backend: implement send notification
- [x] Backend: ensure tenant-id is not removed from user properties when editing user
- [x] Backend: add AWS SNS SMS transport
- [x] configure windmill .env properly in `docker-compose.yml`
- [x] Backend: implement SQL query to DB send communications
- [x] Backend: update number of emails/sms sent
- [x] Frontend: make a custom bulk delete action to delete users
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/backend-services/pull/146
- [ ] https://github.com/sequentech/backend-services/pull/179
- [ ] https://github.com/sequentech/backend-services/pull/190
- [ ] https://github.com/sequentech/backend-services/pull/193
- [ ] https://github.com/sequentech/backend-services/pull/194
- [ ] https://github.com/sequentech/backend-services/pull/195
- [ ] https://github.com/sequentech/backend-services/pull/205
- [ ] https://github.com/sequentech/backend-services/pull/207
- [ ] https://github.com/sequentech/backend-services/pull/216
- [ ] https://github.com/sequentech/backend-services/pull/226
```
