### ISSUE TITLE
✨ Admin Portal - Election - Data

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#324]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Admin-portal: Implement Election Configuration UI according to:

- [Admin Portal - Election - Data](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=1051-35360&mode=design&t=rlnbwUCqRe1sphsA-0)

### Tasks

```[tasklist]
# Tasks
- [x] Prepare Base Tabs
- [x] Change App Resource
- [x] Add Election Form
- [x] Add dates fields and validation of end date
- [x] Add dynamic fields to Election Event
- [x] Add dynamic fields to Election
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/backend-services/pull/101
```

**Comment by edulix** [comment]
Closing this since it was Done. Instead of moving tickets to Done, it's better to close them, which automatically will move them to Done :-)
