### ISSUE TITLE
✨ Admin Portal - Election - Publish

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#325]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Admin-portal: Implement Election Ballot Style according to:

- [Admin Portal - Election - Publish](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=1055-37721&mode=design&t=rlnbwUCqRe1sphsA-0)

### Tasks

```[tasklist]
# Tasks
- [x] Research and compare json with colors in diffs
- [x] Create a dummies json
- [x] Create a diff view component
- [x] Create a publish actions component
- [x] create endpoint to get user info by id.
- [x] modify publish endpoint to be a generate endpoint.
- [x] add publish endpoint.
- [x] add endpoint to get jsons to compare on diff.
- [x] add single viewer json in diffview component
- [x] memorize diff view component for not re rendered when parent component is re rendered
- [x] connect to backend endpoints.
- [x] Restructure the code to align with the new development requested, change the flow of views and add two views, listing and publication.
- [x] Modify the actions component so that it has two modes, list mode and publication mode. In list mode, the generate button should not be visible, and the publish button should not call publish but switch to publication mode. In publication mode, only the actions to publish and regenerate should be available.
- [x] When entering the initial screen flow, the same screen should be displayed as in other areas in case of having no data, and if there is data, the publish tab should directly show the publication history.
- [x] Add a modal to confirm each action before executing it.
- [x] Add a toast notification once the action is completed and carry out the next process if necessary.
- [x] Add all translations and review the data types of each entry.
- [x] Fix error when retrieve ballot publication changes when click in show action table
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/backend-services/pull/172
- [ ] https://github.com/sequentech/backend-services/pull/192
- [ ] https://github.com/sequentech/backend-services/pull/200
- [ ] https://github.com/sequentech/backend-services/pull/202
- [ ] https://github.com/sequentech/backend-services/pull/228
- [ ] https://github.com/sequentech/backend-services/pull/229
- [ ] https://github.com/sequentech/backend-services/pull/232
- [ ] https://github.com/sequentech/backend-services/pull/241
```

## Implementation details (screenshots)

![Image](https://github.com/sequentech/meta/assets/25372521/8a202ad9-ab7c-4e04-a237-de874e1a7af5)

![Image](https://github.com/sequentech/meta/assets/25372521/4d0b98eb-8d47-46b3-90e6-a3ef0d0eb09e)

![Image](https://github.com/sequentech/meta/assets/25372521/729714a2-04ab-4947-9567-58674bf78383)

When diff view component type is simple:

![Image](https://github.com/sequentech/meta/assets/25372521/11fbf085-7e6e-4760-9319-e8e7717f98cc)

![Image](https://github.com/sequentech/meta/assets/25372521/794ef1f9-0a12-4985-b844-c3a470bb1045)

When diff view component type is not defined or setted modify:

![Image](https://github.com/sequentech/meta/assets/25372521/80dbc668-d75f-4f40-a826-acb7681fd15b)

![Image](https://github.com/sequentech/meta/assets/25372521/020b24a0-0ea6-4499-a162-30048b64ea92)

## Implementation details after call Eduardo - new design flow (screenshots)

![Image](https://github.com/sequentech/meta/assets/25372521/41158d08-fdd6-4b04-851c-de3bc2bd47b6)

![Image](https://github.com/sequentech/meta/assets/25372521/c32944ab-5483-48d0-b5a3-1b0033b21c61)

![Image](https://github.com/sequentech/meta/assets/25372521/1516fbd9-0a2f-422e-90d1-904566c6f1d3)

![Image](https://github.com/sequentech/meta/assets/25372521/07187eef-214b-43ca-a30d-5982bdd17476)

![Image](https://github.com/sequentech/meta/assets/25372521/e757f731-b473-4d1f-8540-78d0295dee6a)

![Image](https://github.com/sequentech/meta/assets/25372521/5097d813-e8bd-4bac-a523-85fcfa2cfff7)

![Image](https://github.com/sequentech/meta/assets/25372521/3d58da09-94f5-42a2-aec2-94c9730ca765)

**Comment by Findeton** [comment]
Looks great! I'll build those endpoints for you.

**Comment by Findeton** [comment]
I've created a ticket for a bug from here, please @formonkey  address it asap: https://github.com/sequentech/meta/issues/428
