### ISSUE TITLE
✨ Admin Portal - Candidate

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#326]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Admin-portal: Implement Candidate Configuration UI according to:
- [Admin Portal - Candidate - Data](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=907-55934&mode=design&t=rlnbwUCqRe1sphsA-0)
- [Admin Portal - Candidate - Data - List](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=910-59905&mode=design&t=rlnbwUCqRe1sphsA-0)
- [Admin Portal - Candidate - List - Candidate](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=911-60328&mode=design&t=rlnbwUCqRe1sphsA-0)
- [Admin Portal - Candidate - List - Candidate](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=912-60890&mode=design&t=rlnbwUCqRe1sphsA-0)
- [Admin Portal - Candidate - List  - Add Candidate](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=932-63689&mode=design&t=rlnbwUCqRe1sphsA-0)
- Contest Configuration UI according to written description

### Tasks

```[tasklist]
# Tasks
- [x] Prepare Base Tabs
- [x] Change App Resource
- [x] Add Candidate Form
- [x] Add Contest Form
- [x] Area contest management and UI
- [x] Delete in sidebar
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/backend-services/pull/119
- [ ] https://github.com/sequentech/backend-services/pull/141
```
