### ISSUE TITLE
✨ Admin Portal - Settings - Election Types/Voting Channels

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#327]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Admin-portal: Implement Settings UI according to:

- [Admin Portal - Settings - Election Types](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=896-23446&mode=design&t=rlnbwUCqRe1sphsA-0)
- [Admin Portal - Settings - New Election Type](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=896-32014&mode=design&t=rlnbwUCqRe1sphsA-0)
- [Admin Portal - Settings - Voting Channels](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=899-52505&mode=design&t=rlnbwUCqRe1sphsA-0)

### Tasks

```[tasklist]
# Tasks
- [x] Create a custom Tabs components
- [x] Create a custom route Settings Screen
- [x] Modify ListActions by custom styles
- [x] Create a VottingChannels screen
- [x] Connect with endpoint Event types
- [x] Connect with tenant config
- [x] Add communications screen
- [x] Add languages screen
- [x] Add setting column in tenant table
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/backend-services/pull/98
- [ ] https://github.com/sequentech/backend-services/pull/114
- [ ] https://github.com/sequentech/backend-services/pull/166
```
## Implementation details (screenshots)

![Image](https://github.com/sequentech/meta/assets/25372521/13c22c93-44c4-4896-8d1b-44673c37e847)

![Image](https://github.com/sequentech/meta/assets/25372521/ab635be6-73c8-4a7e-8918-6a349f2835a7)

![Image](https://github.com/sequentech/meta/assets/25372521/62d2534b-c152-4539-b4f8-bb9039ba32f7)

![Image](https://github.com/sequentech/meta/assets/25372521/f36ca5c0-1dbb-497e-a74c-ea7d6cb04e64)

![Image](https://github.com/sequentech/meta/assets/25372521/30334d70-f136-49bd-ab4d-f6d8b2525fbb)
