### ISSUE TITLE
✨ Admin Portal - Election Event - Tally

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#330]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Admin-portal: Implement Tally UI according to:
- [Admin Portal - Election Event - Tallies- List](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=1046-33423&mode=design&t=rlnbwUCqRe1sphsA-0)
- [Admin Portal - Election Event - Tally - New](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=1078-17859&mode=design&t=rlnbwUCqRe1sphsA-0)
- [Admin Portal - Election Event - Tally - New 2](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=1188-33465&mode=design&t=rlnbwUCqRe1sphsA-0)
- [Admin Portal - Election Event -Tally - New 3](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=1078-19163&mode=design&t=rlnbwUCqRe1sphsA-0)
- [Admin Portal - Election Event -Tally - New 4 Progress](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=1078-19956&mode=design&t=rlnbwUCqRe1sphsA-0)
- [Admin Portal - Election Event - Tally - New 5 Progress](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=1188-32796&mode=design&t=rlnbwUCqRe1sphsA-0)
- [Admin Portal - Election Event - Tally - Results](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=1078-20904&mode=design&t=rlnbwUCqRe1sphsA-0)
- [Admin Portal - Election Event - Tally - Results 2](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=1094-24965&mode=design&t=rlnbwUCqRe1sphsA-0)
- [Admin Portal - Election Event - Tally - Results 3](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=1188-32075&mode=design&t=rlnbwUCqRe1sphsA-0)

### Screens:

![Image](https://github.com/sequentech/meta/assets/164689/8e534e72-052b-4483-80af-7bdb2417638a)

![Image](https://github.com/sequentech/meta/assets/164689/21b4cab8-bd7a-40a2-b7df-2a3baa9c33e4)

![Image](https://github.com/sequentech/meta/assets/164689/3016fa9b-f93a-4544-8c25-5147f190b7ca)

![Image](https://github.com/sequentech/meta/assets/164689/e8a6535d-1935-4b30-bd68-108c0e3a4d3c)

_No response_

### Tasks

```[tasklist]
# Tasks
- [x] fixes to the tally, like pdf gen.
- [x] add roles works.
- [x] add some react-admin translations.
- [x] ignore some boards on trustees with env var.
- [x] add session ids to tally_session_execution.
- [x] Move tally endpoint out of "scheduled events".
- [x] Link tally session to keys ceremony.
- [x] Add session states and its management, including checking private keys.
- [x] Update elections progress on tally session status.
- [x] Add results when the tally is completed.
- [x] Connect backend to `admin-portal`.
- [x] Refactor tally tasks.
- [x] Check the file upload component to avoid central text issue
- [x] Avoid double click in next button in tally ceremony trustee component
- [x] refactor all tally flow
- [x] add a card with message and link to the tally start in trustee as in key ceremony
- [x] add a cancel tally trustee ceremony button with dialog confirmation
- [x] make ui interface dialog like the ones in key ceremony
- [x] make accordion ui like in key ceremoy
- [x] add status of the tally ceremony to progress accordion
- [x] move export button in tally into the results accordion header
- [x] adapt trustee tally ceremony to the new flow
- [x] add threshold control of recovered trustee keys with new session field
- [x] better control of results tabs
- [x] add grey line to results tabs
- [x] add dropdown export button to al levels
- [ ] connect export buttons to BE
- [x] rename areas to "Participation Summary" and "Candidate Results"
- [x] rename turnout to %
- [x] add "Number of votes" row to "Participation Summary"
- [ ] connect "Number of votes" buttons to BE
- [x] add % column to "Participation Summary"
- [ ] connect "Participation Summary" % to BE
- [x] add titles to results tabs with the level label
- [x] review candidate results data origins
- [x] change data names for candidate results and add a new type (Sequent_Backend_Candidate_Extended)
- [x] reformat "no data" values to dash
- [x] add turnout data to results (BE pending)
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/backend-services/pull/149
- [ ] https://github.com/sequentech/backend-services/pull/151
- [ ] https://github.com/sequentech/backend-services/pull/152
- [ ] https://github.com/sequentech/backend-services/pull/158
- [ ] https://github.com/sequentech/backend-services/pull/163
- [ ] https://github.com/sequentech/backend-services/pull/167
- [ ] https://github.com/sequentech/backend-services/pull/174
- [ ] https://github.com/sequentech/backend-services/pull/191
- [ ] https://github.com/sequentech/backend-services/pull/199
- [ ] https://github.com/sequentech/backend-services/pull/201
- [ ] https://github.com/sequentech/backend-services/pull/240
- [ ] https://github.com/sequentech/backend-services/pull/258
```
