### ISSUE TITLE
✨ login page: no redirection if election hasn't started

### ISSUE THREAD

**Issue by ElectricPaperInformationssystemeGmbH** [sequentech/meta#331]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

The voter should not be redirected from the login page if the election hasn't started. Instead, the error massage appears after the login attempt.

### Possible Implementation

```
diff --git a/avElection/public-controller/public-controller.js b/avElection/public-controller/public-controller.js
index 75a2b0f..49b8411 100644
--- a/avElection/public-controller/public-controller.js
+++ b/avElection/public-controller/public-controller.js
@@ -106,18 +106,7 @@ angular
             value.data.payload.state
           ) &&
           $window.location.pathname !== ConfigService.defaultRoute
-        ) {
-          if (
-            !presentation ||
-            !presentation.extra_options ||
-            !presentation.extra_options.disable__public_home
-          ) {
-            $window.location.href = '/election/' + $stateParams.id + '/public/home';
-          } else {
-            window.location.href = ConfigService.defaultRoute;
-          }
-          return;
-        }
+        )
 
         // if we are showing the election home but it is disabled then perform
         // a redirect
@@ -127,12 +116,8 @@ angular
           presentation.extra_options &&
           presentation.extra_options.disable__public_home
         ) {
-          if ("smart-link" === $scope.auth_method) {
-            window.location.href = ConfigService.defaultRoute;
-          } else {
-            $window.location.href = '/election/' + $stateParams.id + '/public/login';
-          }
-          return;
+           $window.location.href = '/election/' + $stateParams.id + '/public/login';
+          return;
         }
```

### Tasks

```[tasklist]
# Tasks
- [x] Implement changes
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/election-portal/pull/226
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/election-portal/pull/225
```
