### ISSUE TITLE
🐞 Fix issue with pdf generation on reports

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#332]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

PDF generation fails sometimes after 20secs.

### Expected Behavior

PDF generation works.

### Steps To Reproduce

Missing.

### Environment

- **OS**: Mac OS X Ventura
- **Web browser**: Google Chrome 112.0.5615.137 (Official Build) (arm64)
- **Sequent Platform Version**: 10.0.0

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [ ] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] PR 1
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```

**Comment by Findeton** [comment]
@KNTH01 this seems to happen only when you run windmill in the codespaces shell. When you either run windmill inside the windmill container or in a local shell it doesn't happen. Please check this and let me know if this is the case, and if so then it's just an inconvenience but nothing more fortunately.

**Comment by edulix** [comment]
Thanks for explanation and exploratory work @Findeton. Let's not continue working on this bug for the moment to concentrate our efforts. We can leave it open to work on it later on.
