### ISSUE TITLE
✨Election Protocol Log: initial implementation

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#334]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Initial implementation of election protocol log

### Possible Implementation

https://github.com/sequentech/backend-services/blob/main/docs/immutable-logs.md#election-protocol-log

### Tasks

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/backend-services/pull/165
- [ ] https://github.com/sequentech/backend-services/pull/225
```
