### ISSUE TITLE
✨ Add Jetbrains/Webstorm support

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#336]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Add support for Jetbrains [as indicated here.]( https://github.com/github/codespaces-jetbrains-feedback/issues/30#issuecomment-1319296516)

### Tasks

```[tasklist]
# Tasks
- [ ] Add config to `devcontainer.json`
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/backend-services/pull/86
```
