### ISSUE TITLE
🛡 Security updates

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#339]
### Tasks

```[tasklist]
# Tasks
- [x] Perform the security updates
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/voting-booth/pull/415
- [ ] https://github.com/sequentech/admin-console/pull/409
- [ ] https://github.com/sequentech/iam/pull/328
- [ ] https://github.com/sequentech/frestq/pull/87
- [ ] https://github.com/sequentech/election-orchestra/pull/83
- [ ] https://github.com/sequentech/release-tool/pull/46
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/voting-booth/pull/414
- [ ] https://github.com/sequentech/admin-console/pull/410
- [ ] https://github.com/sequentech/iam/pull/329
- [ ] https://github.com/sequentech/frestq/pull/88
- [ ] https://github.com/sequentech/election-orchestra/pull/84
- [ ] https://github.com/sequentech/release-tool/pull/47
```
