### ISSUE TITLE
Release 10.1.0

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#340]
### Tasks

```[tasklist]
# Tasks
- [ ] Tag the release
- [ ] Create releases with automatic release notes in github
- [ ] Test the release
- [ ] Deploy release in stable <major>xx deployment
- [ ] Deploy release in demo
- [ ] Deploy release in web-demo
```

**Comment by edulix** [comment]
Duplicate of https://github.com/sequentech/meta/issues/352
