### ISSUE TITLE
✨ Keycloak Custom OTP SPI

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#342]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Keycloak Custom OTP SPI

### Tasks

```[tasklist]
# Tasks
- [x] Create initial keycloak-extensions package
- [x] Deploy it in the keycloak image
- [x] Configure it for usage in realms
- [x] Add support for AWS SNS and email
- [x] Implement RESET OTP Required Action
- [x] Fix recursion in OTP Selector
- [x] constant time compare code
- [x] Implement SmartLink API URL
- [x] ensure user events are logged and available through API
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/96
- [ ] https://github.com/sequentech/backend-services/pull/100
- [ ] https://github.com/sequentech/backend-services/pull/102
```

**Comment by edulix** [comment]
Moved the subtask `sanitize email html body like in https://github.dev/dasniko/keycloak-extensions-demo/blob/b09e1c765999afcc25814f7e96fc7641d7f6b6cf/magiclink/src/main/resources/theme-resources/templates/html/magic-link.ftl and use EmailTemplateProvider like there too` to a new task to do later. It's not a priority because we will be writting this text and compiling it into the docker image, so it's not a security issue. The ticket: https://github.com/sequentech/meta/issues/294
