### ISSUE TITLE
✨ Create `ConditionalAuthenticator` that depends in client or client scope

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#345]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Create `ConditionalAuthenticator` that depends in client or client scope. This will allow to have forms that only are required for specific  clients or client scopes. Required to implement embassy-specific subflows.

Read how to do that in https://github.dev/dasniko/keycloak-extensions-demo/ in the `conditional-authenticators` directory. 

### Tasks

```[tasklist]
# Tasks
- [x] Implement the conditional client authenticator
- [x] Test the ConditionalClientAuthenticator
- [x] Use the ConditionalClientAuthenticator in the electoral process realm and add it to keycloak docker-compose
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/backend-services/pull/106
```
