### ISSUE TITLE
🐞 Fix keycloak

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#350]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

Can't login with keycloak.

### Expected Behavior

I can login.

### Steps To Reproduce

Missing.

### Environment

- **OS**: Mac OS X Ventura
- **Web browser**: Google Chrome 112.0.5615.137 (Official Build) (arm64)
- **Sequent Platform Version**: 10.0.0

### Tasks

```[tasklist]
# Tasks
- [x] Update certs.json and keycloak's import.
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/103
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```
