### ISSUE TITLE
Release 10.1.0

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#352]
### Tasks

```[tasklist]
# Tasks
- [x] Tag the release
- [x] Create releases with automatic release notes in github
- [x] Test the release
- [x] Deploy release in stable <major>xx deployment
- [x] Deploy release in demo
- [ ] Deploy release in web-demo
```
