### ISSUE TITLE
✨ (backend) Add Election Types / Voting Channels

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#353]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Add Election Types / Voting Channels.

_No response_

### Tasks

```[tasklist]
# Tasks
- [x] Add Election Types table
- [x] Add Voting Channels property to tenant table.
- [x] Add kiosk property to election table.
- [x] Add types.
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/backend-services/pull/116
```
