### ISSUE TITLE
✨ Enable uploading public files/documents

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#354]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Enable uploading public files/documents. These can be pdfs or images for example.

### Tasks

```[tasklist]
# Tasks
- [ ] Investigate how to upload to s3
- [ ] Create harvest endpoints to start and finish upload. This will mean creating a new document in the hasura table, create an s3 url to upload the file, then call harvest again to mark the upload as finished.
- [ ] Add document_id links to the documents that contain images for the tenant, candidate etc.
- [ ] Update ballot style and voting portal to include images.
- [ ] Update front-end to enable uploading files.
```

```[tasklist]
# Master PRs
- [ ] PR 1
```
