### ISSUE TITLE
✨ Basic CI for artifact creation & shipping 

### ISSUE THREAD

**Issue by efi-shimon-develeap** [sequentech/meta#358]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

We want to create a pipeline that pushes images to artifact repositories when new code is pushed to the main. 
To do so, we need a few items: 
1. Relevant repositories in ECR should be created using IaC to allow the creation of more repositories as we go
2. Relevant role to push images into ECR 
3. Dockerfile improvements to get them to production-grade.

### Tasks

```[tasklist]
# Tasks
- [x] Create a module for ECR repositories
- [x] Create relevant repositories using IaC
- [x] Create a role for the CI process to push relevant images to ECR
- [x] Create a workflow that builds images on each push to the main branch
- [x] Dockerfiles: update all relevant Dockerfiles to Production grade
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/169
```
