### ISSUE TITLE
✨ Base environment creation

### ISSUE THREAD

**Issue by efi-shimon-develeap** [sequentech/meta#359]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

There is a base environment that is starting point in order for us to start creating relevant services, working with them and hosting them in AWS. This environment consists of: 
1. VPC
2. EKS cluster
  2.1 Ingress controller
  2.2 CSI drivers (EBS, Secret Manager) 
3. LoadBalancer 

Other services may be added in the near future. 

This environment should be created using IaC and deployed via that code as well. 

### Tasks

```[tasklist]
# IAC Tasks
- [x] Create module for VPC (using relevant AWS module)
- [x] Create module for EKS  (using relevant AWS module)
- [x] Add ingress controller deployment
- [x] Add relevant CSI drivers
- [ ] * If needed add external-dns deployment
```

```[tasklist]
# Terragrunt
- [x] Create terragrunt configuration for the environment
- [x] Deploy using terragrunt
```

# Main Pull Request
[feat/meta-359/main](https://github.com/sequentech/gitops/pull/1)
