### ISSUE TITLE
✨ Global services Creation & Deployment

### ISSUE THREAD

**Issue by efi-shimon-develeap** [sequentech/meta#361]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

We want to create deployment for services (RDS, Aurora, RabbitMQ etc..) which are part of multiple services. 

### Tasks

```[tasklist]
# IaC
- [x] Create a module for Aurora setup
- [x] Create a module for RabbitMQ setup
- [x] Create a module for SES Setup
- [x] Create module for SNS setup
```

```[tasklist]
# Deployments
- [x] Deploy relevant module to the environment
```
