### ISSUE TITLE
✨  Hashicorp vault 

### ISSUE THREAD

**Issue by efi-shimon-develeap** [sequentech/meta#362]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Using the relevant helm chart, we want to deploy the Hashicorp vault to the cluster. 
For the task, we might need  a few additional items. 

### Tasks

```[tasklist]
# Tasks
- [ ] Get relevant helm chart
- [ ] Check requirements for AWS (if we need IAM role etc) 
- [ ] Create deployment for the environment (values file for phase1)
```

**Comment by edulix** [comment]
@efi-shimon-develeap we should remove this right?
