### ISSUE TITLE
✨ Frontend deployment

### ISSUE THREAD

**Issue by efi-shimon-develeap** [sequentech/meta#363]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

We need to create a deployment for the frontend application, when starting the task and looking at the frontend deployment, we should decide if the deployment is in Kubernetes or in Cloudfront. 

### Tasks

```[tasklist]
# Tasks
- [x] Review frontend application
- [x] Check for all the relevant paths to configure
- [x] If going with helm create chart
- [ ] Get all relevant params from the developer and add them to the chart
- [x] Handle static & global configuration file changes
- [x] create domain url in cloudfront
- [x] Solve CORS issue
- [ ] Add CORS configuration to helm chart
- [ ] Add the ability to pass custom headers in the chart
```

```[tasklist]
### Main PRs
- [ ] https://github.com/sequentech/infrastructure/pull/7
```
