### ISSUE TITLE
✨ Harvest deployment 

### ISSUE THREAD

**Issue by efi-shimon-develeap** [sequentech/meta#364]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

 For each service we are deploying there are two parts: 
  1. IaC:
    - If a service needs access to aws resources we need AWS role with OIDC to allow access to the relevant service.
    - Some of the services have their own AWS resources (S3, RDS, etc..), this should be a part of the service module. 
  2. Helm Chart: 
  - each service has it's own helm chart, need to create and configure the charts.
  - Params, access to environment and relevant variables should be discussed with dev & taken from docker-compose
  - Services that need access from the environment should be configured (ingress)
  3. Probe configuration: 
    - Each service should have readiness and liveness probes, for each service should discuss with dev team so they will create /health and /readiness paths 
  4. Documentation: 
    - IaC should be documented via terraform-docs
    - Charts should be documented via helm-docs
  5. Initialization: 
     - For each of the services we might need to run an initialization in one form or another:
       - init container - when we need to run on each pod start
       - init job - when we need to run once on the deployment startup 
     - Should discuss how each application starts at the moment and see what is relevant at the moment

### Tasks

```[tasklist]
# IaC
- [ ] Create a module with IAM role with relevant permissions for the application 
```

```[tasklist]
# Helm
- [x] Create helm chart for the application
- [x] Configure access for the application
- [ ] Discuss with developers the liveness and readiness probes
- [x] Configure service & ingress if needed
- [ ] Configure secret params
```

```[tasklist]
# Deployment
- [x] Deploy the relevant resources to environment
- [x] Fix issue with LibSSL
- [ ] Check connection to s3 (with IRSA)
- [ ] Integration with relevant applications
```
