### ISSUE TITLE
✨ ImmuDB deployment

### ISSUE THREAD

**Issue by efi-shimon-develeap** [sequentech/meta#365]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

ImmuDB deployment to Kubernetes
-- 

General guidelines: 

 For each service we are deploying there are two parts: 
  1. IaC:
    - If a service needs access to aws resources we need AWS role with OIDC to allow access to the relevant service.
    - Some of the services have their own AWS resources (S3, RDS, etc..), this should be a part of the service module. 
  2. Helm Chart: 
  - each service has it's own helm chart, need to create and configure the charts.
  - Params, access to environment and relevant variables should be discussed with dev & taken from docker-compose
  - Services that need access from the environment should be configured (ingress)
  3. Probe configuration: 
    - Each service should have readiness and liveness probes, for each service should discuss with dev team so they will create /health and /readiness paths 
  4. Documentation: 
    - IaC should be documented via terraform-docs
    - Charts should be documented via helm-docs
  5. Initialization: 
     - For each of the services we might need to run an initialization in one form or another:
       - init container - when we need to run on each pod start
       - init job - when we need to run once on the deployment startup 
     - Should discuss how each application starts at the moment and see what is relevant at the moment

In addition: 
we need to create an s3 backend and relevant role for access

### Tasks

```[tasklist]
# IaC
- [x] Create IAM role with OIDC to allow the application pods to work with the backend
```

```[tasklist]
# Helm
- [x] Create helm chart or use existing for deployment
- [x] Configure chart to use the relevant backend ( values /
- [x] Configure chart to use the IAM role created in the IaC
- [x] Create init job to configure immudb backend
```

```[tasklist]
# Deployment
- [x] Create relevant deployment files & deploy to environment (gitops repo) terragrunt.hcl
- [ ] Check S3 access for immudb (need to test IRSA with immudb
```
