### ISSUE TITLE
✨ KeyCloak deployment 

### ISSUE THREAD

**Issue by efi-shimon-develeap** [sequentech/meta#366]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

We need to create deployment (Both IaC and Kubernetes) for KeyCloak. 
--
General guidelines: 

 For each service we are deploying there are two parts: 
  1. IaC:
    - If a service needs access to aws resources we need AWS role with OIDC to allow access to the relevant service.
    - Some of the services have their own AWS resources (S3, RDS, etc..), this should be a part of the service module. 
  2. Helm Chart: 
  - each service has it's own helm chart, need to create and configure the charts.
  - Params, access to environment and relevant variables should be discussed with dev & taken from docker-compose
  - Services that need access from the environment should be configured (ingress)
  3. Probe configuration: 
    - Each service should have readiness and liveness probes, for each service should discuss with dev team so they will create /health and /readiness paths 
  4. Documentation: 
    - IaC should be documented via terraform-docs
    - Charts should be documented via helm-docs
  5. Initialization: 
     - For each of the services we might need to run an initialization in one form or another:
       - init container - when we need to run on each pod start
       - init job - when we need to run once on the deployment startup 
     - Should discuss how each application starts at the moment and see what is relevant at the moment

Additional resources: 
- Aurora (Postgresql) 
- IAM role
- Secret (Secret manager) 

### Tasks

```[tasklist]
# IaC
- [x] Create a module for Aurora deployment
- [x] Conifgure cloudflare
```

```[tasklist]
# Helm & Deployment
- [x] Configure official helm chart for our use
- [x] Create deployment for Kubernetes
- [x] Deploy to cluster
- [x] create domain url in cloudfront
- [x] fork keycloak chart due to bug in the chart and fix it locally (templating issues)
- [x] add domain param for keycloak
- [x] Fix an issue with SSL
- [x] Fix access issue to admin portal
- [x] Add missing parameters to helm chart
- [x] Configure work with AWS SES & AWS SNS
- [x] Fix an issue where keycloak was loading slowly
- [x] Add default tenents to the environment
- [x] Solve CORS issue when connecting from frontend apps
- [x] Add CORS configuration to helm chart
- [ ] Think of a better way to add default tenents to the environment
- [ ] Check for an improved auth on master real
- [ ] Check how to change master realm configuration
- [x] Add headers to helm chart
- [ ] Review log-audit and add relevant functionality if missing
```
