### ISSUE TITLE
✨ Windmill deployment 

### ISSUE THREAD

**Issue by efi-shimon-develeap** [sequentech/meta#367]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

General guidelines for windmill deployment 

 For each service we are deploying, there are two parts: 
  1. IaC:
    - If a service needs access to aws resources, we need an AWS role with OIDC to allow access to the relevant service.
    - Some services have their own AWS resources (S3, RDS, etc.), which should be a part of the service module. 
  2. Helm Chart: 
  - each service has its helm chart and we need to create and configure the charts.
  - Params, access to the environment, and relevant variables should be discussed with the dev & taken from docker-compose
  - Services that need access from the environment should be configured (ingress)
  3. Probe configuration: 
    - Each service should have readiness and liveness probes, and each service should discuss with the dev team so they will create /health and /readiness paths 
  4. Documentation: 
    - IaC should be documented via terraform-docs
    - Charts should be documented via helm-docs
  5. Initialization: 
     - For each of the services, we might need to run an initialization in one form or another:
       - init container - when we need to run on each pod, start
       - init job - when we need to run once on the deployment startup 
     - Should discuss how each application starts at the moment and see what is relevant at the moment

Additional resources: 
- Secret for Aurora 
- Access to RabbitMQ
- Access to ImmuDB 
- Access to Vault

### Tasks

```[tasklist]
# IaC
- [x] Need to create IAM role with access to relevant services
- [x] Need to consider where to create secret (Secret manager) for access to Aurora & RabbitMQ
```

```[tasklist]
# Helm Chart
- [x] Create a relevant helm chart
- [x] Create a secret for connection to Aurora
- [ ] Create a secret for connection to RabbitMQ
- [x] Create a secret for connection to ImmuDB
- [ ] Create a secret for connection to Vault
- [x] Discuss with developers Init process
- [x] Discuss with developers the readiness & liveness probes
```

```[tasklist]
# Deployment
- [x] Create deployment files & deploy to relevant environment
- [x] Fix issue with LibSSL
- [x] Deploy RabbitMQ to the environment to work with until amqps is checked
- [ ] Check if the service can work with rabbit securly
- [x] Configure access to Rabbit
- [ ] Test integration
```

```[tasklist]
### Main PRs
- [ ] https://github.com/sequentech/infrastructure/pull/9
```
