### ISSUE TITLE
✨ Trustee deployment 

### ISSUE THREAD

**Issue by efi-shimon-develeap** [sequentech/meta#368]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

General guidelines for the deployment of the Trustee 
-- 
   For each service we are deploying, there are two parts:
  1. IaC:
	- If a service needs access to aws resources, we need an AWS role with OIDC to allow access to the relevant service.
	- Some services have their own AWS resources (S3, RDS, etc.), which should be a part of the service module.
  2. Helm Chart:
  - each service has its helm chart and we need to create and configure the charts.
  - Params, access to the environment, and relevant variables should be discussed with the dev & taken from docker-compose
  - Services that need access from the environment should be configured (ingress)
  3. Probe configuration:
	- Each service should have readiness and liveness probes, and each service should discuss with the dev team so they will create /health and /readiness paths
  4. Documentation:
	- IaC should be documented via terraform-docs
	- Charts should be documented via helm-docs
  5. Initialization:
 	- For each of the services, we might need to run an initialization in one form or another:
   	- init container - when we need to run on each pod, start
   	- init job - when we need to run once on the deployment startup
 	- Should discuss how each application starts at the moment and see what is relevant at the moment

Additional items: 
- Size of nodes
- Node affinity roles 
- Access to ImmuDB (secret)
- Access to Valut (Secret) 

### Tasks

```[tasklist]
# IaC
- [x] Create node group for the cluster that can hold the Trustee (Bigger machine) / not sure that this is needed.
```

```[tasklist]
# Helm
- [x] Create a helm chart for the application
- [x] Create/configure access to ImmuDB
```

```[tasklist]
# Deployment
- [x] Create relevant Deployment for the environment
```
