### ISSUE TITLE
✨ Hassura deployment 

### ISSUE THREAD

**Issue by efi-shimon-develeap** [sequentech/meta#369]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Base guidelines 
--

For each service we are deploying, there are two parts:
  1. IaC:
	- If a service needs access to aws resources, we need an AWS role with OIDC to allow access to the relevant service.
	- Some services have their own AWS resources (S3, RDS, etc.), which should be a part of the service module.
  2. Helm Chart:
  - each service has its helm chart and we need to create and configure the charts.
  - Params, access to the environment, and relevant variables should be discussed with the dev & taken from docker-compose
  - Services that need access from the environment should be configured (ingress)
  3. Probe configuration:
	- Each service should have readiness and liveness probes, and each service should discuss with the dev team so they will create /health and /readiness paths
  4. Documentation:
	- IaC should be documented via terraform-docs
	- Charts should be documented via helm-docs
  5. Initialization:
 	- For each of the services, we might need to run an initialization in one form or another:
   	- init container - when we need to run on each pod, start
   	- init job - when we need to run once on the deployment startup
 	- Should discuss how each application starts at the moment and see what is relevant at the moment

### Tasks

```[tasklist]
# IaC
- [ ] create IAM role for relevant access 
- [ ] Secret for aurora access
```

```[tasklist]
# Helm
- [ ] Create helm chart with relevant params
- [ ] Configure access to Aurora (secret) 
- [ ] Configure node access

```

```[tasklist]
# Discussions
- [ ] Talk with Eduardo regarding connections and which app should know where to access.
```

```[tasklist]
# Deployments
- [ ] Configure deployment to kubernetes (helm values etc) 
```
