### ISSUE TITLE
✨ Observability: ELK stack deployment

### ISSUE THREAD

**Issue by efi-shimon-develeap** [sequentech/meta#370]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

We want to deploy ELK stack for logging purposes (OpenSearch), need to deploy scraping (LogStash) into Kubernetes and configure what we are scraping

### Tasks

```[tasklist]
# IaC
- [ ] Create OpenSearch module 
- [ ] Discuss needs when relevant
- [ ] Configure retention & backup 
- [ ] Logstash: Create IAM role for relevant access 

```

```[tasklist]
# Helm
- [ ] Create logstash chart 
- [ ] Configure scraping 
- [ ] Shipping configuration 
- [ ] Logstash volume configuration 
```

```[tasklist]
# Deployment
- [ ] Deploy OpenSearch to the environment using terragrunt
- [ ] Deploy Logstash helm chart
```

**Comment by edulix** [comment]
We decided to go with Grafana & Loki. ELK was big overhead and didn't fit the needs.
