### ISSUE TITLE
✨ Observability: Prometheus stack deployment

### ISSUE THREAD

**Issue by efi-shimon-develeap** [sequentech/meta#371]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

For monitoring porpuses and for scaling we need to store matrics for the Kubernetes cluster 
We will use the Prometheus stack (Grafana, Prometheus,node-exporter, etc). 
To do so we will use the Prometheus-community-stack. 

### Tasks

```[tasklist]
# IaC
- [ ] Check what permissions needed for Prometheus stack & create relevant IAM roles (grafana, Prometheus) 
```

```[tasklist]
# Dashboards
- [ ] Review which dashboards are relevant, create and host them in order to add to grafana when deploying 
```

```[tasklist]
# Helm
- [ ] Investigate which community chart is relevant
- [ ] Configure values for prometheus 
- [ ] Configure retention policies 
- [ ] Configure access & where to store data 
```

```[tasklist]
# IaC
- [ ] Check what permissions needed for Prometheus stack & create relevant IAM roles (grafana, Prometheus) 
```

```[tasklist]
# Deployment
- [ ] Create deployment files and instructions
```

**Comment by edulix** [comment]
This is already done
