### ISSUE TITLE
✨ Observability: Wazuh deployment

### ISSUE THREAD

**Issue by efi-shimon-develeap** [sequentech/meta#372]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

We want to deploy Wazuh to our environment 
*  Wazuh - The Open Source Security Platform. Unified XDR and SIEM protection for endpoints and cloud workloads. 

### Tasks

```[tasklist]
# Research 
- [ ] Learn about Wazuh, best practices and how to properly deploy
```

```[tasklist]
# IaC
- [ ] TBD (Need to understand what is needed here after research) 
```

```[tasklist]
# Kubernetes
- [ ] TBD (Need to understand what is needed here after research) 
```
