### ISSUE TITLE
✨ Scaling configuration

### ISSUE THREAD

**Issue by efi-shimon-develeap** [sequentech/meta#373]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

In this task, we need to create and deploy scaling for the application. This is split into two categories: 
1. scaling application (i.e. cluster-autoscaler) 
2. Scaling configuration (how our applications are scaled) 
* if HPA won't be enough we should consider using Keda as the horizontal scaling app. 
In the first phase, we will create and deploy cluster autoscaler to the environment. 
In the second, we will discuss each application's scaling configuration and update the relevant charts/deployments to fit the bill. 

### Tasks

```[tasklist]
# Scaling configuration
- [ ] Scaling configuration for Harvest
-  [ ] Scaling configuration for KeyCloak
-  [ ] Scaling configuration for Windmill
-  [ ] Scaling configuration for Hasura
```

```[tasklist]
# IaC
- [ ] Create module for cluster-autoscaler
- [ ] Configure IAM for cluster-autoscaler permissions 
- [ ] Module should hold Kubernetes resources for the service
```

```[tasklist]
# Deployment 
- [ ] Create terragrunt configuration for the cluster autoscaler 
- [ ] Deply cluster autoscaler to the environment 
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/gitops/pull/6
```
