### ISSUE TITLE
✨ Backup configuration 

### ISSUE THREAD

**Issue by efi-shimon-develeap** [sequentech/meta#374]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

We work with different databases, and each of them should have its own backup. 
1. ImmuDB (s3) 
2. Aurora (2 different databases) 
3. If needed - EBS volumes 

- When writing the application itself, we should take into consideration the backup mechanism to allow the process to go well. 
- We should Test restore process to see the mechanism works as intended 

### Tasks

```[tasklist]
# Backup process
- [ ] Create backup schedule (snapshots) for Aurora DBS
- [ ] Create backups for ImmuDB
```

```[tasklist]
# Restore process
- [ ] Validate restoration of Aurora DBS, see if this process should be automated, see if needed to be added to IaC
- [ ] Validate restoration of ImmuDB s3 backend & What is needed on the application side to work as intended (restart etc)
```

**Comment by edulix** [comment]
Done in this other ticket https://github.com/sequentech/meta/issues/493
