### ISSUE TITLE
Failover configuration / DRP

### ISSUE THREAD

**Issue by efi-shimon-develeap** [sequentech/meta#375]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Failover configuration should consist of an environment in another region, database configuration, etc. 
In this task, we should define each of the items that should be noted for the DRP and create a semi-automatic restoration 
A few of the items that should be noted are: 

- traffic management 
- database sync
- s3 replication
- vault secrets

### Tasks

```[tasklist]
# Environment creation
- [ ] Brinup for environment in a different region
```

```[tasklist]
# Data
- [ ] Work with Aurora multi-region to enable replication between two relevant regions
- [ ] Create S3 replication between multiple regions 

```

```[tasklist]
# Traffic 
- [ ] Investigate what traffic configurations should be inline to allow migration between the two environments 
```

```[tasklist]
# Secret management
- [ ] Investigate how to set/move vault secrets to the new environment and write the 'how to' 
```
