### ISSUE TITLE
✨ AWS VPN module & configuration

### ISSUE THREAD

**Issue by efi-shimon-develeap** [sequentech/meta#376]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Need to create a module for aws VPN to allow connection from specific addresses. 

### Tasks

```[tasklist]
# IaC
- [ ] Create module for AWS VPN creation and connection
```

```[tasklist]
# Deployment
- [ ] Deploy test for multiple VPN instances (https://docs.aws.amazon.com/vpn/latest/s2svpn/Examples.html) 
```

```[tasklist]
# Terragrunt
- [ ] Create terragrunt template to allow fast deployment 
```
