### ISSUE TITLE
✨ Convert all inserts/updates into harvest-managed mutations for added security

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#378]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Convert all inserts/updates into harvest-managed mutations for added security.

- For each harvest endpoint: 
  - Ensure user token allows him to perform the action
  - Verify input data format conforms to spec, including json fields
  - Validate text/html input with sanitize function
  - Add the endpoint to hasura with appropriate permissions and remove permissions to previous endpoint 
  - Use the endpoint in the UI

### Tasks

```[tasklist]
# Tasks
- [ ] Add tenant
- [ ] Edit tenant
- [ ] Add Election Event
- [ ] Edit Election Event
```

```[tasklist]
# Main PRs
- [ ] PR 1
```
