### ISSUE TITLE
✨ Implement areas for voting portal and Improve automation

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#379]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Implement areas for voting portal and Improve automation

### Tasks

```[tasklist]
# Tasks
- [ ] Endpoint to edit user areas.
- [ ] Automation, add beat.
- [x] yarn && yarn build:ui-essentials on init.
- [x] admin and voting portal containers.
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/backend-services/pull/138
- [ ] https://github.com/sequentech/backend-services/pull/140
- [ ] https://github.com/sequentech/backend-services/pull/142
```
