### ISSUE TITLE
🐞 Codespace docker fixes

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#385]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

There are issues building a new codespace.

### Expected Behavior

Building a new codespace is fast enough.

### Environment

- **OS**: Mac OS X Ventura
- **Web browser**: Google Chrome 112.0.5615.137 (Official Build) (arm64)
- **Sequent Platform Version**: 10.0.0

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [x] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/144
- [ ] https://github.com/sequentech/backend-services/pull/147
```

**Comment by edulix** [comment]
Reopening this issue, for some reason trustee1 is being rebuild and launched when running the docker compose.
