### ISSUE TITLE
Create minor releases

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#39]
Create minor releases that includes latest security updates.

# Tasks

- [x] Test that master-slave deployment and documentation (including [promotion from slave to master](https://sequentech.github.io/documentation/docs/general/guides/deployment/#promoting-a-slave-to-be-master)) works.
- [x] Check non-breaking changes from master are included on 7.1.x branch
- [x] Test 7.1.x and 6.1.x branches in a deployment.
- [x] 7.x
- [x] 6.x

Master dependencies PRs:

- https://github.com/sequentech/ballot-box/pull/142
- https://github.com/sequentech/ballot-box/pull/145
- https://github.com/sequentech/documentation/pull/96
- https://github.com/sequentech/deployment-tool/pull/311

6.1x dependencies PRs:

- https://github.com/sequentech/ballot-box/pull/143
- https://github.com/sequentech/ballot-box/pull/146
- https://github.com/sequentech/deployment-tool/pull/313

7.1.x dependencies PRs:

- https://github.com/sequentech/ballot-box/pull/144
- https://github.com/sequentech/deployment-tool/pull/312
- https://github.com/sequentech/release-tool/pull/26
