### ISSUE TITLE
🐞 Fix codespace creation

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#391]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

Codespace creation seems to be broken.

![image](https://github.com/sequentech/meta/assets/81968/682e946c-8bf8-4118-b09b-c1f6ccf1cbbb)

### Expected Behavior

Codespace creation should work.

### Steps To Reproduce

-

### Environment

-

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [x] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/159
- [ ] https://github.com/sequentech/backend-services/pull/160
- [ ] https://github.com/sequentech/backend-services/pull/161
```
