### ISSUE TITLE
✨ Prepare for pentesting / Add permissions to hasura/admin-portal

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#395]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

All endpoints need to be correctly permissioned. Also in the admin portal buttons and sections should only be shown if the user has the right permissions. Also add password management and activate/deactivate users. This is a continuation of https://github.com/sequentech/meta/issues/335

### Tasks

```[tasklist]
# Tasks
- [x] Add permissions to `hasura` endpoints.
- [ ] Hide sections/buttons depending on permissions on `admin-portal`.
- [x] Add more perms (trustee, candidate/election).
- [x] Add trustees section back to settings.
- [x] Fix language settings in admin-portal. 
- [x] Fix editing election types.
- [x] Remove some unused "scheduled tasks".
```

https://github.com/sequentech/backend-services/pull/372

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/backend-services/pull/372
- [ ] https://github.com/sequentech/backend-services/pull/379
```
