### ISSUE TITLE
✨ Trustee Portal - Key Ceremony

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#398]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Admin-portal: Implement Trustee Keys Ceremony according to figma.

### Tasks

```[tasklist]
# Tasks
- [x] [Trustee Portal - Election Event Configuration - Trustees - Keys Ceremony List](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=1903-24221&mode=design&t=E4qWmqmfspYZhEfo-0)
- [x] [Trustee Portal - Election Event Configuration - Keys Ceremony](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=1903-24652&mode=design&t=E4qWmqmfspYZhEfo-0)
- [x] [Trustee Portal - Election Event Configuration - Key Ceremony Execution](https://www.figma.com/file/sz20ekZ01a8OntNnnw00GQ/Admin-Portal?type=design&node-id=1903-25160&mode=design&t=E4qWmqmfspYZhEfo-0)
- [x] UI: Ensure currentCeremony gets updated frequently.
- [x] UI: Make the `<DropFile />` widget in the `CheckStep` work correctly, especially with drag&drop and when trying multiple times
- [x] UI: Move the `StatusStep` from the `TrusteeWizard` to its own Action View clickable in the `EditElectionEventKeys.tsx` actions per ceremony. WHATS DONE: have status step at the end with it's status controlled by the status of the cenemony. Action sends tally user directly to status screen.
- [x] UI: When logging as `trustee1`, the first election event available if any is selected - but no tab is selected, showing an empty selection. `Keys` tab should be shown (not really, it should be more generic: show the first available tab)
- [x] UI: Ensure the Table HEaders in `EditElectionEventKeys.tsx` have all spanish translations.
- [x] UI: Fix the top info notification for trustee that they have a ceremony to participate to incluso a link to the TrusteeCeremony action.
- [x] UI: Use the same `<TopToolbar>` style as in other places, including being able to change the columns and filter in `EditElectionEventKeys.tsx`
- [x] Backend: ensure that `/get-private-key` and `/check-private-key` updates correctly the `status` and `execution_status` of the `keys_ceremony`
- [ ] Backend: add logs when executing actions
```

## Screenshots

List of keys, trustee view:

<img width="1437" alt="image" src="https://github.com/sequentech/meta/assets/81968/d1f2be43-e37b-41b4-bbcc-04f830836839">

Status view of the key ceremony for a trustee:

<img width="1437" alt="image" src="https://github.com/sequentech/meta/assets/81968/3ef1684b-a62c-4db2-855b-16992163b7b1">

Same view when still waiting for keys to be generated:

<img width="1437" alt="image" src="https://github.com/sequentech/meta/assets/81968/52fb00b2-a780-4af2-9fad-942acac45a82">

When next is clicked, it goes to the start screen:

<img width="1437" alt="image" src="https://github.com/sequentech/meta/assets/81968/ed60b1d0-e8b7-425a-95a3-3b555e9fa679">

When clicking next, then the Download Encrypted Private Key screen is showed:

<img width="1437" alt="image" src="https://github.com/sequentech/meta/assets/81968/1ceeb5ec-d5db-4794-a4ba-1ba672dce5ab">

If Download button is clicked, it tries to download the encrypted private key, and showing a loading animated icon meanwhile:

<img width="1437" alt="image" src="https://github.com/sequentech/meta/assets/81968/29e376fa-0053-4b2c-b34c-5d67e93fd34d">

If there's an error downloading, it shows it below the button:

<img width="1437" alt="image" src="https://github.com/sequentech/meta/assets/81968/ab384979-42bc-46c3-bc14-026ac18b4718">

Once downloaded, it activates the Next button in the toolbar below:

<img width="1437" alt="image" src="https://github.com/sequentech/meta/assets/81968/8bdabc60-7c3f-48d4-8897-509a053664dc">

When the Next button is clicked, a Dialog asking the user to backup the private key appears:

<img width="1437" alt="image" src="https://github.com/sequentech/meta/assets/81968/42723512-fe94-4895-ac75-dad538ff1850">

Only once the user checks that he has performed at least two backups he can click to Continue:

<img width="1437" alt="image" src="https://github.com/sequentech/meta/assets/81968/2b24849c-db13-4eec-8a18-3f41098da6a8">

Then the Check your backup screen appears:

<img width="1437" alt="image" src="https://github.com/sequentech/meta/assets/81968/d7c7eba4-7955-4715-b770-ecb286e66110">

And if the file checked checks out, it enables the next step button and shows a success text:

<img width="1437" alt="image" src="https://github.com/sequentech/meta/assets/81968/5e0c7850-3b87-42df-9a66-e7690a678bf5">

Finally bringing on the finished screen:

<img width="1437" alt="image" src="https://github.com/sequentech/meta/assets/81968/502efa1c-f826-47b1-9a79-b399a44453e6">

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/171
- [ ] https://github.com/sequentech/backend-services/pull/175
- [ ] https://github.com/sequentech/backend-services/pull/181
- [ ] https://github.com/sequentech/backend-services/pull/183
```

**Comment by edulix** [comment]
Moving missing task to https://github.com/sequentech/meta/issues/409
