### ISSUE TITLE
✨ Integrate Ballot Verifier in Voting Portal

### ISSUE THREAD

**Issue by KNTH01** [sequentech/meta#403]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

-

### Tasks

```[tasklist]
# Tasks
- [x] Remove test-app
- [x] Unify npm scripts
- [x] setup a global-settings.ts in voting portal
- [x] Audit ballot in the voting portal is linked to the ballot verifier
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/backend-services/pull/180
```

### Additional context

The Audit Ballot screen has been updated so the user can be redirected to the ballot verifier app:
![image](https://github.com/sequentech/meta/assets/1632391/b63e753a-a287-4077-926a-c625da255ca8)
