### ISSUE TITLE
🐞 Fix Verifier, autogenerate example

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#406]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Autogenerate example for ballot-verifier.

### Tasks

```[tasklist]
# Tasks
- [ ] Update default public key.
- [ ] Auto-generate  example for ballot-verifier.
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/backend-services/pull/185
```
