### ISSUE TITLE
✨ Add authentication in ballot verifier

### ISSUE THREAD

**Issue by KNTH01** [sequentech/meta#407]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Screens

![Image](https://github.com/sequentech/meta/assets/164689/bd694ffd-9c64-409a-9462-7c57cb4e9d3e)

![Image](https://github.com/sequentech/meta/assets/164689/b7add2cf-2c9f-48bc-9043-6d7c3214473d)

![Image](https://github.com/sequentech/meta/assets/164689/8fab1bc2-20a5-4a8c-9143-ceeb814d7a76)

![Image](https://github.com/sequentech/meta/assets/164689/d7425560-58eb-472a-ada3-5d4a16729e03)

![Image](https://github.com/sequentech/meta/assets/164689/ea702a40-feae-4039-adfd-fef566a6e576)

![Image](https://github.com/sequentech/meta/assets/164689/0a097eee-b9fa-438c-967e-099ba231b6f8)

![Image](https://github.com/sequentech/meta/assets/164689/0adfced7-b036-4ae8-8571-0b3a3d1bf3e7)

### Tasks

```[tasklist]
# Tasks
- [ ] Add authentication in ballot verifier
- [ ] Review the authentication in voting-portal (logout, initialization with tenantId and electionEventId)
- [ ] Remove backend-services/packages/voting-portal/src/Config.tsx
- [x] add auth providers
- [x] add login screen
- [x] and login routes to app
- [x] change routes in screens
- [x] add 404 screen
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/backend-services/pull/249
```
