### ISSUE TITLE
✨ Update Velvet input election config and ballot styles

### ISSUE THREAD

**Issue by KNTH01** [sequentech/meta#408]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

- 

### Tasks

```[tasklist]
# Tasks
- [x] Aggregate ballot styles (contest_id, area_id) and push this list into the election config
- [x] Handle multiple ballot styles
- [x] Handle errors and no unwrap
- [x] Differentiate between explicit invalid and implicit invalid and count them correctly
- [x] Update Election Config with its configuration instead of using a single Ballot Style
- [x] Test with multiple contests and areas
- [x] Handle invalid ballots
- [x] Handle  0 votes
- [x] Handle  blank votes
- [x] Count voters by area then count up the total of ellegible voters
```

```[tasklist]
### Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/215
```

- Generate HTML, PDF, and JSON output:

![Image](https://github.com/sequentech/meta/assets/1632391/73955ae7-6d47-4a5c-a24f-f830e76e7e7a)

- Add census:

![Image](https://github.com/sequentech/meta/assets/1632391/30305011-3900-4174-af7e-a954bc57bde0)
