### ISSUE TITLE
✨ Admin Portal - Logs

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#409]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Backend: add logs when executing actions

### Screenshots

Main logs:
<img width="1439" alt="image" src="https://github.com/sequentech/meta/assets/81968/973cd8c4-f220-41e6-ae49-96f267399658">

Election Event logs:
<img width="1439" alt="image" src="https://github.com/sequentech/meta/assets/81968/47193afe-3f63-4315-9db2-98e94e3eb591">

### Tasks

```[tasklist]
# Tasks
- [x] Backend: Provide acces to pgaudit logs
- [x] Backend harvest: Add support for filtering in the pgaudit table
- [x] Backend harvest: mitigate sql inyection
- [x] Frontend: enable view of pgaudit logs
- [x] Backend: logs for keycloak
- [x] Frontend: logs for keycloak
- [x] Backend: implement logs for Election Event
- [x] Backend: configure access to election event logs
- [x] Frontend: logs for Election Event
- [x] Frontend: logs for Election Event: filtering
- [x] Backend: fix timestamps
- [x] Backend: add missing log items
- [x] Backend: convert base64-encoded columns to json or text
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/221
- [ ] https://github.com/sequentech/backend-services/pull/238
- [ ] https://github.com/sequentech/backend-services/pull/239
```

**Comment by edulix** [comment]
Moving missing parts to https://github.com/sequentech/meta/issues/451
