### ISSUE TITLE
✨ Admin Portal - Tally Ceremony Backend 

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#412]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Backend fixes to tally ceremony, related to https://github.com/sequentech/meta/issues/330

### Tasks

```[tasklist]
# Tasks
- [x] Add published field to event status and update admin Dashboard with status.
- [x] Add threshold to tally session table.
- [x] Remove NOT_STARTED from tally execution status.
- [x] Check theshold is met before starting tally.
- [x] Add tracing to velvet.
- [x] set success state to tally session on success, update election event state to tally ceremony finished true.
- [x] Only Add results when tally in progres when the tally for an election is completed
- [x] Add logs.
- [x] Add voting progress.
- [x] Manage CANCELLED state.
- [x] Add logs for keys ceremony and ceremony trustee steps.
- [x] Add logs widget.
- [x] Logs widget should show the bottom unless there's scrolling.
- [x] The max/min progress should be forced to 0/100%.
- [x] Fix sequent-core: remove Cargo.lock from gitigore, add `tokio-postgres` as optional dependency.
- [x] Update sequent-core npm package.
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/backend-services/pull/203
- [ ] https://github.com/sequentech/backend-services/pull/208
- [ ] https://github.com/sequentech/backend-services/pull/217
- [ ] https://github.com/sequentech/backend-services/pull/222
```
