### ISSUE TITLE
✨   Liveness/readiness probes for backends

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#414]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Add liveness/readiness probes.

### Tasks

```[tasklist]
# Tasks
- [ ] Liveness checks the service is working fine. Readiness checks it's available for accepting requests, for example checking the database connection.
- [ ] Implement readyness for:
- [ ] Harvest
- [ ] Windmill
- [ ] Beat
- [ ] Trustees
- [ ] Immudb databases
```

```[tasklist]
# Master PRs
- [ ] PR 1
```
