### ISSUE TITLE
✨ Frontend production builds

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#416]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Frontend production builds

### Tasks

```[tasklist]
# Tasks
- [x] Add admin-portal production config.
- [ ] Add voting-portal production config.
- [ ] Add ballot-verifier production config.
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/backend-services/pull/204
```
