### ISSUE TITLE
🐞 Remove tailwind from admin-portal

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#418]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

Remove tailwind from admin-portal

### Expected Behavior

No tailwind usage

### Steps To Reproduce

-

### Environment

-

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [ ] Remove tailwind from admin-portal
- [ ] Remove related webpack/package.json packages.
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/503
```

# ScreenShots
![Image](https://github.com/sequentech/meta/assets/33923561/13785aae-7b37-44a6-ad90-8291155c9e67)

**Comment by edulix** [comment]
@omri81 The PR is missing from this ticket! :-)
