### ISSUE TITLE
✨ Windmill/etc: Integrate with AWS Secret Manager as an alternative to Vault

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#419]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

 Windmill/etc: Integrate with Secret Manager as an alternative to Vault. We should still be able to use minio in Devcontainer, but have support for configuring AWS secret manager as an alternative secret manager backend.

### Tasks

```[tasklist]
# Tasks
- [x] Implement AWS Secret Manager
- [x] Add support for setting AWS Secret Manager key prefixes
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/286
- [ ] https://github.com/sequentech/backend-services/pull/292
```
