### ISSUE TITLE
✨ Github actions to test PRs

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#424]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Create github actions to test PRs.

### Tasks

```[tasklist]
# Tasks
- [x] Docker builds (no push).
- [x] Run tests on rust projects.
- [x] All actions should run in parallel.
- [x] Add linting action.
- [x] Remove some dead rust code in ballot-verifier.
- [x] Lint/prettify all packages. 
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/backend-services/pull/213
- [ ] https://github.com/sequentech/backend-services/pull/214
```
