### ISSUE TITLE
✨ Enable filtering ballot publication by event

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#425]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Enable filtering ballot publication by event

### Tasks

```[tasklist]
# Tasks
- [x] Add `is_event` field to `ballot_publication`.
- [x] Use the new field when adding ballot_publications.
- [x] Ensure ballot publications for elections only soft_delete ballot styles for the election.
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/backend-services/pull/219
```
