### ISSUE TITLE
✨ Add error logs

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#427]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Add error logs

### Tasks

```[tasklist]
# Tasks
- [x] Add error logs
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/backend-services/pull/224
```
