### ISSUE TITLE
Improve CI pushed images tags

### ISSUE THREAD

**Issue by BarelElbazDeveleap** [sequentech/meta#432]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

We need to add more docker image tags except the git sha:
- build number
- latest

### Tasks

```[tasklist]
# Tasks
- [ ] Add latest tag
- [ ] Add build number tag
```

```[tasklist]
# Master PRs
- [ ] PR 1
```
