### ISSUE TITLE
✨ Integrate velvet into windmill

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#433]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Integrate velvet into windmill. Related to https://github.com/sequentech/meta/issues/408

### Tasks

```[tasklist]
# Tasks
- [x] Integrate kevin's area fix from velvet.
- [x] Call velvet on tally task only once, after creating the input files.
- [x] Call the creation of results tables only once.
- [x] Test it works.
- [x] Integrate kevin's census input from velvet in windmill.
- [x] Test it works with multiple contests/areas.
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/backend-services/pull/245
```
