### ISSUE TITLE
🐞 (Voting Portal) Load ballot styles on election selection screen

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#435]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

Ballot Styles are only loading on your first login.

### Expected Behavior

 Load ballot styles on election selection screen

### Environment

- **OS**: Mac OS X Ventura
- **Web browser**: Google Chrome 112.0.5615.137 (Official Build) (arm64)
- **Sequent Platform Version**: 10.0.0

### Tasks

```[tasklist]
# Tasks
-  [x] Load ballot styles on election selection screen
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/233
```
