### ISSUE TITLE
✨ Implement Backend for Results/Tally Exports

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#442]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Implement Backend for Tally Exports.

### Tasks

```[tasklist]
# Tasks
- [ ] Add fake endpoints to export/import results data.
- [ ] Add missing download fields on results tables, json fields for downloading exports of different file types.
- [ ] Add missing fields for information like total cast votes (even invalid) and percentages.
- [ ] Implement the logic to store the documents on s3 and save the document ids on the json fields.
```

```[tasklist]
# Master PRs
- [ ] PR 1
```
