### ISSUE TITLE
✨ Add support for configuring supporting material attachments

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#443]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Requirement

The system must have the capability to upload multimedia elements that allow presenting to the citizenship on the voter's portal support materials that guide them during the casting of their vote, considering at least:

- Manuals: in PDF format,
- Infographics: in PDF, PNG, or JPG format
- Video tutorials: in MP4 format
- Audio tutorials: in MP3 format

The final format of the support materials will be agreed upon later. For security reasons, this support material must be hosted on our own infrastructure designated for the system to prevent citizens from being directed to pages outside of the System.

### Tasks

```[tasklist]
# Tasks
- [x] admin-portal: add new accordion in election event data tab for support materials
- [x] admin-portal: activation field, title, subtitle with translations
- [x] admin-portal: add materials table with add, edit and delete
- [x] admin-portal: add drawer for edit with title, subtitle and uploader with translations
- [x] voting-portal: add button on start screen to go to suport materials if activated for election event
- [x] voting-portal: add screen to display the list of materials with back to elections button
- [x] voting-portal: add list of support materials with title, subtitle and button to show the material
- [x] voting-portal: add modal to view the material
- [x] add icons to file types in both portals
- [x] add iframes to visualize pdf, videos and audios
- [x] added types and ui refinements
- [x] arranged voting channels for election event
- [x] added max number of allowed votes to election
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/251
- [ ] https://github.com/sequentech/backend-services/pull/263
```
