### ISSUE TITLE
✨ Load front-end settings to enable prod deployment

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#448]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Load front-end settings to enable prod deployment

### Tasks

```[tasklist]
# Tasks
- [x] Settings for `admin-portal`.
- [x] Settings for `voting-portal`.
- [x] Settings for `ballot-verifier`.
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/backend-services/pull/248
```
