### ISSUE TITLE
✨ Fix issues found when voting/tallying

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#449]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Fix issues found when voting/tallying. Related to https://github.com/sequentech/meta/issues/433

### Tasks

```[tasklist]
# Tasks
- [x] Fix rust tests.
- [x] voters creation in keycloak (tenant id, group).
- [x] voting-portal: go back to election chooser.
- [x] only last vote counts.
- [x] Dates in keys ceremony.
- [x] Check generate report on velvet/windmill.
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/backend-services/pull/250
```
