### ISSUE TITLE
✨ Add to keycloak event's realm `onsite-voting-portal` client support

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#450]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Add to keycloak event's realm `onsite-voting-portal` client support

### Tasks

```[tasklist]
# Tasks
- [x] Test the ballot-verifier works
- [x] Add the `onsite-voting-portal` client
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/252
```
