### ISSUE TITLE
✨ Filtering Voters by Election, area or contest

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#452]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Filtering Voters by Election, area or contest. This is needed for different functionality listed below.

### Tasks

```[tasklist]
# Tasks
- [x] Backend: list voters filtering by election_id
- [x] Frontend: show the Voters tab in election ,filtering by election_id
- [x] Frontend: show the Num Voters in Election's Dashboard, counting voters filtering by election id
- [x] Backend: count voters filtering by contest
- [x] Backend: count voters filtering by area
- [x] Frontend: show the num votes per unit of time in Election's dashboard
- [x] Frontend: show the num areas in Election's dashboard
- [x] Frontend: show the num SMS in Election's dashboard
- [x] Frontend: show the num Emails in Election's dashboard
- [x] Backend: API for cast_votes by channel (both for election and election event)
- [x] Frontend: Use API for cast_votes by channel (both for election and election event)
- [x] Backend: API for cast_votes by date range (both for election and election event)
- [x] Frontend: Use API for cast_votes by date range (both for election and election event)
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/253
- [ ] https://github.com/sequentech/backend-services/pull/255
```
