### ISSUE TITLE
✨ Configure Hasura URL with Settings

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#455]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Configure Hasura URL with Settings

### Tasks

```[tasklist]
# Tasks
- [x] Add HASURA_URL as a global settings in voting portal, admin portal and ballot verifier.
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/backend-services/pull/257
```
