### ISSUE TITLE
✨ Admin-Portal: Tally Sheets support

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#457]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Admin-Portal: Tally Sheets support

### Screenshots

![Image](https://github.com/sequentech/meta/assets/164689/8eeaa2c8-ce7b-49f7-bec0-20fd2db5ffa2)

![Image](https://github.com/sequentech/meta/assets/164689/b87cbdaa-0c4e-4c83-b8cc-cd4acfcaebbe)

![Image](https://github.com/sequentech/meta/assets/164689/da53e376-9b9d-4f11-a256-0354ff2f9199)

![Image](https://github.com/sequentech/meta/assets/164689/c0be6acc-c51e-4671-b70a-1e3e5bce3dde)

![Image](https://github.com/sequentech/meta/assets/164689/8c861c84-6a94-41c4-904e-916b8bb92edc)

![Image](https://github.com/sequentech/meta/assets/164689/dcb1b88d-1bab-43d3-8612-5dc08022a60c)

![Image](https://github.com/sequentech/meta/assets/164689/5d4203ff-d207-4fc8-bccc-ce74d0c7b6d7)

![Image](https://github.com/sequentech/meta/assets/164689/203c8cee-9ff2-4d16-962a-c23566d3cd77)

_No response_

### Tasks

```[tasklist]
# Tasks
- [x] Hasura: Add new tally sheet table to hasura
- [ ] Fullstack: Create new tally sheet permissions in backend and frontend: tally-sheet-view, tally-sheet-create, tally-sheet-approve-change, tally-sheet-edit, tally-sheet-delete
- [x] UI: tally-sheet resource view
- [x] UI: tally-sheet resource add
- [x] UI: tally-sheet resource delete
- [x] UI: tally-sheet resource edit
- [x] UI: tally-sheet resource approve change
- [ ] enable and disable tally sheets from election event votting channels
- [x] add permissions to actions
- [x] add publish action connected to BE
- [x] add unpublish action connected to BE
- [x] add delete action connected to BE
- [ ] use be permissions in apollo calls
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/260
- [ ] https://github.com/sequentech/backend-services/pull/272
```
