### ISSUE TITLE
✨ Backend: Tally sheets support

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#458]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Backend: Tally sheets support

### Tasks

```[tasklist]
# Tasks
- [ ] Backend: tally-sheet create
- [ ] Backend: tally-sheet delete
- [ ] Backend: tally-sheet edit
- [ ] Backend: tally-sheet resource approve change
```

```[tasklist]
# Main PRs
- [ ] PR 1
```
