### ISSUE TITLE
🐞 Deployment and authorization issues

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#459]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

- create election event currently requires super admin
- windmill/harvest/beat  are missing env vars: AMQP_ADDR, KEYCLOAK_URL, KEYCLOAK_ADMIN_CLIENT_ID/SECRET, SUPER_ADMIN_TENANT_ID

### Expected Behavior

Fix mentioned issues

### Steps To Reproduce

Create codespace

### Environment

Developer env

### Tasks

```[tasklist]
# Tasks
- [x] Fix authorization issues.
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/265
```
