### ISSUE TITLE
✨ Permissions: Add role to Apollo context

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#460]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Permissions: Add role to Apollo context

### Tasks

```[tasklist]
# Tasks
- [x] Add role to Apollo context
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/backend-services/pull/261
```
