### ISSUE TITLE
✨ Beat deployment

### ISSUE THREAD

**Issue by BarelElbazDeveleap** [sequentech/meta#461]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Create a helm chart to deploy beat (polling service) into the environment, to make it easy use the windmill image with different CMD ["beat"]

### Tasks

```[tasklist]
# Tasks
- [x] Change windmill dockerfile to contain beat as well
- [x] Add a feature in windmill to set the runtime to "beat"
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/infrastructure/pull/9
```
