### ISSUE TITLE
🐞 Fix tally lock and failure

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#463]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

Tally lock is not unlocked on task failure. Also, the tally task seems to always fail on first try.

### Expected Behavior

Tally lock is not unlocked on task failure. Also, the tally task seems to always fail on first try.

### Environment

- **OS**: Mac OS X Ventura
- **Web browser**: Google Chrome 112.0.5615.137 (Official Build) (arm64)
- **Sequent Platform Version**: 10.0.0

### Tasks

```[tasklist]
# Tasks
- [x] Wrap tally task in another function so that we always remove lock even on error.
- [x] Remove tally task retries.
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/264
```
