### ISSUE TITLE
✨ Admin Portal: UI improvements

### ISSUE THREAD

**Issue by KNTH01** [sequentech/meta#465]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

- sidebar doesn't appear to me if the screen is small
- in split screen the trustee key ceremony, when I drag and drop the key I downloaded, if the screen is small the button below in the wizard are always shown, but the "Key tested successfully" or similar green message is hidden

### Tasks

```[tasklist]
# Tasks
- [ ] Fix the success message in trustee key ceremony screen
- [x] Fix the sidebar responsive so it's always displayed
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/backend-services/pull/284
```

**Comment by edulix** [comment]
subtasks: one is done and the other is not reproducible, so closing it
