### ISSUE TITLE
🐞 Fixes for Demo Jan 8

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#469]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

Fixes for Demo Jan 8

### Expected Behavior

-

### Steps To Reproduce

-

### Environment

-

### Tasks

```[tasklist]
# Tasks
- [x] Fix AWS SNS Support
```

**Comment by edulix** [comment]
I think we can try using in keycloak this param, without changing the code: (change sequent to be some configurable value, but the default can be sequent)
--spi-sms-sender-aws-sender-id=sequent

**Comment by edulix** [comment]
Closing it as @efi-shimon-develeap says it works well now with the mentioned fix

**Comment by efi-shimon-develeap** [comment]
@edulix after testing, this works. 
Need to implement a more configurable value as said above.
