### ISSUE TITLE
✨ Fix keycloak /imports tenants to work in production

### ISSUE THREAD

**Issue by BarelElbazDeveleap** [sequentech/meta#470]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Handle keycloak/imports/*.json:
- Substitute localhosts and static configuration for production (Via script the substitutes or by duplicating the files for
production)
- Fix docker context issue, can't copy files from .devcontainer/keycloak when the context is packages/ directory -
solved for now by making an hardlink
- import/ directory is copied into the keycloak app and it's loaded via volume in dev environment (docker-compose)
need to think what to do with it:

![image](https://github.com/sequentech/meta/assets/133586338/e97060e7-2e48-4e58-91c3-840888185b0a)

### Tasks

```[tasklist]
# Tasks
- [ ] Substitute localhosts and static configuration for production (Via script the substitutes or by duplicating the files for production)
- [ ] Fix docker context issue, can't copy files from .devcontainer/keycloak when the context is packages/ directory solved for now by making an hardlink
- [ ] import/ directory is copied into the keycloak app and it's loaded via volume in dev environment (docker-compose) need to think what to do with it
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/backend-services/pull/271
```

```[tasklist]
# Stable PRs
- [ ] 
```
