### ISSUE TITLE
🐞 Fix useContext/Link error on voting portal on production 

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#471]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

This is not loading: https://voting-portal-staging.sequent.vote/tenant/90505c8a-23a9-4cdf-a26b-4e19f6a097d5/event/e65d13cc-3db3-488b-b1ac-a01a475343ce
![Screenshot 2024-01-08 at 17 26 27](https://github.com/sequentech
![Screenshot 2024-01-08 at 17 26 41](https://github.com/sequentech/meta/assets/3913223/32873958-2e59-4dc0-bf86-75264e2d881b)
/meta/assets/3913223/5a2a30d0-6164-47a3-af77-c6ee067e499d)

### Expected Behavior

The voting portal should work

### Steps To Reproduce

1. In the Admin Portal, click in `New Election` in the sidebar, then click in `Create Election`.
2. Click in `Actions` button and then click in `Edit JSON` in the popup moenu and paste the following election configuration json into the modal dialog and accept: `<insert election-config.json here>`.
3. Then click in `Actions` button and then click in `Live preview` to open the voting booth.
4. In the start screen, the error appears as highlighted in red in the screenshot below: `<insert-screenshot-here>`.

### Environment

- **OS**: Mac OS X Ventura
- **Web browser**: Google Chrome 112.0.5615.137 (Official Build) (arm64)
- **Sequent Platform Version**: 10.0.0

### Tasks

```[tasklist]
# Tasks
- [ ] Issue has been triaged
- [ ] Successful replication of the defect
- [ ] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/273
- [ ] https://github.com/sequentech/backend-services/pull/275
- [ ] https://github.com/sequentech/backend-services/pull/276
```
