### ISSUE TITLE
🐞 Error creating election event

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#473]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

In production create election event never ends in the UI side

### Expected Behavior

-

### Steps To Reproduce

-

### Environment

-

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [ ] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/279
```
