### ISSUE TITLE
✨ Full flow e2e tests

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#474]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Implement full flow e2e tests

### Tasks

```[tasklist]
# Tasks
- [ ] execute admin-login
- [ ] add github action
- [ ] execute election-event creation
- [ ] execute election creation
- [ ] execute contest creation
- [ ] execute candidates creation
- [ ] execute area creation
- [ ] execute voter creation
- [ ] execute assign password and area to voter
- [ ] execute keys ceremony
- [ ] execute ballot style creation
- [ ] execute start election
- [ ] execute voter login
- [ ] execute cast vote
- [ ] execute dashboard wait for update with new ballot
- [ ] execute stop election
- [ ] execute tally ceremony
- [ ] execute tally
- [ ] execute download results in different formats
- [ ] execute verify ballot locator 
- [ ] execute verify ballot
```

```[tasklist]
# Main PRs
- [ ] PR 1
```

**Comment by yvwbimpong** [comment]
https://www.loom.com/share/ee236f7a811f49bb8904fe8b986ce1bd?sid=e7dceb4c-80b6-4bbf-b412-b08c201c9caf
