### ISSUE TITLE
Deploy a new environment for APA 

### ISSUE THREAD

**Issue by efi-shimon-develeap** [sequentech/meta#477]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

We need to deploy an environment for the APA project. 
Environment should look the same as staging, using the images from ecr etc.. 

### Tasks

```[tasklist]
# Tasks
- [x] Create and deploy IaC of the environment
- [ ] Document environment bringup process
- [x] Deploy charts to the environment
- [x] Configure dns records for the environment
```

```[tasklist]
# Master PRs
- [ ] PR 1
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```
