### ISSUE TITLE
🐞 Status refresh of Keys in trustees accounts

### ISSUE THREAD

**Issue by ebadia** [sequentech/meta#481]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

- status is not refreshed after checking keys
- breadcrum must be updated correctly depending on step
- click on tree menu does not refreshes screen (it refreshes url path)

### Expected Behavior

-

### Steps To Reproduce

-

### Environment

-

### Tasks

```[tasklist]
# Tasks
- [ ] Issue has been triaged
- [ ] Successful replication of the defect
- [ ] Successful defect resolution merged
- [ ] check status refresh
- [ ] check step update
- [ ] control click on Keys tab
- [ ] change screen on menu clicked
- [ ] column sizes of tally in admin portal
```

```[tasklist]
# Main PRs
- [ ] PR 1
```
