### ISSUE TITLE
✨ Improve Areas creation and other improvements

### ISSUE THREAD

**Issue by ebadia** [sequentech/meta#484]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

- Enric: Contest voting type should be NON preferential (vs No), and it should have it as default instead of empty.
- Enric: Communication templates: add default values (default template values)
- Enric: Remove areas doesn't work.
- Enric: When there are no areas, show the "create area" kind of screen we use in other places.
- Enric: Back button on tally should be hidden (last screen of the tally).
- Enric: Going from publish to dashboard, it doesn't refresh the state of the election event.

### Screenshots

![Image](https://github.com/sequentech/meta/assets/164689/393e70e7-7420-4357-b445-06e5be8db4b8)

![Image](https://github.com/sequentech/meta/assets/164689/7020a0b4-839e-4edc-9cfc-eff20a2c0917)

![Image](https://github.com/sequentech/meta/assets/164689/a682d82a-f876-4184-9903-fe072a6384e7)

![Image](https://github.com/sequentech/meta/assets/164689/55b9125c-d032-4352-89b3-dff9d734157a)

![Image](https://github.com/sequentech/meta/assets/164689/faf1b136-5b4e-4684-8400-24368d7df5fa)

- example: send a mail ntoficaation
- after click on "Dashboard" tab inmediate refresh

![Image](https://github.com/sequentech/meta/assets/164689/20ef76fc-8563-47ef-a4a9-27166108f334)

_No response_

### Tasks

```[tasklist]
# Tasks
- [x] When there are no areas, show the "create area" kind of screen we use in other places
- [x] Remove areas doesn't work. BE cascade
- [x] Contest voting type should be NON preferential (vs No), and it should have it as default instead of empty
- [x] Back button on tally should be hidden (last screen of the tally)
- [x] Going from publish to dashboard, it doesn't refresh the state of the election event
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/backend-services/pull/287
```
