### ISSUE TITLE
✨ Improve performance of PDF generations

### ISSUE THREAD

**Issue by KNTH01** [sequentech/meta#486]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

- parallelize generation

### Tasks

```[tasklist]
# Tasks
- [x] Parallelize generation of PDF
- [x] Add benchmark
- [x] Improve Sequent_Core html_to_pdf
- [x] Code review improvements
- [x] Fix render of cell width
- [x] Fixed percentages for table widths
- [x] Support basic html in title and description of election event, election, contest and candidate
- [x] Escape HTML
- [x] Add missing percentages for statistics
- [x] Add participation percentages
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/288
- [ ] https://github.com/sequentech/backend-services/pull/331
- [ ] https://github.com/sequentech/backend-services/pull/334
- [ ] https://github.com/sequentech/backend-services/pull/335
- [ ] https://github.com/sequentech/backend-services/pull/344
```

### Additional context

[report.pdf](https://github.com/sequentech/meta/files/14165672/report.pdf)

![Image](https://github.com/sequentech/meta/assets/1632391/692b466b-349e-41cd-aa57-09dad9a18132)
