### ISSUE TITLE
✨ Custom sort order for candidates 

### ISSUE THREAD

**Issue by KNTH01** [sequentech/meta#487]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Add custom sort order for candidates

### Tasks

```[tasklist]
# Tasks
- [x] Add a sort order column in candidate table in Hasura
- [x] Implement drag and drop component to order candidates
- [x] Make a custom input to integrate the component into Edit form
- [x] Persist the custom sort order
- [x] Make sure the BallotStyle and Candidate are also updated
- [x] Present the custom sort order on the voting portal
- [x] Display custom order in tree menu
- [x] Display Candidates alias in the tree menu
- [x] Review by felix to see if it's finished
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/297
- [ ] https://github.com/sequentech/backend-services/pull/399
```
