### ISSUE TITLE
✨ Export Voters

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#488]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Export voters, including if they voted or not and when.

### Screenshots

<img width="1439" alt="image" src="https://github.com/sequentech/meta/assets/81968/7b97503e-bbf5-4891-9e42-1ac231c3cb78">

### Tasks

```[tasklist]
# Tasks
- [x] Backend: Implement function to get voter info
- [x] Backend: Change get_users to optionally return voter info
- [x] Frontend: Update expected data format for a user, to contain voter info
- [x] Backend: Generate a callback to export voter info export
- [x] Frontend: Connect to callback to obtain voter info export
- [x] Backend: Substitute everywhere `s3::upload_to_s3` with `s3::upload_file_to_s3`
- [x] Backend: improve the exported TSV to have move usable columns, without Some() and things like that. Separate different keycloak user attrs in different columns, and separate each item from votes_info into a column
- [x] Ensure that export voters works well too for election
- [x] Backend/Frontend: Modify fetch-document to use the document.name as the document key
- [ ] Ensure that export users works for admin users: moved to https://github.com/sequentech/meta/issues/1089
- [ ] Backend: allow sending communications to users filtering by who voted or not voted: moved to https://github.com/sequentech/meta/issues/1090
- [ ] Frontend: Allow to filter by users who voted in at least one election: moved to https://github.com/sequentech/meta/issues/1091
- [ ] Backend: Allow to filter by users who voted in at least one election: moved to https://github.com/sequentech/meta/issues/1091
- [ ] Backend: Add ballot-ID columns (one per election) to the export: moved to https://github.com/sequentech/meta/issues/1092
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/306
- [ ] https://github.com/sequentech/backend-services/pull/313
- [ ] https://github.com/sequentech/backend-services/pull/320
```

**Comment by edulix** [comment]
subtasks moved to their own tickets, so closing this one
