### ISSUE TITLE
✨ Import/Export Whole Elections Events

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#489]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Support Importing Whole Elections Events

### Tasks

```[tasklist]
# Tasks
- [x] Add Harvest+Windmill API call to import whole election events
- [x] Import Election Event configuration
- [x] Import Keycloak Realm Configuration
- [ ] In Data (Election Event), add Export button, that exports in the same json format as the import.
- [ ] The export button should be permissioned (frontend and backend).
- [ ] Add duplicate button (not priority).
- [ ] Import/Export labels/annotations too.
- [ ] Unit tests: Import Election Event configuration
- [x] Connect Frontend to Import Election Event API call
- [ ] Unit tests: Import Keycloak Realm Configuration
- [x] Import Areas
- [ ] Unit tests: Import Areas
- [x] Import Contests
- [ ] Unit tests: Import Areas
- [x] Import AreaContests
- [ ] Unit tests: Import AreaContests
- [ ] Import Ballots
- [ ] Unit tests: Import Ballots
- [ ] Import Ballot Publications
- [ ] Unit tests: Import Ballot Publications
- [ ] Import Ballot Styles
- [ ] Unit tests: Import Ballot Styles
- [x] Import Candidates
- [ ] Unit tests: Import Candidates
- [x] Import Contests
- [ ] Unit tests: Import Contests
- [ ] Import Scheduled Events
- [ ] Unit tests: Import Scheduled Events
- [ ] Make Import hash check to work
- [ ] Improve/design UI
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/381
- [ ] https://github.com/sequentech/backend-services/pull/407
- [ ] https://github.com/sequentech/backend-services/pull/452
- [ ] https://github.com/sequentech/gitops/pull/244
- [ ] https://github.com/sequentech/backend-services/pull/453
- [ ] https://github.com/sequentech/gitops/pull/255
- [ ] https://github.com/sequentech/backend-services/pull/469
- [ ] https://github.com/sequentech/backend-services/pull/474
```

# Import data

[toto.json](https://github.com/sequentech/meta/files/14908823/toto.json)

**Comment by Findeton** [comment]
This is an example of an election event to be imported.

[example.json](https://github.com/sequentech/meta/files/14912026/example.json)
