### ISSUE TITLE
🐞 Fix sidebar menu scroll

### ISSUE THREAD

**Issue by KNTH01** [sequentech/meta#490]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

We cannot scroll inside of the sidebar menu

### Expected Behavior

The sidebar menu should be scrollable

### Steps To Reproduce

-

### Environment

-

### Tasks

```[tasklist]
# Tasks

-\[ ] 1

- [x] Fix
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/289
```
