### ISSUE TITLE
✨ Backup & Restore

### ISSUE THREAD

**Issue by efi-shimon-develeap** [sequentech/meta#493]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Backup & Restore: 
We want to be able to restore an environment when there is an issue for example a curruption in the database. 
To do so we want to create a reocuring backup for the environment that will allow us to restore to a certain time
Tasks: 

Open questions: 
- how many backups do we keep? 
- how frequently do we backup? 

### Tasks

```[tasklist]
# Tasks
- [ ] create backup for the different stateful data:
- [ ] aurora
- [ ] immudb volume
- [ ] Research what is the best way to backup the different applications:
- [ ] aurora - probably snapshots
- [ ] immudb - maybe a job that creates backup of the volumes
- [ ] Restore relevant services from the backup:
- [ ] aurora:
- [ ] need to understand if we are creating a different db or restoring the corrent one
- [ ] imuudb:
- [ ] need to see how to load pvc from a specific volume (probably add this to the configuration of the helm chart)
```

```[tasklist]
# Master PRs
- [ ] PR 1
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```

**Comment by edulix** [comment]
Regarding the open questions, this is an idea for the backups policy:
- 1 backup every 3 hours, lasting 24h
- 1 backup every day, lasting 7 days
- 1 backup every week, lasting 4 weeks
- 1 backup every month, lasting 12 months
