### ISSUE TITLE
✨ Scaling & high availability

### ISSUE THREAD

**Issue by efi-shimon-develeap** [sequentech/meta#494]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

We want our system to be able to scale up when under pressure and scale down when idle. 
In order to do so, we need to implement two type of scaling: 
- Horisontal scaling (the scaling of the pods)
- Vertical scaling (the scaling of the nodes)

In this task we will take care of the two types of scaling for our applications. 

### Tasks

```[tasklist]
# Tasks
- [x] This is done in order to test that the application knows how to work as multiple replicas
- [x] Run our services with more than one replica (beat and trustees shouldn't be scaled)
- [x] If not yet created, create HPA configuration for the different applications
- [x] Enable HPA and configure the trasholds for scaling
- [x] ClusterAutoscaller:
- [x] Node termination handler
- [x] Create IaC module for cluster autoscaller,node-termination-handler creation and deployment
- [x] IAM role with OIDC for access
- [x] Helm chart installation from IaC
- [x] Relevant resources creation
- [x] Deploy cluster autoscaller to the environment
- [x] Apply topology spread constraints to scale into different availability zones
- [x] Run tests for scaling (mock the need for additional nodes & pods in order to see vertical & horisontal scale)
- [x] Test keycloak with multi replicas (sticky sessions)
- [ ] Check the ability of immudb to work in a multi-replica
```

```[tasklist]
# Master PRs
- [ ] PR 1
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```
