### ISSUE TITLE
✨ Windmill updates for tenant files

### ISSUE THREAD

**Issue by efi-shimon-develeap** [sequentech/meta#495]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

We should pass tenant file for windmill helm chart directly and not from keycloak 

### Tasks

```[tasklist]
# Tasks
- [ ] Create configmap configuration in windmill helm chart for default tenant 
- [ ] Allow to choose if we are using the default tenant from keycloak configmap or from windmill
```

```[tasklist]
# Master PRs
- [ ] PR 1
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```
