### ISSUE TITLE
🐞 database access from windmill & harvest

### ISSUE THREAD

**Issue by efi-shimon-develeap** [sequentech/meta#497]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

access issues to keycloak and hasura databases due to insufficient permissions

### Expected Behavior

We want to allow Windmill, Harvest & Beat to use the users of hasura & keycloak to access the relevant databases
This is a short-term fix for the issue we corrently have with access permissions to the databases 

### Steps To Reproduce

1. In the Admin Portal, click in `New Election` in the sidebar, then click in `Create Election`.
2. Click in `Actions` button and then click in `Edit JSON` in the popup moenu and paste the following election configuration json into the modal dialog and accept: `<insert election-config.json here>`.
3. Then click in `Actions` button and then click in `Live preview` to open the voting booth.
4. In the start screen, the error appears as highlighted in red in the screenshot below: `<insert-screenshot-here>`.

### Environment

- **OS**: Mac OS X Ventura
- **Web browser**: Google Chrome 112.0.5615.137 (Official Build) (arm64)
- **Sequent Platform Version**: 10.0.0

### Tasks

```[tasklist]
# Tasks
- [ ]  Update Windmill helm chart to allow passing db-credentials for Keycloak
- [ ]  Update Windmill helm chart to allow passing db-credentials for Hasura
- [ ]  Update Harvest helm chart to allow passing db-credentials for Keycloak
- [ ]  Update Harvest helm chart to allow passing db-credentials for Hasura
```

```[tasklist]
# Main PRs
- [ ] PR 1
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```
