### ISSUE TITLE
✨ pg-audit worker

### ISSUE THREAD

**Issue by efi-shimon-develeap** [sequentech/meta#498]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

We want to add the pg-audit information to be seen from the admin UI, in order to do so we need to create different workers for each database (Hasura, Keycloak)
That scrape the pgaudit logs and push them to immudb

Open question: 
- is this going to strain immudb? 
- can we seperate this from the immudb that is in charge of the environment?
- Do we need here immudb? can we work with s3 or other backend?

### Tasks

```[tasklist]
# Tasks
- [ ] research if we can work with pgaudit aurora plugin to reach this goal
- [ ] see how to scrape the relevant logs and push them into immudb? 
- [ ] if option a is not possible - create a helm chart for pgaudit and do the process from the cluster.
```

```[tasklist]
# Master PRs
- [ ] PR 1
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```
