### ISSUE TITLE
✨ Create & test documentation for environment creation process

### ISSUE THREAD

**Issue by efi-shimon-develeap** [sequentech/meta#505]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Need to have an environment bringup process to allow different people to create an environment 

### Tasks

```[tasklist]
# Tasks
- [x] Document environment bringup
- [x] Assist someone to bringup the environment to see that the documentation is clear
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/gitops/pull/9
```

**Comment by edulix** [comment]
I don't see this ticket merged into Main, please do @BarelElbazDeveleap

**Comment by BarelElbazDeveleap** [comment]
Sure
