### ISSUE TITLE
🐞 VOTING PORTAL 1st review and APA specific features

### ISSUE THREAD

**Issue by lnabergoi** [sequentech/meta#512]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Tasks

**List of features to be fixed: Product voting portal**
- [x] Kevin: The responsive mode for phones has a horizontal scroll.
- [x] Kevin: breadcrumb, headers and footers.
- [x] Kevin: On the mobile version, button corners should not be rounded.
- [x] Kevin: Version position overlaps with "Sequent logo" in the headers.
- [x] Kevin: Ballot page missing clear selection button.
- [x] Kevin: When pressing continue we should automatically scroll back up
- [x] Kevin: Is the text for the name is too big - mobile / desktop
- [x] Kevin: Title Text is not centered in start screen
- [x] Kevin: App version in the error page
- [x] Kevin: Improve error page display
- [x] Felix: The election logo doesn't show up in the headers.
- [x] The voting portal shows English and Spanish even if the configuration has only English.
- [x] Felix: On the Sucess Screen, the Finish button should redirect to the initial screen if either you can vote again or there are more elections where you can vote.
- [x] set ballot as first stage in the breadcrumbs when redirecting automatically to election
- [x] We should use configuration for "Radio button" and not multi-choice
- [x] Icon is too large in mobile
- [x] Audit available in mobile, should be hidden
- [x] Description of contest should not be shown in review screen
- [x] Click to vote "looks" like it is clickable when it shouldn't, need to disable the button after voting just like when election is STOPPED/PAUSED
- [ ] Felix: Ballot review page: the ability to remove the audit ballot feature and fix the page description text.
- [ ] Review the hardcoded APA specific features and list them
- [x] Order contests by creation date

**APA specific**
- [x] Felix: Instruction screen missing background image
- [x] Felix: Skip the election list page before the vote
- [ ] Felix: Color schema from APA in https://web-demo.sequentech.io/booth/530067/demo-vote

![Screenshot 2024-01-19 at 4 38 59 PM](https://github.com/sequentech/meta/assets/4264627/8bb460c9-f7a4-4501-a915-a187509615a6)
![Screenshot 2024-01-19 at 4 37 37 PM](https://github.com/sequentech/meta/assets/4264627/c5cb1c9f-2b24-4c20-884f-45791064b97e)

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/308
- [ ] https://github.com/sequentech/backend-services/pull/311
- [ ] https://github.com/sequentech/backend-services/pull/314
- [ ] https://github.com/sequentech/backend-services/pull/322
```

**Comment by edulix** [comment]
@Findeton what is missing here?

**Comment by edulix** [comment]
@Findeton bumping my question :-P

**Comment by Findeton** [comment]
@edulix Nothing, closing here.
