### ISSUE TITLE
✨ Limit windmill tasks max_retries 

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#514]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Limit windmill tasks max_retries 

### Tasks

```[tasklist]
# Tasks
- [x] Add max_retries limit.
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/backend-services/pull/305
```
