### ISSUE TITLE
🐞 Can't perform tally in certain conditions

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#515]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

When the plaintexts are still being mixed, the tally fails.

### Expected Behavior

When the plaintexts are still being mixed, the tally suceeds.

### Steps To Reproduce

This happens when velvet is run but there are no plaintext messages at all. Specifically this happens when the tally is being mixed.

### Tasks

```[tasklist]
# Tasks
- [x] Refactor `AreaContestDataType` into a struct.
- [x] Refactor `process_plaintexts` to be more readable.
- [x] Only call velvet if there are plaintexts to be processed.
- [x] Improve logging (avoid logging too much). (removing this, is in https://github.com/sequentech/meta/issues/658)
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/307
```
