### ISSUE TITLE
✨ Continuous deployment configuration argocd

### ISSUE THREAD

**Issue by BarelElbazDeveleap** [sequentech/meta#519]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

We need argo applications for the services inside the K8S cluster to deploy newer versions, rollback broken services, self-heal easily, and make the gitops repo the source of truth of the environment.

In this ticket, we will create argo applications & templates for the various applications

### Tasks

```[tasklist]
# Tasks
- [x] Remove the applicationset since it's not needed
- [x] Create argo applications templates for the various services in gitops repo
- [ ] Document the helm charts values using helm doc etc...
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/gitops/pull/13
- [ ] https://github.com/sequentech/infrastructure/pull/24
```

**Comment by BarelElbazDeveleap** [comment]
Need to write documentation
