### ISSUE TITLE
Security dependencies and check release readiness

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#52]
```[tasklist]
## Tasks
- [x] Update security dependencies for the first gen.
- [x] [Check release readiness](https://sequentech.github.io/documentation/docs/general/contribute/production-readiness) (for example, github actions work).
```

```[tasklist]
# Master PRs:
- [ ] https://github.com/sequentech/frestq/pull/58
- [ ] https://github.com/sequentech/election-orchestra/pull/53
- [ ] https://github.com/sequentech/frestq/pull/57
- [ ] https://github.com/sequentech/election-orchestra/pull/52
- [ ] https://github.com/sequentech/frestq/pull/64
- [ ] https://github.com/sequentech/election-orchestra/pull/59
- [ ] https://github.com/sequentech/common-ui/pull/278
- [ ] https://github.com/sequentech/iam/pull/265
- [ ] https://github.com/sequentech/iam/pull/266
```

```[tasklist]
# 7.1.x PRs:

- [ ] https://github.com/sequentech/frestq/pull/61
- [ ] https://github.com/sequentech/election-orchestra/pull/56
- [ ] https://github.com/sequentech/frestq/pull/62
- [ ] https://github.com/sequentech/election-orchestra/pull/57
- [ ] https://github.com/sequentech/frestq/pull/63
- [ ] https://github.com/sequentech/election-orchestra/pull/58
- [ ] https://github.com/sequentech/common-ui/pull/280
- [ ] https://github.com/sequentech/iam/pull/267
- [ ] https://github.com/sequentech/iam/pull/268
```
