### ISSUE TITLE
🐞 Admin portal contest candidates order issues

### ISSUE THREAD

**Issue by ebadia** [sequentech/meta#521]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

-

### Expected Behavior

-

### Steps To Reproduce

-

### Environment

-

### Screenshots

![Image](https://github.com/sequentech/meta/assets/164689/61ee2571-19df-448c-8ac4-2e1b3c2d89ea)

![Image](https://github.com/sequentech/meta/assets/164689/8fffd40c-711e-4c99-b512-6ce6ca1a7bc1)

![Image](https://github.com/sequentech/meta/assets/164689/e035d1a0-4ed2-425f-926d-aa86791f4291)

![Image](https://github.com/sequentech/meta/assets/164689/5c18abf2-5eb8-4fe5-ac82-94ed3a1000aa)

### Tasks

```[tasklist]
# Tasks
- [x] Successful replication of the defect
- [x] contest candidates order Does not have default value
- [x] contest candidates order Did not get updated when moving the candidate manually and saving
- [x] There might be less candidates in the "Reorder candidates" than in the list of the left side
- [x] Do we change to be like google design? (there was no design request) [NOT FOR DEMO UNLESS WE GET TIME].
- [x] Should take best practices from known design / standard: Just added a drag icon for signal that this is draggable.
- [x] when we send a communication, when we select a communication template, it is selected but it doesn’t look selected.
- [x] version number in on line in header
- [x] translations in permissions
- [x] use alias translated in sidebar elements
- [ ] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/316
```
