### ISSUE TITLE
🐞 Tally and harvest bugs

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#522]
### Tasks

```[tasklist]
# Tasks
- [x] Fix hasura::document::insert_document.
- [x] Fix decode_jwt for multiple audiences.
- [x] Fix decode_jwt for user with no name.
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/312
- [ ] https://github.com/sequentech/backend-services/pull/315
```
