### ISSUE TITLE
🐞 Admin portal: Fix sidebar scroll behavior

### ISSUE THREAD

**Issue by KNTH01** [sequentech/meta#525]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

- Sidebar has horizontal scroll bar
- Sidebar has vertical scroll bar that gets partially hidden on scroll

### Expected Behavior

- Sidebar does not have horizontal scroll bar
- Sidebar vertical scroll bar allows to see all items

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [x] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/347
- [ ] https://github.com/sequentech/backend-services/pull/400
- [ ] https://github.com/sequentech/backend-services/pull/443
```
