### ISSUE TITLE
✨ Order Candidates in the Contest

### ISSUE THREAD

**Issue by KNTH01** [sequentech/meta#526]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

- Use `CandidatesOrder` enum instead of `checkShuffleAllOptions` and `shuffle_all_options`
- Implement a sort function that give the output order based on the `CandidatesOrder` enum: alphabetical, custom, random, default
- Review if more things is needed

### Tasks

```[tasklist]
# Tasks
- [x] Clean shuffle_all_options
- [x] Implement sort alphabetical
- [x] Implement sort random
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/backend-services/pull/326
```

**Comment by Findeton** [comment]
We need to move the sort function to ui-essentials so that it can also be used in the ballot verifier, but we can do that after the demo.
