### ISSUE TITLE
🐞 Felix demo fixes

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#527]
### Tasks

  - [x] Fix `voting-portal` logo overflow on mobile.
  - [x] Fix: creating election event fails silently.
  - [x] Fix: audit is mentioned on review page.
  - [x] Update invalid vote policy to enum.
  - [x] Update radio selection to use select policy and max = 1.
  - [x] logout before redirect on finish, configurable redirect url.
  - [x] configurable logo.
  - [x] Fix num_allowed_revotes.
  - [x] configurable css for event and election.
  - [x] move event presentation into ballot style.
  - [x] flag to hide audit ballot.
  - [ ] admin-portal: invalid vote policy.
  - [x] admin-portal: logo.
  - [x] admin-portal: css.
  - [ ] admin-portal: select policy.
  - [x] modify support materials to enable hiding and also get public url to be used (ie css).
  - [x] automatic logout on session expired.
  - [x] Publish per election need to be fixed
  - [x] Session was closed before finished 
    - Token refresh issue?
    - Need to set token to be longer
    - Need to have a better error something like "session expired"
      - Show a message that you are getting logged out
        - maybe send to login screen?
  - [x] Automatic scrolling the the tally window
  - [x] Messages from previous keys session are in the logs.
  - [x] Skip election chooser policy.

### Tasks

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/367
- [ ] https://github.com/sequentech/backend-services/pull/317
- [ ] https://github.com/sequentech/backend-services/pull/319
- [ ] https://github.com/sequentech/backend-services/pull/328
- [ ] https://github.com/sequentech/backend-services/pull/329
- [ ] https://github.com/sequentech/backend-services/pull/332
- [ ] https://github.com/sequentech/backend-services/pull/345
- [ ] https://github.com/sequentech/backend-services/pull/323
- [ ] https://github.com/sequentech/infrastructure/pull/25
```
