### ISSUE TITLE
🐞 Trustees: authentication expires

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#528]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

After some time, the authentication for immudb expires and it's not renewed.

```
2024-01-25T17:31:55+02:00 ERROR Error listing board names: ‘status: Unauthenticated, message: “Please login”, details: [], metadata: MetadataMap { headers: {“content-type”: “application/grpc”, “immudb-uuid”: “cmkjtmckonegca5vpog0”} }’
```

### Expected Behavior

Authenticate on every loop in the trustees.

### Tasks

```[tasklist]
# Tasks
- [x] Move immudb auth inside the loop on `main.rs` in `braid`.
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/318
```
