### ISSUE TITLE
✨ Tally accordion scroll and data refresh

### ISSUE THREAD

**Issue by ebadia** [sequentech/meta#531]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

-

### Tasks

```[tasklist]
# Tasks
- [x] improve scroll of accordion component
- [x] improve screen flick in data refresh
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/backend-services/pull/333
- [ ] https://github.com/sequentech/backend-services/pull/337
```

**Comment by Findeton** [comment]
Follow up issue: https://github.com/sequentech/meta/issues/538
