### ISSUE TITLE
✨ Enhance Keycloak Voting Login Themes

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#534]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Enhance Keycloak Voting Login Themes.

### Screenshots

Empty List of Users now include the Import button:
<img width="1137" alt="image" src="https://github.com/sequentech/meta/assets/81968/8c7b760a-6ee4-41cd-b6d4-8005537033f6">

The Login screen of the admin portal has multiple improvements:

<img width="1440" alt="image" src="https://github.com/sequentech/meta/assets/81968/646f79fe-77aa-48fe-91ec-ca9c2a749ae1">

### Tasks

```[tasklist]
# Tasks
- [x] Move from `sequent` theme to having two: `sequent.admin-portal` and `sequent.voting-portal`, which might have slightly different configuration, but one extends the other for deduplication.
- [x] Add background image to the login
- [x] Use Sequent Blue Color for login box top border and login button
- [x] Improve the login text copy
- [x] Center the Header in mobile
- [x] Simplify default admin login with username and password
- [x] Update the default election realm config
- [x] Admin-portal: remove unnecessary password policies during password validation
- [x] Add the Import button in the EmptyList of Users
- [x] Remove users from the default event realm
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/338
```
