### ISSUE TITLE
🐞 Enric bugfixes in the Voting Portal

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#535]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

Bugfixes/Improvements to be made in the Voting Portal.

### Expected Behavior

-

### Steps To Reproduce

-

### Environment

-

### Tasks

```[tasklist]
# Tasks
- [x] Mobile version (Safari) - After casting my ballot I can go back to the review screen and “cast” it again, OR go back 2 times and change my ballot, which will then be re-encrypted and recast. See the screen recording here - detect if this is the case and logout which has to redirect to login https://drive.google.com/file/d/1-EL_uAeDUiQZ3XTUCsWqi5oyVG8byKFk/view?usp=sharing
- [x] Ensure that if the minimum number of selected options for a contest is not chosen, then a dialog warning that this didn't happen is shown and does NOT allow to continue, only to go back and fix this.
- [x] Ensure that the the “Finish” button in the Success Screen (after successfully voting) leads to google.com, but only after doing a logout()
- [x] change the main page’s voting instruction to this text? This is more fluent in English. Please follow these steps to cast your ballot:
- [x] 1 . Select your options: Choose your preferred candidates and answer the election questions one by one as they appear. You can edit your ballot until you are ready to proceed.
- [x] 2 . Review your ballot: Once you are satisfied with your selections, we will encrypt your ballot and show you a final review of your choices. You will also receive a unique tracker ID for your ballot.
- [x] 3 . Cast your ballot: Finally, you can cast your ballot so it is properly registered. Alternatively, you can opt to audit and confirm that your ballot was correctly captured and encrypted.
- [x] Implement the text improvements explained in this doc: https://docs.google.com/spreadsheets/d/1_W7wKz12cInLt_-Q7SO0k5i8H9VFvHtK22HS05PP-GQ/edit#gid=0
- [x] Mobile version (Safari) - at the first load of the voting portal, the voter sees the Election screen without any election found. << What should happen is that if the list is loading, it should show a loading widget (just like what we do in Admin portal) and if the election is really empty, it show a centered element saying "List of Elections is Empty".
- [x] The “Review your ballot” text in the ReviewScreen should be different when Audit screen is disabled, because it talks about Audit screen when it is enabled.
- [x] There is a clickable area on the customer logo that leads to our website. The clickable area should be removed.
- [x] The QR code found in the success screen Print PDF. sends the voter to the login page instead of the ballot locator if the voter is not logged in.
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/340
- [ ] https://github.com/sequentech/backend-services/pull/343
```
