### ISSUE TITLE
✨ Admin Portal: Improve User password change

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#536]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Admin Portal: Improve User password change.

### Tasks

```[tasklist]
# Tasks
- [ ] UI: Move User Password change to a specific action that launches in the sidebar.
- [ ] UI: Allow in this Password change sidebar to allow to either force request password change to user after login or not.
- [ ] Backend: Allow in this Password change sidebar to allow to either force request password change to user after login or not.
```

```[tasklist]
# Main PRs
- [ ] PR 1
```
