### ISSUE TITLE
🐞 Edu demo fixes

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#537]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

-

### Expected Behavior

-

### Steps To Reproduce

-

### Environment

-

### Tasks

```[tasklist]
# Tasks
- [x] Adding line to tab bar in  sidebar screens (User and Roles, Logs, Settings)
- [x] Checking permissions in sidebar screens (User and Roles, Logs, Settings, CommTempl) and hiding logs for now
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/339
```
