### ISSUE TITLE
✨ Reduce Borsch impact on Hashable/Auditable Ballot

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#540]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

The whole Auditable/Hashable Ballot are serialized with Borsch. This makes decoding the ballot prone to decoding errors, when versions of the underlying structs change, as even the Ballot Style is serialized with Borsch and its struct changes frequently with versions. For example if in a deployment versions change in the middle of an election because of a required update, this could render many ballots as invalid.

Borsch should be only used in the encoding of the selections, leaving the rest of the ballot as a json.

### Tasks

```[tasklist]
# Tasks
- [x] Change structs and pass `sequent-core` rust compilation.
- [x] Pass `sequent-core` tests.
- [x] Pass wasm compilation.
- [x] Test it works on an election.
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/backend-services/pull/341
```
