### ISSUE TITLE
✨ Use AWS Secrets Manager instead of Vault

### ISSUE THREAD

**Issue by BarelElbazDeveleap** [sequentech/meta#541]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Adapt the infra to the new backend (windmill) change of supporting AWS Secrets Manager instead of Hashicorp Vault:
- Replace the environment variables in the helm chart (`SECRETS_BACKEND=AwsSecretManager`)
- Test a full flow to see if it's working

### Tasks

```[tasklist]
# Tasks
- [x] Replace the environment variables in the helm charts (`SECRETS_BACKEND=AwsSecretManager`)
- [x] Give the service accounts permissions to put/read secrets from secretsmanager
- [x] Avoid secrets collision - the secrets manager is the same for all the environments unlike hashicorp Vault
- [x] Test a full flow to see if it's working
- [x] Store and read trustees config from secrets service (hashicorpVault and awsSecretsManager)
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/infrastructure/pull/23
- [ ] https://github.com/sequentech/gitops/pull/11
- [ ] https://github.com/sequentech/backend-services/pull/352
```

**Comment by BarelElbazDeveleap** [comment]
One thing you need to consider is that in the current setup, you have a separate vault (Hashicorp) per environment, when you use AWS secrets manager it is the same "vault" for all the environments (staging, apa ...)
Could we make sure we will not cause a secret collision/overlap?

We need to somehow append the environment name to the key name or something similar, what do you think?

**Comment by edulix** [comment]
I'll modify the PR to add a prefix to the secrets on your suggestion

**Comment by edulix** [comment]
What's the status of this? can we merge?

**Comment by BarelElbazDeveleap** [comment]
Waiting for your review on the trustee change:
https://github.com/sequentech/backend-services/pull/352
