### ISSUE TITLE
✨ Organize devops & infra repos

### ISSUE THREAD

**Issue by BarelElbazDeveleap** [sequentech/meta#542]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Clean up infrastructure and gitops repositories:
- Delete merged branches
- Put Parent Issue: <link> in PRs
- Keep branch naming convention feat/meta-XXX/<dest>
- Merge open PRs and close tickets

### Tasks

```[tasklist]
# Tasks
- [x] Delete merged branches
- [x] Put Parent Issue: <link> in PRs
- [x] Keep branch naming convention feat/meta-XXX/<dest>
- [x] Merge open PRs and close tickets
```

```[tasklist]
# Master PRs
- [ ] No PRs needed for this task
```

**Comment by BarelElbazDeveleap** [comment]
@edulix I organized the repos, you can take a look
