### ISSUE TITLE
✨ Continuous Deployment fully automated process

### ISSUE THREAD

**Issue by BarelElbazDeveleap** [sequentech/meta#543]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

We should automate the whole deployment process using GitHub actions
Argocd observes the gitops repo, we should create a branch and PR on gitops repo whenever a release is created on backend services
The PR should be opened per environment, and the deployment should happen on merge
We should deploy new images (replace the tags using the argo applications)
We should run Hasura migrations and similarities when needed

### Tasks

```[tasklist]
# Tasks
- [ ] Suggest a Design for the automated CD process and review it
- [ ] Trigger a GA workflow on the wanted trigger (e.g release is created on backend services repo)
- [ ] Branch out gitops per environments and change everything needed in the configuration
- [ ] Make argocd automatically syncs everything that enters main branch
- [ ] Block direct pushes to main branch for security and stability
- [ ] Automate the configuration updates based on the new versions
- [ ] Automate the hasura migration execution based on the changed files
```

```[tasklist]
# Master PRs
- [ ] PR 1
```

**Comment by colethienes** [comment]
> Add a github comment with a diff of changes in the PR for gitops

I have an app that does just this.  I recently released a Github app called Infro that several companies use internally that allows Argo CD users to preview Kubernetes changes in Github pull requests before they merge. I’m providing it for free to open source projects ([here’s](https://github.com/broersma-forslund/homelab/pull/158#issuecomment-1962289857) an example in the wild). [Here’s](https://medium.com/@colethienes/argocd-pull-request-checks-c863190c5f8c?source=friends_link&sk=2eda79520de33483591448c6dfe8d284) a setup guide with links to documentation. It’s in early stages, so I’m sure there will be warts. All feedback is welcome!
