### ISSUE TITLE
✨ Deploy pgaudit logs services to our environments

### ISSUE THREAD

**Issue by BarelElbazDeveleap** [sequentech/meta#544]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

We need the pgaudit logs service available in our Kubernetes envs
We need to define the service (Create a Dockerfile for production if needed)
Create a helm chart if needed
deploy it into the environment and make it works

### Tasks

```[tasklist]
# Tasks
- [ ] Understand the service & its purpose
- [ ] Create Dockerfile.prod if needed
- [ ] Create a helm chart if needed
- [ ] Deploy it via argocd if needed
- [ ] Make it works and communicates with other services
```

```[tasklist]
# Master PRs
- [ ] PR 1
```
