### ISSUE TITLE
✨ Enhance the system monitoring

### ISSUE THREAD

**Issue by BarelElbazDeveleap** [sequentech/meta#545]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Improve the environment monitoring by
Loki with S3 backend
Wazuh
Create a customized dashboard with relevant information (Define what is considered as relevant first)is 

### Tasks

```[tasklist]
# Tasks
- [ ] Connect Loki to S3 backend
- [ ] install Wazuh if needed
- [ ] Define the metrics we want to monitor
- [ ] Customize the dashboard to show interesting metrics
```

```[tasklist]
# Master PRs
- [ ] PR 1
```
