### ISSUE TITLE
✨ Implement Alerting service for the system

### ISSUE THREAD

**Issue by BarelElbazDeveleap** [sequentech/meta#546]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

If something is going wrong with one of the environments we want to be aware of it and get notifications:
1. Define the notifications channel (slack channel for example)
2. Define what alerts we want to get (define severity) @edulix 
3. Make the authentication with the notification channels (slackbot / token etc...)
4. Implement Grafana Alerts
5. Test alerting

### Tasks

```[tasklist]
# Tasks
- [ ] Define the notifications channel (slack channel for example)
- [ ] Define what alerts we want to get (define severity)
- [ ] Make the authentication with the notification channels (slackbot / token etc...)
- [ ] Implement Grafana Alerts
- [ ] Test alerting
```

```[tasklist]
# Master PRs
- [ ] PR 1
```
