### ISSUE TITLE
✨ Document the automated deployment process

### ISSUE THREAD

**Issue by BarelElbazDeveleap** [sequentech/meta#547]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Document the automated deployment process
Explain to @Findeton and have a recorded session

### Tasks

```[tasklist]
# Tasks
- [ ] Write down the documentation about the new automated CD process
- [ ] Explain Felix in a recorded session about the new proccess
```

```[tasklist]
# Master PRs
- [ ] PR 1
```

**Comment by edulix** [comment]
Already address in https://github.com/sequentech/meta/issues/543
