### ISSUE TITLE
✨ Implement test functionality in the CI process

### ISSUE THREAD

**Issue by BarelElbazDeveleap** [sequentech/meta#548]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Implement E2E test stages in the CI process
understand how to run test
implement the testing logic

### Tasks

```[tasklist]
# Tasks
- [ ] Understand how to dispatch tests
- [ ] Implement the testing logic in the CI workflow 
```

```[tasklist]
# Master PRs
- [ ] PR 1
```
