### ISSUE TITLE
✨ Print PDF vote receipt

### ISSUE THREAD

**Issue by KNTH01** [sequentech/meta#549]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Print to PDF a vote receipt

### Tasks

```[tasklist]
# Tasks
- [x] create hasura action => harvest endpoint
- [x] create windmill task
- [x] create default template, configurable
- [x] upload to s3 / minio
- [x] display / download pdf
- [x] finalize pdf default template
- [x] Create a new communication template with ballot receipt type and document communication method
- [x] Create a new Receipt type for election data
- [x] Filter communication templates by ballot receipt and document communication method
- [x] Attach the communication template to the election data
- [x] use the election data to serve the custom template to the end user
- [x] Add richtext editor for the ballot receipt document
- [x] Replace `https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js` cdn to a script from our private network
- [x] Same for logo: `https://sequentech.io/wp-content/uploads/2022/05/Sequent-logo-positive-1.svg`
- [x] Add styling possibility to the user template
- [x] Can we make a QR code that is more bulky? I'm not sure we need such a high resolution QR code.
- [x] Please add some more margin to the left, right and top. It looks too small.
- [x] update documentation for upload public-assets folder
- [x] move a magic number to global settings in voting portal
- [x] secure ballot hash before to generate PDF
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/backend-services/pull/348
- [ ] https://github.com/sequentech/backend-services/pull/366
- [ ] https://github.com/sequentech/backend-services/pull/374
- [ ] https://github.com/sequentech/backend-services/pull/377
```

### Additional context

[vote-receipt-9311419f39e7b47c9fef103df20036a9e0131571cb172bf83719b71a65065810.pdf](https://github.com/sequentech/meta/files/14419008/vote-receipt-9311419f39e7b47c9fef103df20036a9e0131571cb172bf83719b71a65065810.pdf)

**Comment by edulix** [comment]
This is not finished right? we're missing the securing of the hash
