### ISSUE TITLE
✨ Migrating 2nd-gen to reusable workflows

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#55]
```[tasklist]
### Tasks
- [x] renamed `roadmap` repo to `meta` (and `master` to `main`)
- [x] updated `meta` repo's description and README
- [x] created sample reusable workflow `update-flake.yml` and used it in `bulletin-board` repo successfully
- [x] migrating all the other 2nd-gen workflows and ensuring they work by using them in the `bulletin-board` repo
- [x] migrating `strand` repo to reusable workflows
- [ ] migrating `sequent-core` repo to reusable workflows (@findeton)
- [ ] migrating `new-ballot-verifier` repo to reusable workflows  (@findeton)
- [ ] migrating `braid` repo to reusable workflows (@findeton)
```

```[tasklist]
### PRs
- [ ] https://github.com/sequentech/strand/pull/80
- [ ] https://github.com/sequentech/strand/pull/80
```

**Comment by edulix** [comment]
unneeded, monorepo
