### ISSUE TITLE
✨ Transfer clusters ownership to an IAM role

### ISSUE THREAD

**Issue by BarelElbazDeveleap** [sequentech/meta#551]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Since Efi created the EKS cluster his user is the admin user in the kube-system/aws-auth
1. Create an IAM role with EKS permissions
2. This task is about transferring the ownership of the existing clusters
3. Ensure that future environments will be created by the IAM role by default

See this:
https://repost.aws/questions/QU5EORNOckTOawE11UnDxEVw/is-it-safe-to-delete-eks-cluster-creator-iam-user

### Tasks

```[tasklist]
# Tasks
- [ ] Create an IAM role with EKS permissions
- [x] This task is about transferring the ownership of the existing clusters
- [x] Ensure that future environments will be created by the IAM role by default
```

```[tasklist]
# Master PRs
- [ ] PR 1
```

**Comment by BarelElbazDeveleap** [comment]
We've looked into it, and deleting Efi's user shouldn't cause any trouble for our EKS setup.
Anyway, if you face some issues:
1. Create a fictive IAM user named efi (should be: `arn:aws:iam::581718213778:user/efi`)
2. Give it the EKS permissions (AmazonEKSAdminPolicy, AmazonEC2FullAccess, AmazonVPCFullAccess)

**Comment by edulix** [comment]
Barel info is great but we want to actually transfer ownership to do things properly with roles. Reopening this ticket, moving it to Q1.

**Comment by edulix** [comment]
@angelAtSequent is this done?

**Comment by angelAtSequent** [comment]
> @angelAtSequent is this done?

I would say so as per [docs](https://repost.aws/questions/QU5EORNOckTOawE11UnDxEVw/is-it-safe-to-delete-eks-cluster-creator-iam-user):

> So, deleting the cluster creator AWS IAM principal should only be done when you are absolutely sure that (1) you have an AWS IAM principal with adequate permissions to call all the Amazon EKS API commands you need to manage the cluster, and (2) you have an AWS IAM principal configured in RBAC with the kube-system/aws-auth configmap, with system:masters in order to manage Kubernetes RBAC for subsequent users and resources.

Now we can all of us (at least, felix you and I) execute terraform without errors, and also, we can manage the aws-auth configmap, so i'll say it's done and it's safe to delete barel IAM user

**Comment by angelAtSequent** [comment]
I don't think we need to create an IAM role to use it to create clusters, we just need to ensure we create EKS cluster with the KMS keys having multiple admin users (including the root account) and the aws-configmap contains multiple users (including the root account too). root account won't dissapear.

Example commit including these changes: https://github.com/sequentech/gitops/pull/158/files#diff-428adbec3b37c8143b648e4987486ed95746bf97b6d36dbae37f02111dd7467f

**Comment by angelAtSequent** [comment]
In addition, this would be automatically address with the ops-machine (it runs on ec2 with an iam role) #915

**Comment by Findeton** [comment]
Closing as this seems done.
