### ISSUE TITLE
✨ weighted voting support

### ISSUE THREAD

**Issue by sergiydmukhinepi** [sequentech/meta#552]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

We need to add support of weighted voting. This is a problem where a person has to vote the same way on several ballot papers. To simplify the procedure, the votes should be multiplied automatically.
Votes weighted by the number of voting power that each voter has. Like, voter 1 has 3 shares so his vote counts X3, voter 2 has 10 shares so X10

### Possible Implementation

Ballot papers are multiplied before anonymisation in MixNet
1. An election is equipped with an additional authentication field "multiplication factor"
3. Mixnet receives the factor and multiplies the ballots. The ballots are then shuffled as usual.
4. The verifier also needs to be adjusted so that it knows the relationship between the voter and the multiplication factor.

### Tasks

```[tasklist]
# Tasks
- [x] Initial code review for implementation design
- [x] ballot-box: Get the multiplication factor when dumping ballots and duplicate ballots accordingly
- [x] ballot-box: Put the multiplication factor and voterids in a file to be added to the tally.tar.gz
- [x] election-orchestra: Adapt to new format of input ballots
- [x] election-verifier: Check the multiplication factor for ballot duplication
- [x] Add election JSON documentation for how weighted voting support
- [x] Review and Approval by Client
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/ballot-box/pull/196
- [ ] https://github.com/sequentech/election-orchestra/pull/94
- [ ] https://github.com/sequentech/documentation/pull/146
- [ ] https://github.com/sequentech/election-verifier/pull/59
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/ballot-box/pull/193
- [ ] https://github.com/sequentech/election-orchestra/pull/90
- [ ] https://github.com/sequentech/documentation/pull/142
- [ ] https://github.com/sequentech/election-verifier/pull/56
```

**Comment by ruescasd** [comment]
For future reference

https://github.com/sequentech/backend-services/wiki/Notes-on-weighted-voting

**Comment by sergiydmukhinepi** [comment]
@edulix @Findeton 
I have finally set up the instance to test the issue. Looks good. Can be merged
