### ISSUE TITLE
🐞 Tally error

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#555]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

In Staging a tally didn't work, with this error in the logs:

```

2024-02-08T14:44:20.959785764Z │  │  │  ├──┘
2024-02-08T14:44:20.959795529Z │  │  │  ├── 80ms ERROR error=FromPipe(JsonParse(Error("invalid type: null, expected f64", line: 1, column: 2037)))
2024-02-08T14:44:20.960561135Z │  │  ├──┘
2024-02-08T14:44:20.960573919Z │  │  ├── 82ms ERROR error=FromPipe(JsonParse(Error("invalid type: null, expected f64", line: 1, column: 2037)))
2024-02-08T14:44:20.961133641Z │  ├──┘
2024-02-08T14:44:20.961512813Z │  ├──271ms ERROR error=Anyhow(FromPipe(JsonParse(Error("invalid type: null, expected f64", line: 1, column: 2037))))
2024-02-08T14:44:20.961533936Z ├──┘
2024-02-08T14:44:20.961541985Z ├──293ms ERROR error=Anyhow(Error executing tally session
2024-02-08T14:44:20.961545637Z │  
2024-02-08T14:44:20.961548564Z │  Caused by:
2024-02-08T14:44:20.961551937Z │      Anyhow(FromPipe(JsonParse(Error("invalid type: null, expected f64", line: 1, column: 2037)))))
2024-02-08T14:44:20.961554874Z ┘
```

### Expected Behavior

No error

### Environment

Staging. Couldn't reproduce locally.

### Tasks

```[tasklist]
# Tasks
- [ ] Issue has been triaged
- [ ] Successful replication of the defect
- [ ] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/353
- [ ] https://github.com/sequentech/backend-services/pull/354
```
