### ISSUE TITLE
✨ Add schedules to settings

### ISSUE THREAD

**Issue by ebadia** [sequentech/meta#556]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Add new dates crud with the following base dates:

- System lockdown for finalization of Internet voting settings
- Start and end of pre-registration for OVCS
- Start and end of test voting period
- Start and end of Internet voting period
- Date and time covering the schedule for the following activities:
- Lab test
- Field test
- Mock elections
- FTS

### Tasks

```[tasklist]
# Tasks
- [ ] add schedule tab to settings
- [ ] add predefined dates list
- [ ] add dates list
- [ ] add dates new and edit
- [ ] add delete date
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/backend-services/pull/355
```
