### ISSUE TITLE
🛡 Security updates

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#567]
### Tasks

```[tasklist]
# Tasks
- [x] Perform the security updates
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/common-ui/pull/380
- [ ] https://github.com/sequentech/election-portal/pull/227
- [ ] https://github.com/sequentech/election-portal/pull/229
- [ ] https://github.com/sequentech/voting-booth/pull/428
- [ ] https://github.com/sequentech/voting-booth/pull/429
- [ ] https://github.com/sequentech/admin-console/pull/413
- [ ] https://github.com/sequentech/election-orchestra/pull/86
- [ ] https://github.com/sequentech/frestq/pull/90
- [ ] https://github.com/sequentech/release-tool/pull/48
- [ ] https://github.com/sequentech/release-tool/pull/49
- [ ] https://github.com/sequentech/iam/pull/330
- [ ] https://github.com/sequentech/ballot-box/pull/191
- [ ] https://github.com/sequentech/frestq/pull/92
- [ ] https://github.com/sequentech/frestq/pull/94
- [ ] https://github.com/sequentech/election-orchestra/pull/88
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/common-ui/pull/381
- [ ] https://github.com/sequentech/election-portal/pull/228
- [ ] https://github.com/sequentech/election-portal/pull/230
- [ ] https://github.com/sequentech/voting-booth/pull/430
- [ ] https://github.com/sequentech/admin-console/pull/414
- [ ] https://github.com/sequentech/election-orchestra/pull/87
- [ ] https://github.com/sequentech/frestq/pull/91
- [ ] https://github.com/sequentech/release-tool/pull/50
- [ ] https://github.com/sequentech/iam/pull/331
- [ ] https://github.com/sequentech/ballot-box/pull/192
- [ ] https://github.com/sequentech/frestq/pull/93
- [ ] https://github.com/sequentech/frestq/pull/95
- [ ] https://github.com/sequentech/election-orchestra/pull/89
```
