### ISSUE TITLE
Bring up a new environment for Comelec

### ISSUE THREAD

**Issue by BarelElbazDeveleap** [sequentech/meta#568]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Bring up a new environment for comelec code name.
Record whatever you can to share the process later

### Tasks

```[tasklist]
# Tasks
- [x] Create the new environment in gitops repo
- [x] Configure the new environment modules in gitops
- [x] Deploy the infrastructure via terragrunt
- [x] Update the DNS records in Cloudflare
- [x] Create K8S namespaces
- [x] Adapt services configurations
- [x] deploy the services using Helm
- [x] Debug and troubleshoot - stabilize the new environment
- [x] Deploy argocd
- [x] Add the environment to the CD workflow
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/gitops/pull/22
- [ ] https://github.com/sequentech/infrastructure/pull/26
```

**Comment by edulix** [comment]
Done
