### ISSUE TITLE
🐞 Write-ins config not working

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#572]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

If a placeholder is not set in the write_in_config fields, the fields are not set.

### Expected Behavior

Allow write in fields without placeholder

### Steps To Reproduce

-

### Environment

1st gen

### Tasks

```[tasklist]
# Tasks
- [x] Make `placeholder`parameter optional.
- [x] Ensure it doesn't break voting booth.
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/ballot-box/pull/189
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/ballot-box/pull/187
```
