### ISSUE TITLE
🐞 Access denied S3 bucket when trying to print the ballot

### ISSUE THREAD

**Issue by BarelElbazDeveleap** [sequentech/meta#574]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

Access denied S3 bucket when trying to print the ballot
Check if there is a typo in sequent-comelec-bucket-us-east-1.s3.amazonaws.comtenant-90505c8a-23a9-4cdf-a26b-4e19f6a097d5.
DNS_PROBE_FINISHED_NXDOMAIN

### Expected Behavior

Show the PDF and be able to print it 

### Steps To Reproduce

Cast a ballot, try to print it

### Environment

- **OS**: Mac OS X Ventura
- **Web browser**: Google Chrome 112.0.5615.137 (Official Build) (arm64)
- **Sequent Platform Version**: 10.0.0

### Tasks

```[tasklist]
# Tasks
- [x] Fix the issue in the helm charts default values.yaml
- [x] Fix the issue in the environments
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/infrastructure/pull/27
- [ ] https://github.com/sequentech/gitops/pull/23
```
