### ISSUE TITLE
🐞 Demo Public Key as environment variable

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#575]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] #1001

### Current Behavior

The default public key at the moment is a magic number.

### Expected Behavior

Add an env var for the demo public key.

### Steps To Reproduce

-

### Environment

-

### Tasks

```[tasklist]
# Tasks
- [x] Add env var and use it instead of the magic constant.
- [x] Check that it works on voting portal and that it doesn't cast the ballot.
- [x] Add demo banner on voting portal.
- [x] Add demo dialog
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/472
```

**Comment by omri81** [comment]
Related issue:
