### ISSUE TITLE
🐞 Ahash error fix (again)

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#582]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

Related to https://github.com/sequentech/backend-services/pull/350

Error compiling windmill/braid/rust projects:

<img width="740" alt="Screenshot 2024-02-22 at 19 17 20" src="https://github.com/sequentech/meta/assets/3913223/70738c70-ff3f-4864-9116-dc6e0b0667d1">

### Expected Behavior

No compilation error

### Steps To Reproduce

1. Run codespace

### Proposed fix:

- update curve25519-dalek to 4.1.2
- Run: 

```
cargo update ahash@0.8
cargo update ahash@0.7
cargo update crc32c@0.6
```

### Environment

-

### Tasks

```[tasklist]
# Tasks
- [ ] Update required packages
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/369
```
