### ISSUE TITLE
Security dependencies and check release readiness

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#59]
```[tasklist]
## Tasks
- [x] Update security dependencies for the first gen.
- [x] [Check release readiness](https://sequentech.github.io/documentation/docs/general/contribute/production-readiness) (for example, github actions work).
```

```[tasklist]
## PRs 7.x
- [ ] https://github.com/sequentech/common-ui/pull/287
- [ ] https://github.com/sequentech/admin-console/pull/358
- [ ] https://github.com/sequentech/voting-booth/pull/315
- [ ] https://github.com/sequentech/election-portal/pull/189
- [ ] https://github.com/sequentech/voting-booth/pull/317
- [ ] https://github.com/sequentech/common-ui/pull/290
- [ ] https://github.com/sequentech/admin-console/pull/360
- [ ] https://github.com/sequentech/election-portal/pull/191
- [ ] https://github.com/sequentech/release-tool/pull/35
- [ ] https://github.com/sequentech/ballot-verifier/pull/21
- [ ] https://github.com/sequentech/mixnet/pull/17
- [ ] https://github.com/sequentech/misc-tools/pull/50
- [ ] https://github.com/sequentech/election-orchestra/pull/60
- [ ] https://github.com/sequentech/frestq/pull/65
- [ ] https://github.com/sequentech/tally-pipes/pull/99
- [ ] https://github.com/sequentech/tally-methods/pull/72
- [ ] https://github.com/sequentech/deployment-tool/pull/328
- [ ] https://github.com/sequentech/iam/pull/275
```

```[tasklist]
## PRs master
- [ ] https://github.com/sequentech/common-ui/pull/289
- [ ] https://github.com/sequentech/admin-console/pull/359
- [ ] https://github.com/sequentech/voting-booth/pull/316
- [ ] https://github.com/sequentech/election-portal/pull/190
- [ ] https://github.com/sequentech/voting-booth/pull/318
- [ ] https://github.com/sequentech/common-ui/pull/291
- [ ] https://github.com/sequentech/admin-console/pull/361
- [ ] https://github.com/sequentech/election-portal/pull/192
- [ ] https://github.com/sequentech/release-tool/pull/36
- [ ] https://github.com/sequentech/ballot-verifier/pull/22
- [ ] https://github.com/sequentech/mixnet/pull/18
- [ ] https://github.com/sequentech/misc-tools/pull/51
- [ ] https://github.com/sequentech/election-orchestra/pull/61
- [ ] https://github.com/sequentech/frestq/pull/66
- [ ] https://github.com/sequentech/tally-pipes/pull/100
- [ ] https://github.com/sequentech/tally-methods/pull/73
- [ ] https://github.com/sequentech/deployment-tool/pull/329
- [ ] https://github.com/sequentech/iam/pull/276
```
