### ISSUE TITLE
🐞 Deployment error version `GLIBC_2.32' not found 

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#590]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by bb_helper)

Related to: https://github.com/sequentech/meta/issues/582

### Expected Behavior

No deployment error.

### Steps To Reproduce

See logs for rust deployments

### Environment

staging

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [x] update debian to bookworm to use glibc > 2.31
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/371
```
