### ISSUE TITLE
✨ Eligibility verifiability

### ISSUE THREAD

**Issue by ruescasd** [sequentech/meta#594]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

```[tasklist]
- [ ] Server side key generation
- [ ] Client side signing
- [ ] Server-side cast time verification
- [ ] Cryptographic board artifact
- [ ] Verifier checks
```

### Tasks

# Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Main PRs
- [ ] PR 1
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```
