### ISSUE TITLE
Fix problems with automatic translation in google chrome

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#60]
## Problem description

In some cases, the web browser automatically translates the frontend web sites when it shouldn't. EPI has reported this happening in a case in which the whole website is already in english, but the browser detects the german article `die` as an english word and translate it to the english translation of the word `die`. Not good.

## Proposed Solution

Add to `config.yml` a parameter `config.sequent_ui.prevent_site_translation` that is `false` by default, but when enabled it sets the `translate="no"` attribute to the `<html>` element . [`translate`is an official HTML5 attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/translate) that indicates that the content of this element should not be translated.

## Rationale

Adding the `translate="no"` attribute should prevent the browser from translating what it shouldn't. Note that, we are already indicating the language of the content in the HTML element, so it should not be translating from that language. And if the text language is for example "german" and the user wants a translation to "arabic", we would be preventing that from happening. For that reason, this should not be enabled by default. But in any specific deployment, it can be set.

```[tasklist]
## Tasks
- [x] Add the `prevent_site_translation` parameter to `SequentConfig.js` and apply it in the `voting-booth` repository.
- [x] Add the `prevent_site_translation` parameter to `SequentConfig.js` and apply it in the `admin-console` repository.
- [x] Add the `prevent_site_translation` parameter to `SequentConfig.js` and apply it in the `election-portal` repository.
- [x] Add the `prevent_site_translation` parameter to `config.yml` (including the multiple `config.yml` files in the `doc/` folder) and apply it in the `deployment-tool` repository.
- [x] Update the `config.yml` examples in the `documentation` repository.
```

```[tasklist]
## Master PRs
- [ ] https://github.com/sequentech/deployment-tool/pull/324
- [ ] https://github.com/sequentech/voting-booth/pull/310
- [ ] https://github.com/sequentech/election-portal/pull/185
- [ ] https://github.com/sequentech/admin-console/pull/349
- [ ] https://github.com/sequentech/documentation/pull/111
```

```[tasklist]
## 7.2.x PRs
- [ ] https://github.com/sequentech/voting-booth/pull/309
- [ ] https://github.com/sequentech/deployment-tool/pull/323
- [ ] https://github.com/sequentech/election-portal/pull/184
- [ ] https://github.com/sequentech/admin-console/pull/348
```
