### ISSUE TITLE
✨ Voter payment support with Adyen

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#603]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Voter payment support with Adyen

### Possible Implementation
Generic:

1. Please check the document at: https://docs.adyen.com/online-payments/build-your-integration/?platform=Web
2. Ayden: Configure one single company and a merchant account for each Project
3. Ayden: create a user for each deployment

AZM Project:

1. The payment process should appear during the registration process after the user has filled in the following information:
2. Name, Lastname, DoB, Phone number, email address(please ask the user to retype the email and they Phone number to ensure there are no errors)
3. Once the payment has been submitted, the system will:
- register in the system the successful transition as one of the fields in the voter information ( boolean, TRUE, FALSE)
- send an email with an OTP to the user to the registered email address
- The voting portal will show a screen where he will need to input the email OTP, request a new one, and have the ability to change the email address  previously registered
4. Once the email OTP has been successfully verified, the system will:
- send an SMS with an OTP to the user to the registered phone number
- The Voting portal will show a screen where he will need to input the SMS OTP, request a new one, and have the ability to change the phone number previously registered

Payment methods allowed For AZM:

- ACH Direct   Debit
- Amazon Pay
- Apple Pay
- Cash App Pay
- Google Pay™️
- JCB
- Maestro
- Mastercard
- Samsung Pay
- Visa
- American Express (AMEX)

NOTE: Additional information can be shown in the registration process as a toll-free phone number for support

_No response_

### Tasks

# Screenshots

<empty>

```[tasklist]
# Tasks
- [x] Demo: Show initial adyen payment form
- [x] Demo: Implement adyen callback
- [x] Demo: Prefill User Name in Adyen
- [x] Demo: Create "User Attribute - assign" authenticator to assign tenant-id and area-id
- [x] Demo: Configure Validate Email
- [x] Demo: Configure Validate Tlf
- [x] Demo: Configure CSS
- [ ] PerformancePeriod: Move the payment form to be a Required Action
- [ ] PerformancePeriod: Configure Email Verification as a Required Action
- [ ] PerformancePeriod: Configure Tlf Verification as a Required Action
- [ ] PerformancePeriod: Add "validate email" and "validate telephone" fields to the registration
- [ ] PerformancePeriod: Implement correct token callback
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/396
```

### Additional context

The system will handle errors for refused payments and allow the users to modify their payment information[ACH Direct Debit](https://www.adyen.com/payment-methods/ach-direct-debit)
[Amazon Pay](https://www.adyen.com/payment-methods/amazon-pay)
[Apple Pay](https://www.adyen.com/payment-methods/apple-pay)
[Cash App Pay](https://www.adyen.com/payment-methods/cash-app-pay)
[Google Pay™️](https://www.adyen.com/payment-methods/google-pay)
[JCB](https://www.adyen.com/payment-methods/jcb)
[Maestro](https://www.adyen.com/payment-methods/maestro)
[Mastercard](https://www.adyen.com/payment-methods/mastercard)
Samsung Pay
[Visa](https://www.adyen.com/payment-methods/visa)
[American Express (AMEX)](https://www.adyen.com/payment-methods/american-express)
