### ISSUE TITLE
🐞 admin-portal: Election Event -> Publish tab: status not correctly updated when changing tab

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#610]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

admin-portal: Election Event -> Publish tab: status not correctly updated when changing tab. See video below:

https://github.com/sequentech/meta/assets/81968/64a709af-fa91-4310-b432-fbd2a77be98d

### Expected Behavior

Should work as expected

### Steps To Reproduce

-

### Environment

-

### Tasks

```[tasklist]
# Tasks
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/376
```
