### ISSUE TITLE
✨ Add env vars

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#611]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Add missing env vars

### Tasks

# Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] Add env vars to infrastructure
- [ ] Add env vars to gitops
```

```[tasklist]
# Main PRs
- [ ] PR 1
```
