### ISSUE TITLE
Set up bulletin-board documentation 

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#62]
## Enhancement description

Create the documentation for the bulletin-board following the divio [4-types of documentation](https://documentation.divio.com/introduction/).

```[tasklist]

## Tasks

- [x] Configure reference documentation generation with rustdoc with a vscode task in `tasks.json` and a vscode plugin, to make it work in the development environment.
- [ ] Initial reference documentation.
- [ ] Automate documentation deployment with netlify, including all types of documentation, with automated PR preview deployments and using a github reusable workflow from the `meta` repo.
- [x] Configure initial narrative documentation with docusaurus in the repository in the `doc/` directory, opening the right ports in vscode devcontainers for it to work there.
- [ ] Initial narrative documentation following Divio 4-types of documentation for the bulletin-board.
````
