### ISSUE TITLE
✨ support allowing to disable candidates

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#620]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Support allowing to disable candidates to be hidden in the voting portal. The candidate should be able to be enabled/disabled from the admin portal, this would be reflected only after a new publication, and then reflected in the voting portal by not showing the candidate in the ballot.

Note that this has nothing to do with the tally: anyone having voted to this candidate would still be normally counted.

### Screenshots

New option in the candidate to disable it.
<img width="1440" alt="image" src="https://github.com/sequentech/meta/assets/81968/f35fa859-4a33-4dde-9b15-ef3f6e8cf40e">

And when disabled, it disappears from the voting portal.

### Tasks

# Screenshots

<empty>

```[tasklist]
# Tasks
- [x] sequent-core/ui-essentials: Add `candidate.presentation.is_disabled` boolean field
- [x] admin-portal: Add boolean input to mark a candidate as disabled
- [x] voting-booth: hide candidates with `candidate.presentation.is_disabled` set to `true`
- [x] voting-booth: fixed global-settings.json missing a comma
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/378
```
