### ISSUE TITLE
✨ Update keycloak realms config env var on staging and test

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#622]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

Update keycloak realms config env var on staging and test

### Expected Behavior

-

### Steps To Reproduce

-

### Environment

-

### Tasks

```[tasklist]
# Tasks
- [ ] TODO
```

```[tasklist]
# Main PRs
- [ ] PR 1
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```
