### ISSUE TITLE
🐞 Voting Portal: Election lists shows "empty" when loading

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#632]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

Voting Portal: Election lists shows "empty" when loading.

### Expected Behavior

Should show a loading indicator instead.

### Steps To Reproduce

-

### Environment

-

### Tasks

```[tasklist]
# Tasks

```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/397
```
