### ISSUE TITLE
🐞 Deployment fixes for Dev environment (2nd gen)

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#638]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

Deployment not finished.

### Expected Behavior

Deployment fully working.

### Steps To Reproduce

-

### Environment

-

### Tasks

```[tasklist]
# Tasks
- [ ] Fix rabbitmq deployment.
- [ ] configure loki/graphana/prometheus.
- [ ] update gitops env values.
- [ ] Check trustees config.
- [ ] Full check for environment.
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/gitops/pull/43
- [ ] https://github.com/sequentech/infrastructure/pull/31
```
