### ISSUE TITLE
🐞 Admin/Voting portal fixes

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#645]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

-

### Possible Implementation

-

### Tasks

# Screenshots

<empty>

```[tasklist]
# Tasks
- [x] list not working, type, candidate
- [x] contest translation title, description not working
- [x] candidates have no translation
- [x] candidate images not seen in voting portal
- [x] add link to candidate
- [x] enable deleting images
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/380
- [ ] https://github.com/sequentech/backend-services/pull/383
- [ ] https://github.com/sequentech/backend-services/pull/384
- [ ] https://github.com/sequentech/backend-services/pull/385
- [ ] https://github.com/sequentech/backend-services/pull/386
```
