### ISSUE TITLE
✨ COMELEC Demo

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#655]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Integration with Inetum IAM

### Tasks

# Screenshots

<empty>

```[tasklist]
# Tasks
- [x] Inetum: Initial SDK integration
- [x] migrate to keycloak 24.0
- [x] Modified Registration form that does not create an user (deferring it to do that later, after collecting more evidence)
- [x] Update user after inetum step, looking up the user using configurable field(s) from auth-notes and updating the user config again with configurable auth-notes config, and only if that user has no credentials
- [x] Migrate clients to support keycloak 24.0. This can be done for the particular client in the {project_name} Admin Console, in client details > Advanced > in the section with `OpenID Connect Compatibility Modes`. Dedicated `Exclude Issuer From Authentication Response` switch exists, which can be turned on to prevent adding the `iss` parameter to the authentication response.
- [x] Inetum: Call `create/new` from the backend
- [x] Inetum: send the form with the results to the keycloak backend
- [x] Inetum: call back to Inetum from the backend to receive the status and save it internally
- [x] Add initial registration step that collects email and password, with a lookup step that adds that to the user if
- [x] Add a "choose document type step" that is used by the InetumAuthenticator
- [x] Show correctly the VerifyEmail and chooseMFA steps afterwards
- [x] Implement `Verify Email with OTP RA`
- [x] Add `Registration success page`
- [ ] Add passkeys support https://keycloak.ch/keycloak-tutorials/tutorial-passkey/
- [ ] Add `Registration failure page` with a code to show and register if there was any error during registration
- [ ] Translate to english
- [ ] Add `IdpPhoneVerificationAuthenticator` similar to `IdpEmailVerificationAuthenticator`, but for SMS
- [ ] Implement a `RealmResourceProvider` that verifies the user and generates a link with a token that: 1. resets password, 2. verifies the user (`VERIFIED`) setting the appropriate property
- [ ] Implement a Rust endpoint that calls the given `RealmResourceProvider` and generates a PDF with the QR code link and save it.
- [ ] Link the Rust endpoint in hasura.
- [ ] Call the Rust endpoint from the admin portal.
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/393
- [ ] https://github.com/sequentech/backend-services/pull/406
- [ ] https://github.com/sequentech/backend-services/pull/410
- [ ] https://github.com/sequentech/infrastructure/pull/36
- [ ] https://github.com/sequentech/backend-services/pull/413
- [ ] https://github.com/sequentech/backend-services/pull/414
```
