### ISSUE TITLE
✨ check license headers with `reuse` tool

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#657]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

github action to check license headers with `reuse`

### Tasks

# Screenshots

<empty>

```[tasklist]
# Tasks
- [x] Add Github Action checking license headers
- [x] Add VS Code Task to check license headers
- [x] Add missing license headers
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/427
```
