### ISSUE TITLE
🐞 Documentation: OIDC config is using wrongly named `private_config` vs `private_info` field

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#659]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

Documentation: OIDC config is using wrongly named `private_config` vs `private_info` field

### Expected Behavior

-

### Steps To Reproduce

-

### Environment

-

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [x] Successful defect resolution merged
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/documentation/pull/143
```

**Comment by edulix** [comment]
Reported by @sergiydmukhinepi
