### ISSUE TITLE
✨ Keycloak: Implement and use in production AWS SES Email Provider

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#660]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Keycloak: Implement and use in production AWS SES Email Provider.

### Tasks

```[tasklist]
# Tasks
- [x] Implement the AWS SES Email provider
- [x] Use the AWS SES Email Provider in staging
- [x] Use the AWS SES Email Provider in other envs
- [x] Implement AWS SES permissions correctly in Terraform/Kubernetes
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/382
- [ ] https://github.com/sequentech/gitops/pull/78
- [ ] https://github.com/sequentech/infrastructure/pull/32
- [ ] https://github.com/sequentech/backend-services/pull/387
- [ ] https://github.com/sequentech/infrastructure/pull/33
- [ ] https://github.com/sequentech/gitops/pull/83
- [ ] https://github.com/sequentech/gitops/pull/84
- [ ] https://github.com/sequentech/gitops/pull/97
- [ ] https://github.com/sequentech/backend-services/pull/401
```

**Comment by edulix** [comment]
@angelAtSequent is anything missing here? can we close this?

**Comment by angelAtSequent** [comment]
> @angelAtSequent is anything missing here? can we close this?

After todays meeting explaining how to test sms and email sending, i'll review every environment:

- [ ] us-east-1/**apa**
  - version: 
  - [ ] sms
  - [ ] email
- [ ] us-east-1/**comelec**
  - version: 
  - [ ] sms
  - [ ] email
- [ ] us-east-1/**dev**
  - version: 
  - [ ] sms
  - [ ] email
- [ ] us-east-1/**staging**
  - version: 
  - [ ] sms
  - [ ] email
- [ ] us-east-1/**ua**
  - version: 
  - [ ] sms
  - [ ] email
- [ ] eu-west-1/**ualicante**
  - version: 
  - [ ] sms
  - [ ] email
- [ ] eu-west-1/**ciccp**
  - version: 
  - [ ] sms
  - [ ] email

**Comment by angelAtSequent** [comment]
Anyway we have the following action points:

- Fix the SMS sending error. @edulix is working on it
- ualicante doesn't work (admin-portal). 
- Keycloack default/template realm need some tweaks, otherwise, on every new election event someone has to configure somethings on keycloak (email sender and host at minimum + the app url)
- the **ua** environment doesn't work correctly (the voting portal can not send emails, so users can not access).
