### ISSUE TITLE
Multi-repo release notes

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#67]
# Problem Description

Partners and technical users of the software want to know what's new in each new release without having to read each of the 10+ repositories involved in each release.

# Solution description

Improve the release tool to not only generate the release notes for each repository, but also a general release notes that includes all the changes from all repos without duplications.

```[tasklist]
# Tasks
- [ ] New per-repository release-notes generation script that includes not only PRs but also the parent issue instead if it does exist
- [ ] New script to update old PRs to add relations to parent issues when existing
- [ ] Create a bot that ensures there's a relation the parent issue automatically when needed
- [ ] Create a release script to include the generation of release-notes in the meta repository, creating comprehensive release notes from all the other repositories.
- [ ] Update the release documentation to reflect step by step how to do a release in the future
- [ ] Generate the comprehensive release notes for the 7.3.0 release 
```

```[tasklist]
## PRs 7.x
```

```[tasklist]
## PRs master
```

**Comment by edulix** [comment]
Here is a Gist with some information about licensing code from chatgpt https://gist.github.com/edulix/28ef593b6ba328e7d539a86113bdc9ab

**Comment by edulix** [comment]
Waiting for a github support ticket to be resolved to continue.
