### ISSUE TITLE
🐞 question-extra-invalid_vote_policy doesn't work

### ISSUE THREAD

**Issue by sergiydmukhinepi** [sequentech/meta#678]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

This parameter no longer works.
https://sequentech.github.io/documentation/docs/general/reference/election-creation-json#question-extra-invalid_vote_policy

### Expected Behavior

like discreibed

### Steps To Reproduce

https://gist.github.com/sergiydmukhinepi/7a80b0eb1c954e7635d8da759d635ed6

### Environment

- **OS**: Mac OS X Ventura
- **Web browser**: Google Chrome 112.0.5615.137 (Official Build) (arm64)
- **Sequent Platform Version**: 10.0.0

### Tasks

```[tasklist]
# Tasks
- [x] Add class to question numeration on review page.
- [x] Fix showing blank selections on questions with only write-ins.
- [x] Show red border on write-in fields with min/max over the limits.
- [x] Enable utf-8 characters on titles of error messages (including on dialog).
- [x] Don't show blank question error  on `allowed` invalid vote policy.
- [x] Show tranlasted name of field instead of id on write-in field errors.
- [x] Don't show write-in max/min errors on `allowed` invalid vote policy.
```

```[tasklist]
# 10.2.x PRs
- [ ] https://github.com/sequentech/voting-booth/pull/433
- [ ] https://github.com/sequentech/documentation/pull/144
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/voting-booth/pull/432
- [ ] https://github.com/sequentech/documentation/pull/145
```

**Comment by sergiydmukhinepi** [comment]
@Findeton Unfortunately, your change does not help. The message appears regardless of whether I set the parameter to "allowed" or not. 
![image](https://github.com/sequentech/meta/assets/154313589/a6218e43-b103-4e35-8d83-a45a6660ece5)

**Comment by sergiydmukhinepi** [comment]
@Findeton The write_in_config field ids are used instead of labels to indicate the violation of the filed length constraints.
![image](https://github.com/sequentech/meta/assets/154313589/4786f807-7e0a-4095-958a-a6c539f32c97)

**Comment by sergiydmukhinepi** [comment]
@Findeton The second warning in the previous screenshot just appears, whatever you do, it's there and I don't know why.

**Comment by sergiydmukhinepi** [comment]
@Findeton Blank questions appear on the review screen
![image](https://github.com/sequentech/meta/assets/154313589/1190c2f8-c286-4012-a237-c76bc02d0137)

**Comment by sergiydmukhinepi** [comment]
@Findeton Now I no longer get any warnings. When I fill in a field with a shorter string, as well as when completed fields are submitted without a tick.

**Comment by sergiydmukhinepi** [comment]
@Findeton The UTF characters in the warnings are also not displayed correctly.
![image](https://github.com/sequentech/meta/assets/154313589/1e75ec4b-002b-4355-bd36-547cbbc5b3df)

**Comment by Findeton** [comment]
Hi @sergiydmukhinepi I'm still working on this, I forgot to move it to the "In Progress" column.

**Comment by sergiydmukhinepi** [comment]
Hi @Findeton I have tested the new version and it looks better. Unfortunately, a few things are still missing. I don't understand why the message appears. It only appears in the first question when I enter something. Everything seems to be fine.
![image](https://github.com/sequentech/meta/assets/154313589/872ed1de-d278-407e-84c5-8305573c7057)

The problem with the UTF characters still exists
![image](https://github.com/sequentech/meta/assets/154313589/da6ef2e9-9fb0-4efb-a55f-1529881cf8ee)

**Comment by sergiydmukhinepi** [comment]
@Findeton Looks good. You can merge it
