### ISSUE TITLE
🐞 Not all error messages are translated

### ISSUE THREAD

**Issue by sergiydmukhinepi** [sequentech/meta#680]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

OIDC errors are not translated
![image](https://github.com/sequentech/meta/assets/154313589/54d1c76e-d718-467d-bf62-cbf709631aef)
Please review

### Expected Behavior

Localised text should appear

### Steps To Reproduce

https://demo.gremienwahlen.de/election/222397/public/login

### Environment

- **Sequent Platform Version**: 10.2.0

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [x] Successful defect resolution merged
```

```[tasklist]
# 10.2.x PRs
- [ ] https://github.com/sequentech/common-ui/pull/384
```

```[tasklist]
# master PRs
- [ ] https://github.com/sequentech/common-ui/pull/386
```

**Comment by sergiydmukhinepi** [comment]
@Findeton Looks good
