### ISSUE TITLE
🐞 OIDC automatically authentication with no clicking

### ISSUE THREAD

**Issue by sergiydmukhinepi** [sequentech/meta#681]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

 it might be a bug, it seems like it's trying to automatically authenticate with no clicking
![image](https://github.com/sequentech/meta/assets/154313589/54d1c76e-d718-467d-bf62-cbf709631aef)

### Expected Behavior

no error, no auto click

### Steps To Reproduce

https://demo.gremienwahlen.de/election/222397/public/login

### Environment

- **Sequent Platform Version**: 10.2.0

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [ ] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] PR 1
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/common-ui/pull/383
```

**Comment by edulix** [comment]
We haven't been able to replicate the issue in our own branch, please provide a configuration that can replicate it. However, please try branch https://github.com/sequentech/common-ui/pull/383 to see if it solves the issue.

**Comment by sergiydmukhinepi** [comment]
@edulix You can find the configuration in the email I sent out on 11 March.
