### ISSUE TITLE
Can't duplicate election when editing date extra field

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#70]
## Problem description

Election creation fails when duplicating some elections.

## How to reproduce

1. Login in the admin console
2. Create this election https://gist.github.com/edulix/fc2fbbfac6d43434425e751f0049caed
3. click in "duplicate the election" in the election dashboard
4. go to the Census Configuration tab, click to edit the Date of birth field. Don't edit it, just click to edit.
5. Go to the create election tab and try to create it.
6. It fails

## Expected result

It shouldn't fail to create the election. Also, editing date extra fields should allow to configure the different extra field params.

```[tasklist]
# Tasks
- [x] `common-ui` repository: ensure that when the election creation request never includes the `value` key for `extra_fields` objects.
- [x] `admin-console` repository: Update the extra-field listing screen to allow configure different extra-field params for `date` extra field type (and other types). 
```

```[tasklist]
## Stable PRs
- [ ] https://github.com/sequentech/common-ui/pull/295
- [ ] https://github.com/sequentech/admin-console/pull/365
```

```[tasklist]
## Master PRs
- [ ] https://github.com/sequentech/admin-console/pull/366
- [ ] https://github.com/sequentech/common-ui/pull/296
```
