### ISSUE TITLE
🐞 APA fixes

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#701]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

Some bugs were discovered on APA deployment.

### Expected Behavior

No bugs

### Steps To Reproduce

-

### Environment

- **Env**: APA

### Tasks

```[tasklist]
# Tasks
- [x] Null description on election event translation is inconsistent with rust type and blocks ballot publication.
- [x] Can't reorder candidates.
- [ ] sorting from tab to tab is kept and doesn't work
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/392
```
