### ISSUE TITLE
✨ Check if the authorities are online

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#704]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Colored indication in the dashboard that authorities have been started

![Image](https://github.com/sequentech/epi/assets/87812708/f7ec6ec6-1de5-4766-a900-887086c65c2a)

Before start tally authorities have to be checked, if they are online. Warning should be raised if not.

Replaces ticket: https://github.com/sequentech/epi/issues/36

### Possible Implementation

-

### Tasks

# Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/ballot-box/pull/197
- [ ] https://github.com/sequentech/election-orchestra/pull/95
- [ ] https://github.com/sequentech/admin-console/pull/420
- [ ] https://github.com/sequentech/iam/pull/337
- [ ] https://github.com/sequentech/documentation/pull/147
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/ballot-box/pull/194
- [ ] https://github.com/sequentech/election-orchestra/pull/91
- [ ] https://github.com/sequentech/admin-console/pull/416
- [ ] https://github.com/sequentech/iam/pull/335
- [ ] https://github.com/sequentech/documentation/pull/148
```

**Comment by sergiydmukhinepi** [comment]
@Findeton The indicator works, but the check to see if the trustees are online before starting the tally isn't implemented yet. And it would be great if you could add the same check before creating the election.
