### ISSUE TITLE
✨ Enable selecting blank answers

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#706]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Enable selecting blank answers.

### Tasks

# Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] Add selector for blank answers.
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/voting-booth/pull/435
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/voting-booth/pull/434
```
