### ISSUE TITLE
🐞 Invalid vote policy

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#711]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

Fix `invalid_vote_policy`, also add `warn-explicit-not-allowed`.

### Expected Behavior

-

### Tasks

```[tasklist]
# Tasks
- [ ] Issue has been triaged
- [ ] Successful replication of the defect
- [ ] Successful defect resolution merged
```

```[tasklist]
# 10.3.x PRs
- [ ] https://github.com/sequentech/voting-booth/pull/436
```

```[tasklist]
# master PRs
- [ ] https://github.com/sequentech/voting-booth/pull/437
```

**Comment by markgrafd** [comment]
@Findeton Thank you, very much!!

**Comment by sergiydmukhinepi** [comment]
@Findeton Do I understand correctly that you have added a new invalid voting policy warn-explicit-not-allowed? Have you also updated the documentation?

**Comment by Findeton** [comment]
@sergiydmukhinepi sorry, I've updated the ticket now. I haven't added any new policies at all. I've modified the existing policies so that if there's an explicit invalid vote, then that's what counts.
