### ISSUE TITLE
🐞 Total number of valid votes not displayed in percentage in Velvet

### ISSUE THREAD

**Issue by KNTH01** [sequentech/meta#713]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

![image](https://github.com/sequentech/meta/assets/1632391/5e95ac00-38ae-4048-96cf-5a9e71d6c1f7)

### Expected Behavior

-

### Steps To Reproduce

-

### Environment

-

### Tasks

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/402
```

![image](https://github.com/sequentech/meta/assets/1632391/7fc1fbb4-c5a3-4510-b930-8babae19ed92)

**Comment by KNTH01** [comment]
Resolved here: https://github.com/sequentech/backend-services/pull/403
