### ISSUE TITLE
✨ Pipe to generate PDF with Vote Receipt

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#714]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Pipe to generate PDF with Vote Receipt:
- One file per vote
- Generate QR code with the data inside the vote receipt
- Include a template argument to make it configurable
- Show the content of the vote similar to the verifier or review screen

### Tasks

# Screenshots

<empty>

```[tasklist]
# Tasks
- [x] todo
- [ ] Make velvet and pipe configuration possible from the admin portal
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/403
```
