### ISSUE TITLE
🐞 Results PDF cuts result tables

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#715]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

If a results table doesn't fit into one page, the PDF cuts it instead of spreading it over the next page.

Related: https://github.com/pagedjs/pagedjs/issues/149

### Expected Behavior

-

### Steps To Reproduce

-

### Environment

- **OS**: Mac OS X Ventura
- **Web browser**: Google Chrome 112.0.5615.137 (Official Build) (arm64)
- **Sequent Platform Version**: 10.0.0

### Tasks

```[tasklist]
# Tasks
- [x] Remove use of pagedjs to avoid cutting tables. This removes page numbers but it's better than removing candidates.
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/404
```
