### ISSUE TITLE
🐞 OIDC: Use Authorization Code Flow instead of implicit flow

### ISSUE THREAD

**Issue by sergiydmukhinepi** [sequentech/meta#716]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

I have been testing the OIDC with other client and got same issue as last time. The implicit flow will not be supportet in the next version
https://github.com/jhipster/generator-jhipster/issues/21636
https://oauth.net/2.1/
So it will be dropped and we will have same issue with all clients.

### Expected Behavior

Use Authorization Code Flow instead of implicit flow

### Steps To Reproduce

OIDC

### Environment

- **OS**: Mac OS X Ventura
- **Web browser**: Google Chrome 112.0.5615.137 (Official Build) (arm64)
- **Sequent Platform Version**: 10.0.0

### Tasks

```[tasklist]
# Tasks
- [ ] Issue has been triaged
- [ ] Successful replication of the defect
- [ ] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/common-ui/pull/391
- [ ] https://github.com/sequentech/iam/pull/340
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/common-ui/pull/388
- [ ] https://github.com/sequentech/iam/pull/338
- [ ] https://github.com/sequentech/iam/pull/339
```

**Comment by sergiydmukhinepi** [comment]
@Findeton Please improve error handling as discussed. For example, if the oidc provider has disabled the client.
