### ISSUE TITLE
Release release 10.3.0

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#748]
### Tasks

```[tasklist]
# Tasks
- [x] Tag the release
- [x] Create releases with automatic release notes in github
- [x] Test the release
- [ ] Deploy release in stable <major>xx deployment
- [ ] Deploy release in demo
- [ ] Deploy release in web-demo
```
