### ISSUE TITLE
✨ French/Catalan for Voting Portal

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#749]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Add French/Catalan support for Voting Portal (2nd gen).

### Tasks

# Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] Add french/catalan langs.
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/425
```
