### ISSUE TITLE
Security dependencies update

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#75]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Security dependencies update

### Tasks

```[tasklist]
# Tasks
- [ ]  Update security dependencies for the 1st-gen platform.
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/iam/pull/277
- [ ] https://github.com/sequentech/election-orchestra/pull/62
- [ ] https://github.com/sequentech/frestq/pull/67
- [ ] https://github.com/sequentech/common-ui/pull/298
- [ ] https://github.com/sequentech/common-ui/pull/300
- [ ] https://github.com/sequentech/voting-booth/pull/325
- [ ] https://github.com/sequentech/election-portal/pull/196
- [ ] https://github.com/sequentech/admin-console/pull/368
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/iam/pull/280
- [ ] https://github.com/sequentech/election-orchestra/pull/63
- [ ] https://github.com/sequentech/frestq/pull/68
- [ ] https://github.com/sequentech/common-ui/pull/297
- [ ] https://github.com/sequentech/common-ui/pull/299
- [ ] https://github.com/sequentech/voting-booth/pull/324
- [ ] https://github.com/sequentech/election-portal/pull/195
- [ ] https://github.com/sequentech/admin-console/pull/367
```
