### ISSUE TITLE
✨ Parity algorithm and Invalid vote policy

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#750]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Add parity option for plurality-at-large questions (2nd gen). This means each candidate should be marked as either man/woman. There should also be a configurable maximum number of candidates from the same sex that can be voted (and if you go over that, it should be an implicit null vote). In the voting portal, the candidates should be separated by sex, even from the same list, as shown in the image.

For example, if the maximum number of candidates to be selected is 6 and the maximum number of candidates from the same sex is 3, then you could vote to only 3 candidates, all of them men. 

https://www.boua.ua.es/pdf.asp?pdf=2658.pdf

![image (3)](https://github.com/sequentech/meta/assets/3913223/222934f7-a169-46c7-9f7b-33c8972b54ff)

### Tasks

# Screenshots

<empty>

```[tasklist]
# Tasks
- [x] Implement parity policy.
- [x] Implement invalid vote policy on voting portal.
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/424
```
