### ISSUE TITLE
🐞 date in frontend should be formatted according to browser settings

### ISSUE THREAD

**Issue by sergiydmukhinepi** [sequentech/meta#751]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

The date in the dashboard, activity log and PDF ticket is shown in UTC. When creating scheduled events, the date is specified in the user's local time. The time is then displayed in UTC in the dashboard.
![image](https://github.com/sequentech/meta/assets/154313589/a943dd2e-fea3-439a-9f2a-0f0aeaa9133b)

### Expected Behavior

All dates are displayed according to browser format and time zone.

### Steps To Reproduce

see current behaviour

### Environment

- **Web browser**: Google Chrome 112.0.5615.137 (Official Build) (arm64)
- **Sequent Platform Version**: 10.2.0

### Tasks

```[tasklist]
# Tasks
- [ ] Issue has been triaged
- [ ] Successful replication of the defect
- [ ] Successful defect resolution merged
```

```[tasklist]
# 10.4.x PRs
- [ ] https://github.com/sequentech/voting-booth/pull/448
- [ ] https://github.com/sequentech/admin-console/pull/429
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/admin-console/pull/430
- [ ] https://github.com/sequentech/voting-booth/pull/449
```

**Comment by sergiydmukhinepi** [comment]
@Findeton Description contains unlocalized date formats 
![image](https://github.com/user-attachments/assets/58392171-9cc4-45e2-934a-0d9075d05b87)
