### ISSUE TITLE
✨ Improve/rethink/fix Live Preview

### ISSUE THREAD

**Issue by sergiydmukhinepi** [sequentech/meta#752]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

The live preview works terribly. The nginx URL length restrictions are annoying and insecure. You never know if large choices will be displayed.
Live preview of very large choices like this one doesn't even work in the UI by creating a new election.

### Tasks

# Screenshots

![Image](https://github.com/sequentech/meta/assets/3913223/7eb8efa4-0521-44d6-a15f-4f6add444912)

```[tasklist]
# Tasks
- [x] Add permissioned live-preview POST API call on iam to upload election json.
- [x] Add permissionless live-preview GET API call on iam to download election json.
- [x] Modify admin-console to use new live-preview POST api call.
- [x] Modify voting-booth/common-ui to enable live-preview using GET api call.
- [x] Modify deployment-tool to configure max input body size.
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/iam/pull/350
- [ ] https://github.com/sequentech/deployment-tool/pull/358
- [ ] https://github.com/sequentech/admin-console/pull/432
- [ ] https://github.com/sequentech/common-ui/pull/401
- [ ] https://github.com/sequentech/voting-booth/pull/452
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/iam/pull/348
- [ ] https://github.com/sequentech/deployment-tool/pull/356
- [ ] https://github.com/sequentech/admin-console/pull/431
- [ ] https://github.com/sequentech/common-ui/pull/400
- [ ] https://github.com/sequentech/voting-booth/pull/450
- [ ] https://github.com/sequentech/deployment-tool/pull/357
```

**Comment by Findeton** [comment]
@sergiydmukhinepi Our proposed implementation is to add an api call to upload the json config for the live preview, assigning an uuid to it. Then the voting booth can read the configuration when the uuid is passed as a parameter in the url. This will remove size constraints. 

Note that ONLY the API call to upload the json config will be permissioned. Anyone with the uuid (which will be treated as a secret) will have access to the live preview. Also, the API call to upload the json config will NOT check the validity of this config, it will assume the election config is valid.

Please let us know if this implementation is good enough for you and if so I'll implement it right away.

**Comment by sergiydmukhinepi** [comment]
@Findeton It looks good. What about back compatibility? Can we use both preview generations in this case? This is important for us as we operate a preview server that is used by several customers. We do not want to set up a new instance for the new preview version. Is it possible to combine the old and new preview functions on one server?

**Comment by Findeton** [comment]
@sergiydmukhinepi yes we can keep backwards compatibility. I'll start working on this right away.

**Comment by Findeton** [comment]
Hi @sergiydmukhinepi please review whether the new Live preview in branch `10.4.x` works well for you (also for large elections).

**Comment by sergiydmukhinepi** [comment]
@Findeton Thanks for the implementation. I have tested the feature with this configuration and it doesn't work. 
https://gist.github.com/sergiydmukhinepi/c79db63751e2aa3bb591e0101b79b9b5
I received this answer
`{"message": "", "field": null, "error_codename": "BAD_REQUEST"}`

**Comment by sergiydmukhinepi** [comment]
@Findeton Would you please add the election-id to the reply. Now I just get uuid `{"status": "ok", "id": "fb444758-3c0c-4098-9d96-7acbb17e8a2a"}`

**Comment by Findeton** [comment]
> [@Findeton](https://github.com/Findeton) Thanks for the implementation. I have tested the feature with this configuration and it doesn't work. https://gist.github.com/sergiydmukhinepi/c79db63751e2aa3bb591e0101b79b9b5 I received this answer `{"message": "", "field": null, "error_codename": "BAD_REQUEST"}`

The issue was the max body size for nginx and for the iam. I've generalized `max_body_size` to also take into consideration the iam.

**Comment by Findeton** [comment]
> [@Findeton](https://github.com/Findeton) Would you please add the election-id to the reply. Now I just get uuid `{"status": "ok", "id": "fb444758-3c0c-4098-9d96-7acbb17e8a2a"}`

The api call doesn't do any checks on the contents, you should know what you're sending and therefore know the id of the (parent) election that you're sending.

**Comment by sergiydmukhinepi** [comment]
@Findeton This is not true. Imagine you want to create an election where the id is -1. Before creating it, you want to make sure that everything is OK and call up Preview. In this case, the preview is created with the next highest ID. This is how it works

Übersetzt mit DeepL (https://www.deepl.com/app/?utm_source=ios&utm_medium=app&utm_campaign=share-translation)
