### ISSUE TITLE
🐞 Halifax demo fixes

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#753]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Tasks

```[tasklist]
# Tasks
- [x] Replace election with ballot on voting portal.
- [x] Fix tally issues.
- [x] Review invalid and blank vote policies, it doesn't seem to work.
- [x] candidates order doesn't seem to work.
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/417
- [ ] https://github.com/sequentech/backend-services/pull/418
- [ ] https://github.com/sequentech/backend-services/pull/419
- [ ] https://github.com/sequentech/backend-services/pull/420
- [ ] https://github.com/sequentech/backend-services/pull/421
- [ ] https://github.com/sequentech/infrastructure/pull/39
- [ ] https://github.com/sequentech/gitops/pull/139
- [ ] https://github.com/sequentech/backend-services/pull/476
```
