### ISSUE TITLE
✨ Separation of voting session time and bearer token lifetime

### ISSUE THREAD

**Issue by sergiydmukhinepi** [sequentech/meta#762]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

The lifetime of the SmartLink must be separated from the lifetime of the actual user session. The auth_token_expiration_seconds parameter should continue to control the lifetime of the bearer token across the entire instance. In addition, we want to control the user session via another parameter in config.yml, e.g. user_session_expiration_seconds.
This should also be controllable via booth_log_out__countdown_seconds per election in the json configuration file.

### Tasks

# Screenshots

<empty>

```[tasklist]
# Tasks
- [x] Task 1
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/iam/pull/355
- [ ] https://github.com/sequentech/voting-booth/pull/463
- [ ] https://github.com/sequentech/ballot-box/pull/210
- [ ] https://github.com/sequentech/common-ui/pull/407
- [ ] https://github.com/sequentech/admin-console/pull/436
- [ ] https://github.com/sequentech/misc-tools/pull/58
- [ ] https://github.com/sequentech/deployment-tool/pull/361
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/iam/pull/351
- [ ] https://github.com/sequentech/voting-booth/pull/453
- [ ] https://github.com/sequentech/ballot-box/pull/207
- [ ] https://github.com/sequentech/common-ui/pull/402
- [ ] https://github.com/sequentech/admin-console/pull/433
- [ ] https://github.com/sequentech/misc-tools/pull/57
- [ ] https://github.com/sequentech/deployment-tool/pull/359
- [ ] https://github.com/sequentech/deployment-tool/pull/360
- [ ] https://github.com/sequentech/voting-booth/pull/455
- [ ] https://github.com/sequentech/common-ui/pull/404
- [ ] https://github.com/sequentech/voting-booth/pull/456
```
