### ISSUE TITLE
✨ UA deployment

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#767]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Deploy ua

### Tasks

# Screenshots

<empty>

```[tasklist]
# Tasks
- [x] Trustee 3
- [ ] Monitoring tags for grafana
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/gitops/pull/140
- [ ] https://github.com/sequentech/backend-services/pull/422
- [ ] https://github.com/sequentech/gitops/pull/150
- [ ] https://github.com/sequentech/gitops/pull/151
- [ ] https://github.com/sequentech/gitops/pull/152
- [ ] https://github.com/sequentech/backend-services/pull/433
```
