### ISSUE TITLE
🐞 Alternative method auth messages include invalid link

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#77]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Current Behavior

Alternative method auth messages include invalid link

### Expected Behavior

The link should work

### Tasks

```[tasklist]
# Tasks
- [x] Fix issue
```

```[tasklist]
# Master PRs
- [ ] 
- [ ] https://github.com/sequentech/iam/pull/285
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/iam/pull/284
```
