### ISSUE TITLE
✨ Ensure deployments use DB encryption and enforcing a backup policy

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#780]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Ensure deployments use DB encryption and enforcing a backup policy

### Tasks

```[tasklist]
# Tasks
- [x] Check if KMS is being in used
- [x] Check backup policy and retention policy
- [x] Check backup and encryption on RabbitMQ component
- [x] Check RabbitMQ is running in HA
- [x] Enable RabbitMQ KMS Encryption
- [x] IAM Policies to be group aware
- [x] EBS volumes / Snapshots
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/infrastructure/pull/40
- [ ] https://github.com/sequentech/gitops/pull/158
- [ ] https://github.com/sequentech/infrastructure/pull/41
- [ ] https://github.com/sequentech/gitops/pull/217
```

**Comment by angelAtSequent** [comment]
# KMS Encryption

It is already enabled, double checked in AWS and the IAC code.

**Comment by angelAtSequent** [comment]
# Backup Policy

The backup policy is already set, default to 10 days. Double checked in AWS console and the IAC code.

**Comment by angelAtSequent** [comment]
RabbitMQ doesn't have configured encryption at all, it must be activated

**Comment by angelAtSequent** [comment]
After discussing on Slack: https://sequentech.slack.com/archives/C03HWNB6FSQ/p1714462304848489?thread_ts=1714458764.169509&cid=C03HWNB6FSQ

I've added the task to check RabbitMQ is running in HA:

![imagen](https://github.com/sequentech/meta/assets/168065560/3ab4bd0c-759c-4539-bdfc-8a6408e88b44)
We are not overriding the default value set on the module:

https://github.com/sequentech/infrastructure/blob/main/aws/RabbitMQ/variables.tf#L20-L30

**Comment by angelAtSequent** [comment]
As agreed, 

The only rabbitmq-instance will remain as it is. 
I've created a new version of the rabbitmq module that enables kms encryption and gets rids of the secondary instance.
It's currently shutdown (not causing any cost).

**Comment by angelAtSequent** [comment]
About group aware, i've implemented something on the rabbitmq and the rds tf modules to gather the users under the devops IAM group, then using them on the IAM policies we need.

**Comment by angelAtSequent** [comment]
About EBS volumes, I see a few of them not in use:

- us-east-1:
- - apa-cluster: 4 volumes - 0 Snapshots
- - my-cluster (dev): 10 volumes - 3 Snapshots
- - comelect: 2: volumes - 588 Snapshots
- - - ua-cluster: 0 volumes - 98 Snapshots

A few manual volumes and snapshots are there too.

![Captura desde 2024-05-02 06-56-38](https://github.com/sequentech/meta/assets/168065560/a777eb03-9082-4740-ad2f-acb4e3125151)

- us-east-2: Clean

**Comment by angelAtSequent** [comment]
Regarding access to eks (to further investigate how are the backups being created)

As i was talking with Eduardo, we are kind of block for running terraform code on the `eks` projects until we understand who triggered the creation of the clusters.

This is due to a default value set on the `eks` terraform module: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/variables.tf#L195-L199

This prevents other users to run terraform with the following error:
```shell
│ Error: reading KMS Key (c67bc362-de48-4bca-8a36-a79b8f7b1512): reading KMS Key (c67bc362-de48-4bca-8a36-a79b8f7b1512): AccessDeniedException: User: arn:aws:iam::581718213778:user/angel-devops is not authorized to perform: kms:DescribeKey on resource: arn:aws:kms:us-east-1:581718213778:key/c67bc362-de48-4bca-8a36-a79b8f7b1512 because no resource-based policy allows the kms:DescribeKey action
```

We need to:
- Identify who created these clusters.
- We already fixed the `ua` cluster (created by felix).
- Run terraform in the following branch https://github.com/sequentech/gitops/pull/158 (or merge in main) with the access keys of that user.
- - This include a static list of `kms_key_administrators` that includes the root account user (so we will never lost access again)

Code that fixes this issue: https://github.com/sequentech/gitops/pull/158/commits/fab37426d2c702892b60cb931845af5ba091467a

I can continue designing how to implement the backup policy/clean up policy on backups being made from the clusters as i already have access to `ua`, but fixing this kms problem widely is critical to continue.

**Comment by angelAtSequent** [comment]
Regarding EBS and Snapshots:

After being able to access a Kubernetes Cluster (ua), i was able to detect what was the main snapshot consumer, immudb.
It had a backup policy but not a cleanup policy.

As agreed with Eduardo, we wanted to change the backup strategy to not only take backups and clean up older than X time, but also give it a little bit of intelygence.
So I've opted to create:
- Hourly
- Daily
- Weekly
Snapshots and then, keep X,Y,Z snapshots per type.

This must help: https://github.com/sequentech/infrastructure/pull/41

It requires, after deploying this new approach, to deactivate the old approach, then, cleanup the old snapshots.
More info in the PR above.

**Comment by angelAtSequent** [comment]
> us

Deployed on staging (my-cluster). I'll left it configured for some days to check everything is working as expected

**Comment by edulix** [comment]
Closing it since it was moved to done, please reopen it if it's a mistake to close it.
