### ISSUE TITLE
✨ Frontend refactor/fixes

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#801]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Frontend refactor/fixes

### Tasks

# Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] add checkbox to max num per type
- [ ] add classes to components
- [ ] add velvet test to check max num per type generates an invalid vote
- [x] fix langs config in admin-portal/voting-portal
- [x] when you create an entity/candidate/election/event and you don't have english as your lang, the name disappears after creation
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/426
- [ ] https://github.com/sequentech/backend-services/pull/428
- [ ] https://github.com/sequentech/backend-services/pull/432
- [ ] https://github.com/sequentech/backend-services/pull/437
```
