### ISSUE TITLE
🐞 Dumping of votes dumps only the first vote when not filtering by voter id

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#802]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

Dumping of votes dumps only the first vote when not filtering by voter id.

### Expected Behavior

Should dump all relevant votes.

### Steps To Reproduce

-

### Environment

-

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [x] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/ballot-box/pull/202
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/ballot-box/pull/201
```
