### ISSUE TITLE
🐞 `ballot-box` unit tests don't compile

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#803]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

 `ballot-box` unit tests don't compile

### Expected Behavior

The `ballot-box` unit tests should compile and pass.

### Steps To Reproduce

-

### Environment

-

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [ ] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/ballot-box/pull/204
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/ballot-box/pull/203
```
