### ISSUE TITLE
✨ Implement countdown and warning dialog before logout in voting-portal/admin-portal

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#804]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Implement countdown and warning dialog before logout in voting-portal/admin-portal.

### Possible Implementation

Please take a look at how it works in the 1st-gen in this link, looking at the logout button: https://10xx.sequentech.io/booth/468/demo-vote

https://github.com/sequentech/meta/assets/81968/4eb38457-42ce-43f1-8e96-3bdbeceea338

The idea is that that button (which in the 2nd-gen is typically the profile button instead) would show the same kind of UI. On hover, it shows a popup with the notification of when logout is going to happen and when only X seconds are left, it should show a modal dialog warning the user - and after, logout should happen.

### Backend Notes

We should a presentation section `voting_portal_countdown_policy` at the `Election Event` level since this is related to the authentication that happens at the election event realm. This policy  that should have 3 options for now: `NoCountDown` and `Countdown`, `CountdownWithAlert`. We should have 2 configurable uint values related to this policy: `countdown_anticipation_secs` and `countdown_alert_anticipation_secs`.

This policy should be added at the election event level, and be rendered as part of the publication when publishing the election event. It should also be part of the export and import of an election event.

### Voting Portal Frontend Notes

Implement the feature in the frontend without changing the backend. Assume that later there will be an Election Event presentation option to retrieve if the countdown in the format explained in the backend section. Leave it almost done, so that minimal changes in the voting portal code is necessary once backend changes are implemented. 

### Retrocompatibility

In all section of backend, admin portal and voting portal we need to ensure retrocompatibility. If there's an election event created with a version of the system that did not set any countdown policy, it should all work as expected, defaulting to `NoCountdown`. Voting Portal should still work fine, admin portal should still allow editing this policy, and publication and export/import of an election should still support loading or generating the default `NoCountdown`.

### Implementation Screenshots

Please add screen recording of the implementation when it's done of all the new UI

### Tasks

```[tasklist]
# Tasks
- [x] @yvwbimpong: Implement the feature in the voting portal.
- [ ] @omri81: implement the feature in the backend.
- [x] @omri81: implement the UI in Admin Portal.
- [ ] Integrate with Admin portal work and get the policy and seconds to show
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/528
- [ ] https://github.com/sequentech/step/pull/533
```

**Comment by yvwbimpong** [comment]
https://github.com/sequentech/meta/assets/29688503/32a24ecf-b91d-4bf7-8f2c-3e83e1f1382e

**Comment by yvwbimpong** [comment]
![Image](https://github.com/sequentech/meta/assets/29688503/94f454e6-5639-4e0b-8346-f934de4d4ff9)

**Comment by yvwbimpong** [comment]
https://github.com/sequentech/meta/assets/29688503/ead7f265-49fa-45dc-86ae-067152764a53

**Comment by yvwbimpong** [comment]
https://github.com/sequentech/meta/assets/29688503/754c2c4c-11f6-433f-ab4c-5909a7279c4a

**Comment by yvwbimpong** [comment]
https://github.com/sequentech/meta/assets/29688503/94f6e54a-aa15-446c-a535-5a686323d727
