### ISSUE TITLE
✨ Login URL: language override using an url param

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#805]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Login URL: language override using an url param

### Tasks

# Screenshots

<empty>

```[tasklist]
# Tasks
- [x] Create a handler for lang query param
- [x] Override existing language settings in case of param
- [x] Update language setter function in ui-essentials to accept an optional language
- [x] See keycloak localization options
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/478
```

**Comment by edulix** [comment]
Soon we are going to have to document each change. For now, can you please comment here how to reproduce this new feature for testing and approval? Should I just add `?lang=es` or similar to the `/login` url and it should work?

**Comment by edulix** [comment]
Also @OmerN-Moveo please update the subtasks list, by adding any subtasks there and checking them while you do them. Other than that, great work!

**Comment by OmerN-Moveo** [comment]
> Soon we are going to have to document each change. For now, can you please comment here how to reproduce this new feature for testing and approval? Should I just add `?lang=es` or similar to the `/login` url and it should work?

@edulix 
Correct just adding the queryParam ?lang=es
will work under any url inside the voting portal
