### ISSUE TITLE
✨ new-ballot-verifier: update ui design and implementation

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#81]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

new-ballot-verifier: we should update the design and implementation according to the new voting-booth design styles and have a general review by luis.

### Tasks

```[tasklist]
# Tasks
- [x] Update design: [Review UI](https://docs.google.com/document/d/1bxH5tg85YO75QxUCi_Lz6jMoEXgup-kABCqmWQvXD-o/edit#heading=h.mpeloqs6sjfx) and update it (create it in figma) with Luis feedback and new Voting Booth design. This is [the new Figma.](https://www.figma.com/file/lVNVX8BwQJjBPk0ZPb0NJ3/Ballot-Verifier?type=design&node-id=0-1&t=bpF2u3Yc2UEESPwC-0)
- [x] Create ui-design repo for shared components and ui style definitions. This repo should have the basic structure (github actions, storybook, devcontainer, license checks...).
- [x] Move existing style and reusable components from new-ballot-verifier to this repo, removing it  from new-ballot-verifier and make it use the ui-essentials repo for the components/style.
- [x] Implement the style and reusable components from the design on the ui-essentials repo, including storybook and tests.
- [x] Implement the screens of the Figma design, including storybook and tests.
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/ui-essentials/pull/7
- [ ] https://github.com/sequentech/new-ballot-verifier/pull/34
```
