### ISSUE TITLE
🛡 Security updates

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#810]
### Tasks

```[tasklist]
# Tasks
- [ ] Perform the security updates
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/release-tool/pull/54
- [ ] https://github.com/sequentech/release-tool/pull/53
- [ ] https://github.com/sequentech/release-tool/pull/52
- [ ] https://github.com/sequentech/iam/pull/343
- [ ] https://github.com/sequentech/election-orchestra/pull/97
- [ ] https://github.com/sequentech/frestq/pull/98
- [ ] https://github.com/sequentech/common-ui/pull/394
- [ ] https://github.com/sequentech/election-portal/pull/233
- [ ] https://github.com/sequentech/election-portal/pull/234
- [ ] https://github.com/sequentech/admin-console/pull/422
- [ ] https://github.com/sequentech/voting-booth/pull/440
- [ ] https://github.com/sequentech/voting-booth/pull/441
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/iam/pull/342
- [ ] https://github.com/sequentech/election-orchestra/pull/98
- [ ] https://github.com/sequentech/frestq/pull/99
- [ ] https://github.com/sequentech/common-ui/pull/393
- [ ] https://github.com/sequentech/election-portal/pull/235
- [ ] https://github.com/sequentech/admin-console/pull/423
```
