### ISSUE TITLE
🐞 Trustees stuck while creating an election

### ISSUE THREAD

**Issue by sergiydmukhinepi** [sequentech/meta#812]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

Trustees get stuck after creating some key pairs in the parent election and give no response back. No election could be created afterwards. Btw, I tried to reproduce the problem on your demo server and you should probably restart the trustees.

### Expected Behavior

It should work as usual

### Steps To Reproduce

use this config to reproduce
https://gist.github.com/sergiydmukhinepi/97fbeb79dd8ce02bc2cc540ee174b824

### Environment

- **Web browser**: Google Chrome 112.0.5615.137 (Official Build) (arm64)
- **Sequent Platform Version**: 10.4.1

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [x] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/frestq/pull/101
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/frestq/pull/100
```

**Comment by edulix** [comment]
@sergiydmukhinepi please check the fix in the PR works for you before we merge and do a release.
