### ISSUE TITLE
✨ UAlicante deployment

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#814]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

UAlicante deployment

### Tasks

# Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/gitops/pull/159
- [ ] https://github.com/sequentech/gitops/pull/311
```
