### ISSUE TITLE
Security updates

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#83]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

New major release.

### Tasks

```[tasklist]
# Tasks
- [x] Security updates
```

```[tasklist]
# Master PRs
- [ ] 
- [ ] https://github.com/sequentech/iam/pull/286
- [ ] https://github.com/sequentech/frestq/pull/69
- [ ] https://github.com/sequentech/frestq/pull/70
- [ ] https://github.com/sequentech/election-orchestra/pull/64
- [ ] https://github.com/sequentech/election-orchestra/pull/65
- [ ] https://github.com/sequentech/admin-console/pull/369
- [ ] https://github.com/sequentech/voting-booth/pull/328
- [ ] https://github.com/sequentech/election-portal/pull/197
- [ ] https://github.com/sequentech/common-ui/pull/305
- [ ] https://github.com/sequentech/tally-pipes/pull/101
- [ ] https://github.com/sequentech/misc-tools/pull/52
- [ ] https://github.com/sequentech/ballot-box/pull/166
- [ ] https://github.com/sequentech/release-tool/pull/40
- [ ] https://github.com/sequentech/release-tool/pull/41
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/iam/pull/288
- [ ] https://github.com/sequentech/frestq/pull/71
- [ ] https://github.com/sequentech/frestq/pull/72
- [ ] https://github.com/sequentech/election-orchestra/pull/66
- [ ] https://github.com/sequentech/election-orchestra/pull/67
- [ ] https://github.com/sequentech/admin-console/pull/370
- [ ] https://github.com/sequentech/voting-booth/pull/329
- [ ] https://github.com/sequentech/election-portal/pull/198
- [ ] https://github.com/sequentech/common-ui/pull/306
- [ ] https://github.com/sequentech/tally-pipes/pull/102
- [ ] https://github.com/sequentech/misc-tools/pull/53
- [ ] https://github.com/sequentech/ballot-box/pull/167
```
