### ISSUE TITLE
✨ Schedule Election and Election Event Start and Stop

### ISSUE THREAD

**Issue by lnabergoi** [sequentech/meta#849]
### Preflight checklist

- [x] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

-

### Tasks

# Screenshots

<empty>

```[tasklist]
# Tasks
- [x] Add start/stop elements to the election logs
- [x] Automatically change start/stop dates when saving the election, not when clicking in schedule toggle button, to be consistent
- [x] Add a way to reset to null the start/stop date
- [x] Start/stop only relevant election
- [x] If scheduled start time has passed, don't fail, instead start the election automatically, unless stop date is also in the past. Similar behavior for stop election.
- [x] Add the schedule start/stop to the election event too
- [ ] Deduplicate election start/stop dates if there's no good reason for it to be duplicated
- [x] Use the elections status instead of the election event status
- [x] change admin-portal start/stop apis and buttons of start stop to be from the elections status.
- [x] change status of election in voting portal to be from election and not election event
- [x] modify task and api to be for either election or election_event
- [ ] Transition the used code to use sql transactions instead of graphql: `get_election_event_helper`, `update_election_event_status`
- [x] create scheduled tasks when importing election when needed
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/446
- [ ] https://github.com/sequentech/backend-services/pull/448
- [ ] https://github.com/sequentech/backend-services/pull/449
- [ ] https://github.com/sequentech/backend-services/pull/450
- [ ] https://github.com/sequentech/step/pull/547
```
