### ISSUE TITLE
✨ new-ballot-verifier: update dependencies

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#85]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Update software dependencies.

### Tasks

```[tasklist]
# Tasks
- [ ] Update dependencies for security reasons (both in new-ballot-verifier and its dependencies: sequent-core, strand)
- [ ] update devcontainers and github actions following how it is done in bulletin-board repo
```

```[tasklist]
# Master PRs
- [ ] 
```

```[tasklist]
# Stable PRs
- [ ] Task 1
```

**Comment by edulix** [comment]
superseeded by https://github.com/sequentech/meta/issues/154
