### ISSUE TITLE
🐞 UA fixes

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#868]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).
- [x] Hide option to edit profile in voting portal.
- [x] Translate ballot tracker.
- [x] Style/logo for ballot tracker should be the same as voting portal.
- [x] Configure enabled/default languages for ballot tracker.
- [x] When accessing the Ballot tracker from the ballot Id in the review vote page, the system the ballot tracker doesn't show the logo and is in English with the option to change the language
- [x] review translations of the ballot tracker in Spanish. Some of them are still in English
- [x] Add an option in the Admin portal to the election event to remove the option in the voting portal to access the voter profile in keylock.
- [x] Ensure that the text in the "Review screen" is modified to not add anything about the "Audit" button, when the ballot audit is configured to be not shown in the election event ballot design.
- [x] Ensure the translation of messages contain the same label for button as the one that are in the screen: example Review Page"En los botones de bajo pone "Editar Voto" y "Enviar Voto". No se corresponde con los textos de "Cambiar selección" o "Enviar papeleta"
- [x] Remove the mention of Election results in the modals on the Election List page.
- [x] The logo of the voting portal doesn't look good in the Safari browser.
- [x] When the voter doesn't choose any selection, the system should show a <Invalid/Null Vote> <Voto invalido/Voto nulo> in the review screen.
- [x] Column size in the review screen is not equal when choosing candidates from 2 lists.
- [x] Explicit invalid votes with no implicit invalid errors are counted as blank.
- [x] When a null vote explicit option is configured in the Tally report doesn't show the number of votes for that option.
- [x] The system doesn't allow the execution of more than one tally when there are more than two trustees ( trustees get an error when training to re-import their keys, all of them). The system must allow as many tallies as required as It does in other environments.
- [x] The system must allow to importation of all the trustees' keys, even if the threshold is lower than the number of trustees
- [x] In the Spanish translation, change any mention of "boleta" to "papeleta".
- [x] The button label "Siguiente" in the ballot screen in Spanish is spelled wrong it says " Siguente".
- [x] In the Admin Portal, when you filter in a table or order a column, it generates an error on all other pages.
- [x] Sometimes, the print receipt is not working.
- [x] Change the translation in Spanish of the "Voto invalido o en blanco" pop up in the ballot page in Spanish "Algunas de sus respuestas podrían hacer que la papeleta en una o más preguntas sea inválida o en blanco." to  "Algunas de sus respuestas harán que la papeleta en una o más preguntas sea inválida o en blanco."
- [x] Election Results doesn't provide the ability to download the tar.gz at the election level.
- [x] Percentage results are wrong. See [this](https://admin-portal-ua.sequent.vote/#/sequent_backend_election_event/3efdc671-57ca-4841-81f6-b0b731aa742e/5). Also note null vote is shown as cero but it's not cero.
- [x] We shouldn't allow casting votes with demo keys.
- [x] Tally list should include time/hour.
- [x] Winning positions.
- [x] A Keys ceremony dialog is not translated.

### Current Behavior

-

### Expected Behavior

-

### Steps To Reproduce

-

### Environment

-

### Tasks

```[tasklist]
# Tasks
- [x] If auditing is disabled, the text on the review page shouldn't mention it.
- [x] Voting blank is not triggering a warning message (also in review page).
- [x] Explicit null should also trigger warning.
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/438
- [ ] https://github.com/sequentech/backend-services/pull/439
- [ ] https://github.com/sequentech/backend-services/pull/441
- [ ] https://github.com/sequentech/backend-services/pull/445
- [ ] https://github.com/sequentech/backend-services/pull/456
- [ ] https://github.com/sequentech/backend-services/pull/457
- [ ] https://github.com/sequentech/backend-services/pull/470
```
