### ISSUE TITLE
✨ Improve Vote receipts

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#872]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Improve Vote receipts

### Tasks

# Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/451
- [ ] https://github.com/sequentech/backend-services/pull/458
- [ ] https://github.com/sequentech/backend-services/pull/459
- [ ] https://github.com/sequentech/backend-services/pull/460
```
