### ISSUE TITLE
✨ Generate Timestamp for election reports as data available to the template

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#873]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### DEV DISCLAIMER
For now it generates in utc time,
We should create a task that adds configuration for timeZone + dateFormat per election event in the admin portal and pass it to the report generation as a config.
This is supported by the report generation function 
* dateFormat is an enum
* timeZone is an enum that can be utc / custom by passing the Offset(diff time from utc) such as Offset(3)  or Offset(-2)
representing (utc +3) or utc(-2).

### Suggestion

Generate Timestamp for election reports as data available to the template

### Tasks

# Screenshots

<empty>

```[tasklist]
# Tasks
- [x] Create a utils function to generate a timestamp based on date format and timezone
- [x] Create DateFormat and TimeZone enums and implement defaults and traits
- [x] Update create report function to pass the timestamp variable to the templates
- [x] Update templates to use timestamp variable instead of generating them witin a script tag
- [x] Update pipes to accept timezone and dateFormat arguments
- [x] Add the date and time to the template and template vars of the root template for vote_receipt.hbs and windmill/src/services/vote_receipt.rs(for vote receipts from the voting portal)
- [x] In report_contents.hbs translate the title, right now is in spanish
- [x] Ensure none of the templates use qrcode.js from cloudflare etc, right now I just saw that in vote_receipts.hbs that's the case, but in vote_receipt.hbs is correct using our own hosted lib
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/557
```
