### ISSUE TITLE
🐞 Threshold trustees don't work.

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#883]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

If there are more connected trustees than the threshold, tally doesn't work.

### Expected Behavior

Threshold works.

### Steps To Reproduce

-

### Environment

-

### Tasks

```[tasklist]
# Tasks
- [x] Remove unused `insert_ballots` task.
- [x] Fix predicate error on braid.
- [x] Only select trustees with restored keys, only up to the threshold and randomize the selection.
- [x] Allow to restore keys on connected state (when there are enough trustees connected already to cover the threshold).
- [x] Add config for 3rd trustee in development.
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/440
```
