### ISSUE TITLE
✨ Refactor gitops/globals to allow eu-west regions

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#885]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Refactor gitops/globals to enable eu-west regions

### Tasks

# Screenshots

<empty>

```[tasklist]
# Tasks
- [x] Adapt global directory to allow two different locations: america - europe
- [x] Create ualicante project structure
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/gitops/pull/211
```

**Comment by angelAtSequent** [comment]
I was able to adopt what is already created in AWS on this branch without breaking anything on the already existing environments in USA.

I had to check the tfstate bucket created for eu-west-1 to see what was already created by @Findeton .
I think im not missing anything, anyway, @Findeton can continue deploying infra using this branch https://github.com/sequentech/gitops/pull/211 (in the PR)

**Comment by Findeton** [comment]
I've looked at the code and it LGTM. I'll use it to continue the deployment and then merge it.

**Comment by edulix** [comment]
Closing it since it was moved to done, please reopen it if it's a mistake to close it.
