### ISSUE TITLE
✨ new-ballot-verifier: unit and e2e tests

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#89]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

The new-ballot-verifier should have a complete suite of unit tests and e2e tests.

### Tasks

```[tasklist]
# Tasks
- [ ] Complete unit tests
- [ ] Complete e2e unit tests
```

```[tasklist]
# Master PRs
- [ ] 
```

```[tasklist]
# Stable PRs
- [ ] Task 1
```
