### ISSUE TITLE
🐞 Activity log scrolling doesn't work in big screens

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#90]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Current Behavior

Activity log scrolling doesn't work in big screens, it requires resizing the window.

### Expected Behavior

It should work fine in any screen size.

### Tasks

```[tasklist]
# Tasks
- [x] Fix activity log scrolling. The fix applied is simply returning more elements by default to ensure that the screen, even if big, either starts with scroll or has shown all the elements already.
```

```[tasklist]
# Master PRs
- [ ] 
- [ ] https://github.com/sequentech/common-ui/pull/304
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/common-ui/pull/303
```
