### ISSUE TITLE
🐞 PDF Auth Codes don't work with SmartLink

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#91]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Current Behavior

PDF Auth Codes don't work with some authentication methods like user-and-password or smartlink.

### Expected Behavior

PDF Auth Codes should work with any authentication method.

### Tasks

```[tasklist]
# Tasks
- [x] Fix PDF Auth Code support for all authentication methods
- [x] Test which methods work with PDF Auth Codes
```

```[tasklist]
# Master PRs
- [ ] 
- [ ] https://github.com/sequentech/common-ui/pull/302
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/common-ui/pull/301
```
