### ISSUE TITLE
🐞 Double click is needed to deselect

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#911]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

we have to click twice to deselect the "invalid vote" answer? If you click directly in the checkbox, nothing happens. 

### Expected Behavior

Only one click needed

### Steps To Reproduce

https://uni-halle.gremienwahlen.de/booth/2000/demo-vote

### Environment

- **OS**: Mac OS X Ventura
- **Web browser**: Google Chrome 112.0.5615.137 (Official Build) (arm64)
- **Sequent Platform Version**: 10.0.0

### Tasks

```[tasklist]
# Tasks
- [ ] Issue has been triaged
- [ ] Successful replication of the defect
- [ ] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/voting-booth/pull/443
- [ ] https://github.com/sequentech/voting-booth/pull/445
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/voting-booth/pull/442
- [ ] https://github.com/sequentech/voting-booth/pull/444
```

**Comment by Findeton** [comment]
@sergiydmukhinepi  please review on your end that this issue is fixed.

**Comment by sergiydmukhinepi** [comment]
@Findeton thank you for the fix. Unfortunately there is still some issue.  If you click directly in the checkbox, nothing happens. https://vnext.gremienwahlen.de/booth/1737920602/demo-vote

**Comment by Findeton** [comment]
@sergiydmukhinepi Thanks for your review. Please review it again, the issue you mention is fixed now.

**Comment by sergiydmukhinepi** [comment]
@Findeton thank you, it works
