### ISSUE TITLE
🐞 Logs are being deleted when services are restarted

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#912]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

Logs are being deleted when services are restarted

### Expected Behavior

Logs should be correctly rotated, not on restart

### Steps To Reproduce

-

### Environment

-

### Tasks

```[tasklist]
# Tasks
- [ ] Issue has been triaged
- [ ] Successful replication of the defect
- [ ] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/deployment-tool/pull/355
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/deployment-tool/pull/354
```
