### ISSUE TITLE
✨ Create and document a Terraform Deployment machine

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#915]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Create and document a Terraform Deployment machine. This machine should be always used for deployments, intead of doing it manually. It should use a [tmuxinator configuration/setup similar to this](https://sequentech.github.io/documentation/docs/general/guides/deployment/#collaborate-sharing-with-tmuxinator), and have a tab per deployment with the configuration of the tmux session in a file similar to the deployment-skel in the link above. The idea is that no-one should be deploying and testing terraform from their own machine.

Then, document the setup and how it should be used.

### Possible Implementation

-

### Tasks

```[tasklist]
# Tasks
- [x] Create the terraform module
- [x] Deploy the infrastructure
- [x] Write documentation about how to use it
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/infrastructure/pull/43
- [ ] https://github.com/sequentech/gitops/pull/320
```

**Comment by angelAtSequent** [comment]
Moving to done :)
