### ISSUE TITLE
🐞 Voting Booth: Incorrect message about skipped ballots

### ISSUE THREAD

**Issue by ElectricPaperInformationssystemeGmbH** [sequentech/meta#93]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Current Behavior

Within parent-children elections, a voter can skip a children election. But then, if the election-chooser screen is enabled, the skipped election can be chosen and voted for by the voter afterwards. If this happen, the following message is still displayed even though the voter already voted in the skipped election:
`You skipped 1 ballot. You can call them up again by logging into the election portal again.`

### Expected Behavior

The system should show the message about skipped elections only when the skipped elections have not been voted for.

### Steps To Reproduce

1. Election with ballot chooser
2. Skip some question
3. Vote in all elections including the skipped one using the election chooser

### Environment

```markdown
- OS:
- Web browser:
```

### Tasks

```[tasklist]
# Tasks
- [x] Fix issue in the voting booth
```

```[tasklist]
# Master PRs
- [ ] https://github.com/sequentech/voting-booth/pull/327
```

```[tasklist]
# Stable PRs
- [ ] https://github.com/sequentech/voting-booth/pull/326
```
