### ISSUE TITLE
✨ Hardcode candidates import and area contests for demo

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#964]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Hardcode imports for demo

### Tasks

# Screenshots

<empty>

```[tasklist]
# Tasks
- [x] Assign all contests to all areas.
- [x] Candidates import.
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/462
- [ ] https://github.com/sequentech/backend-services/pull/463
```
