### ISSUE TITLE
🐞 Fix Election Event Import: `localizationTexts` not being imported

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#980]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

Fix Election Event Import: `localizationTexts` not being imported.

## Solution

The reason: keycloak-rs is v21 instead of v24. Should be using keycloak = "24.0.301" in windmill. https://crates.io/crates/keycloak

### Expected Behavior

`localizationTexts` being imported.

### Steps To Reproduce

[final-comelec.json](https://github.com/sequentech/meta/files/15446277/final-comelec.json)

### Environment

-

### Tasks

```[tasklist]
# Tasks
- [ ] Issue has been triaged
- [ ] Successful replication of the defect
- [ ] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [x] https://github.com/sequentech/backend-services/pull/471
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```

**Comment by edulix** [comment]
Closing this
