### ISSUE TITLE
✨ Github Action & script counting LOCs

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#981]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Github Action & script counting LOCs

### Tasks

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/backend-services/pull/465
- [ ] https://github.com/sequentech/backend-services/pull/467
```
